### ISSUE TITLE
Возможность изменить цвет комплектующих не залезая в спецификацию

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#100]
Мы с Игорем ранее обсуждали, что те таблицы соответствия, которые я ему высылала могут и не подойти заказчику, тогда цвет например уплотнителя и/или водоотводного профиля мы должны иметь возможность изменить самостоятельно.
Теоретически конечно можно зайти в спецификацию и изменить там цвет этих комплектующих.
Но, во-первых, как мы решили с Евгением, не правильно лезть в автоматически рассчитанную спецификацию, а во-вторых, даже я могу какую нибудь одну строчку не изменю, то все, как говорится, finita la commedia, а про других менеджеров я уж молчу.
Можно что-то придумать на эту тему?

**Comment by unpete** [comment]
> Теоретически конечно можно зайти в спецификацию и изменить там цвет этих комплектующих

Нельзя. В текущей сборке, редактирование спецификации руками не предусмотрено.
Если такой инструмент нужен, можно запланировать отдельную задачу, но редактор спецификаций - это сложный самостоятельный проект. Потребуется отслеживать версии, чтобы итоговая спецификация склеивалась из автоматической части и ручных корректировок

**Comment by aribaz** [comment]
Вообще-то можно, и у меня получилось и изменить цвет и сохранить заказ. И при повторном открытии заказа мои изменения сохранены. Количество ++ не могу изменить, а длину и количество могу, но это кажется никак не повлияло на сумму, а вот наименование номенклатуры, ее цвет и характеристику внутри спецификации изменить могу.

**Comment by unpete** [comment]
Технически - можно, методически - нельзя.
Если открыть изделие в построителе и записать - ручные корректировки потеряются.

**Comment by unpete** [comment]
Закрываю, цветовые характеристики и допматериалы должны рассчитываться через параметры
