### ISSUE TITLE
Филенка 40

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#101]
Добавить номенклатуру Филенка 40 для возможности замены ею стеклопакета 40мм в дверях в нижней части.

**Comment by aribaz** [comment]
Странно то, что параметрах продукции она есть, а в справочнике Номенклатура нет,  может я ее просто не имею возможности видеть? 
Пробовала скопировать название из Параметров продукции и вставить в поиск в справочнике Номенклатура, но пусто. По идее я должна же ее видеть.

**Comment by unpete** [comment]
> Странно то, что параметрах продукции она есть, а в справочнике Номенклатура нет

В этом, как раз, нет ничего странного. Параметры и номенклатура - самостоятельные справочники.
Вероятно, Игорь просто забыл перенести в базу зоны №2 какие-то данные.

**Comment by aribaz** [comment]
Задача выполнена, закрываю
