### ISSUE TITLE
Как нарисовать новое окно

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#102]
Как можно нарисовать  новое окно, которого нет в шаблоне?
Если смотреть ролик, то в нем Вы рисуете окно не используя шаблон. Таким методом нарисовать не получается, так как система профиля у меня в этом случае пуста и список выбора тоже пуст. Палочку он конечно рисует, но что это за профиль не понятно, в табчасти строка Вставка пуста для этой палки и изменить ее на что-то необходимое нет возможности, список выбора пуст.

Если для рисования использовать глухарь, то это не совсем верно, так как нарисовать я хочу двустворчатое, а для него профиль рамы используется другой и есть возможность поменять только на Рама низ, а бок и верх заменить на раму нет возможности. Если за основу взять одностворчатое, то не дает вставить вертикальный импост, точнее в качестве него использовать именно импост, а не профиль рамы.
Может я что-то не так делаю?

Ну и вытекающий вопрос, как потом новое окно сохранить в шаблонах?

**Comment by unpete** [comment]
Адресую вопрос к @Oparin-Igor 
Нужна статья

**Comment by aribaz** [comment]
Мне почему то кажется что я не смогу нарисовать вообще абстрактное окно. Если я правильно помню, то построитель может рисовать только то, что описано в параметрах продукции, а в параметрах продукции есть несколько строчек с существующими шаблонами, а строчки для абстрактного окна там нет почему-то.
Я догадываюсь, почему у меня не получается нарисовать на основе одностворчатого окна двустворчатое с вертикальным импостом. Потому что на вкладке Элементы в параметрах этого окна в качестве импоста есть только Горбылек 83/76, а симметричных импостов или каких-либо других нет, а раз такой элемент параметрами этой продукции не предусмотрен я и не могу его вставить (недступен для выбора). Это же касается и глухаря. 
Если мои предположения верны, то получается что я не могу нарисовать любое окно, а могу только то, что в шаблонах и все. Это совсем не радует, если не сказать больше.
Я предполагала, что в параметрах продукции будет описана вся система наших профилей в целом, а не раздельно и только для некоторых комбинаций.

**Comment by Oparin-Igor** [comment]
Так как каждая система(тип окна) имеет свой (отличный от других) набор профилей. Поэтому созданы различные системы. Наибольшее количество профилей содержит 3-х ств. окно. Об этом было оговорено ранне. Если каких либо профилей не хватает можно дополнить.

**Comment by Oparin-Igor** [comment]
Добрый день, Наталья.
Вообще схемы были сделаны для того что бы избежать ошибок при конструировании например такие. При 
рисовании двери открывающуюся наружу можно вставить створку Z,  и много других подобных ошибок.
Все типы окон нарисовать сложно, всегда найдется что-то исключительное.

По поводу удаления и переименования систем я точно вам не отвечу, возможно это приведет к нежелательным последствиям.
Добавить систему могу.
Предоставьте состав профилей и какие будут по умолчанию.
С разбивкой по типам (рама, створка, импост, заполнение, добор и т.д.)

**Comment by aribaz** [comment]
Давайте я попробую на основе трехстворчатого порисовать еще какие-нибудь окошки, мне как раз прислали пару заказов на тестирование, может и не понадобится новая система, я посмотрела, что входит в состав в принципе вполне должно хватить для большого количества вариантов. 
А если переименовать нельзя, может сделать копию трехстворчатого и шаблон назвать просто Оконный блок?
Я понимаю, что невозможно нарисовать все типы окон, я к этому и не стремлюсь, просто эти 5 вариантов - они конечно часто встречаются, но это не весь список наиболее часто встречающихся окон.
Я хочу довнести наиболее часто встречающиеся окна, а что раз в пятилетку попадается или даже раз в год, то можно и нарисовать руками, главное чтобы оно нарисовалось. Идея в том, чтобы им каждый раз не пришлось один и тот же тип окна рисовать с нуля - это главное.
Я могу как-то эти окна сохранить в качестве шаблона/типового окна?

**Comment by aribaz** [comment]
Про лишнюю техвставку я ошиблась, импост на горизонтальный не поменяла, вот она и вставилась, а вот балконную закладку действительно есть возможность прицепить к раме низ, хотя физически это сделать невозможно. так как она по всей длине имеет два шипа, а пазов под них в рамном профиле нет.

**Comment by aribaz** [comment]
Использую в качестве основы четырех-створчатое, потому что на трехстворчатом через раз не делает перерасчет спецификации при изменении конструкции окна.

**Comment by aribaz** [comment]
Рисовать в целом получается достаточно много окон.
Можно продублировать шаблон Четырехстворчатое и назвать его просто Оконный блок, чтобы не возникало путаницы в головах менеджеров, что написано одно, а нарисовано другое?
Состав профилей пусть остается таким же.
