### ISSUE TITLE
Номер документа при изменении организации

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#103]
Я вот с чем столкнулась. 
Ранее я все заказы создавала от организации Арибаз, сегодня попробовала сделать заказ от имени Комфортного дома. нумерация заказов привязана к префиксу пользователя. Префикс пользователя не содержит данные об организации, так как префикс заказа созданного мной и для организации Арибаз и для организации Комфортный дом оинаков, более того нумерация заказов сквозная для всех организаций. предыдущий для Арибаз НЗАР00000007, а для следующего от Комфортного дома НЗАР00000008.
Мне кажется с точки зрения ведения бухгалтерии это (сквозная нумерация) не совсем правильно, особенно с точки зрения налоговых органов. Лишние вопросы а где заказ с номером N.
Я почему-то думала, что для заказов, составляемых пользователем от организации Комфортный дом префикс будет другим. Что-то типа как в 1С, если создают один и тот же тип документа от разных организаций, то они имеют каждый свою нумерацию и префикс внутри отдельно взятой организации.
Было бы очень удобно видеть в табчасти от какой организации ведутся расчеты с контрагентом, чтобы не заходить в каждый и не смотреть он это или нет.

**Comment by unpete** [comment]
Скорее всего, потерялась подписка на событие "при изменении организации".
Номер генерируется для организации по умолчанию, но он должен пересчитываться при редактировании  реквизитов.
Задачу переименовываю, т.к. она вообще про документы, а не конкретно про заказы

**Comment by unpete** [comment]
Добавил обработчик при изменении организации - просьба проверить.

Сделать нумерацию полностью "сквозной" не получится. В автономном режиме, когда нет связи с сервером, уникальность номера обеспечивается в рамках текущего пользователя.

> Лишние вопросы а где заказ с номером N

Этот вопрос существует только в голове бухгалтера.
Никаких проблем с налоговой из-за префиксов в нумерации заказов возникнуть не может.
Есть требование сквозной нумерации счетов-фактур, но она решается совсем другими средствами.

**Comment by aribaz** [comment]
Спасибо, работает.

**Comment by unpete** [comment]
Принято, что инициатор закрывает задачу после проверки, чтобы она не висела среди активных
