### ISSUE TITLE
Как нарисовать составной блок

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#105]
Игорь, подскажите, как мне нарисовать составной блок. Я говорю о балконном блоке, в котором есть балконная дверь и рядом одно или два окна.
Ну и в принципе как рисовать составные окна, например несколько глухарей (чаще всего) одного размера как правило иногда ставят ленточно рама к раме вертикально и/или горизонтально.
Их конечно теоретически можно нарисовать и посчитать отдельными строками, но с точки зрения клиента это не очень правильно.

**Comment by aribaz** [comment]
Я создаю сначала балконную дверь, далее новый слой и на нем рисую новое окно. Но ведь его надо расположить рядом с блоком (справа от него)и когда я начинаю на новом слое рисовать окно, привязываю первую точку к правому верхнему углу балконного блока, то профиль рамы верхний имеет угол около 30градусов, вместо угла 90. Я скорее всего что-то делаю не так, а вот что?

**Comment by unpete** [comment]
Рекомендую ознакомиться с [объектной моделью](https://github.com/oknosoft/windowbuilder/wiki/%D0%A1%D1%82%D1%80%D1%83%D0%BA%D1%82%D1%83%D1%80%D0%B0), чтобы использовать правильную терминологию.
У изделия есть слои.
Рамные контуры рекомендуется размещать в разных слоях, но это не обязательное требование.

**Comment by aribaz** [comment]
У меня получилось нарисовать составной блок, но вот в чем еще вопрос, инструмент уровнять действует только по опорным линиям, а если надо будет чтобы низ горбылька двери и низ створки окна были на одном уровне - это руками ловить, правильно я понимаю?
