### ISSUE TITLE
Цена на штапик  = 0

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#106]
Так как характеристика штапика в спецификации пуста, а в документе УЦН привязка цен осуществляется по характеристике, а  строчки с пустой характеристикой нет, то в спецификации штапик считается по цене 0р.

**Comment by aribaz** [comment]
Это же касается технологической вставки.
Тип древесины для штапиков и технологических вставок не цепляется автоматически, характеристика в спецификации остается пустой, и соответственно цена считается равной 0, хотя я цены на эти материалы установила с привязкой к типу древесины.
Но для основого профиля привязка типа древесины учитывается.

**Comment by unpete** [comment]
В спецификации соединений для строк номенклатуры штапиков была не указана формула "характеристика по параметрам". В результате, штапики оставались без характеристик.

**Comment by aribaz** [comment]
Работает, спасибо.
