### ISSUE TITLE
Копирование строки заказа (пожелания сервису)

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#107]
Сейчас пробую рисовать совсем другие окна. И вот что поняла. Было бы удобно иметь такой инструмент как копирование строки заказа.
Например у меня есть два вида окон которые по конфигурации ничем не отличаются как и по геометрическим параметрам, а отличаются только типом стеклопакета. С учетом того, что окно не типовое и его я рисовала руками, было бы здорово, если бы я (пользователь) имела возможность скопировать уже созданное окно с его геометрией и размерами, а потом зайти в него для редактирования и изменить в нем только тип стеклопакета и количество при необходимости, ну или цвет и тип ручек, в общем параметры окна, а рисовать его уже не надо - это позволит сократить время на создание заказа, и это намного удобнее, чем в одном и том же заказе рисовать еще раз практически такое же окно.
И вообще было бы здорово скопировать в одном заказе и вставить продукцию в другой.

**Comment by unpete** [comment]
- Копирование изделий доступно начиная с самых ранних версий построителя. При выборе типового блока, есть возможность указать не только _заказ-шаблон_, но вообще любой, в том числе - текущий заказ и далее - любое изделие этого заказа
- Еще замечание: шаблон отличается от обычного заказа _только_ состоянием транспорта (в интерфейсе этот реквизит отображается, как _Этап согласования_). Соответственно, любой заказ можно превратить в шаблон
- И еще, плодить шаблоны нужно с осторожностью - они жрут память могут снижать быстродействие на старых компьютерах

**Comment by aribaz** [comment]
А как это сделать? Есть кнопка штамп, где так и написано "Загрузить из типового блока или заказа", но когда ее нажимаю открываются только шаблоны, как там выбрать уже существующий и/или текущий заказ?

**Comment by unpete** [comment]
Открыть форму выбора заказов из поля со списком шаблонов можно так же, как любую другую форму выбора: либо мышью по ссылке _показать всё_ (когда мышь над стрелочкой выпадающего списка), либо нажав {F4} на клавиатуре, при выделенном поле ввода.

Была ошибка в форме выбора из-за которой список заказов оказался пустым.
Исправил + дополнительный бантик: в форму выбора заказа добавлено отображение эскизов изделий текущего заказа (так же, как в основной форме списка заказов)

**Comment by aribaz** [comment]
Спасибо все работает.
