### ISSUE TITLE
? Цвет ручек и колпачков для балконной двери.

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#108]
Как и где можно выбрать цвет ручек и колпачков для балконной двери?

**Comment by aribaz** [comment]
Имею ввиду колпачки для петель
CF 495 160 H1 02 Рамная часть бихр
CG 495 160 H1 02 Створочная часть бихр

Для них есть такие варианты цветов (по одному колпачку на каждую петлю вне зависимости от того рамная она или стрворчатая):

1. никель
2. мат. никель
3. бронза
4. золото
5. белая
6. коричневая

**Comment by nmivan** [comment]
@aribaz , проблема еще актуальна?
