### ISSUE TITLE
Нулевая цена на профиль Дер. СтворкаНиз 79

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#109]
На этот профиль цена установлена в документе УЦН, а в спецификациях этот профиль  стоит с ценой 0р.

**Comment by Oparin-Igor** [comment]
Проверьте даты.

**Comment by aribaz** [comment]
Документ УЦН от 09-09-16, заказ я создала 05-10-16, и все равно цена на этот профиль в спецификации равна 0, как и ранее.

**Comment by unpete** [comment]
Возможно, проблема возникает, когда на номенклатуру + цвет есть несколько цен, установленных разными датами. Просьба поставить эксперимент. Если подтвердится - полезу в код ценообразования.
Сейчас с ценой на СтворкуНиз 79 всё хорошо.

Еще гипотеза: цены может портить обмен с Комплексной автоматизацией. Там у документа установки цен другая структура, а у нас к шине данных подключены одновременно и Заказ дилера и КА.

Важно помнить, что цены номенклатуры применяются при старте приложения. Если изменить и провести документ установки цен, в текущем сеансе ничего не произойдёт - надо перезагрузить страницу в браузере.

**Comment by aribaz** [comment]
Сейчас цена профиля есть в спецификации. Это здорово.

А как  привязать цену к цвету?
Список выбора характеристик для ЛКМ пуст. Может я что-то не так поняла, что надо сделать?
Я устанавливала цену одним днем для Створка Низ 79 и для Створка 79, проблема возникла только с Створка Низ79, к цветам не привязывалась, так как не знаю как это сделать.

Про перезагрузить страничку, у меня уже рефлекс выработался )

**Comment by unpete** [comment]
> А как привязать цену к цвету?

Три варианта:
- Поручить Игорю, чтобы он создал характеристики без привязки к заказам
- Запросить доступ к редактированию 1С-части Заказа дилера с ролью Технолог и создать характеристики самостоятельно
- Запросить интерфейс для создания характеристик на стороне сервиса
