### ISSUE TITLE
Профиль низа рамы для дверей

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#110]
Для балконной двери в качестве нижнего профиля рамы не могу выбрать (недоступен) Порог.
За основу был использован шаблон Балконная дверь.

**Comment by Oparin-Igor** [comment]
Порог только во входных дверях.
Про балконные не оговаривали.

**Comment by Oparin-Igor** [comment]
Пришлите схему нижнего сечения.

**Comment by aribaz** [comment]
Игорь, я уточнила у конструктора про пороги. Вот что выяснила.
В качестве нижнего профиля рамы в балконной двери могут быть:

1. Рама Низ83
2. Порог 63
3. Порог 83

Еще выяснилось, что необходимо добавить две номенклатуры профилей:

1. ПорогСкос 63
2. ПорогСкос 83

Итого для балконной двери в качестве нижнего профиля рамы могут быть:

1. Рама Низ83
2. Порог 63
3. Порог 83
4. ПорогСкос 63
5. ПорогСкос 83

Два новых профиля также могут быть нижним профилем рамы и во входных дверях.

В некоторых случаях на профили типа Порог (и прямые, и скошенные) может устанавливаться Алюминиевый порог (артикул W86/32T.I) - 1 хлыст 6м.пог. - ситуация распространенная, желание заказчика. Крепится он к нижнему профилю рамы с помощью саморезов 2,5х13 с шагом 200мм.

На входных дверях еще может присутствовать помимо Алюминиевого порога другой алюминиевый профиль - Капельник, но он  крепится к нижнему профилю створки двери.

Файл с сечениями и внешним видом новых порогов отправила на почту в формате DWG.

**Comment by aribaz** [comment]
Игорь, прошу меня извинить еще раз. Но вчера у начальника цеха выяснила еще некоторые детали.

Я писала выше:

> В некоторых случаях на профили типа Порог (и прямые, и скошенные) может устанавливаться Алюминиевый порог (артикул W86 / 32T.I) - 1 хлыст = 6м.пог. - Ситуация распространенная, желание заказчика. Это относится и к балконным и ко входным дверям. Крепится он к нижнему профилю рамы с помощью саморезов 2,5х13 с шагом 200мм.

Как оказалось на профиль типа Порог (прямой  и скошенный) может устанавливаться/не устанавливаться только Алюминиевая накладка (алюминиевая тонкая планка), а не Алюминиевый порог. Это тоже желание заказчика. У нее один вариант исполнения - алюминиевый.

А то, что я описала как Алюминиевый порог (W86/32T.I) - это самостоятельный профиль рамы по низу (он покупной, сделан из алюминия), который может применяться как на входных, так и на балконных дверях. Его установка требует уменьшения (среза - дополнительная операция) наплава на профиле нижней створки двери. И применение этого алюминиевого порога  - это тоже желание заказчика.
![83 63](https://cloud.githubusercontent.com/assets/22028048/20102185/3188274c-a5d6-11e6-8a2e-9ed673fc19a8.jpg)
![default](https://cloud.githubusercontent.com/assets/22028048/20102187/31882364-a5d6-11e6-9023-f28340779808.jpg)
![default](https://cloud.githubusercontent.com/assets/22028048/20102186/31883c32-a5d6-11e6-8573-ae0d9be44306.jpg)
![default](https://cloud.githubusercontent.com/assets/22028048/20102188/318b2e42-a5d6-11e6-94fc-40a1c3339c4b.jpg)

**Comment by nmivan** [comment]
@aribaz , чем кончилась эта задача?

**Comment by aribaz** [comment]
@nmivan Профили привязаны мной в соответствии с технологией использования на производстве. Все работает, закрываю.
