### ISSUE TITLE
Рисование. TAB/ALT+TAB

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#111]
Евгений, у вас в уроке по рисованию вы единожды поставив точку рисуете сразу весь контур задавая размеры и точки с помощью кнопки Tab/Alt+Tab, у меня так не получается. Когда я ставлю первую кнопку мышкой, то с помощью этих клавиш определяю размер и положение профиля, создаю конечную точку, а когда рисую последующую палку, то эти кнопки не дают результата (поля для ввода не становятся доступными для ввода, приходится мышкой указывать положение конечной точки и в таком случае контур обрывается и не получается нарисовать профиль нужной длины (немного не попадаю), чтобы дорисовать контур приходится магнитом привязываться к последней точке предварительно исправив ее геометрические размеры, а вот  уже для новой (третьей) палки поля для ввода активны (доступны для изменения) посредством этих клавиш.
Может я что-то не так делаю?

**Comment by unpete** [comment]
- Про комбинацию Alt+Tab ничего не знаю. Есть Shift+Tab. Вот список [быстрых клавиш](https://github.com/oknosoft/windowbuilder/wiki/%D0%9A%D0%BB%D0%B0%D0%B2%D0%B8%D0%B0%D1%82%D1%83%D1%80%D0%BD%D0%B0%D1%8F-%D0%BD%D0%B0%D0%B2%D0%B8%D0%B3%D0%B0%D1%86%D0%B8%D1%8F-%D0%B2-%D1%82%D0%B0%D0%B1%D0%BB%D0%B8%D1%86%D0%B0%D1%85)
- Проблему не понял. Если задача важная - покажете на конференции

**Comment by aribaz** [comment]
Все поняла и нашла.
Спасибо.

**Comment by aribaz** [comment]
При рисовании третьей точки (конец второго профиля) - чтобы пользоваться полями ввода нажимаем Shif+Tab и продолжаем.
Сначала рисуем контур, а потом меняем профили в нем при необходимости.
