### ISSUE TITLE
Маркировка блоков

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#112]
Я вот о чем подумала.
Наши окна маркируются автоматически, и в состав маркировки входит заказ, номер окна, тип окна(шаблона) размеры и площадь.
Здесь есть некоторые сложности, во всяком случае у нас.
Первое это Заказ. Так как номер заказа никто и никогда к сожалению не знает, а все ориентируются на имя непосредственного заказчика или месторасположение заказа. Я просила в 1С добавить колонку клиент, чтобы можно было легко определять что это за заказ, это хорошо. Менеджер глядя в табличку увидит что это за заказ, а вот как быть потом с рабочими цеха, они все тоже привыкли к маркировке на основе Заказчика(имя, местоположение), а не номера заказа, хотя и сегодня каждый заказ имеет свой номер - но этот номер никому и ни о чем не говорит. Ведь практически каждый заказ имеет окно 1,2,3, а как ребятам в цеху определять какие палки/окна к чему относятся? Если станут ориентироваться на номер (что в принципе логично), то обязательно ошибутся и не один десяток раз, ведь номера заказов друг от друга отличаются мало, в то время как заказчик всегда уникален и тут сложно ошибиться между Мамонтово/01/ и Бабаев/01/ (например). С одной стороны можно для этих целей использовать внутренний номер заказа, тогда он автоматом попадает в маркировку окна и проблема решена, но когда мы разговаривали, вы сказали что внутренний номер не надо использовать для идентификации клиента, а он прямо сам напрашивается на это.
Еще один момент  - это правила маркировки окон, они определены архитектурой здания и заложены в СНИПах, являются обязательными при конструировании здания инженерами и архитекторами. 
Они гласят следующее:
маркировка окон начинается с первого (цокольного) этажа здания с крайнего левого угла и периметру здания по ходу часовой стрелки, ведется поэтажно (сначала один этаж по часовой, потом второй по часовой и так далее).
Обычно так: ОК (ОБ)-1, ОК-2 ит.д. , сквозная нумерация в пределах здания; и допускается второй варинат: ОК-101, ОК-101...., ОК-201, где 100 - это окна первого этажа, 200 - окна второго этажа.
Очень часто на больших объектах плана здания на момент составления сметы у нас нет, по разным объективным причинам, и менеджер волен присваивать нумерацию как ему вздумается (и тут чем они руководствуются мне вообще не ясно), и эта его нумерация ну очень далека от той что должна быть, а именно на ту, что должна быть ориентируются монтажники при производстве монтажных работ. Планы объекта мы конечно получаем, но позже того момента, когда составляем смету.
Что мы получаем. Менеджер агульно (и не он в этом виноват) проставил маркировку, максимум что он может сделать это в примечании к окну добавить информацию об этаже для этого окна, если она у него есть в данный момент (а как правило нет, потому что это в основном тендеры и вообще у больших объектов своя специфика), производство как правило начинает делать заказ пачками - первые 10, вторые десять (условно). И получается вот что: мы эти два десятка везем на объект, и на объекте из этих 20 окон можем поставить 5 на первом этаже, причем не по фасаду ленточно (по периметру), а два с одного фасад и три с другого фасада, вторые пять на втором и тоже не на одном фасаде и так далее. Строители (генподрядчики здания) просят (я бы сказала требуют) нас как субподрядчиков монтировать окна по-этажно, так того требуют СНИПы и правила производства строительных работ, и нам от этих требований не уйти, так уж сложилась строительная отрасль и не нам менять правила. И более того нам не подписывают акты (и соответственно не оплачивают) если мы ставим например 50 окон но по всему зданию, из которых 7 на первом этаже, нам максимум подпишут акт на 7 необходимых им окон, а так как там суммы получаются не малые и необходимы они на закупку сырья (если окна дубовые то это ооочень большие суммы) то мы получаемся в плохом положении окна мы сделали (примерно на ту сумму, что нам авансом оплатили), денег не получили, а чтобы сделать те, что требуют нужны еще деньги чтобы купить сырье и изготовить. Лес это специфический материал, он то есть на рынке, то нет, особенно хороший - а именно он дает наименьшее количество рекламаций по качеству изделий. А потом нам так долго мозг вынсят...
Нужен какой-то способ/инструмент, чтобы маркировку окон по плану можно было связать с маркировкой уже существующей и чтобы именно по плановой маркировке ориентироваться при составлении задания на производство, сделать нужные сейчас окна  - это здесь главное. Окна очень часто похожи могут отличаться на 1см-5мм - это я не утрирую, и искать среди них что же именно надо запустить ориентируясь на нашу маркировку и размеры очень и очень тяжело. Такая работа по сопоставлению все равно будет проделана, но надо чтобы она как-то отразилась в заказе.
Таких заказов в принципе не много в год, но они большие по 300 штук примерно, а то и больше.
Это не срочно, но в принципе можете что-то предложить на эту тему?

**Comment by unpete** [comment]
Напомню, что не следует путать информацию базы данных и печатные формы.
Каждая строка заказа имеет поле "комментарий", где можно разместить, например, обозначение для печати

**Comment by unpete** [comment]
Для цеха, есть безбумажка.
Рабочий может сфотографировать QR код своим телефоном и получить подробную информацию по любому изделию.
