### ISSUE TITLE
Фильтр вставок при групповой вставке импостов и раскладок

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#113]
При использовании этого инструмента, при выборе Импост, в качестве вставки для деления по оси Y в качестве выбора доступны не все импосты, но зато много стеклопакетов, стекол и даже лак.
А для оси Х все нормально, только элементы типа импост все имеющиеся.

**Comment by nmivan** [comment]
@aribaz , задача актуальна?

**Comment by aribaz** [comment]
@nmivan все работает штатно
