### ISSUE TITLE
Инструмент Размеры и сдвиг

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#114]
Я не совсем понимаю как он работает.
В этом инструменте есть три основные кнопки, которые позволяют измерить/изменить расстояние межу элементами и узлами, а так же размерные линии. Есть еще три дополнительные, которые по идее (если я правильно поняла) позволяют привязаться к линиям профиля (внешняя, внутренняя, опорная или ось).
Как мне показалось все эти три дополнительные кнопки работают только для опорных линий, вне зависимости от того какую я нажимаю кнопку привязки линий в комбинации с основной.
И если для расстояния между элементами то расстояние (цифру) которое я ввожу в поле вода оно и отображается на чертеже, хоть и только в привязке к опорной линии, то есть совпадают цифры (ввожу 500 и на чертеже становится 500).
То для инструмента Расстояние между узлами цифры отличаются в 2 мм, то есть я ввожу например 500, а на чертеже отображается 502. 
Идея с привязкой к линиям профиля классная, но то ли я не поняла как это работает, то ли привязка к линиям не работает. Потому что вне зависимости от выбора расположения линий на чертеже размерные линии исходят от опорных линий и никак иначе и для Узлов и для Элементов и для Размерных линий. И получается обе эти кнопки дают одинаковый результат, но кнопка Расстояние между элементами удобнее.
Или я что-то не так делаю?

И для инструмента размерной линии к первой точке (узлу) прилипает хорошо, а на конечной точке часто промахиваюсь мимо узла и размерная линия или улетает совсем или убегает на противоположный конец по диагонали.
Тут наверное есть определенные нюансы или это ловкость рук?

**Comment by unpete** [comment]
Инструмент `размеры и сдвиг` и `пользовательские размерные линии` существенно доработаны - реализована привязки к любым точкам профиля и позиционирование относительно внешних в внутренних рёбер профиля

**Comment by nmivan** [comment]
@aribaz , еще остались вопросы по задаче?

**Comment by aribaz** [comment]
@nmivan, нет все понятно
