### ISSUE TITLE
Paging: Вычислять и переходить на нужную страницу по событию закрытия формы объекта

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#115]
Вновь созданные заказы не сохраняются вне зависимости от Организации.
Хотя новый заказ создать можно, маркировка и заказа  и изделий в нем соответствует выбранной организации, но по нажатию на кнопку Сохранить заказ и далее закрыть созданный заказ не отображается в Черновиках.

**Comment by unpete** [comment]
Объекты сохраняются нормально, но если список оказывается длиннее 30 записей, новые объекты попадают на вторую или последующие страницы и их не видно на исходной странице.
Задачу переименовал

**Comment by aribaz** [comment]
Спасибо, нашла. Я не сообразила, просто до строчки с указанием страниц было еще пустое место на несколько заказов, штуки 3 точно еще войдет, поэтому и не подумала что так может быть.

**Comment by unpete** [comment]
Задача пусть повисит в открытых.
Поведение системы, вводит пользователя в заблуждение и это желательно исправить

**Comment by aribaz** [comment]
У меня в списке всего 22 заказа, на одну страничку вмещается 15

**Comment by nmivan** [comment]
@unpete , мы не решили еще эту задачу?

**Comment by unpete** [comment]
Это про динсписок. Не решили, но закрываю до лучших времён.
