### ISSUE TITLE
Составной тип в поле выбора

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#116]
Как можно отразить состоявшуюся оплату по заказу в сервисе? 
Ведь сервис не обязывает к использованию 1С, а пока насколько я поняла, оплату можно только на стороне 1С отразить.
Вопрос вот почему. В этой версии 1С мы не ведем сейчас ничего, и для перехода на новую платформу необходимо время и обучение бухгалтера работе с этой версией (она у нас с компьютерами и программами на ВЫ). Если мы хотим запустить тестирование заказов и начать пользоваться сервисом до настройки диспетчеризации неплохо было бы иметь возможность провести оплату/аванс по заказу, это позволит менеджерам/директору видеть реальную картину по заказам с точки зрения оплат и избавит от необходимости вести таблички для понимания происходящего. Это еще один плюс в пользу перехода на Сервис (для менеджеров, для нас и так понятны все плюсы) и шаг к успешному внедрению уже на стадии тестирования и использовании сервиса не в полную силу.

**Comment by unpete** [comment]
Добавил закладку с документами оплаты и отгрузки рядом с установкой цен.
Права не проверял, но по замыслу, дилеры могут только смотреть.
Добавлены новые роли:
- Редактирование оплат
- Редактирование отгрузок
- Редактирование диспетчеризации (для рабочих в цехе, которые не могут править заказы, но могут регистрировать события по изделиям)

**Comment by aribaz** [comment]
Попробовала сделать приходник. В качестве Контрагента, подотчетника дает возможность выбрать только из справочника Физические лица Арибаза, поле ответственный обязательно и для него есть возможность выбрать только имя пользователя из всех имеющихся, хотя по факту это должен быть кассир, а на стороне 1С когда мы с вами делали приходники, там ответственного вообще не указывали - не так разве? Не могу указать за какой конкретно заказ осуществляется оплата, список выбора пуст.
Номер созданного мною приходника имеет номер НЗ2-0000001, а на стороне 1С или АР... или АК..., номера платежных документов наверное должны быть сквозными для организации. И как быть с тем, что сейчас номера приходников и вообще любые номера у нас назначаются совсем другой конфигурацией?
Мы можем на стороне сервиса этими документами просто регистрировать факт оплаты и тогда до некоторой поры присвоение номеров в сервисе нас не очень волнует, а действительные документы делать на стороне ЗУП ведь реальная бухгалтерия в ней сейчас ведется со всей вытекающей отчетностью.

Для Оплаты по карте в качестве контрагента могу выбрать именно контрагента, могу выбрать заказ, ответственный как и в Приходнике. Номер НЗ2-...

С платежкой все так же как и с оплатой по карте.

Реализация:
Контрагента выбрать могу, ответственный обязательно (один из пользователей), номер НЗ2-....
А вот с тем, что хочу реализовать сложнее - нам открывается список товаров, которые я и должна выбрать, для этого надо зайти в Продукцию, а в ней нет группы Деревянный профиль.
Мне кажется такая форма не совсем удобна, потому что выбирать из огромного списка изделия - то еще развлечение. Я понимаю, что должна быть возможность закрыть не заказ в целом, а отпустить часть заказа. Может сделать еще строчку Заказ на вкладке Реквизиты, и чтобы на вкладке товары можно было уже выбирать изделия из одного заказа, так будет быстрее и проще. Ведь документ реализация всегда делаем по заказу, а не по контрагенту, хотя конечно теоретически можно в пределах одного контрагента и по нескольким заказам, но это усложняет жизнь бухгалтеру, они никогда так не делают (во всяком случае наши). Ну или чтобы список товаров хотя бы ограничивался набором изделий для пары Организация- Контрагент.  

Вот что обнаружила. При выборе товара список видимости продукции отображается не верно, если использовать колесо, то последнее что я вижу это TROCAL, и все, а если стрелками шагать вниз, то после него я вижу еще 9 видов продукции в том числе и Деревянный профиль, который ранее не увидела. (это же касается вкладки Технология, раздел Номенклатура/Продукция

И если туда зайти (в Деревянный профиль), то я увижу 6 строчек с наименованиями Дуб сращенный, Дуб цельноламельный (и еще 4 типа дерева), если выбрать один из них, то соответственно никаких размеров и параметров непосредственной продукции нет, заполняется только графа Номенклатура, а графы кол-во, Ед, Цена, скидка, НДС, Сумма, Сумма НДС, Заказ остаются пустыми, но в них могу вписать что угодно. В графе заказ могу выбрать Заказ согласно паре Организация-Контрагент, но это ничего не меняет для выбора конкретных  изделий. В общем реализацию сделать не смогла, хоть она и провелась в таком виде. Хотя если это инструмент регистрации выпуска продукции, для отображения статуса заказа, то в целом неплохо, только он никак не отобразился ни на вкладке исполнено, ни на вкладке Изготовлено.
Все заказы, по которым я оформила платежи отобразились в Фильтре Долги с указанными мной суммами.

**Comment by unpete** [comment]
> Не могу указать за какой конкретно заказ

Можете, работает отбор по контрагенту + организации

> номера документов [...] сквозными для организации

Для этого пришлось бы отказаться от автономного режима. В текущей реализации, номера уникальны в пределах пользователя

>  И как быть с тем, что сейчас любые номера назначаются совсем другой конфигурацией

Выкинуть "другую конфигурацию" и не возвращаться к этому вопросу

> Заполнение документов

Это отдельная задача. Можно будет сделать ввод на основании, групповое заполнение и т.д. Сейчас  формы позволяют зарегистрировать данные. Эргономику отодвигаем на следующий этап

> Прокрутка и динамические списки

Посмотрите [этот документ](https://github.com/oknosoft/metadata.js/blob/master/roadmap.md)
Для v2 уже реализован infinite loader - [вот видео](https://youtu.be/x1oFNfapwSE?list=PLiVLBB_TTj5njgxk5E_EjwxzCGM4XyKlQ)
Формы объектов и списков со временем будут более функциональными. Предусмотрены фильтрация, сортировка и группировка

**Comment by aribaz** [comment]
Так у меня и беда в том что для Приходника (только для него) в качестве контрагента я не могу выбрать контрагента, только физические лица из справочника, а справочник Котрагентов не доступен.

**Comment by unpete** [comment]
Исправил ошибку при выборе составного типа в элементе управления _OCombo_
![composite_types](https://cloud.githubusercontent.com/assets/12096477/20845573/9078b34c-b8e7-11e6-9ab7-031d49e6b323.png)

**Comment by aribaz** [comment]
Спасибо, работает.
Закрываю
