### ISSUE TITLE
Створка Низ79 с водоотводом, водоотвод не попадает в спецификацию

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#117]
При выборе нижнего профиля створки Створка Низ79 с водоотводом в спецификацию с  этим профилем должны попадать следующие материалы:
Профиль покрытия оконных створок (арт. FP-18.01), м.пог.
накладка торц. на профиль FP-18, лев (коричневая или белая), шт
накладка торц. на профиль FP-18, прав (коричневая или белая), шт
Держатель защелкивающийся 1шт на 150мм профиля
Саморез 3х16 1шт на 150мм профиля
Но сегодня этого не происходит.

**Comment by Oparin-Igor** [comment]
При выборе нижнего профиля створки Створка Низ79 с водоотводом в спецификацию с этим профилем должны попадает
Профиль покрытия оконных створок (арт. FP-18.01), м.пог.
накладка торц. на профиль FP-18, лев (коричневая или белая), шт
накладка торц. на профиль FP-18, прав (коричневая или белая), шт

**Comment by Oparin-Igor** [comment]
Держатель защелкивающийся 1шт на 150мм профиля
Саморез 3х16 1шт на 150мм профиля
Добавлю,  изначально не оговаривали.

**Comment by aribaz** [comment]
Здесь наверное вы меня не совсем правильно понимаете.

Профиль покрытия оконных створок и Дер. Профиль водоотводный 22/34 - это два разных профиля.
Первый из которых устанавливается на профиль створки и примыкает к стеклопакету и он есть только если в качестве нижнего профиля створки выбираем Створка низ79 с водоотводом, а второй  присутствует всегда и устанавливается физически на пофиль рама Низ.

Да при выборе нижнего профиля створки "Створка Низ79 с водоотводом" в спецификацию попадают уже сегодня:

1. - Створканиз79
2. - Дер. Профиль водоотводный 22/34
3. - Дер. Торцевая накл. к проф. водоотв. прав.
4. - Дер. Торцевая накл. к проф. водоотв. лев.

Но это не весь список , должно быть так:

1. Створканиз79
2. Дер. Профиль водоотводный 22/34 (это обязательно)
3. Дер. Торцевая накл. к проф. водоотв. прав.
4. Дер. Торцевая накл. к проф. водоотв. лев.
5. Профиль покрытия оконных створок  (арт. FP-18.01), м.пог. (это желание заказчика)
6. накладка торц. на профиль FP-18, лев (коричневая или белая), шт
7. накладка торц. на профиль FP-18, прав (коричневая или белая), шт
8. Держатель защелкивающийся 1шт на 150мм профиля (он нужен чтобы закрепить профиль покрытия оконных створок на Створке низ79)
9. Саморез 3х16 1шт на 150мм профиля (он  нужен чтобы прикрутить держатель к профилю створка Низ79)

Профиль покрытия оконных створок так же как и Водоотводный профиль 22/34 покупаем неокрашенный, и для него тоже нужна таблица соответствия цветов, как и для профиля 22/34

И вот еще что обнаружила если я выбираю в качестве нижнего профиля створки профиль Створка Низ79, то в спецификацию попадает только сам профиль Створка Низ79, а должно быть так:
1. - СтворкаНиз79
2. - Дер. Профиль водоотводный 22/34 (он есть всегда, это не зависит от желания заказчика)
3. - Дер. Торцевая накл. к проф. водоотв. прав.
4. - Дер. Торцевая накл. к проф. водоотв. лев.

**Comment by aribaz** [comment]
Выяснила еще некоторые сведения по этому профилю. Оказывается по великому желанию заказчика мы может установить этот профиль не только на Створку низ 79, но и на горбыльки, а так же на техвставку. В общем получается  на нижний профиль контура в который устанавливается заполнение (это может быть и филенка и стеклопакет). Такие новшества ввели недавно, раньше только на низ створки ставили и все.

У нас получается такие параметры:

Профиль покрытия: 

- да
- нет

Место установки профиля:

- Только  низ створки (для балконной двери он крепится к балконной закладке, а не к створке низ79, а  если окно: глухарь со створкой - то на глухую часть по низу заполнения его тоже ставят всегда)

- Низ  заполнения (это и низ створки, и горбыльки, и низ глухих частей)

- Низ створки и низ глухих частей (например, в окне есть горбыльки и вверху глухая фрамуга, ставят на низ створки и низ фрамуги, а на горбыльки не ставят).

**Comment by Oparin-Igor** [comment]
Вставка "Дер СтворкаНиз 79"
К Услуге "Покраска профиля покр. створок" добавить характеристику цвет "" выбранный пользователем.
Соединение "Дер. || рам ств низ 79"
К Услуге "Покраска профиля покр. створок" добавить характеристику цвет "" выбранный пользователем.

**Comment by aribaz** [comment]
Эту задачу закрываю, так как со створкой низ теперь он попадает. Вопрос что еще в других профилях нужен вынесен в отдельную задачу #181
