### ISSUE TITLE
Водоотводный профиль 22/34 (характеристики)

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#118]
Этот профиль поставляется Изготовителем в трех цветах:
1. Неокрашенный
2. RAL 8017
3. RAL 9016

Нужны эти характеристики для этого профиля, чтобы можно было было установить цены на них (они разные).

Еще один важный момент по этому профилю.
Чтобы получить любой другой цвет, отличный от цветов Изготовителя, мы закупаем неокрашенный профиль и при необходимости везем необходимое количество неокрашенного профиля в третью организацию на покраску. В таком случае в спецификации должен значится профиль неокрашенный и Услуга "Окраска профиля" и необходимо какое-нибудь поле для справочной информации о необходимом цвете, чтобы и производственники знали (что брать со склада) и снабженец (в какой цвет красить). Стоимость услуги окраски профиля, если правильно помню, не зависит от цвета, но я уточню.
По факту получается профиль может быть трех цветов:
1. RAL 8017
2. RAL 9016
3. Заказной

Мы никогда не устанавливаем в изделие неокрашенный профиль, а для цвета Заказной должно отобразиться поле для явного указания необходимого цвета, как правило это цвета RAL.

Для торцевых накладок к этому профилю - они бывают двух цветов:
Коричневые и белые, цена на них одинаковая, но в спецификации должна быть информация о том, какого цвета накладки должно взять производство.

**Comment by Oparin-Igor** [comment]
В старой версии программы цвета привязывались через справочник цвето-ценовые группы, сейчас
как мне объяснил Евгений, через формулы, но я этой технологией еще не владею, нет достаточного количества примеров.

**Comment by nmivan** [comment]
@aribaz , эта задача решена?

**Comment by aribaz** [comment]
@nmivan закрываю
