### ISSUE TITLE
Печатная форма. Ведомость потребности материалов по заказу.

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#119]
Созрела необходимость в первой индивидуальной печатной форме. 
Ведомость потребности материалов на заказ. 
Должна быть возможность эту ведомость конвертировать в формат xls или если можно будет выделить табличку, скопировать и вставить в файл Excel, тоже хорошо.
Ввиду того, что в ближайшем будущем планируем начать тестирование и использование сервиса для определения стоимости заказа, я пришла к мысли, что нам может помочь некая промежуточная стадия между расчетом заказа и диспетчеризацией.
Ведомость потребности материалов - это аналог спецификации, в котором материалы сгруппированы по типам материалов, а потребность в них суммирована в пределах каждого изделия или заказа .
Например для одностворчатого окна в ней будет не 4 строчки с Уплотнителем 3050 (как в спецификации), а одна на каждую створку, так как уплотнитель устанавливается одним цельным отрезком по периметру створки, это же касается и силикона и самоклеющейся ленты. То как должна она выглядеть, я сделаю пример.

Когда  мы этим сервисом начнем пользоваться для определения стоимости заказа, мы столкнемся с тем, что для того чтобы посчитать необходимые материалы для снабжения надо отрисовать заказ руками конструктора, это процесс не быстрый. Эта табличка поможет нам значительно сократить процесс. При необходимости конечно конструктор отрисует заказ для производства, но закупить материалы необходимо до того как заказ попадет в производство и здесь у нас будет запас времени. Снизим степень авральности работы.
Сегодня у нас в производство поступает чертеж с внешним видом окна, на котором есть пометки, при необходимости, конструктора о пазах, или нестандартном профиле, заодно можно будет попробовать протестировать эскизы получаемые в Сервисе, у рабочих будет возможность начать понимать как все будет выглядеть, потому что разница небольшая во внешнем виде чертежей есть и к ней надо привыкнуть. Безбумажка для цеха это хорошо, но эскиз изделия в цеху должен быть.
Помимо прочего это и в будущем, когда заработает сервис в полную силу и когда перейдем на 1С: КА,  она позволит нам списывать материалы на заказы по бухгалтерии. Ведь если для организаций Арибаз и Комфортный дом далее это можно будет делать автоматом на стороне 1С, то для организации ИП Доронин - не все так просто и все что пошло на заказы этого ИП, а куплено за официальные деньги Арибаз или Комфортного дома (а такое бывает, к сожалению) должно будет рассредоточиться на заказах Арибаза и/или Комфортного дома (это издержки нашей жизни, нам от них не уйти), а для того, чтобы это сделать надо знать сколько и чего пошло на каждый заказ ИП Доронин.
Скорее всего нам хватит общей потребности в материалах на весь заказ в целом,  а не на каждое изделие в отдельности.
И она должна выглядеть примерно следующим образом (состав):

**Профиль дерево**:
Рама83 700мм - 2шт 
Рама 83 1200мм - 2шт 
Створка 79 650мм -1шт
Створка 79 1200мм - 2шт
Створка 79 Низ 650 - 1шт
                        _Итого: 8шт_
**Штапик**
Штапик 18/18 630мм- 4шт

**Стеклопакеты**
4-16-4-12-4 580х1100-1шт (0,638кв.м)
                                   Итого: 1шт. (0,638кв.м)
**ЛКМ**
Лак (цвет) - 0,84л
Грунт (цвет) 0,42л

**Уплотняющие материалы и силикон**
Уплотнитель 3053 - 3,04 м.пог.
Уплотнитель 3070 - 2,85 м.пог
Силикон 750мл

Примерно так. Список не полный, но принцип понятен я думаю

Это нам позволит более продуктивно стартовать, это очень важно для нас. Это нам позволит получить меньше негатива на самом раннем этапе со стороны не только менеджера (их преимущества очевидны), но и  конструктора (а это очень важно) и снабжения, даст им возможность оценить преимущества сервиса уже на этом этапе.

Если этой таблички не будет, мы конечно выживем, но преимущества сервиса в сегодняшнем виде с точки зрения конструктора и снабжения очень малы, если не ситуация не станет обратной для них. И я изначально это понимаю, но мне важно дать понять именно конструктору и снабжению, что их жизнь от этого не только не усложнится, а облегчится. Только так мы сможем успешно освоить внедрение. Конструктор и без того переживает за то, что останется без работы, и все наши увещевания о том, что этого не произойдет - ни на грамм ее не успокаивают.

Ведь обрабатывая заказы таким образом (без диспетчеризации) мы повысим скорость обработки заказа на этапе расчета, а вот конструктор наш обалдеет от числа заказов, подлежащих обработке, будет скапливаться большое количество необработанных заказов и у снабжения, что негативно скажется на внедрении сервиса это раз, а во-вторых, на самом производстве и надо снизить прогнозируемые потери.
О возможных трудностях подобного поэтапного внедрения сервиса, я Сергея предупредила, и все же он хочет внедрять поэтапно, менеджеры зашиваются, некоторые заказы теряем из-за нехватки времени.
Что скажете?

**Comment by aribaz** [comment]
[Ведомость потребности материалов.xlsx](https://github.com/oknosoft/windowbuilder/files/522105/default.xlsx)

Это примерно.
Я пока не совсем понимаю для себя как правильнее сделать.
Я хотела сначала выделять по строкам материалы типа уплотнитель, силикон и т.п. для каждой створки изделия и иметь возможность видеть сумму расхода по этому материалу. А может и не надо по створкам выделять для этих материалов
А вот для профилей, нужна отдельная строчка на палку определенной длины - это точно.
Может что подскажете?

**Comment by aribaz** [comment]
Еще наверное для ведомости нужна такая опция, как какую именно группу материалов выгрузить в файл, чтобы потом не заниматься удалением ненужного; а не только для какого заказа/заказов или изделия/изделий.
Варианты:
Всю (для списания)
Стеклопакеты
Профиль с привязкой к типу материала и с возможностью штапики и основной профиль отдельно выводить
Уплотнитель
Силикон
ЛКМ
и далее по табличке (там я группы матеиалов выделила).

**Comment by unpete** [comment]
Чтобы не делать большую работу 2 раза, математику абстрактного отчета с фильтрами и группировками будем рисовать сразу в терминах v2. Подзадачи:

- [ ] Каркас веб-приложения _Заказ дилера_ (metadata v2 + react + redux)
- [ ] Авторизация
- [ ] Формы выбора заказов и продукций
- [ ] Отчет _Анализ потребностей_

**Comment by aribaz** [comment]
Евгений, добрый вечер.
Вы как-то писали, что скоро снимите видео на эту тему. Можно ли завтра на конференции увидеть как это работает? 
Я в среду и четверг еду на фабрику на полный день, буду учить создавать заказы и рисовать новые изделия двух менеджеров, у них что-то не совсем получается самостоятельно, было бы здорово, если бы заодно показала и эту возможность.

**Comment by unpete** [comment]
см. видео [отчет потребность в материалах](https://youtu.be/4RSgzawVEqo?list=PLiVLBB_TTj5mQXHOzodkzP3duImksxVgB)

**Comment by aribaz** [comment]
Спасибо, работает.

**Comment by aribaz** [comment]
Евгений, у меня не работает кнопка заполнить по заказу. Появляется пустое окно и в нем поле Найти не активно.
![image](https://cloud.githubusercontent.com/assets/22028048/22422747/1828493e-e6ff-11e6-9bd0-036c82522fbe.png)

**Comment by aribaz** [comment]
Все работает, я не все указала

**Comment by aribaz** [comment]
А вот поле Найти все равно не работает, при наведении на него появляется кружок  зачеркнутый  (типа стоянка запрещена), и курсор даже не встает туда.

**Comment by aribaz** [comment]
А можно выбрать например несколько заказов? и по ним сделать отчет. Если да то как? Я пробовала, но у меня в списке остается или один или второй заказ. Но я могу добавить строку дополнительно с изделием из другого заказа. Я попробовала, только в таблице в графе Расчет везде осталось пустота, хотя я предположила, что в ней должен был отобразиться номер расчета к которому это относилось. Или я что-то сделала не так?
Даже если группировать по расчетам, столбец остается пуст и группировки не происходит, все в одном списке с заголовком order. Что я делаю не так?

**Comment by unpete** [comment]
Добавил подзадачи в https://github.com/oknosoft/windowbuilder/issues/119#issuecomment-258775102

**Comment by unpete** [comment]
Реализован универсальный отчет для v0.12 см. [видео](https://youtu.be/W2DpQ5IG_dc?list=PLiVLBB_TTj5mQXHOzodkzP3duImksxVgB)
- подключаемые макеты html
- триггер перед компоновкой результата
- варианты настроек
- изменяемый состав разделов отчета
- отбор по любым полям спецификации + разыменование ссылочных полей
- группировка по одному (любому) полю

В планах:
- поля со списками и деревьями значений для настройки отборов и группировок
- ссылочные значения в отборе
- группировки по нескольким полям
- автомасштабирование svg
- итоги и автоитоги в группировках

**Comment by aribaz** [comment]
В нашей базе макет отчета не правильный.

**Comment by unpete** [comment]
Подключил правильный макет + добавил контроль ошибки 404 при получении эскизов тех продукций, которые не являются изделиями построителя (подоконники, откосы и т.д.)
Можно тестировать после перезапуска браузера на варианте отчета `резка в цех`.
Чтобы этот вариант стал вариантом по умолчанию, в форме подготовки отчета, нажать кнопку `сохранить`
Выявил ошибку при сохранении. Сейчас варианты сохраняются только локально и не мигрируют к другим пользователям. Это из-за фильтров при обмене. Задумано, чтобы пользователь без админских прав не испортил хороший вариант отчета, но сейчас даже пользователь с админскими правами не может изменить вариант у соседа.

**Comment by aribaz** [comment]
Что-то не совсем то, что ожидала. Нет списка потребности. Может я что-то не так делаю?
[ПФ Спецификация](https://youtu.be/e3kvixx5o_I)

**Comment by aribaz** [comment]
Добрый день, Евгений.
Собрала некоторые комментарии по отчету. Подскажите как сделать.
Мне нужны три отчета с разными шапками, которые по сути отличаются составом спецификации и внешним видом.
Я понимаю, что на основе этого отчета можно сделать сколько угодно с разными шапками - посредством копировать вставить и исправить шапки и внутри каждого настроить свою группировку и фильтры согласно потребностям. 

Вот [чего](https://youtu.be/bebjiPtEg1A) я не могу.

**Comment by nmivan** [comment]
@aribaz , эта задача актуальна?

**Comment by aribaz** [comment]
@nmivan нет
