### ISSUE TITLE
Поле налоги не работает

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#120]
В заказе на вкладке Реквизиты есть поле Налоги с возможностью поставить галочку внутри они или сверху, галочки не активны.

**Comment by unpete** [comment]
Эти поля только для чтения.
Значения _учитывать НДС_ и _Сумма включает НДС_ устанавливаются в _Договоре_

**Comment by aribaz** [comment]
поняла, спасибо

**Comment by aribaz** [comment]
Там есть два варианта:
Учитывать НДС
Сумма включает НДС

А если организация поставщик работает по упрощенной схеме и НДС не облагается, какой вариант выбрать?

И еще мне подумалось, а не правильнее ли этот пункт привязывать не к договору, а к организации и/или контрагенту. Я не сильно разбираюсь в бухгалтерии, но ведь покупатель покупает у поставщика, счет на оплату выставляет поставщик согласно своей схеме налогообложения и покупатель никак не может повлиять на это, а поставщик изменить по своему усмотрению. Ведь если мы не облагаемся НДС, то и во всех наших счетах и и любых документах с ценами должна быть сноска "НДС не облагается", и покупатель с этим просто мирится.
Я попробовала нарисовать одно и то же окно для разных контрагентов но от одного поставщика, при этом:
в договоре Светлый дом и Арибаз поставила галочку - Сумма включает НДС (5 378,59)
в договоре ФабрикаМассив и Арибаз поставила галочку  - Учитывать НДС (6 199,05)
Но ведь это не совсем так, ведь поставщик определяет как учитывается НДС (и об этом есть сведения в налоговых органах), а по факту один и тот же поставщик с одним дилером  НДС накинул сверху, а с другим как бы внутри его зачел, хотя по факту Арибаз НДС не облагается. Мне кажется если эти оба дилера работают с одной организацией, то они или оба получают НДС сверху, или для обоих он внутри, но для всех дилеров одинаково.

Или я не правильно что-то понимаю.

**Comment by unpete** [comment]
Договоры регистрирует сотрудник поставщика.
Указание правил налогообложения в договоре, а не для организации в целом, возможно, избыточно, но так проще получить совместимость с типовыми конфигурациями

**Comment by aribaz** [comment]
Поняла
