### ISSUE TITLE
Добавление других стеклопакетов в блок

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#122]
Мы пользуемся различными формулами стеклопакетов, для которых постоянна толщина стеклопакетов 40мм, а тип стекла может быть разным, и даже иногда толщина стекла и рамки, может быть такое, что вместо стекла 4мм ставим 6мм, а одну рамку на 2мм меньше.
Для учета наших потребностей в ассортименте стеклопакетов что я должна сделать?
Создать новые и дать их список для привязки к соединениям?
Переименовать уже имеющиеся в соответствии с нашими потребностями (тогда мне нужен список какие я могу переименовывать, а какие не могу)?

**Comment by Oparin-Igor** [comment]
Переименовывать не надо, надо добавить недостающие.
Формулы пакетов?

**Comment by aribaz** [comment]
4-16-4-12-4i
3.1.3-14-4-12-4i
3.1.3-12-4-12-3.1.3i
6Зак-14-4-12-4i
4-16-4МАТ-12-4i
4МФпрозр-16-4-12-4i
4-16-4Бронза-12-4i
4Бронза-16-4МАТ-12-4i
Это основные, общая толщина каждого стеклопакета 40мм.

Игорь  и у меня вытекающий вопрос если мне понадобится добавить еще стеклопакет (один или несколько) я смогу это сделать сама на стороне сервиса или это через вас?

**Comment by aribaz** [comment]
По стеклопакетам есть ограничения в размерах, нашла на сайте производителя
Минимальный размер стеклопакета 250х350мм
Максимальный размер стеклопакета 2500х3500мм
Максимальный размер одной из сторон стеклопакета с пленкой 1500мм.

И еще такой момент как можно учесть цену на площадь одного стеклопакета?
Если площадь стеклопакета от 0 до 0,3кв.м, то к цене применяется коэффициент 1,25
Если площадь стеклопакета от 3 до 4 кв.м, то к цене применяется коэффициент 1,25
Фигурные стеклопакеты коэффициент 1,3
Сложная форма (круг, арка, многоугольник) - коэффициент 1,5
Изготовление по шаблону (два радиуса и пр) - коэффициент 2
Стеклопакет с внутренним радиусом - коэффициент 2

Еще если стеклопакет не прямоугольной формы, то применяется не только коэффициент к цене, но и площадь считается не конечного стеклопакета, а приведенного четырехугольника, площадь которого всегда больше.
Если стеклопакет круглый и радиус у него 0,5м, то расчет будет таким:
Чтобы сделать круг с радиусом 0,5м, нам нужен квадрат со стороной 1м, следовательно
Ц= 1*1*Цс*1,5, а не Ц= (Пи)*r*r*Цс*1,5.
Как можно учесть использование коэффициентов для формы и как считать приведенную площадь, хотя в документах всегда ставят фактическую площадь стеклопакета, а стоимость рассчитывают по приведенной.

**Comment by aribaz** [comment]
Есть еще один момент.
Производители стеклопакетов не дают нам прайс на все возможные стеклопакеты, но дают возможность самим расценить стеклопакет с любой формулой. Они отталкиваются от стоимости нашего базового стеклопакета 4-16-4-12-4 (40мм) - 1350р/кв.м.. При этом изменение толщин алюминиевых рамок внутри стеклопакета не влечет за собой изменение цены, при сохранении общей толщины стеклопакета и условии что рамки остаются алюминевыми. Если нам необходимо одно из стекол заменить на другое, то нам для этого дан прайс-лист на замену одного стекла в стеклопакете, в котором приведен список возможных стекол с указанием его стоимости за 1кв.м..
К примеру если я хочу одно из стекол в обычном стеклопакете заменить на стекло белое матовое 4мм (400р/кв.м), то стоимость нового стеклпакета 4Мат-16-4-12-4 станет равной 1350+400=1750р/кв.м., если я хочу то же самое проделать со стеклопакетом энергосберегающим 4-16-4-12-4i (1380р/кв.м), то получаем 4Мат-16-4-12-4i по цене 1380+400=1780р/кв.м.

И на новые стеклопакеты тоже действуют правила применения коэффициентов непрямугольной формы, описанных ранее.
К чему я это все пишу. 
Я не смогу составить такое количество вариантов стеклопакетов, точнее ассортимент будет слишком велик, а использоваться будет хорошо если 1/20, а предугадать что может потребоваться, а что нет - я не могу, увы. 
При этом я хочу дать возможность менеджерам  в любой момент времени учесть именно тот стеклопакет, который нужен заказчику.
Можно ли к стеклопакетам добавить некоторые параметры для расчета цены?

В прайсе есть такие пункты:

- Заполнение камеры аргоном - 50р/кв.м. одной камеры, камер - 2шт.
- Увеличение цены стеклопакетов при замене одного стекла 4мм на: (список из 50 позиций с ценам на каждую, р/кв.м., причем фактически можно изменить и все три стекла, и два, и одно, но в основном одно) - этот пункт я описала выше
- увеличение цены стеклопакета при изменении одной алюминиевой рамки на: (список из 37 вариантов неалюминиевых рамок, а в стеклопакете у нас 2 рамки
- цены на пленку (Список из 24 видов пленки)
- применение коэффициентов и увеличение цены пленки при изменении параметров (здесь речь о площади пленки и коэффициент на разные границы).

У меня была мысль внести такой вариант "Нестандартный стеклопакет 40мм" он для того, чтобы менеджер смог оперативно учесть это в заказе. Изначально он без цены, но есть возможность его использовать в окнах, в час икс старший менеджер делает документ Установки цен на этот стеклопакет (цену на него сам считает из прайса) и видит стоимость заказа с учетом конкретно этого стеклопакета и попутно сообщает мне, что появился новый тип стеклопакета, тогда или я сама или вашими силами добавляем новую номенклатуру (ведь на это может понадобиться некоторое время, а цена-то нужна сейчас), и далее по цепочке. Минус здесь в том, что директор не хочет, чтобы менеджеры работали с прайс-листами, так как часто делают ошибки при применении цен и всегда не в нашу пользу, да и мы как правило в качестве плановой себестоимости материала не используем закупочную цену как она есть у поставщика, а менеджер не вспомнит об этом когда надо.

Что можете сказать по этому поводу?

**Comment by Oparin-Igor** [comment]
В программе существует два варианта расчета стеклопакетов.

1. Пакеты составные (изготавливаются на своем производстве и на нее считаются расходные материалы стекло, рамка, бутил и т.д.).
Стоимость считается в зависимости от стоимости и расхода комплектующих.
В зависимости от состава формируется Формула 4х12х4х16х4.

2.Пакеты покупные (покупная номенклатура стеклопакетов). В номенклатуре должна содержаться формула понятная для поставщиков.
Например СПД 40мм. 4х12х4х16х4.

Различия для тех и других в наимпеновании.

Для разной номенклатуры пакетов должна быть создана номенклатура.
СПД 40мм. 4х12х4х16х4 и СПД 40мм. 4х16х4х12х4 это разная номенклатура хотя и цена одинаковая.

В программе на каждый пакет должна быть создана своя вставка.
Предоставьте весь список стеклопакетов, с разными стеклами и рамками, я занесу в программу номенклатуру и справочники.
До этого у вас был сокращенный список.

**Comment by aribaz** [comment]
Игорь, подскажите а могу ли я использовать первый вариант расчета стклопакетов с точки зрения определения их цены, но при этом для себя понимать, что при этом стеклопакеты я все  равно буду заказывать на стороне, а не делать на месте. 
Меня в этом варианте интересует как будет составляться формула стеклопакета?
Методом выбора из имеющихся готовых формул или что-то типа:
Стекло наружнее : толщина и тип стекла
Рамка: тип, толщина
Стекло среднее: толщина и тип стекла
Рамка: тип  и толщина
Стекло внутренне: толщина и тип стекла
Здесь главное, чтобы толщина всего стеклопакета не была больше 40мм.
Если методом указания составляющих стеклопакета, то это здорово меня устраивает.
Я правильно себе представила модель при "самодельных" стеклопакетах или там тоже просто строка с выбором готовой формулы?

У меня проблема в том, что я не смогу предоставить полный перечень готовых формул стеклопакетов, которые может изготовить производитель, потому что по желанию заказчика можно заменить и все три стекла на цветные, с пленкой и какие-угодно, даже витраж и давальческое сырье, а еще для этих же стеклопакетов камеру заполнить аргоном, а можно и две камеры заполнить. А по закону подлости понадобится именно тот, которого нет в базе.
 Здесь у меня беда в том, что я даже представить не смогу какую он захочет комбинацию из стекол их толщин, и как следствие толщин рамок. 
И с этой точки зрения мне проще дать возможность менеджеру составить формулу самому - если такая в сервисе вообще есть, пусть это и не будем мы делать сами.

**Comment by aribaz** [comment]
Договорились с Евгением о том, что надо добавить номенклатуру Стеклопакет формула (или как-то по-другому назвать) и при выборе этого стеклопакета  появляется два поля:

- Формула (здесь он указывает формулу от руки сам)
- Цена (указывает цену за кв.м. такого стеклопакета)

И помимо этой номенклатуры прошу добавить такие формулы готовых стеклопакетов:
4-16-4-12-4i
3.1.3-14-4-12-4i
3.1.3-12-4-12-3.1.3i
6Зак-14-4-12-4i
4Зак-16-4-12-4i
4-16-4МАТ-12-4i
4МФпрозр-16-4-12-4i
4-16-4Бронза-12-4i
4Бронза-16-4МАТ-12-4i

Они встречаются неоднократно и их используем повторно в других заказах.


Со временем будут формулы для пересчета стоимости цен стеклопакетов в привязке к коэффициентам по площади и форме.

**Comment by unpete** [comment]
- [ ] Добавить номенклатуру, вставку и параметры Заказного стеклопакета
- [ ] Добавить в характеристику табчасть `Параметры элементов`
- [ ] Реализовать редактор дополнительных параметров элементов

Математика получится абстрактная, не ограниченная именно стеклопакетами.
В любой вставке можно будет описать дополнительные параметры и указать эти параметры в для любого элемента изделия.

**Comment by aribaz** [comment]
Евгений, а можно привязать формулу для стеклопакетов не только заказных, но и покупных по аналогии с москиткой, которая бы учитывала площадь стеклопакета при определении цены?

**Comment by Oparin-Igor** [comment]
1.  4-16-4-12-4i  
Для стеклопакетов есть вне гласное правило, первое стекло уличное.
Формула для пакетов с энергосберегающим стеклом.
4i-16-4-12-4   иначе энергосберегающее стекло будет приносить обратный эффект.
Основной признак не правильной установки запотевание пакетов.
6Зак читается как 63 в сокращении лучше использовать латинские буквы
6Zak (в расшифровке как закаленное)
2. Через параметры что будем определять? Какие параметры вы имеете ввиду? Какие перечисления будут использованы?
3. Пакеты будут выглядеть примерно так:
СПД- признак для покупного пакета
СПД 40мм. 4ix16x4x12x4
СПД 40мм. T3.1.3ix14x4x12x4
СПД 40мм. T3.1.3ix12x4x12xT3.1.3
СПД 40мм. 6Zakx14x4x12x4
СПД 40мм. 4Zakx16x4x12x4
СПД 40мм. 4ix16x4Mtx12x4
СПД 40мм. 4МФпрозрx16x4x12x4i
СПД 40мм. 4ix16x4Sbx12x4
СПД 40мм. 4ix16x4Mtx12x4Sb

**Comment by Oparin-Igor** [comment]
не только заказных, но и покупных 
Объясните разницу я её не вижу.

**Comment by aribaz** [comment]
По формулам, все эти формулы (последовательность рамок и стекол) я взяла в нашей базе 1С, туда они попадают из документов поступления ТМЦ, у нас все энергосберегающие стеклопакеты приходят с формулами 4-16-4-12-4i - это я сама видела не раз на этикетках, знаю точно, что наши окна не запотевают - рекламаций по этому признаку ни разу не было на моей памяти.
Позвонила спросила у начальника цеха формулу он подтвердил и сказал, что 4i стоит в комнате.

Поэтому пусть последовательность (рамака/стекло) останется наша, против латиницы ничего не имею против, можно и просто с маленькой "з".

Я не сильна, к сожалению, в операторах и возможностях привязки формул, возможно и нет разницы, это даже лучше.

Про параметры я не совсем поняла, о каких параметрах речь у стеклопакетов их вроде нет, кроме заказного. Я в письме писала о параметрах: цвет уплотнителя. цвет водоотвода и параметры дверных блоков.

**Comment by Oparin-Igor** [comment]
Извините запамятовал вы правы энергосберегающее устанавливают внутрь помещения
Единственно что хочу добавить, что если ставть 1-е и последнее энергосберегающее стекло (ставить обязательно в паре 1-е и последнее),то стеклопакеты значительно теплее, но их нельзя ставить на солнечную сторону.
1. Принимаете вариант формул или нет?
СПД 40мм. 4x16x4x12x4i
СПД 40мм. T3.1.3x14x4x12x4i
СПД 40мм. T3.1.3x12x4x12xT3.1.3i
СПД 40мм. 6Zakx14x4x12x4i
СПД 40мм. 4Zakx16x4x12x4i
СПД 40мм. 4x16x4Mtx12x4i
СПД 40мм. 4МФпрозрx16x4x12x4i
СПД 40мм. 4x16x4Sbx12x4i
СПД 40мм. 4Sbx16x4Mtx12x4i
2. > Добавить номенклатуру, вставку 

> и параметры

 Заказного стеклопакета
О каких параметрах идет реч?

**Comment by aribaz** [comment]
Вариант формул принимаю с поправкой вместо Sb использовать "бронза" или "бр" или "br", потому что когда мы говорим о стекле Бронза (русскими буквами) мы говорим о саратовском стекле тонированном в массе и именно о нем речь в этих формулах, а когда используем бронза на латинице, то говорим о стекле Planibel или StopSol (если аббревиатуру Sb я правильно поняла) -  оно хоть и бронза тоже есть, но всегда с выраженным отражающим эффектом (типа зеркала). Стекло Бронза (на русском) - оно дешевле и не имеет эффект зеркала, производители стеклопакетов нас понимают что нам нужна в этом случае именно бронза саратовская, а не Planibel/StopSol.
По прозрачному стеклу матовому, для нас нет разницы как сокращать, можно и от Matelux, здесь нас поймут правильно с первого раза.
Все остальное принимаю.

> О каких параметрах идет реч?

У номенклатуры "Стеклопакет заказной 40" есть параметры:

- Формула
- Цена закупа
Они доступны любому пользователю в табчасти строки заказа и вызываются кнопкой (что-то типа ярлычка) на панели элементов, в то время как другие стеклопакеты этих параметров не имеют.
Это было сделано к вопросу о необходимости учесть в заказе стеклопакет, которого нет в базе - этим закрыли вопрос.

Евгений описал формулу в Москитках (это тоже вставка с параметрами, но в створку) по определению цены с учетом площади готовой москитки для ценообразования, поэтому я и писала 

> не только заказных, но и покупных
Потому что посчитала, что раз так можно сделать с москиткой, то так можно поступить и с заказными точно, и уточнила про покупные, но не факт (я не знаю наверняка этого), нужен ответ Евгения.
