### ISSUE TITLE
Эскиз ручки на дверях входных

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#123]
При левом открывании двери эскиз ручки выглядит как для правого

**Comment by Oparin-Igor** [comment]
Добавлен эскиз левой ручки.

**Comment by aribaz** [comment]
![2016-10-05_08-40-07](https://cloud.githubusercontent.com/assets/22028048/19102274/9127b6f0-8ad7-11e6-9df7-171d8b42ad2a.png)


Пока ничего не изменилось

**Comment by nmivan** [comment]
@aribaz , эта задача актуальна?

**Comment by aribaz** [comment]
@nmivan, эскиза теперь нет совсем ни для левой, ни для правой.
