### ISSUE TITLE
Скрыть вкладку Спецификация для роли Менеджер

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#124]
Можно ли скрыть вкладку Спецификация для простых менеджеров.
У нас есть один дилер, который слишком много задает вопросов о ценообразовании на продукцию, ему ну очень интересно что и сколько стоит (комплектующие и пр.) и почему получается такая цена. Сейчас эта информация недоступна ему так как у него есть только цены за квадрат условного изделия а мы ему этих сведений не предоставляем, но сервис даст ему возможность увидеть всю внутрянку, это плохо, слишком он активен и то чем это может грозить нам не очень нравится. Отказаться от него не можем, отношения с ним долгосрочные, и толк от него как от дилера есть и весьма неплохой, но всю кухню ему показывать не хотим категорически.
Можно как-то решить вопрос?

**Comment by unpete** [comment]
Подобные вопросы задают часто.
Честный ответ: **нет**. При чем, это относится к любой программе, в которой работает дилер (суперокна, клаез, альтавин, виндроу и т.д.)
Если программа позволяет рассчитать спецификацию, то спецификация, правила и цены на дилерском компьютере есть. Всегда существует способ эти данные прочитать.
Можно скрыть некоторые закладки и отчеты из интерфейса, но это косметическая мера не будет препятствием для хакера.

**Comment by aribaz** [comment]
Я думаю косметической меры нам будет достаточно - это позволит исключить возможность "копания в деталях" самим дилером и скрыть "кухню" от посторонних случайных глаз - и это уже хорошо. 

А осознанное обращение к хакерам - это уже не просто любопытство, а целенаправленные действия - от них тяжело защититься, было бы желание, а взломать можно наверное что-угодно.

**Comment by unpete** [comment]
> взломать можно наверное что-угодно

Нет, не что угодно.
Для взлома серверной части `Заказа дилера` потребовались бы невообразимо большие ресурсы - сотни лет работы сотен суперкомпьютеров.
Прочитать данные, которые физически хранятся на компьютере дилера - намного дешевле.

> косметической меры нам будет достаточно

Ок. Так все и делают. Например, файловые базы 1С вообще никак не защищены. Любой студент может без пароля достучаться до любых данных в файловой 1С-ке.

**Comment by nmivan** [comment]
@aribaz , что решили в итоге?

**Comment by aribaz** [comment]
Итого не подводили, скорее всего нет.

**Comment by nmivan** [comment]
нет - в смысле не надо делать?

**Comment by nmivan** [comment]
@aribaz , так может все-таки сделаем?
Я не согласен с @unpete в этом вопросе, мне кажется разумным скрыть то, что дилеру не надо видеть. Цель сокрытия - "чтобы в глаза не бросалось", а не "чтобы не мог никак увидеть".
Что думаете?

**Comment by aribaz** [comment]
Цель сокрытия - не столько "чтобы в глаза не бросалось", а столько для того, чтобы не объяснять дилерам, что у нас есть аренда, не сезон, зарпалата, налоги, транспорт, брак и прочие расходы и во сколько все это нам обходится.
Дилеры- это живые люди с разным мировоззрением, жизненным опытом, жадностью и тревожностью. Дилеров не выбирают, если они регулярно приносят заказы (возможно за исключением каких-то особых случаев). 
Особо активные дилеры полезут обязательно в бутылку (вдруг их обманывают), чтобы не потерять дилера (если он хорош в продажах) придется кое-что объяснять или же не объяснять (но дилер может обидеться), но тут уже не важно обидится он или нет,
С другой стороны мы имеем право не показывать дилерам что и за сколько МЫ покупаем, и какие расходы у нас есть. Для них важна итоговая стоимость изделия.
Ведь покупая стол в магазине вы же не видете сколько на материалы затратил изготовитель, иначе бы вам было морально некомфортно покупать этот стол за цену в 3-ое превышающую стоимость материалов, работа и прочие расходы всегда кажутся ерундой и мелочью "да, там всего четыре палки скрутить, а за это столько денег хотите (клиенты стали считать деньги), да у вас тут прибыль 200%.... Не тут меня обманывают..." - и не важно конечный это клиент или дилер. А таких людей не мало, образования не всем хватает  для осмысления всего. Деревянные окна всегда дороже пластика и не дать клиенту уйти не просто, а тут еще дилер будет думать что и его обманывают, хотя от правды это далеко.
Ставить цену в спецификации с учетом маржи тоже неправильно, хотя можно не ставить (не показывать) вовсе - но мне эти цифры бывают нужны часто.
Решение конечно за Вами, как за разработчиками.
Но мы были бы очень благодарны за понимание.

**Comment by blackmixer** [comment]
Для Роли Изменение нормативно-справочной информации построителя и корректировки спецификации
Текущий вид спецификации полностью устраивает 
А если у пользователя данной роли нет то Скрыть колонки с ценами 
И строки спецификации содержащие в себе номенклатуру определённых групп 
(в константах и списках есть уже элементы что можно использовать для фильтрации)
Служебные элементы  utilities
Техоперации operations
Мера косметическая избавляющая нас от многих вопросов со стороны пользователя сервиса

**Comment by unpete** [comment]
Поля с себестоимостью будут по умолчанию будут скрыты.
Если у пользователя `Полные права` или `Натройка технологии` или `Согласование заказа` или `Редактирование цен`, для него колонки с ценами включаем.
Про вертикальную фильтрацию (скрыть техопреации) - подумаю.

**Comment by unpete** [comment]
Можно было сделать формулой, но решил прямо в коде. Функционал представляется типовым.
Тестируйте после перезапуска браузера.
Для технолога ничего не должно поменяться, у дилеров колонки с ценами должны спрятаться.

**Comment by blackmixer** [comment]
Через модификаторы формулой предопределил таб части формы 
```
//для роли ИзменениеТехнологическойНСИ ни чего не меняем в поведении системы
const {current_user} = $p;
      if(current_user && (
          current_user.role_available('ИзменениеТехнологическойНСИ') 
                 )) {
        return;
      };
//Ширина колонок Спецификации (0 - спрятали)
$p.cat.characteristics.metadata().form.obj.tabular_sections.specification.widths = "50,*,70,*,50,70,70,80,70,70,70,0,0,0";
//Тип колонок ro в спецификации (Read only)    (https://docs.dhtmlx.com/grid__columns_types.html)
$p.cat.characteristics.metadata().form.obj.tabular_sections.specification.types = "ron,ro,ro,ro,ro,ro,ro,ro,ro,ro,ro,ro,ro,ro";
//Тип колонок конструкции 
$p.cat.characteristics.metadata().form.obj.tabular_sections.constructions.types = "ron,ron,ron,ron,ron,ron,ro,ro,ro,ro";
//Тип колонок конструкции координаты
$p.cat.characteristics.metadata().form.obj.tabular_sections.coordinates.types = "ron,ron,ron,ro,ro,ro,ro,ron,ron,ron,ron,ron,ron,ron,ron,ron,ro,ro"
//Тип колонок вставки
$p.cat.characteristics.metadata().form.obj.tabular_sections.inserts.types = "ro,ro,ro";
//Тип колонок соединяемые элементы
$p.cat.characteristics.metadata().form.obj.tabular_sections.cnn_elmnts.types = "ron,ro,ro,ro,ro,ro";
//Тип колонок параметры
$p.cat.characteristics.metadata().form.obj.tabular_sections.params.types = "ron,ro,ro,ro,ro";
//ширина колонок параметры
$p.cat.characteristics.metadata().form.obj.tabular_sections.params.widths = "50,80,*,*,0";

```

возник вопрос как  предопределить поведение интерфейса из формулы ??
отключить или спрятать кнопку 
(скрыть disableItem('btn_save'); или спрятать hideItem('btn_save');  )
