### ISSUE TITLE
Фурнитура

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#125]
Не могу понять список фурнитуры в табчасти строка заказа.
При выборе любого вида окна мне доступен для выбора выпадающий список фурнитуры для створки:
1.  ROTO KSR
2.  ROTO фрамужная
3.  ROTO NT
4.  Отв.планка
5.  Дверь входная
6.  Дверь входная дерево
7.  Дв вход. ШТ без ручки
8.  Дв вход. ШТ с ручкой
9.  Без фурнитуры
10. двери балконные
11. Балконка с замком
12. MACO поворотная
13. MACO поворотная удален
14. MACO поворотно-откидная удален
15. MACO поворотно-откидная
16. MACO пов-откид Скрытая удален
17. MACO фрамуга
18. MACO ШТ поворотная удален
19. *Maco ШТ поворотная
20. MACO ШТ поворотно-откидная удален
21. MACO ШТ пов-откид Дер удален
22. *Maco ШТ пов-откид
23. MACO ШТ ответная
24. MACO ШТ ответная б/р удален
25. MACO ШТ ответная с/р удален
26. *Maco ШТ ответная Дерево
27. Дв межкомнатная
28. Дв межкомн. ШТ ответная
29. Россия поворотная
30. удалено не удалять

Если нажать на кнопку Показать все, то список менее обширен и сгруппирован:

MACO:
1.  MACO ШТ ответная
2.  MACO поворотная
3.  MACO поворотно-откидная
4.  MACO фрамуга
Двери дерево:
5.  Дверь входная дерево
6.  Двери балконные 
Общее:
7.  Балконка с замком (значится как раздвижная,  у нас таких нет)
8.  Без фурнитуры
9.  Дв вход. ШТ без ручки
10. Дв вход. ШТ с ручкой
11. Дв межкомнатная (межкомнатные двери делаем в другом цеху, он не имеет отношения к сервису)
12. Дв межкомн. ШТ ответная (межкомнатные двери делаем в другом цеху, он не имеет отношения к сервису)
13. Дверь входная
14. Раздвижная С640 без ручки (не наша)
15. Россия поворотная (не наша)

А по факту у нас их еще меньше:
1.  поворотное, 
2.  поворотно-откидное, 
3.  штульповая створка окна
4.  фрамуга, 
5.  балконная дверь, 
6.  входная дверь, 
7.  штульповая створка входной двери
8.  без фурнитуры

Можно как-то эти списки привести к единому знаменателю? 
Ведь менеджер будет пользоваться выпадающим списком, а там черт ногу сломит, много названий похожих, а если промахнется?

**Comment by Oparin-Igor** [comment]
Выбираем
MACO:
1. MACO ШТ ответная
2. MACO поворотная
3. MACO поворотно-откидная
4. MACO фрамуга
Двери дерево:
5. Дверь входная дерево
6. Двери балконные 

Комплектации не предоставлено.
7. штульповая створка входной двери

**Comment by aribaz** [comment]
А можно в качестве доступного нам списка для выбора оставить только это

MACO: 
1. MACO ШТ ответная 
2. MACO Поворотная 
3. MACO поворотно-откидная 
4. MACO фрамуга 
Двери плинтус дерево О : 
5. Дверь входная дерево 
6. двери балконные

Комплектации не предоставлено. 
7. штульповая створка входной двери (комплектация за нами)
