### ISSUE TITLE
Тип ручек для окон

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#126]
Для окон у меня есть возможность выбрать ручку какую мне необходимо и ее цвет, это здорово, правда список ручек включает в себя не только те ручки которые я заявляла, но и другие, их в общем немного, но больше, чем наших:
1. Planet (на моей памяти такие не использовали, не заявляла их)
2. Hoppe (встречались, но не заявляла их)
3. Roto (встречались, но не заявляла их)
4. Ручка с ключем (у нас такие есть только Harmony с ключом, они так и называются, , но не заявляла их)
5. ручка 2-х сторон (Что это такое? нажимной гарнитур?, если да то  и для типа нажимного гарнитура можно выбрать разный тип непосредственно ручки)
6. ручка 2-х сторон ключ (то же самое  плюс ключ?)
7. нет
8. Рапсодия
9. Гармония
10. Симфония
11. Гармония с ключем

5 и 6 категории (назначение) мне не ясны,  в общем наверное не мешают, но назначение этих пунктов я должна знать.
Если выбрать пункт:  1,2,3,4,5,6 то в спецификацию сами ручки не попадают вообще никакие.
Если ручка совсем не попадает в спецификацию, то наверное и смысла иметь возможность ее выбрать нет, более того заказчик потом окажется без ручек вовсе, это плохо.

Если я правильно помню, то для окон могут быть использованы нажимные гарнитуры, а не только ручки, их нет.

**Comment by aribaz** [comment]
С нажимными гарнитурами для окон  ошиблась, только ручки.

**Comment by Oparin-Igor** [comment]
Вопрос в реализации на стороне браузера "связи параметров", он был когда-то запланирован.
Суть в том, чтобы можно было выбрать только те параметры которые используете.

**Comment by aribaz** [comment]
Пока вопрос оставляю открытым, потому как необходимые нам ручек есть не все для выбора.

**Comment by Oparin-Igor** [comment]
>Planet (на моей памяти такие не использовали, не заявляла их)
Вся номенклатура переданная ранее занесена в номенклатуру, этих ручек не было в списке.
Договаривались, что вы дополните и откорректируете весь список номенклатуры ручек, затем я привяжу номенклатуру к параметрам.

**Comment by aribaz** [comment]
Я помню, что их не было.
Я внесла их и написала, об этом в вопросе 168.

> Игорь @Oparin-Igor , я довнесла недостающие материалы из файла "Материалы в спецификацию с параметрами", можно их привязывать.

В том числе были и все ручки с учетом того в каких они цветах есть (то есть поставляются в Россию).
Мне наверное следовало уточнить какие именно параметры (номенклатуру для них) я внесла, но фразу "недостающие" я посчитала достаточной, учту на будущее - список был не из трех позиций.

**Comment by Oparin-Igor** [comment]
5 и 6 категории ручки оконные, соединяются винтами с оконным штифтом.
Нажимной гарнитур имеет более толстый штифт для оконных запоров не подходит.

**Comment by aribaz** [comment]
Эти два варианта уже были я наверное не совсем понимаю о чем речь, у нас на окнах подобного нет.

Для **окон** по ручкам у меня такие варианты:

1. Ручка Harmony
2. Ручка Rhapsody
3. Ручка Simphony
4. Ручка Harmony с ключом
5. Ручка Rhapsody с ключом
6. Ручка Harmony кнопка
7. Ручка Rhapsody кнопка
8. Ручка Harmony фикс. 45град.
9. Ручка Rhapsody фикс. 45град.
10. без ручки

В теории есть такие цвета:
белый
бронза
коричневый
серебро
шампань
титан
Но ручки (вне зависимости от типа) не каждого цвета ввозят на территорию России, поэтому я внесла только те артикулы, которые завозят (см. табличку Ручки оконные).

Вариант Без ручки - в спецификацию с ним соответственно никакие ручки не попадают.

[Ручки оконные.xlsx](https://github.com/oknosoft/windowbuilder/files/699070/default.xlsx)

**Comment by nmivan** [comment]
@aribaz , эта задача актуальна?

**Comment by aribaz** [comment]
@nmivan решено
