### ISSUE TITLE
Параметры фурнитуры для входной двери

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#127]
Для входных (не балконных) дверей есть два типа фурнитуры:
1. Дверь входная 
2. Дверь входная дерево.

Какую надо выбирать я не знаю наверняка, но вроде по названию должна быть Дверь входная дерево.

Мы ранее договаривались о том, что могут быть разные варианты

Петли (варианты):
1. OTLAV (d16мм, реже 20мм),
2. Roto (накладные) - для больших и по ширине и по высоте дверей,
3. Simonswerk
   По факту у нас только петли отлав и выбрать другие не могу

Замки:
- много-запорные замки
- замок с ригелем и защелкой
- штульп с запором
- нажимной гарнитур

Для двери входной дерево я не имею возможности выбрать ничего, но в спецификацию попадает нажимной гарнитур, правда всегда белый и только Рапсодия, петли Отлав и колпачки к ним, правда без привязки к цвету, что не полностью соответствует реальности.

Для Дверь входная, есть вариант выбрать ручку, из того что есть нам подходит нажимной гарнитур, но цвет ручки выбрать не могу, есть вариант выбрать замок (есть в том числе замок с ригелем и есть замок с защелкой, а замка с ригелем и защелкой нет, из петель нет Отлав и ROTO, нет возможности выбрать цвет колпачков (это актуально для петель РОТО и Отлав). 
Например мне нужен замок: Штульп с запором, что я должна выбрать в поле ДВ замок?
И если в двери не используется нажимной гарнитур, какую ручку я должна выбрать (полукруглая, скоба и треугольная - это для ПВХ, мы такие никогда не ставим)? Они у нас для дверей такие же  как и для окон.
У нас нажимной гарнитур вынесен в замок, в сервисе он числится в ручках.
Если честно, с входными дверями я вообще не понимаю что и где выбирать. чтобы достичь желаемых результатов.
Прошу помощи. А то  мне скоро представлять это все на тестирование, а эту часть я объяснить не смогу.

**Comment by Oparin-Igor** [comment]
Было предоставлено два варианта комплектации.
- Входная дверь.
- Балконная дверь.
Какие нужны варианты и комплектующие для выбора?

**Comment by aribaz** [comment]
Игорь, я вопрос задала конструктору,  как она мне ответит я напишу. Вопрос этот не очень горит. Скорее всего к концу октября у меня будут данные.

**Comment by aribaz** [comment]
Двери входные могут комплектоваться (параметры):

- [ ] Замок:

1. Многозапорный
2. Однозапорный:

- с роликом 
- с защелкой

- [ ] Штульповое открывание:

1. нет
2. да:

- штульповый запор
- шпингалеты

- [ ] Петли:

1 Otlav:

- диаметр петель:
а) 16мм
б) 20мм

- колпачки:
а) простые:
б) пешка

- цвет колпачков #108 (для каждого диаметра свои артикулы по цветам):
а) для простых
никель
мат. никель
бронза
золото
белая
коричневая
б) для пешек
Золото
бронза

2 Simonswerk:
а) цвет фурнитуры (именно самих петель):
- белые 
- коричневые

3 Rotoline
а) цвет фурнитуры (именно самих петель):
- белые
- коричневые

4 Roto NT Power hinge

- [ ] Количество петель на створку:

1. 3
2. 4

- [ ] Нажимные гарнитуры:

1. Harmony
2. Rhapsody

а) Тип гарнитура:
- простой
- раздельный

б) Цвет гарнитура:

- белый (для всех)
- светлая бронза (для всех)
- титан (для всех)
- серебро (для всех)
- коричневый (только Harmony)
- золото матовое (только Harmony раздельный)

- [ ] Металлозащита порога
1. Алюминиевый порог (см. #110) 
2. Алюминиевая накладка
3. нет

- [ ] Капельник
1. да
2. нет

Все, что должно попадать в спецификацию при выборе этих параметров я постараюсь выслать сегодня-завтра.

**Comment by aribaz** [comment]
Двери входные могут иметь такие параметры:

- [ ] **Замок многозапорный:**
а)Тип замка:

- замок с приводом от ручки (осн)
- замок с приводом от ключа (жел.зак)

б)Профильный цилиндр:

- ключ с 2-х сторон
- ключ/вертушок

- [ ] **Штульповое открывание:**

1.	нет
2.	да:

- штульповый запор
- шпингалеты

- [ ] **Петли:**

1 Otlav:
 а)диаметр петель:

- 16мм
- 20мм

б)цвет колпачков #108 (для каждого диаметра свои артикулы по цветам):

- никель
- мат. никель
- бронза
- золото
- белая
- коричневая

2 Rotoline
а) цвет фурнитуры (именно самих петель):

- белые
- коричневые

3 Simonswerk:

а) цвет фурнитуры (именно самих петель):

- белые
- коричневые

- [ ] **Количество петель на створку:**

1.	3 (три)
2.	4 (четыре)

- [ ] **Нажимные гарнитуры:**

1.	Harmony
2.	Rhapsody

а) Тип гарнитура:

- простой
- раздельный

б) Цвет гарнитура:

- белый (для всех)
- светлая бронза (для всех)
- титан (для всех)
- серебро (для всех)
- коричневый (только Harmony)


- [ ] **Металлозащита порога**

- Алюминиевый порог (см. #110)
- Алюминиевая накладка
- нет

- [ ] **Капельник**

1) да:
а)цвет капельника:

- RAL 8017
- RAL 9016
- Заказной

2) нет

**Comment by nmivan** [comment]
@aribaz , задачу вы адресовали себе, но все-таки спрошу: она актуальна?

**Comment by aribaz** [comment]
@nmivan закрываю, решено
