### ISSUE TITLE
Печатная форма Договор

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#128]
У меня вот какой возник вопрос на эту тему.
Мы - производство (отдельная организация), наши изделия кто-то продает - менеджер, он их продает кому-то - заказчику.
В качестве менеджера могут выступать два типа продавцов:
- штатный МШ (от имени нашего предприятия)
- дилер МД (от имени разных контрагентов)
- Заказчик - это конечный потребитель нашей продукции.

Рассмотрим продажу изделий через каждого менеджера отдельно.

**Арибаз-МШ-Заказчик**
В таком случае МШ выступает как оформитель заказа, он не имеет проценты с этого заказа и состоит у нас в штате, и в итоге мы получаем один договор и один счет на оплату между Арибаз и непосредственно заказчиком. Здесь номер каждого договора уникален, он создается ровно тогда когда появляется заказчик, готовый купить продукцию, и если этот же заказчик через полгода решит сделать у нас еще один заказа, то договор будет новый. И печатная форма договора одна.  Именно эта схема и доступна сейчас в сервисе.

Арибаз-МД-Заказчик
Здесь дилер выступает посредником между заводом и конечным потребителем, дилер не является непосредственным заказчиком. И здесь с точки зрения документации другая схема.
Как правило в начале каждого года заключается новый Договор1 (условно) между дилером и Арибаз, хотя самих клиентов еще может не быть. Экземпляр этого договора есть только у нас и дилера, их всего два. Если дилер работает на нас не с начала года, то договор с ним заключаем когда есть устная договоренность о совместной работе. А есть еще Договор2 (условно), он тоже заключается в двух экземплярах, но один экземпляр - у дилера, второй - у заказчика, нам их договор не нужен. Нам здесь нужен по факту только их расчет заказ, который является неотъемлемым приложением к Договору1.
Эти договоры 1 и 2 отличаются не только сторонами, но и стоимостью, и даже иногда составом (в основном монтаж наш или дилера. Причем если монтаж дилерский, то строчка с монтажом в расчет-заказе для Арибаз не должна присутствовать, а в расчет-заказе для клиента - да.  Договор1 - он один на весь год, а Договор2 заключается каждый раз (на один расчет-заказ - один отдельный договор2) с новым клиентом непосредственным.
Соответственно есть печатная форма договора для Арибаз, а есть для Клиента, две дополнительные формы.
Итого:
- три формы договора (стороны: арибаз-клиент, арибаз-дилер, дилер-клиент)
- три формы расчет-заказа (стороны и состав заказа: арибаз-клиент, арибаз-дилер, дилер-клиент)
- три формы счета на оплату. Вот здесь не уверенна, документ на оплату это бухгалтерский документ, и его выставляет тот, кто оказывает услуги/продает товар и возможно между дилером и клиентом дилер его должен делать руками своего бухгалтера (сохраняя свою сквозную нумерацию внутри фирмы) на их 1С (или в чем они ведут свою бухгалтерию), а скорее всего так и есть, тогда счет на оплату - одна форма, только для варианта работы арибаз-дилер-клиент он должен содержать в себе только те строки заказа, которые делаем именно мы (без дилерского монтажа и доставки), а для работы арибаз-клиент все, что заказал клиент.

Можно ли это осуществить? Если да, насколько это трудозатратно (время, деньги).
Это ускорило бы подготовку документов и следовательно их подписание, ну и в целом скорость обработки заказа от старта до запуска в работу не только со стороны завода, но и со стороны дилера. Дилер будет иметь возможность сразу распечать договор при клиенте и подписать его. И клиенту тоже удобно, не ждать когда подготовят договор. Нарисовали окна, посчитали, распечатали договор и счет, все подписали и оплатили. Красота )
Думаю это было бы удобно не только нам, но и всем кто работает с дилерами.

И еще одна тонкость: текст договора для Комфортного дома и для Арибаз может немного отличаться. так как КД - НДС облагается, а Арибаз - на упрощенке, а для ИП Доронин - скорее всего будет дублировать Арибазовский.

**Comment by unpete** [comment]
Существенный для понимания момент: не надо дублировать сущности.
Есть справочник _Договоры_. У него ключ _Контрагент_ + _Организация_. Договор нужен, как разделитель учета.
По одному _Договору_ можно оформить кучу _Заказов_. Не нужно создавать новый договор под каждую сделку.
То, что вы обсуждаете - просто N разных печатных форм _Заказа_, в шапке которых написано слово _Договор_.
По одному заказу можно напечатать сколько угодно бумажек с разным текстом, разным составом и разными суммами.

**Comment by aribaz** [comment]
По сути да, именно об N разных печатных форм для одного заказа, в шапке которого значится слово Договор я и спрашиваю

**Comment by unpete** [comment]
С учетом #272, не вижу, чем еще могу помочь по этой задаче.
Клиенты теперь могут самостоятельно создавать шаблоны в MS Word и подключать печатные формы к любым документам. Задачу предлагаю закрыть.

**Comment by nmivan** [comment]
Будем считать, что задача решается подключением печатных форм в нужном количестве, либо одной, зависящей от контекста.
