### ISSUE TITLE
Водоотводный профиль 22/34 закупка и учет в спецификации

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#129]
Этот вопрос мы устно обсуждали, и я помню, что готового решения по нему сейчас нет. Но я его все же запишу, вдруг придет мысль как сделать. А то забуду про это совсем.

Предыстория.
Этот профиль продается в хлыстах по 6м.
Если профиль заказывают в цвете отличном от RAL 8017, то мы берем неокрашенный хлыст в необходимом количестве и везем его на покраску, потом забираем. Но дело в другом. Даже если в заказе только одно окно, от заказа мы не отказываемся и получится вот что. Как правило створки не бывают больше 1м, мы покрасим 6м и заплатим сторонней организации за 6метров, а в изделие пойдет 1м, и что более важно в стоимость войдет только 1м, остальные 5 метров лягут на наши плечи. Если заказной цвет RAL 9016 или RAL8003, это не страшно, он используется часто, но если какой-то другой, то вероятность того, что мы сможем оставшиеся 5 метров где-то еще использовать стремится к нулю, и они становятся нашими потерями.

Мне пока виден один вариант, если это не RAL 9016 или RAL8003:
1. Для одного-двух изделий можно довключить в расчет отдельной строкой остатки этого профиля, заказчик его оплатит, и мы готовы его отдать покупателю (обманывать мы никого не хотим).
2. Для количества изделий более 2, проанализировать весь заказ и если общая длина этого профиля не кратна 6, то опять же остаток, хотя общая длина не гарантирует правильный расход, тут ведь надо учесть раскрой.

Наверное есть еще вариант, но пока не знаю можно ли так. Нарезать неокрашенный профиль на необходимые длины и нарезку везти на покраску, тогда проблем нет, надо только уточнить на производстве можно ли так

**Comment by aribaz** [comment]
Уточнила у начальника цеха, если просят экзотические цвета (Заказной) и одно окно (недавно был случай) - то он на производстве пилит неокрашенный (к готовой длине профиля минимум +40мм*2) и везет на покраску не хлыст, а полуфабрикат, его красят, он обрезает технологические отверстия и устанавливает. 

Можно ли при выборе для алюминиевых профилей (водоотводный профиль и профиль покрытия оконных створок) цвета Заказной увидеть где-то что-то типа подсказки: "Предварительная напиловка профиля". 
Как услугу ее учитывать не надо, так как он весь профиль всегда пилит в размер, здесь важно чтобы не увезли хлыст целиком, а сначала напилили, а потом везли только то, что надо. 
Потому как готовый крашенный профиль он пилит позже, потому что на складе он есть, а этот надо успеть покрасить

**Comment by nmivan** [comment]
@aribaz , задача актуальна?

**Comment by aribaz** [comment]
@nmivan да, актуальна. Можно конечно научить менеджеров писать комментарий на эскизе с этим предупреждением, но это человеческий фактор, красим редко, могут забыть. Могу конечно включить данный пункт в спецификацию, но вряд ли это убережет, а по срокам это опоздание 4-5 дней, если его не много.

**Comment by unpete** [comment]
что мешает добавить такую номенклатуру в спецификацию с отбором по группе цветов?
разместить можно хоть во вставке в профиль, хоть в допвставке в изделие через привязку вставок.
Результат можно видеть в печатной форме и (или) автоматически добавлять на эскиз, если указать для этой позиции визуализацию.

**Comment by aribaz** [comment]
Вы имеет ввиду добавить в спецификацию позицию номенклатуру "Предварительная нарезка водоотвода" с условием по цветам и для нее сделать визуализацию на эскиз?
