### ISSUE TITLE
Оптимизировать соединения II с заполнениями

### ISSUE THREAD

**Issue by unpete** [oknosoft/windowbuilder#13]
Сейчас в базе много практически одинаковых соединений, отличающихся только штапиком.
Возможно, имеет смысл эти соединения схлопнуть, а штапик сделать параметрическим?

**Comment by Oparin-Igor** [comment]
Если рассматривать вопрос в масштабе нашего, в прошлом, автоматизированного предприятия, то этого делать не надо, т.к. настройка размеров для каждого штапика индивидуальна. В некоторых случаях даже была необходимость разделения глухарь и створка, + признак используемых систем с привязкой к соединениям.
.

**Comment by unpete** [comment]
> настройка размеров для каждого штапика индивидуальна
Размеры и будут рассчитываться индивидуально для разных строк с нужным штапиком.
Зато, экземпляров соединений станет меньше

**Comment by Oparin-Igor** [comment]
Я чего-то не догоняю..
Задача сократить соединения или параметры, плодить параметры, то же не очень хорошая идея.
Тут надо добавить 3 параметра точно. 
1 Профильная система.
2 Глухарь или створка.
3 Створка Т или Z

**Comment by unpete** [comment]
Спешить не надо - вопрос второстепенный, но:

- Профильная система - параметр не нужен, движок и сам догадается
- Глухарь или створка - параметр не нужен, движок и сам догадается
- Створка Т или Z - это разные соединения. Вопрос был про кучу соединений одного и того же профиля с _заполнениями разной толщины_

**Comment by Oparin-Igor** [comment]
Как параметр толщины заполнения будет выглядеть и как его задавать и как он будет выбираться автоматически в зависимости от толщины пакета
