### ISSUE TITLE
Характеристика мебельного щита

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#130]
Прошу добавить характеристику щита в привязке к типу древесины и сростки, так как цены сильно отличаются, сейчас доступен только щит без характеристик.

**Comment by Oparin-Igor** [comment]
см. #118, имеющаяся формула для основного профиля, в доп.профилях и заполнениях не работает.

**Comment by aribaz** [comment]
[Заказ с дверью](https://light.oknosoft.ru/#obj=doc.calc_order&ref=a825466a-4306-4a10-e301-473f630ee9e6&frm=doc&view=orders)

Здесь в зависимости от выбранного материала изделия характеристика Мебельного щита 10мм должна наследовать характеристику изделия.

Не может быть такого, что для изделия из сращенной сосны ставим филенку из дуба цельноламельного. Из чего само изделие, из того и филенка.

Пока список выбора пуст.

**Comment by aribaz** [comment]
Евгений, добрый день.

С филенкой фокус не сработал. Характеристика щита (вставка 1368) не наследуется от материала сырья.

Я создала еще одну формулу копированием, и на закладке Параметры заменила параметр Цвет на Материал сырья, сохранила новую формулу, а потом во вставке 1368 я заменила старую формулу на новую, но результат не появился.

Это я что-то не так сделала?
Помогите пожалуйста.

Говоря об этом мы с вами еще говорили о предопределенном параметре для таких случаев, как отдельный вопрос пока не выношу.

**Comment by aribaz** [comment]
И цвета мебельного щита  и ЛКМ для него наследуются неправильно для составного цвета, для обеих сторон принимается цвет наружной стороны.

**Comment by nmivan** [comment]
@aribaz , задача актуальна?

**Comment by aribaz** [comment]
@nmivan для двухцветной покраски ЛКМ совсем не попадают в спецификацию совместно со щитом - для филенки
вставка 1368

**Comment by unpete** [comment]
Расчет спецификации внутри вставок работает одинаково для всех материалов. Такие задачи правильнее не решать, а выяснять, что мешает людям сделать настройки самостоятельно и дополнять документацию и (или) реализовывать инструменты для отладки формирования спецификаций из интерфейса пользователя.
Например, сделать флаг `drbug`, при котором система пишет подробный лог про каждый шаг расчета спецификации - какую обрабатываем вставку, какие отборы и по каким параметрам сработали.
