### ISSUE TITLE
Шаблон для входной двери открывание наружу из 113 профиля

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#131]
Прошу еще добавить шаблон к входным дверям.
Открывание наружу из 113 профиля

**Comment by Oparin-Igor** [comment]
Нет схемы применения профилей, в списке профилей не было ств 113 открывание наружу.

**Comment by aribaz** [comment]
Игорь, это не претензия к Вам. Это я выяснила, когда в очередной раз проговаривала с конструктором возможные варианты для дверей, она вспомнила про них. Я запросила по дверям схемы у конструктора, как только они у меня появятся, я выложу.

**Comment by Oparin-Igor** [comment]
Я без обид, просто объясняю что необходимо, чего у меня нет.

**Comment by aribaz** [comment]
@nmivan закрываю
