### ISSUE TITLE
Цвет  филенки

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#132]
у меня такой вопрос созрел. Когда в дверях я меняю заполнение со стеклопакета на филенку, то цвет заполнения в табчасти остается прозрачным как для стеклопакета, надо ли менять этот цвет на необходимый по заказу. 
Или это ни на что не влияет с точки зрения спецификации?

**Comment by Oparin-Igor** [comment]
Цвет менять надо. В зависимости от цвета определяется расход ЛКМ.
Расход пока не считается, нет кода для расчета ЛКМ по площади .

**Comment by aribaz** [comment]
Поняла, жду кода для расчета, я так понимаю по кодам - это к Евгению?

**Comment by aribaz** [comment]
[Заказ](https://light.oknosoft.ru/#obj=doc.calc_order&ref=a825466a-4306-4a10-e301-473f630ee9e6&frm=doc&view=orders)

У нас здесь такая схема.

Филенка  состоит обычно из двух деталей деревянных и пеноплекса между ними; если применяется деревянный профиль с алюминиевым обкладом (это еще предстоит настроить) - тогда деревянная деталь одна, далее пеноплекс и со стороны улицы вместо второй детали ставим алюминиевый лист или наборный алюминиевый профиль.

Если материал изготовления лиственница или дуб, то появляется еще изолянт.
Если на дубе хотят гладкую поверхность, появляется еще порозаполнитель.

- Лак на одну деталь наносят с двух сторон (2слоя с лица, 1слой с изнанки) расход его составляет 125гр/кв.м. на 1 деталь (с учетом сторон окраски и количества слоев).
- Грунт/Изолянт на одну деталь наносят тоже с двух сторон (1 слой с лица и 1слой с изнанки) расход его составляет 75гр/кв.м. на 1 деталь
- Порозаполнитель на одну деталь наносят только с одной стороны (1слой с лица) расход его составляет 50гр/кв.м. на 1 деталь

[Расход ЛКМ на филенку.xlsx](https://github.com/oknosoft/windowbuilder/files/577527/default.xlsx)


![2016-11-08_09-08-31](https://cloud.githubusercontent.com/assets/22028048/20089382/a08fd908-a597-11e6-832d-8400c3405912.png)

Каждая деталь красится отдельно в разборе. Расход ЛКМ зависит от количества деталей в филенке

**Comment by unpete** [comment]
Просьба при закрытии или повторном открытии задач не забывать про комментарии (проверено, дублирует #... и т.д.)
