### ISSUE TITLE
Балконная закладка неправильное отображение 

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#133]
Игорь, у меня еще вопрос на дверях в нижней части угловое соединение балконной закладки справа отображено не верно (обведено желтым), должно быть так же как и слева. 
Это же касается и входных дверей.
![2016-09-14_08-35-29](https://cloud.githubusercontent.com/assets/22028048/19192690/c0a0640c-8caf-11e6-949c-1211b241162c.png)

**Comment by Oparin-Igor** [comment]
Ошибок в настройках технологии нет. Это ошибка построителя.

**Comment by aribaz** [comment]
А мне что с этим делать? Это вопрос к Евгению?

**Comment by aribaz** [comment]
В шаблоне Трехстворчатое с одной створкой неправильное отображение рамной закладки справа от створки.

**Comment by unpete** [comment]
Доработал метод расчета координат доборных профилей.

**Comment by aribaz** [comment]
Отображается верно.
Спасибо.
Закрываю.
