### ISSUE TITLE
Сущности по ЛКМ

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#134]
У меня по покрытию выявились некоторые сложности.
После длительного разбора пкрытия ЛКМ-ами, выяснилось следующее.

Лаки и грунты в принципе по применению делятся на прозрачные покрытия (все цвета поставщика, они внесены в список цветов) и глухие покрытия (белый и все цвета RAL) - у них значительно разная цена.
Помимо этого прозрачные лаки могут быть с 30% блеском (основной для них), либо матовым - желание заказчика.
У грунта для прозрачных лаков есть дубль, но на четверть дешевле основного - его применяем при тендерных заказах - это позволяет выиграть тендер.

Для пород, содержащих танины (лиственница и дуб) изолянт разный, как по цене, так и по составу. Помимо этого для дуба есть еще один изолянт, когда заказчик хочет сделать поверхность дуба гладкой, скрыть поры (и для прозрачного покрытия, и для глухого) - тогда применяется другой изолянт. Итого 3 изолянта

Я предполагала изначально, что учту цену лака в цвете, но получилось так, что  и лак и грунт может быть разным не только по цене (в привязке к цвету), но и по эффекту, который он дает - а это расширяет ассортимент сущностей, и об этом надо как-то программе сообщить.

Что можете мне посоветовать, чтобы не задваивать сущности?
Для прозрачных лаков я могу расширить спектр цветов, добавив к ним слова Матовый и 30% блеск - и цену лака учесть так. А как быть с изолянтами (они разные для лиственницы и дуба, и внутри дуба есть два варианта) и грунтом (для прозрачных цветов в он может быть дешевым и основным?
С одной стороны мне не хочется делать дубли сущностей, с другой стороны я должна учесть различия в цене, ибо они могут стать решающими в том быть заказу или не быть.
У меня есть мысль как учесть цену и специфику покрытия в названии цвета, тогда мой ассортимент цветов будет ооочень обширен, но сущностей останется 4 и перепривязывать их к материалам профилей не придется, это конечно немного усложнит выбор менеджера - но даст возможность учесть пожелания клиента и варьировать цену заказа в зависимости от цвета (на этом настаивает директор).
И тогда в названии цвета будет содержаться  некий код (рецептура покрытия) для службы снабжения и производства каким именно лаком покрывать, какой грунт и изолянты использовать, только названия будут длиннее, чем сейчас  и ассортимент шире.
Что скажете?

Это я к вопросу о привязке цены к цвету. Е
сли ассортимент названий расширять, то скорее всего запрошу доступ к 1С с ролью технолога (так наверное быстрее будет, чем делать мне возможность осуществить привязку лака к цвету на стороне сервиса).
Если будем сущности задваивать с возможностью выбора менеджеру указать специфику покрытия - тогда я попрошу Игоря это делать.

Еще этот вопрос надо рассматривать в перспективе будущих изменений - возможно добявятся спец покрытия и эффекты к изделиям, например - патинирование, браширование, золочение - их стали спрашивать, мы на окнах пока этого не делали (только на мебели межкомнатных дверях другого цеха) - но суть в том. что это дополнительная опция к заказу, которая может быть, а может не быть - двое из которых относятся к цвету покрытия, а браширование (выявление текстуры дерева щетками) - это обработка древесины механическая, происходит до окрашивания.
Браширование на окнах - вещь сомнительная, а вот патина и золото - вполне себе могут быть добавлены и возможно не в таком уж далеком будущем.
Но проблемы решаем по мере поступления, просто хочу чтобы было понимание у вас что еще может всплыть в этом направлении.

**Comment by unpete** [comment]
Обсудим на конференции.
Замечание: создавать искусственные (лишние) элементы - очень плохая идея.
Правильный путь - добавить N параметров изделия и учесть их в алгоритме.
Если нужны параметры `матовость` и `класс изолянта`, следует именно добавлять параметры, а не пытаться растворить их в цвете.

**Comment by Oparin-Igor** [comment]
Используются разные производители красок или смешиваются из различных красок в определенной пропорции.
По лаку - надо для каждого типа древесины прописать состав лаков и нормы расхода.
Вопрос #109 привязать цену к цвету? скорее относится к составу ЛКМ.
В зависимости от расхода и стоимости ЛКМ.
Хотелось бы побольше конкретики, нет данных для реализации.

**Comment by aribaz** [comment]
Готовлю табличку, завтра постараюсь к обеду выложить, надо уточнить некоторые детали.

**Comment by aribaz** [comment]
[Прайс на ЛКМ ТЕКНОС 2016-06-07.xlsx](https://github.com/oknosoft/windowbuilder/files/525440/2016-06-07.xlsx)

Как-то так получилось у меня, если возникнут вопросы задавайте.
По-другому  не знаю как ее составить.

**Comment by aribaz** [comment]
Еще один момент не учла в табличке, так как все лаки и грунты изначально идут в одном цвете, то для придания оттенка грунту и лаку у производителя есть пигментная паста, которую они у себя на производстве добавляют в банку и именно эта паста отвечает за цвет, но мы в руках эту пасту никогда не держали, нам лаки и грунты поступают уже отколерованные. Тем не менее паста не бесплатная, нам ее учитывают в счетах в составе лаков и грунтов и отдельной строкой никогда не выделяют, жду данных от поставщика по колеровочной пасте.

**Comment by Oparin-Igor** [comment]
>Сырье
>плохое
>хорошее Параметр не определить на этапе заказа.
Или заказчик выбирает из какого сырья изготавливать.

**Comment by aribaz** [comment]
Заказчик не выбирает, иногда бывают трудности на рынке с древисиной, которые могут длиться достаточно долго и приходится брать не совсем хорошее качество сырья по цвету самой древесины, потому что если без пропитки на такое дерево положить цвет особенно на прозрачные светлые цвета, то в местах где была синь, цвет ляжет тоже пятнами.
Сегодня в производстве используют как основной грунт, в составе которого уже есть пропитка и проблема снимается в основном. Но совсем от нее отказаться не могу, вдруг не окажется на складе поставщика именно этого грунта и тогда пропитка обязательна  при плохом сырье.
Можно как параметр завести Пропитка с возможными значениями: Да, Нет. По умолчанию, действует Нет, и если вдруг понадобится, то менеджер будет иметь возможность установить значение Да.
На моей памяти были не раз случаи, когда нет хорошей лиственницы пару месяцев, а сроки по заказам идут,  и заказы сдавать надо, а именно на ней чаще всего и выползают пятна. О том что предвидятся сбои с поставкой материалов мы не всегда можем узнать от поставщиков заранее, это связано в основном с погодными условиями (дожди) в местах заготовки кругляка.

**Comment by Oparin-Igor** [comment]
Тогда может заложить применение пропиток для плохой древесины как стандартное, а применять или нет при выдаче со склада и корректировать накладные.

**Comment by aribaz** [comment]
Он тогда повлияет на стоимость заказа для заказчика в большую сторону, и для нас это может закончиться потерей заказа.

**Comment by aribaz** [comment]
Игорь, выяснила всю ситуацию по ЛКМ. Итого по сущностям:

- [ ] Пропитка
Она к цвету никак не привязана, ее можно использовать и для глухих и для прозрачных покрытий, привязка к плохому сырью.
Расход на 1м.пог. бруса составляет 0,064л - 1слой. Наносится в 1слой всегда.

- [ ] Грунт
Грунт используется всегда. У поставщика грунт в базовом цвете весь (или бесцветный, или белый). Чтобы он приобрел необходимый цвет в него добавляют колеровку (пасту) , когда мы просим грунт, например, береза, то они на производстве у себя берут грунт AquaPrimer 2907-02 Base T (18л) - 109,76евро/банку, добавляют в нее колер береза (расход колера в зависимости от цвета разный от 100гр, до 1 литра на банку) - 0,68евро/литр, итого у нас получается чуть больше 18л колерованного грунта. Эта паста никак не значится в документах как отдельная единица, просто к названию базового грунта добавляют название цвета пасты. Мы эту пасту никогда не использовали сами. Для грунтовки изделий используется  именно колерованный грунт, а не базовый.
Колер для каждого цвета стоит по разному за один и тот же объем.
Расход грунта колерованного составляет 0,032л на 1м.пог. бруса  -  1слой.
Наносим всегда в 2 слоя.

- [ ] Лак
В качестве лака применяется смесь, условно называемая лаком. Лак сам по себе у поставщика весь в базовом тоне (или прозрачный, или белый).
Чтобы получить 1литр смеси лака надо:

1. 800мл  - базового лака
2. 80мл - колерованного грунта (подкрашивает лак)
3. 120мл - обычной воды (позволяет смеси проходить через сопло краскопульта, обеспечивает текучесть смеси, лаки и грунты у нас водные, поэтому разбавляем водой - так положено, это не экономия). 
Смешав эти три компонента мы получим готовую смесь лака.
Эту смесь всегда наносим в 2слоя, расход смеси лака на 1м.пог. бруса соствляет 0,064л.

- [ ] Изолянт для лиственницы
Он не подкрашивается применяется вне зависимости от типа покрытия и качества материала.
Это смесь из 2 компонентов:

1. GORI 644 CLEAR (7,5л/банка)
2. REAKTOR 7531 CLEAR (5л/банка)
На нашем производстве смешивают обе банки в одной емкости, и эту смесь используют только как изолянт для лиственницы. 
Она (смесь) наносится в 1слой всегда, расход на 1слой 0,064л на 1м.пог. бруса

- [ ] Изолянт для дуба стандартный вариант
Он состоит из двух компонентов, но они наносятся по-очередно (по-слойно), мы их не смешиваем в 1 банке. а используем по-отдельности. Применяется вне зависимости от типа покрытия и качества материала (при условии открытых пор). Используется для дуба с открытыми порами, когда гладкая поверхность не требуется.
Компоненты:
Первый слой - GORI 642-01COLORLESS, расход 0,032л на 1м.пог. бруса (кол-во слоев - 1)
Второй слой  - GORI 643CLEAR, расход 0,032л на 1м.пог. бруса (кол-во слоев - 1)

- [ ] Порозаполнитель.
Он применяется только в том случае, если тип древесины  - дуб и заказчик хочет скрыть поры дуба и иметь гладкую поверхность профилей.  На других типах древесины он не нужен совсем. Наносится в 1слой всегда, расход на 1слой составляет 0,064л на 1м.пог.бруса

- [ ] Изолянт для дуба для закрытых пор.
Применяется вне зависимости от качества материала. Но только в том случае, если материал  - дуб и заказчик хочет на нем хочет гладкую поверхность. Наносится он в два слоя всегда, вне зависимости от типа покрытия. Но для каждого типа покрытия, применяются разные варианты:

- Для  прозрачных цветов применяется смесь из двух компонентов:

1. Protec 330 (10 частей)
2. Protec 330/1 (1 часть) 
Расход этой смеси составляет: 0,064л на 1м.пог. бруса, слоев - 2

- Для глухих цветов в этом случае используется
Protec 370 - это самостоятельный компонент, он ни с чем не смешивается. Наносится для этих случаев всегда, в 2слоя. Расход  его на 1 слой составляет 0,064л на 1м.пог. бруса.


- [ ] Изолянт для сосны - никогда не применяется, так как нет в ней танинов.

Таким же способом (сущностями) красят и штапик, и филенки, и нащельники, и раскладку - для них изменяется только расход этих сущностей. О нем еще не собрала данные.

**Comment by aribaz** [comment]
Игорь, извините что так долго, я переделала табличку, чтобы и вам было понятней, и у самой уложилось в голове.

Сначала смотрите лист **Параметры для ЛКМ** - в нем параметры, которые должен/может выбрать пользователь.

далее лист **Спецификация** в нем привязка номенклатур к сущностям, типу покрытия и виду материала) - то есть что должно попасть в спецификацию при выборе одних или других комбинаций параметров, а так же расход этих сущностей в зависимости от типа изделия. на которые они наносятся.

на странице **Составы** речь идет только об изолянтах - там просто очень сложная схема применения номенклатур в зависимости от вида дерева, типа покрытия  (они по составу отличаются, хотя у всех у них одно назначение и по сути это одна сущность.

Я переименовала параметры в более удобоваримые названия, как мне думается, критику принимаю.
[Сущности ЛКМ.xlsx](https://github.com/oknosoft/windowbuilder/files/611895/default.xlsx)

**Comment by aribaz** [comment]
И Как напоминание, что у нас цена зависит еще от цвета (это пасты). В руках мы эти пасты не держали никогда, как самостоятельную сущность и сами ничего не смешивали и как мне кажется, мне производители рецептуру добавления паст на ведро (грунта/лака) не дадут, значит будем отталкиваться от 1л пасты на банку 18л (грунта или лака) - это только для расчета цены, а для расчета количества грунта или лака считаем, что мы туда ничего не добавляем.

**Comment by aribaz** [comment]
Еще в списке цветов сейчас отсутствует цвет Составной - при выборе этого цвета  стоимость работ увеличивается по сравнению с покраской изделия в один цвет.

При выборе цвета "Составной" должно появиться два поля:

- Цвет снаружи
- Цвет изнутри

в каждом из которых можно выбрать один из цветов, описанных в таблице.

И вроде по покраске все.

**Comment by aribaz** [comment]
Учет цены за цвет решили сделать в Ценовой группе (это за мной)

**Comment by unpete** [comment]
Редактор составных цветов см #23

**Comment by aribaz** [comment]
Евгений, в справочнике я сделала три группы цветов по типу покрытия, они называются Тип покрытия, в них включила номенклатуры, на которые это влияет - это вместо параметра "Тип покрытия".

И еще сделала 15 групп по цвето-ценовым группам - это влияет на стоимость лака и грунта подписала добавку к цене в названии, на закладке Соответствия указала какие цвета относятся к это группе, только я не поняла что я должна была указать на Закладке Ценовые группы.

Не уверенна, что правильно сделала, если что подскажите, я исправлю.

**Comment by nmivan** [comment]
@aribaz , эта задача актуальна?

**Comment by aribaz** [comment]
@nmivan закрываю, вопрос решили
