### ISSUE TITLE
Учетная запись для меня на стороне 1С с правами Технолога

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#135]
Евгений, только пожалуйста подскажите куда потом мне надо заходить, чтобы добраться до справочников.

**Comment by unpete** [comment]
В терминале ярлык `zdn - отладка`. Имя пользователя и пароль, такие же, как для подключения к сервису.
**Важно**: перед тем, как изменять любые данные, убедитесь, что в свойствах `Интеграция - настройка` на первой закладке в поле `Zone` указано значение `2`.
Текущую зону мог поменять, например, Игорь или я при добавлении нового абонента.
Если зона <> 2, надо указать 2 и применить настройку кнопкой `Записать URLS`
При редактировании документов и справочников в 1С, данные синхронно отправляются в ту область данных сервиса, которая назначена текущей в обработке `Интеграция - настройка`

**Comment by unpete** [comment]
Если некие объекты окажутся доступными только для чтения - пишите, отредактирую права

**Comment by aribaz** [comment]
Спасибо, завтра попробую.

**Comment by aribaz** [comment]
Евгений, подскажите, если я хочу немного подправить шаблон, мне это где делать? На стороне 1С, я не нашла их в фильтрах, это можно делать на стороне сервиса?

И еще момент, если мы явно выносим такие параметы как Цвет уплотнителя, водоотвода, отлива - имеют ли тогда смысл таблицы соответствия цветов для этих параметров?

**Comment by unpete** [comment]
> подправить шаблон

Графический редактор только со стороны сервиса.
В 1С можно изменить только правила расчета спецификации

> таблицы соответствия цветов для этих параметров

Насколько я понимаю, таблица соответствия работает так:
- анализируется ключ из двух полей: исходный цвет + номенклатура текущей строки спецификации
- если для номенклатуры или цветовой группы, в которую входит текущая номенклатура найдено соответствие, используется цвет соответствия, а не исходный цвет

**Comment by aribaz** [comment]
Стала исправлять таблицу соответствия цветов, что мне делать если необходимого цвета (не для профиля основного)  нет. В какую паку их добавлять?

**Comment by aribaz** [comment]
И еще мне нужны цвета по каталогу RAl. их сейчас нет, завести для них отдельную папку?

**Comment by aribaz** [comment]
Что-то нужно сделать чтобы изменения, которые я внесла отобразились на стороне сервиса?

**Comment by unpete** [comment]
> дуб 3118076. Я могу его переименовать? или создать новый?

Новые ссылки создаём в крайнем случае, если уверены, что это не дубль.
В данном случае, элемент правильнее переименовать.

> цвета по каталогу RAl. их сейчас нет, завести для них отдельную папку

Папки нужны для группировки объектов по существенным свойствам этих объектов (относится не конкретно к цветам, а вообще к любым справочникам).
Например, папки _Тёплый_, _Холодный_, _Тёмный_, _Составной_ могли бы иметь смысл.
У цветов уже есть реквизит RAL. Понять, что у некого цвета есть ral-идентификатор мы можем по заполненности этого реквизита. Не нужно дублировать эту информацию в папке.

Для привязки цветов к системам и элементам, используется справочник _Соответствия цветов_ (тот же самый, что и собственно для соответствий, но с другим _Назначением_)

**Comment by aribaz** [comment]
Сейчас зашла в 1С,  зона 0, изменила на 2, она мне выдала сообщение "Опасно! Неверное значение может нарушить синхронизацию. Продолжить редактирование?" Я нажала отмена. Или ничего страшного не произойдет?

**Comment by unpete** [comment]
> ничего страшного не произойдет?

Страшного ничего не произойдёт. Зону 0 ставит Игорь.
Два технолога одновременно работать в 1С не могут.
Можно, конечно, создать для вас отдельную базу и не париться с зонами, но для меня это означает удвоение расходов на администрирование.
