### ISSUE TITLE
Роль заместителя для любого пользователя.

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#136]
Евгений, подскажите, как нам быть например, если человек ушел в отпуск, заболел или уволился, а у него в базе остались заказы, которые нам нужны? Например для подтверждения (для старшего менеджера), или отправки на согласование (для менеджера). Ведь паролей у меня не будет от учеток ни дилеров, ни наших сотрудников.

**Comment by unpete** [comment]
На сегодня, задействованы следующие группы доступа:

- Добавление и изменение документов Расчет-заказ
- Согласование и проведение документов Расчет-заказ
- Настройка технологии
- Настройка интеграции
- Редактирование скидок
- Редактирование событий диспетчеризации
- Редактирование оплат
- Редактирование отгрузок
- Изменение участников групп доступа (администратор пользователей)
- Полноправные абоненты (все перечисленные выше роли)

В любой момент любого пользователя можно включить в любую группу или исключить из группы - его права в сервисе изменятся.

**Comment by aribaz** [comment]
А у меня вытекающий вопрос.
Можно ли каждому конкретному пользователю назначать роли, а не права с предопределенным набором прав?
Это было бы здорово и позволило бы более гибко настроить права доступа каждому пользователю, так сказать каждому по потребностям.

**Comment by unpete** [comment]
> каждому конкретному пользователю назначать роли

В БСП механизм немного другой:
1. Сначала создаются Профили полномочий и группы доступа - по сути - списки ролей
2. Далее, пользователей включают в одну или несколько групп доступа

Оперировать атомарными ролями было бы слишком трудоёмко. В современных конфигурациях 1С, этих ролей - сотни.
Ваше требование можно реализовать, если создать по профилю на каждую роль.

Предложенный в БСП механизм - весьма неплох. Сразу заметно, что люди потратили несколько человеколет на его разработку и учли опыт многих тысяч реальных внедрений.

**Comment by aribaz** [comment]
Меня в принципе все устраивает, кроме некоторых моментов.
Группа "Добавление и изменение документов Расчет-заказ" - меня устраивает - это обычные дилеры.

Меня больше интересует группа "Согласование и проведение документов Расчет-заказ".
Если я правильно понимаю, то имея права этой группы можно устанавливать цены на материалы, заводить /редактировать контрагентов, проводить оплаты по заказу; согласовывать и проводить заказы, редактировать их.
Я бы эту группу разделила на две части: экономическую и производственную.
**Экономическая часть**
Здесь все, что касается ценообразования заказов - из чего складывается стоимость заказа (без учета скидок и наценок, плановая себестоимость так сказать) - эту часть ведет один человек, ответственный за цены и это не старший менеджер, человек этот может вообще заказы никак не оформлять и к ним в целом не иметь отношения. Но он вносит цены на материалы, может их редактировать, устанавливает К марж и прочие цено-образующие документы.

**Производственная часть:**
Здесь все что касается основных и вспомогательных действий с заказами уже созданными (добавление/редактирование контрагентов, проведение заказов, согласование заказов, редактирование заказов, проведение оплат по заказам). И это как раз старший менеджер, он курирует заказы все или группу заказов по контрагентам, но он не знает и не должен знать из чего складывается стоимость заказа. 
Скорее всего все менеджеры завода будут старшими менеджерами (будут иметь права провести/согласовать заказ) возможно закрепленными за разными дилерами, но ни один из них не должен знать из чего складывается стоимость заказа; а все дилеры - это просто менеджеры.

Собственно в разделении этих зон одной группы прав вся моя беда.
Все остальное - нас устраивает полностью.

**Comment by unpete** [comment]
> Согласование и проведение документов Расчет-заказ. Если я правильно понимаю, то имея права этой группы можно устанавливать цены на материалы, заводить /редактировать контрагентов, проводить оплаты по заказу; согласовывать и проводить заказы, редактировать их

- устанавливать цены нельзя - для этого нужна роль _РедактированиеЦен_
- заводить /редактировать контрагентов - можно
- проводить оплаты по заказу нельзя - для этого нужна роль _РедактированиеОплат_
- согласовывать и проводить заказы, редактировать их - можно

> Экономическая часть

Менеджер не может повлиять на плановую себестоимость, но конечные цены и скидка - в его власти. Свободу менеджера можно ограничить, но текущий проект - не про это.

>  ни один из них не должен знать из чего складывается стоимость заказа

У нас уже было обсуждение на эту тему. Информация о составе заказа есть в системе. Если человек имеет доступ к заказу, он имеет доступ и к деталям.

**Comment by aribaz** [comment]
Роли редактирование цен и редактирование оплат - это здорово.

Вы вроде говорили о каких-то косметических мерах? Чего с помощью них можно достичь (если они возможны)?
