### ISSUE TITLE
Срок сдачи заказа

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#139]
Еще я поняла, что сейчас нет нигде данных о том, когда заказ надо сдать, а эти данные нужны, чтобы ориентироваться в списке запущенных заказов. Этап диспетчеризации наступит не скоро и для менеджеров надо предоставить какое-то поле для явного указания в нем  срока сдачи, ведь пока диспетчеризацию не настроим нельзя говорить об автоматическом расчете сроков, а знать когда нужно сдать заказ надо.

**Comment by unpete** [comment]
> Этап диспетчеризации наступит не скоро

Скоро или нет, зависит только от вас. Так называемая диспетчеризация состоит из двух частей: плановые и фактические даты.
Структуры для хранения этих дат придуманы и реализованы с учетом многолетнего опыта диспетчеризации. Усложнять их не надо. Упростить так же, не получится.
Задача для Вас: понять, как устроен регистр диспетчеризации и начать пользоваться.
Есть задача и для меня: сделать интерфейс для редактирования и просмотра данных диспетчеризации, но эта задача - косметическая. Движок работает уже сейчас - без интерфейса.

**Comment by aribaz** [comment]
Я понимаю, что это зависит от нас, в этом у меня и беда, что не от меня лично. Мы уже договорились с начальником в цеха, что я после работы ему звоню и мы по минут 15-20 разбираем все мои комментарии, и уже начали работать в таком ритме, думаю в неделю, дней 10 уложимся, во всяком случае постараемся. Другого выхода я не вижу, к сожалению. 
Я здесь имела ввиду несколько другое, нигде не встретила поля, которое бы было предназначено для плановой даты сдави заказа, я понимаю, что пока мы не предоставим даты, она не появится там никак, но и поля не увидела. Может и правда не увидела.

**Comment by unpete** [comment]
> не встретила поля, которое бы было предназначено для плановой даты сдачи заказа

Это вычисляемое поле. Алгоритм зависит от заказчика. Скорее всего, вас устроит, если плановой датой сдачи заказа будем считать максимальную плановую дату из всех экземпляров изделий заказа.
Редактировать эту дату напрямую, было бы ошибкой.
По аналогии с полем "Сумма документа". Поле есть, но изменить можно только суммы в строках заказа. Сумма документа пересчитывается автоматически.
В типовой 1С КА, дата отгрузки размещена в строках заказа. Это ошибка архитектуры типовой конфигурации, т.к. у разных экземпляров одной строки могут быть разные плановые и фактические даты.

**Comment by aribaz** [comment]
Мы пришли к тому что необходимо поле для договора  и очень примерной ориентации.

**Comment by nmivan** [comment]
@aribaz , задача актуальна?

**Comment by aribaz** [comment]
@nmivan Максимальная дата заказа меня устроит в большинстве случаев, но не всегда, потому как бывают заказы разделенные по этапам (связано с проведением строительных работ на объекте) и тогда например первый этаж мы сдаем в одно время, второй этаж. в другое и так далее, или по фасадам, хотя юридически все числится в одном договоре. 
Можно где-то почитать на эту тему что есть уже сейчас, как оно должно работать и что надо сделать, чтобы этим воспользоваться? Может и не нужно поле.

**Comment by nmivan** [comment]
После решения задачи [329](https://github.com/oknosoft/windowbuilder/issues/329), думаю, можно будет почитать.

**Comment by nmivan** [comment]
@aribaz , прошу почитать[ раздел в wiki](https://github.com/oknosoft/windowbuilder/wiki/%D0%9D%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-%D0%B8-%D0%B0%D0%BB%D0%B3%D0%BE%D1%80%D0%B8%D1%82%D0%BC-%D0%BF%D0%BB%D0%B0%D0%BD%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F), потом предлагаю обсудить еще раз эту задачу.
