### ISSUE TITLE
Возможность выбрать изделие заказа указав эскиз

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#140]
Еще часто ловлю себя на том, что хочу выбрать конкретное изделие заказа ткнув в эскиз, расположенный снизу, а не выбирать его из строк. Проще выбирать по внешнему виду, чем по описанию в табчасти, к тому же описание не всегда будет соответствовать действительности с точки зрения конструкции изделия.
Но это пожелания на будущее.

**Comment by unpete** [comment]
Эскизы в формах списка и документа сделаны активными.
- одиночный клик в форме документа активизирует строку в табчасти продукции, соответствующую текущему изделию
- двойной клик в формах документа и списка открывает графический редактор изделия
- двойной клик в форме выбора произвольного изделия (команда _заполнить по шаблону_), закрывает формы выбора и заполняет текущее изделие, экономя при этом два клика и поиск изделия в списке

**Comment by aribaz** [comment]
Спасибо большое. Это очень круто!!!
И за то подсвечивается строка с изделием, эскиз которого выделили. Это очень удобно и наглядно.
