### ISSUE TITLE
Горячая клавиша для кнопки Редактировать изделие в построителе.

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#141]
Было бы здорово, если бы для клавиши Редактировать изделие в построителе была возможность пользоваться горячей клавишей (сочетанием клавиш) на клавиатуре, а не искать кнопку мышкой - это не очень удобно, для тех кто привык пользоваться клавиатурой - это замедляет процесс.
В идеале, было бы здорово выбрав нужную строку стрелками открыть изделие для редактирования клавишей Enter, но другая клавиша тоже подойдет.
Это тоже из серии Пожелания сервису.

**Comment by nmivan** [comment]
@aribaz , пожелание актуально? Или привыкли к кнопке?

**Comment by aribaz** [comment]
@nmivan, человек ко всему привыкает, в принципе для редактирования я пользуюсь двойным щелчком по эскизу - это в целом аналог, плохо только то, что если строк в заказе >18, то остальные эскизы уже не видны, только первые 18, а остальные приходится открывать кнопкой. Если будет возможность пролистывать эскизы, то горячая клавиша и не нужна.

**Comment by unpete** [comment]
Скроллинг эскизов и горячие клавиши добавлю v2. Функции полезные, но не
срочные.
