### ISSUE TITLE
Добавление параметров к изделию

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#143]
Прошу добавить параметры к строке изделия в табчасти:
- [x]  Цвет уплотнителя
- [x] Цвет  водоотводного профиля
- [x] Цвет  профиля покрытия оконных створок

**Comment by Oparin-Igor** [comment]
У каждого параметра должен быть перечень значений
Цвет уплотнителя:
-бежевое
-белое
-дуб
-и т.д.

**Comment by aribaz** [comment]
- [ ] Уплотнитель  (4 варианта):

- белый
- коричневый
- светлый дуб (основной)
- бежевый (крайне редко)

- [ ]  Цвет  водоотводного  профиля #118 :

- RAL 8017
- RAL 9016
- Заказной

- [ ] Цвет профиля покрытия оконных створок #117:
- RAL 8017
- RAL 9016
- Заказной

**Comment by aribaz** [comment]
Для водоотводного профиля и профиля покрытия оконных створок при выборе цвета "Заказной", в спецификацию должна попасть услуга "Окраска профиля", измеряется в м.пог. профиля, осуществляется на стороне, мы за это платим. 
И помимо того что мы купили и привезли на свой склад неокрашенный профиль, нам потом надо этот неокрашенный отвезти сторонней организации на окраску и обратно в цех (поставщик этого профиля окраской не занимается, к сожалению), и не всегда получается соединить эту поездку совместно с чем-то, получается специальное катание из-за одной палки - это деньги, по хорошему надо тоже как-то учесть, как минимум с той точки зрения, что на это надо запланировать время, чтобы не просрочить заказ и не создать себе аврал - это к вопросу плановых дат готовности заказа..

И к вопросу #129  уточнила у начальника цеха, если просят экзотические цвета (Заказной) и одно окно (недавно был случай) - то он на производстве пилит неокрашенный (к готовой длине профиля +40мм*2) и везет на покраску не хлыст, а полуфабрикат, его красят, он обрезает технологические отверстия и устанавливает. Можно ли при выборе для этих профилей цвета Заказной увидеть где-то что-то типа подсказки: "Предварительная напиловка профиля". Как услугу ее учитывать не надо, так как он весь профиль всегда пилит в размер, здесь важно чтобы не увезли хлыст.

**Comment by nmivan** [comment]
@aribaz , эта задача решена?

**Comment by aribaz** [comment]
@nmivan , да все готово
