### ISSUE TITLE
Копия заказа

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#144]
Добавить возможность скопировать заказ целиком, а не по частям.

**Comment by nmivan** [comment]
@aribaz , речь о копировании заказа внутри сервиса или о копировании во внешнее приложение, наподобие ворда?

**Comment by nmivan** [comment]
@aribaz , напоминаю, ждем ответа.

**Comment by aribaz** [comment]
@nmivan спасибо, потерла его в списке.
Речь идет о копировании внутри сервиса. Сейчас есть возможность скопировать какое-то изделие. Если нужно для сравнения сделать расчет одного и того же заказа в разной породе дерева, то сейчас менеджер сначала делает один заказа, потом создает второй и чтобы заново не заводить все параметры, использует уже созданный заказ и по-одному изделию вставляет в новый заказ, а было бы здорово, чтобы можно было целиком скопировать заказ со всем изделиями/параметрами. Если строк в заказе много  - это значительно сократит время создания и обработки заказа.
