### ISSUE TITLE
Состав колонок списка заказов и отдельного заказа.

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#145]
Вот еще часто о чем думаю.
У нас сегодня есть график по оконному цеху, мы вам его показывали он сейчас в себе содержит общую информацию по каждому заказу в целом и по вообще по всем заказам, конечно он еще содержит в себе данные о том, что снабжением обработано (заказано/оплачено/доставлено), а что нет. Этот инструмент удобен для ориентирования особенно производственникам  и снабжению, а так же конструктору, реже менеджеру (некоторая часть).

Может быть есть возможность предоставить конкретному пользователю настраивать внешний вид списка заказов и списка изделий? 

Это было бы очень удобно, и в последствии избавило бы от составления этого графика вручную - он был бы у всех в том виде в каком удобно отдельно взятому пользователю и в нем всегда актуальные сведения.

Например, мне как менеджеру хочется видеть в табчасти заказа (для каждой строки заказа) такие колонки как: цвет заказа, тип ручек и их цвет, цвет уплотнителя, цвет водоотводника - это мне бы позволило бегло взглянув на страничку сразу увидеть, например, что в одном изделии я не изменила материал, или наоборот промахнулась мимо нужного и заняло бы все это у меня считанные минуты, тогда как сейчас, чтобы быть точно уверенной, что я в заказе все правильно выбрала, мне нужно открыть каждое изделие и проверить все эти параметры - и не факт, что не промахнусь еще раз, а для ручек так вообще ткнуть каждую створку и в табчасти створки посмотреть парметры ручек, это не очень удобно и если в заказе больше 5 окон, да еще многостворочных, так это еще и большие временные затраты, а проверить себя нужно обязательно. Лично я уже сталкивалась с тем, что забывала изменить одну ручку, или цвет, или материал, или стеклопакет. Это даст бОльшую уверенность в том. что заказ обработан верно и глупых косяков не предвидится.
С другой стороны, мне как менеджеру в списке заказов не очень хочется видеть все параметры заказа, так как я ориентируюсь в них по полю Клиент - для меня этого достаточно, чтобы понимать что это за заказ. И меня почти устраивает набор колонок списка заказов, разве что я бы добавила колону Организация - это удобнее, чем рассматривать префикс заказа для понимания, а правильно ли я указала Организацию.

Если смотреть с точки зрения производства и снабжения, то здесь хочется, видеть для списка заказов параметры каждого. Ведь запускаемся мы без диспетчеризации и она последует не так скоро, а жизнь сервис не должен усложнить. Мне как начальнику производства было бы удобно видеть из чего этот заказ, какие там стеклопакеты, какой цвет заказа и прочие параметры - для меня важны, именно по ним ориентируется производство. С точки зрения снабжения - это позволит мне в будущем составлять ведомости по группам заказов, ориентируясь на один тип материала, и снабжение будет четко знать, какие именно заказы надо включить в ведомость, чтобы получить список простых стеклопакетов, или, например, сможет составить ведомость для заказа бруса одного типа материала, ориентируясь на колонку материал. 

Это существенно облегчит всем жизнь тем, что даст возможность видеть необходимую информацию по заказу, с другой стороны даст возможность убрать лишнюю информацию, чтобы не перегружать пространство ненужными конкретному человеку данными.

Было бы совсем круто, если бы снабжение смогло уже на этой стадии  регистрировать там такие события (возможно цветом, хотя конечно правильнее  - дата события, но и цвета будет вполне достаточно), как заказ материалов, оплата материалов, доставка материалов. Это бы позволило вообще отказаться от графика и сэкономило бы кучу времени на его составление, и более того предоставило бы заинтересованным лицам всегда актуальную информацию - а это сократит бесконечные звонки на тему график сегодняшний, а это оплатили? а это доставили?
Если это будет реализовано на старте это прямо праздник получится)

**Comment by unpete** [comment]
> настраивать внешний вид списка заказов и списка изделий

- Это отчет
- Он описается на основные регистры системы - планирование и диспетчеризация
- Его можно подключить к одному из вариантов списка заказов
- Он не будет повторять вашу таблицу в точности, т.к. в вашей таблице есть логические ошибки, но будет в состоянии эту таблицу заменить, сможет отвечать на все вопросы, на которые сейчас отвечает ваша таблица

**Comment by aribaz** [comment]
[Таблица для списка изделий с параметрами.xlsx](https://github.com/oknosoft/windowbuilder/files/535366/default.xlsx)

Нужна для проверки менеджером самого себя. Все ли правильно он сделал.
Еще было бы здорово, если бы в табчасти заказа можно было видеть сумму по колонке Количество изделий и по колонке Площадь (но с учетом количества) - сейчас мы по площади понимаем загрузку цеха, а по количеству  - планируем кол-во машин на доставку.

И если в списке заказов появится графа Организация - для менеджера так будет удобнее, я понимаю, что и сейчас я могу понять от какой организации делаем заказ, но приходится вглядываться в номер заказа, чтобы по префиксу понять это.

**Comment by unpete** [comment]
> сейчас мы по площади понимаем загрузку цеха, а по количеству - планируем кол-во машин на доставку

Главное, что выделяет `Заказ дилера` на фоне остальных решений для подготовки производства, это `регистр планирования`.
Судить о загрузке производства надо не по вульгарным количествам и площадям, а по остаткам этого регистра на интересующую дату. Так же, как вы это делаете для понимания остатка денег на счетах и в кассах и остатка материалов на складах.

> если бы в табчасти заказа можно было видеть сумму 

Экранные формы должны быть максимально простыми. Они предназначены для редактирования данных.
Для анализа и агрегирования данных используются отчеты. Они так же, должны быть простыми и доступны контекстно из любого места.

**Comment by nmivan** [comment]
@aribaz , чем кончилось обсуждение? Последний ответ был от Евгения.

**Comment by aribaz** [comment]
@nmivan в целом я с ним согласна, что все о чем я прошу это отчеты и правильнее всего решать задачу именно с этой стороны.  Впорос в том, когда появится возможность такие отчеты делать. Это из разряда на будущее.

**Comment by nmivan** [comment]
@aribaz , отчеты сейчас у нас в приоритете и в работе как раз, их реализация в платформе. Чтобы можно было быстро делать отчеты в прикладном решении (сервисе Заказ дилера).
Предлагаю эту задачу закрыть, а открыть новые - по отчету/отчетам, которые вам необходимы (кроме тех, что вы уже писали).

**Comment by aribaz** [comment]
@nmivan хорошо, закрываю, по новым буду в своем репозитории создавать
