### ISSUE TITLE
Балконная дверь (параметры)

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#146]
Для шаблона Балконная дверь при выборе Фурнитура - двери балконные (это правильный вариант).
1. нет возможности выбрать основную ручку и ее цвет. В спецификацию автоматом попадает 59506, список вариантов как в окнах должен быть.
2. Параметр: ручка балконная (и для пластиковой, и для металлической) в спецификацию ничего не попадает. 
   ![image](https://cloud.githubusercontent.com/assets/22028048/19352019/df975558-9166-11e6-8ac9-33e8e1350efd.png)
   ![image](https://cloud.githubusercontent.com/assets/22028048/19352063/1d98951a-9167-11e6-85cd-0c9a05b448d6.png)

Это пластиковые ручки

Необходимы параметры колпачков (исключительно желание заказчика): 
цвет колпачков (простых: коричневый, бронза, мат. латунь и возможно еще пара; пешка - золото, бронза и вроде тоже еще пара вариантов)
тип колпачков (простые - это умолчание; пешка - редкое желание клиента)

**Comment by Oparin-Igor** [comment]
Наименование параметра и значений?

**Comment by aribaz** [comment]
Наименование параметров для балконных дверей:

- [ ] Тип ручки

- Harmony
- Harmony с ключом
- Symphony
- Rharsody
- нет


- [ ] Цвет ручек

**Harmony**

- светлая бронза
- золото матовое
- титан
- шампань
- серебро
- коричневый

**Harmony с ключом**

- белый
- светлая бронза
- титан
- шампань
- серебро
- коричневый

**Symphony**

- белый
- светлая бронза
- титан 
- шампань
- коричневый

**Rharsody**

- белый
- светлая бронза
- золото матовое
- титан
- шампань
- серебро
- коричневый

**нет**

- нет цветов


- [ ] Тип колпачков

- прямые
- пешка



- [ ] Цвет колпачков прямых (это желание заказчика)

- никель 
- матовый никель
- бронза
- золото
- белый
- коричневый

- [ ] Цвет колпачков пешка

- золото
- бронза
- матовая латунь
- коричневый

Цвет балконных ручек можно описать в таблице соответствия цветов.

Здесь важен видимость списка цветов для каждого отдельно взятого параметра, а то закажут ручку Симфония  - золото матовое, а ее в природе нет.

В балконной двери , как и во входных дверях цвет ручек и колпачков может и не совпадать

**Comment by Oparin-Igor** [comment]
Данная задача решается через ключ соответствие параметров.
Пример списка (параметр не учитываем, только цвет):
цвет ручка оконная - цвет ручка балконная

нет
нет цветов (без выбора)

 Цвет ручек (колпачков) или цвет ручек и колпачков может не совпадать?

**Comment by aribaz** [comment]
Для окон цвет ручек и накладок на петели совпадает; а для дверей и балконных, и входных цвет ручек и колпачков могут быть совершенно разными (здесь решает заказчик какие колпачки он хочет к конкретному цвету ручек), так как производители ручек и колпачков разные, и поэтому нет совпадений по оттенкам

**Comment by aribaz** [comment]
Игорь, прошу прощения, за слишком частое внесение изменений.
Сегодня еще раз обговаривали все параметры по дверям в целом, выплыли еще нюансы.
Итого по балконным дверям:

1)	**Тип фурнитуры:**
a)	Масо поворотно-откидная 
Она для тех случаев, когда хотят сделать балконную дверь поворотно-откидной и еще использовать микрощелевое проветривание. Но в отличие от окна этот тип фурнитуры должен иметь еще дополнительно параметры балконной двери: микролифт, блокада ручки, балконная защелка, ручка балконная 
b)	Двери балконные
Наш стандартный вариант с петлями отлав и без проветриваний, какой и предусмотрен для этих дверей сейчас.
2)	**Тип ручки**
a)	Ручка
i)	Harmony
ii)	Rhapsody
iii)	Symphony
iv)	Harmony с ключом
b)	Нажимной гарнитур
(во входных дверях это простой нажимной гарнитур)
i)	Harmony
ii)	Rhapsody
c)	Раздельный нажимной гарнитур
i)	Harmony
ii)	Rhapsody
3)	**Цвет ручки и гарнитура**
a)	Белый (кроме  ручки гармонии
b)	Светлая бронза
c)	Титан
d)	Шампань
e)	Серебро (кроме симфонии)
f)	Коричневый 
 (ручки и гарнитур только Harmony)
g)	Золото матовое 
(только для ручек, кроме симфонии)
4)	**Цвет колпачков на петли**
a)	никель
b)	мат. никель
c)	бронза
d)	золото
e)	белый
f)	коричневый
5)	**Штульповое открывание**
a)	Нет
b)	Штульповый запор
c)	Шпингалеты
6)	**Блокада ручки** (по желанию клиента, только для ручек, не для гарнитуров)
a)	Да (не все цвета)
i)	Кнопка (только для Рапсодии)
ii)	Ключ (только для Гармонии и Рапсодии)
b)	нет
7)	**Балконная защелка**
a)	Да
b)	нет
8)	**Ручка балконная**
a)	Белая
b)	Коричневая
c)	нет

**Comment by aribaz** [comment]
пункт 6 Блокада ручки
его учитываем в названии ручки и отдельно не выносим
Уже знаю, что это не блокада

**Comment by nmivan** [comment]
@aribaz , по этой задаче чем кончилось?
