### ISSUE TITLE
Эскизы петель на шаблонных окнах

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#147]
Не отображаются эскизы петель на окнах.
Для Шаблона балконная дверь я изменила фурнитуру на двери балконные и эскизы петель появились

**Comment by Oparin-Igor** [comment]
Размеры петель? Эскиз?

**Comment by aribaz** [comment]
Петли на эскизе отображаются если например из трехстворчатого сделать другое окно и сохранить изделие, тогда петли отрисованы.
https://light.oknosoft.ru/#obj=cat.characteristics&ref=f9008e21-8ac8-4522-9736-1e45083c732c&frm=builder&view=orders

**Comment by Oparin-Igor** [comment]
В поворотном так же теперь рисуются.

**Comment by nmivan** [comment]
@aribaz , эта задача актуальна?
