### ISSUE TITLE
Фильтр Согласовано

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#148]
Если заказ находится в этом фильтре, то это означает, что заказ уже был отправлен и он проведен (ведь только после этого он может попасть в этот фильтр).
Но в этом фильтре кнопка Отправить заказ активна, хотя, конечно,  по нажатию на нее заказ не перемещается в Отправленные, но и кнопка не должна быть активной.
И исходя из того, что чтобы заказ попал сюда его сначала надо провести, то и кнопка Провести заказ не должна быть активной, во всяком случае до того момента, пока не нажму на кнопку Отменить проведение, а то открываешь заказ и не понятно проведен он уже или нет, к тому же если нажать кнопку Провести, то она все равно остается активной. И изделия заказа доступны к изменениям

**Comment by unpete** [comment]
Если у пользователя нет роли _Согласование заказов_, отправленные и согласованные заказы он видит _серыми_ - только для чтения.
Пользователь с ролью _Согласование заказов_ - достаточно опытный. Управление доступностью полей для такого пользователя - задача не первой очереди.
