### ISSUE TITLE
Шаблоны

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#149]
У меня такой вопрос, а должен ли простой менеджер иметь доступ к Шаблонам продукции, сейчас они находятся в разделе Заказы, а сюда имеют доступ все?
Может он должен находиться в разделе Технология? Раз решено не создавать кучу типов шаблонов? Сами шаблоны в построителе им доступны и этого наверное вполне достаточно, а то залезут посмотреть, исправят и не заметят и сохранят.

**Comment by unpete** [comment]
Если у пользователя нет роли _Технолог_, шаблоны он видит серыми - только для чтения.
