### ISSUE TITLE
Права менеджера, как у ведущего менеджера 

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#152]
Стала проверять наценки на дилерах (обычный менеджер), ранее я проверяла их на Баранова и Сень, и все было нормально, а сегодня они почему-то имеют право не только видеть вкладку Учет, но и редактировать ее - а раньше могли только видеть. Создать нового они там не могут, но по идее и менять не должны, и как по мне и видеть им это тоже не зачем - там все цены, скидки и наценки, К марж, в общем вся теория построения цен - простым сметртным не хотелось бы ее показывать. Получается у меня эксперимент чистым не получится, и я пока его отложила.

Проверяла как и ранее во вкладке инкогнито.

**Comment by unpete** [comment]
> Создать нового они там не могут, но по идее и менять не должны

Прав на запись у них нет - только просмотр.
Ограничение видимости закладок добавил - в рабочую базу перенесу сегодня после конференции.

**Comment by aribaz** [comment]
Работает
