### ISSUE TITLE
Наценки и скидки дилера

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#153]
Я по всей вероятности запуталась в наименованиях этих скидок и наценок и их сценариях применения. Прошла по ним методом изменений одной позиции и все равно не поняла, как они должны работать.
 Во-первых, по скидкам и наценкам у нас есть такие поля:

**Форма Кмарж:**
1. Наценка внешн.
2. Скидка внешн.
3. Скидка

Здесь есть два поля со скидками, и я не понимаю кто эти скидки предоставляет и кому? Завод, дилер (все вообще) или дилер (конкретный пользователь).

**Форма Контрагенты:**
1. Наценка дилера (внешняя)

Это как я понимаю наценка дилера как организации и судя по всему она первична, потому как только этот процент накидывается на сумму поставщика. 
Если в этом поле стоит 0 (ноль, а не пусто), то в табчасти строки заказа  в полях Цена дилера, Скидка дилера и Сумма дилера равны 0 все (для всех дилеров, я проверяла). Изменить значение этой наценки на "Пусто" не получается, если нажать в форме на крестик, а потом Ок появляется все равно 0.

**Вкладка Общие:**
1. Наценка дилера (значение берется из формы Кмарж)
2. Скидка дилера (всегда 0, какие-бы я цифры в предыдущих формах не применяла)

Цифры в этих  полях на этой вкладке я могу написать вручную, но это ничего не дает.

**Табчасть строки заказа:**
1. Скидка поставщика
2. Скидка дилера

Эти поля доступны мне для изменений от руки, если я посредством этих полей даю скидку поставщика, то он считает правильно сумму поставщика, а вот цену дилера считает не от суммы поставщика, а от цены поставщика. А ведь если я в этой форме предоставляю скидку поставщика, то цена дилера должна по идее считаться от суммы поставщика - ведь иначе программа игнорирует скидку поставщика для конечного клиента. Или скидку я предоставляю не конечному клиенту, а даю возможность больше заработать дилеру (типа бонуса?)?

После изменений, вносимых мной в каждое поле я перезагружала страничку, и только потом создавала строку заказа.

В Кмарж я установила значение Наценки 3%, 
Если в форме контрагента Наценка дилера (внешн.)  0, то эти 3% ни на что не влияют.
Если в форме контрагента Наценка дилера (внешн.)  <> 0, то применяется именно Наценка дилера (внешн) и не важно что и где указано в других формах.

Еще я пробовала в форме Кмарж установить значения полей Скидка внешн. и Скидка - но это никак не сказалось не только на цифрах, но и ни одна из них не попала на вкладку Общие по аналогии с Наценкой внешн. (хотя может и не должна).

Цифры во всех полях ставила разные, чтобы можно было понять что применяется.

Мне бы понять ЧТО первично, и алгоритм применения этих скидок и наценок.

Еще один нюанс, который заметила случайно.

У меня как оказалось для двух контрагентов в справочнике Договоры установлены галочки по НДС. 
Для Светлого дома - Сумма включает НДС 
Для Фабрики массив - Учитывать НДС

Если в форме этих контрагентов установить значение Наценка дилера внешн. <> 0 (я поставила 10% для обоих), то получается вот что:
**Для Светлого дома:**
Цена поставщика и Сумма поставщика  = 3086,05 (скидка поставщика 0),
Цена дилера и Сумма дилера = 3394,66 (+10% к заводу, Скидка дилера 0 )

**Для Фабрики массив:**
Цена поставщика и Сумма поставщика  = 3086,05 (скидка поставщика 0),
Цена дилера 3394,66 (+10% к заводу, Скидка дилера 0 )
Сумма дилера = 3556,8 

К какой цифре должна применяться НДС?

Вроде по идее к сумме поставщика, ведь НДС поставщик платит. Тогда 3086,05_1,18=3641, 54 - это и цена и сумма поставщика - ведь нам дилер должен именно столько отдать.
Плюс его 10%, 3641,54_1,1=4005,69.
Я наверное не поняла алгоритм расчета?

Я попробовала в табчасти строки заказа применить скидку дилера и скидку поставщика и вот какие цифры получила
Изделие без скидок и наценок стоит 3086,05, для этой пары организация -контрагент, НДС (18%) сверху  должен считаться ( в договоре галка стоит), для контрагента есть Наценка дилера (внешн.) 10%.

Вот цифры из табчасти

Цена поставщика 3086,05
Скидка поставщика 5%
Сумма поставщика 3378,9700000000003  (Как получилась эта цифра?)
Цена дилера 3224,92=(3086,05_0,95)_1,1 - дали сначала скидку поставщика, потом сделали наценку дилера.
Скидка дилера 2%
Сумма дилера 3160,42=3224,92*0,98

Мне совсем не понятно как сказывается НДС на цене поставщика (есть три варианта - сидит в цене, сверху цены и без ндс). Но по факту получается, что не важно какая схема налогоблажения применяется для организации, так как для все трех случаев цена поставщика одинакова - может я чего-то недопонимаю, но мне кажется это не совсем верно.

Один раз у меня получилось при наценке дилера (внешн.) =0 (Контрагенты) учесть Наценку внешн. =3% (из Кмарж,), но как у меня это получилось в табчасти строки заказа Цену дилера и сумму дилеру увидеть с учетом этих 3%, я не поняла, потому что потом меняла ее на 10% (в контрагенте), а когда снова поставила 0, то уже 3% не учлись и все цифры дилера  стали 0 в табчасти строки заказа.

В общем я основательно не понимаю как на практике работает сценарий наценок и скидок.

Вопрос терпит до вашего возвращения из Питера, хочу на конференции обговорить это, Желательно показать.

**Comment by aribaz** [comment]
Ошибка на вкладке Общие
Подтягивает значение Наценки из формы К марж

**Comment by unpete** [comment]
Упростил назначение дилерских наценок и скидок в браузере.
Если пересчет заказа выполняет менеджер, дилерская цена может уплыть. Мы ведь, не знаем, какую наценку указал дилер на своём компьютере.
Похоже, надо добавить в `Расчет` скрытое поле, в котором хранить эту дилерскую наценку.
В остальном, поведение системы стало более предсказуемым.

**Comment by aribaz** [comment]
Из того, что я опробовала получается так:

Значения скидок и наценок в форме Контрагента первичны только если на вкладке Общие и К марж стоят 0.

Значение Кмарж первично, если я на вкладке Общие поставила руками 0, сохранила эти изменения кнопкой Применить настройки и перезагрузить программу, но после этого вместо установленных ранее мною 0 появляются значения из К марж, которые и применяются к заказу.

Значения скидок и наценок на вкладке Общие  - они первичнее всех, если здесь ставлю руками какие-то цифры отличные от 0, именно они и применяются, после кнопки "Применить настройки и перезагрузить программу".

Как было задумано не знаю, но работает именно так. Проверяла только под своими правами.

Я думаю в целом этого достаточно, чтобы и дать возможность дилерам жить самостоятельно (в плане установок цен) и нам получать то, что хотим от них. 
Я только не совсем поняла про дилерскую цену, которая может уплыть. Здесь речь о том, что когда менеджер старший проверяет заказ (тогда ведь применяются те цифры, которые стоят у него на вкладке Общие)?

**Comment by aribaz** [comment]
Проверяла из под Сень.
Для контрагента Сень внутри формы Контрагента Наценка дилера (внешняя) равна 0, и поэтому в учетной записи сень при создании заказа сумма дилера равна 0.
Кнопка "Применить настройки и перезагрузить программу"  не срабатывает у Сень, такое ощущение что ошибка исправилась только в моей учетке, потому что здесь все осталось по-прежнему, с теми ошибками, которые раньше были у меня. Как было при входе 50 и 5,  так и остается, вне зависимости от того, что я там ставлю.
[Заказ](https://light.oknosoft.ru/#obj=cat.characteristics&ref=2ee24574-7268-419e-8f47-26d3f44baecd&frm=builder&view=orders)

**Comment by aribaz** [comment]
Еще вот что не совсем понимаю.
Основная схема работы у нас - это дилеры, в нашем случае они все имеют права менеджера и следовательно могут использовать для указания своих наценок и скидок только вкладку Общие. 
Сейчас так  работает расчет, что если на вкладке Общие наценки и/или скидки отличны от 0, то именно они первичны и все остальные скидки и наценки не применяются.
У нас как у производителя есть Кмарж, которым мы учитываем наши накладные расходы, зарплату, транспорт, а так же прибыль. С помощью К марж мы получаем Цпост. Если мы хотим дилерам давать какие-то скидки (а такая возможность есть с точки зрения программы), то мы заранее должны установить такой коэффициент маржи, чтобы после этой скидки не опуститься ниже себестоимости плановой.
Я вот о чем думаю. 
Можно ли сделать так, чтобы полем Кмарж была возможность определять только минимальную плановую себестоимость изделий? 
Ведь в основном производственники могут более менее точно сказать сколько денег надо на материалы и зарплату, а распределить накладные расходы, транспорт, зарплату итр, амортизацию очень тяжело, плюс надо как-то предусмотреть прибыль от выпуска продукции. У нас уже сейчас есть стоиомость материалов (и если подцепим работы, то будет и зарплата). Как правило все производственники учитывают все доп расходы, связанные с производством в процентах от материалов+работу, а потом по идее на сумму материалов, работ и производственных расходов накручивается прибыль планируемая.
Вот сумма материалов, работ и производственных расходов - это как раз минимальная плановая себестоимость продукции. 
Планируемая прибыль - величина изменяемая от степени жадности производителя и возможности покупателя.
Я предлагаю полем К марж учитывать минимальную плановую себестоимость. И ввести дополнительно поле Плановая прибыль, и уже от произведения этих величин давать скидку. Скидки ведь не должны давать возможность производить себе в убыток, ну или как минимум человек должен идти на это осознанно (в тяжелые времена приходится поступать и так, чтобы предприятие не закрыть вообще).
Если цена поставщика будет складываться из условных прямых затрат (Плановая себестоимость * Кмарж*Кплан.приб), то давая скидку дилеру мы всегда точно понимаем на сколько изменится наша плановая прибыль, именно прибыль.
Сегодня в К марж сидят и производственные расходы и работа и прибыль и все это выраженно одним числом, тяжело в таком случае давать осознанную скидку.
Можно ли так?

**Comment by aribaz** [comment]
Еще я вот о чем подумала.

У нас есть колонки с ценами поставщика и дилера внутри заказа, которые мы можем скрыть/показать. А в разделе Заказы видна только колонка с суммами поставщика. Мне кажется дилеру было бы удобнее там видеть не только то, что он должен нам отдать, но и ту цифру, которую он должен взять у клиента. Может добавить колонку с суммой дилера в список заказов с возможностью скрыть ту или другую?
Не знаю права ли я, но мне кажется это было бы удобно, хотя можем подождать мнения самих дилеров.

**Comment by aribaz** [comment]
Как можно учесть скидку поставщика?

Цена дилера всегда считается от суммы поставщика, которая в свою очередь считается как разность цены поставщика и скидки поставщика. Поле скидка поставщика в строке заказа доступно только с правами старшего менеджера и оно всегда равно 0. Хотя скидка дилера в строке заказа заполняется значением из поля Скидка дилера на вкладке Общие, но можно и руками потом изменить на другое значение.
Теоретически можно или уменьшить наценку дилера или увеличить скидку дилера, но тогда изменится только конечная цена для покупателя, а сумма поставщика никак не изменится, которую нам будет должен отдать дилер с этого заказа. Ведь скидка поставщика сказывается на той сумме, которую нам должен отдать дилер с заказа.
А сейчас скидку поставщика можно учесть только с правами старшего менеджера и применять ее придется вручную к каждой строке заказа.

**Comment by unpete** [comment]
> Поле скидка поставщика в строке заказа доступно только с правами старшего менеджера и оно всегда равно 0

Не _нулю_, а тому значению, которое _указано в маржинальных коэффициентах_. см. [Ценообразование](/oknosoft/windowbuilder/wiki/Ценообразование)
Строка маржинальных коэффициентов рассчитывается для каждой строки продукции.
Вы можете задать не только индивидуальные скидки для каждого дилера, но и назначить эти скидки разными для разных номенклатур.
Оформлять эти скидки можно как явно - в поле _Скидка_, так и скрыто - через разные _КМарж_ для разных дилеров и групп продукции

**Comment by unpete** [comment]
Несколькими постами выше, задан вопрос _Можно ли так?_
Ответ: да, можно и это не требует моего участия.
Движки формирования спецификаций и ценообразования достаточно гибки и абстрактны - никто не посмеет запретить вам включить в спецификацию плановые постоянные затраты

**Comment by aribaz** [comment]
Заработало.
Я проверяла ране, у меня был именно 0, несмотря на цифры в Кмарж отличные от нуля, потому и писала.
Спасибо, закрываю.
