### ISSUE TITLE
Кнопки загрузки/выгрузки данных на Общие

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#154]
У нас есть три кнопки на вкладке Общие:
1. Применить настройки и перезагрузить программу
2. Стереть справочники и перезаполнить данными сервера
3. Выгрузить изменения справочников на сервер

Хочу понять для чего какие кнопки использовать, а то мне кажется я что-то не так понимаю.
Это тоже в общем ждет до вашего  возвращения.

**Comment by unpete** [comment]
- Применить настройки и перезагрузить программу - если меняли дилерские наценки-скидки или настройку колонок
- Стереть справочники и перезаполнить - если меняли `Зону` или испортилась база на компьютере пользователя из-за ошибки диска
- Выгрузить изменения на сервер - для обычных пользователей эта кнопка недоступна - позволяет закинуть на сервер изменения в справочниках пользователей, контрагентов, организаций и т.д., если эти изменения делались со стороны браузера

**Comment by aribaz** [comment]
Спасибо, работает.

**Comment by aribaz** [comment]
Закрываю
