### ISSUE TITLE
Названия параметров продукции

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#155]
Можно ли переименовать названия параметров продукции (системы профилей)?

Я бы хотела три типа названий, к тому же очень обобщенных и сокращенных:
- [ ] **Дер.  ОБ:**
1. Дер. окно глухарь со створкой
2. Дер. окно глухое
3. Дер. окно со створк.
4. Дер. окно трехстворчатое
5. Дер. окно штульповое
6. Дер. оконный блок (его я создала копированием Дер. окно трехстворчатое, добавила его в шаблон и оставила от него только коробку, назвала в комментарии Свободное проектирование, чтобы не приходилось каждый раз удалять створки и пр.)
- [ ] **Дер. ББ:**
1. Дер. дверь балконная
- [ ] **Дер. ДБ:**
1. Дер. двери откр. внутрь 113
2. Дер. двери откр. внутрь 120
3. Дер. двери откр. наружу 113
4. Дер. двери откр. наружу 120

1С-ка даст для нескольких строчек применить одно название, не удалять наборы а переименовать их согласно группе использования?

Нам бы этих трех наименований хватило чтобы сориентироваться по названию что это - окно, балконная дверь/блок или входная дверь, а детали видны на эскизе. Это основная схема и для строителей.
Плюс это позволит сэкономить место в табчасти заказа и видеть минимально необходимую информацию по изделиям,  а то названия очень длинные?
Ведь все изделия отличные от шаблона (все что нарисовано с нуля) будет называться Дер. оконный блок - о том что это за блок можно будет понять открыв его или взглянув на эскизы, а таких окон будет много, и этого нам достаточно.
Ведь у нас уже три разных типа окна имеют название в табчасти Дер. окно трехстворчатое - хотя именно створок там по факту и 2, и 3 и 4 - и это не проясняет никак ситуацию без эскиза, а наоборот, к тому же места в табличке занимает название много.

**Comment by Oparin-Igor** [comment]
В справочнике !параметры продукции" для каждого набора своя уникальная продукция (номенклатура).
Я понял правильно?
Убрать продукцию.
1.Дер. окно глухарь со створкой
2.Дер. окно глухое
3.Дер. окно со створк.
4.Дер. окно трехстворчатое
5 Дер. окно штульповое
Вместо нее будет одна"Дер. ОБ": с большим набором профилей.

**Comment by aribaz** [comment]
Это было бы здорово, если это не влечет за собой каких-то больших трудностей и временных затрат.
При этом шаблоны которые есть сегодня должны остаться.

Если это долго очень  и трудоемко, то можно и оставить.

**Comment by nmivan** [comment]
@aribaz , задача не решилась?

**Comment by aribaz** [comment]
@nmivan закрыли вопрос
