### ISSUE TITLE
Блокада ручки

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#156]
Игорь, у меня некоторый вопрос назрел.
Как я понимаю параметр Блокада ручки это устройство на ручке, позволяющее заблокировать окно, применяется как правило для защиты детей от выпадения из окон.
Сейчас это параметр виден только для фурнитуры Масо поворотно-откидная, хотя он должен применяться к любому изделию (окно, дверь), в котором есть именно ручка, а не гарнитур.

Но при этом у нас есть ручка Гармония с ключом в списке ручек, так вот Гармония с ключом это и есть ручка Гармония с блокировкой окна ключом.
Как я выяснила блокировка (блокада) может быть только на ручках, на гарнитурах ее быть не может - не производят такие.

В нашем случае в роли блокировки может выступать:
- ключ
- кнопка
- фиксация окна в положении 45градусов

У нас есть три типа ручки (гармония, Рапсодия и Симфония), каждая из которых может иметь один из трех видов блокировки в разных цветах (цвета которые привозят вообще в Россию сейчас уточняю).
Как нам поступить с этой блокировкой?
Убрать параметр Блокада и добавить тип ручки с блокировкой? Или убрать из списка тип ручки Гармония с ключом, а для параметра "Блокада ручки" вместо ДА сделать три параметра (ключ, кнопка, 45гр) и связать параметры "тип ручки-блокада-цвет" с конкретным артикулом?

Это я сейчас описываю параметры для балконных дверей и выплыл вопрос о блокаде.

**Comment by Oparin-Igor** [comment]
Блокада и ручка с с блокировкой это разные механизмы и у них разные функции.
Блокировка (блокада) служит для предотвращения выпадения верхней петли при смене режима открывания с поворотно-откидного в поворотное.
Фиксация ручки для того чтобы ребенок не смог поменя ть режим открывания, например с пов-откидного в поворотное или открыть створку.
поэтому  ключ или кнопка должна быть в наименовании ручки.

**Comment by aribaz** [comment]
Тогда я запуталась.
С тем для чего предназначена блокада я разобралась и чем это отличается от всяких устройств на ручках, позволяющих защитить детей тоже, пусть ручки с защитой будут в наименовании.

А что тогда такое микролифт?
У нас есть такое понятие как блокиратор откидывания или по-другому приподниматель (он препятствует ошибочному открыванию), я предположила, что это и есть микролифт (от слова приподниматель), а получается что наш приподниматель это и есть блокада, тогда я не знаю что микролифтом у вас называется.
Или я не верно вас поняла?

**Comment by Oparin-Igor** [comment]
Микролиф - это устройство в ножницах (у других производителей в угл.переключателе), позволяющее при повороте ручки на 45 гр., откинуть створку в режим микропроветривания.

**Comment by aribaz** [comment]
А как тогда параметр Микропроветривание? 
У нас есть в том числе вариант "на ножницах" - он не включает в себя этот микролифт?
Или даже при микропроветривании "на ножницах" - микролифта может и не быть?

**Comment by Oparin-Igor** [comment]
При выборе варианта "на ножницах" устанавливаются ножницы с микролифтом.
Или правильнее,  при выборе параметра "микролифт" -ДА.

**Comment by aribaz** [comment]
Я правильно поняла, что  Микролифт: ДА и Микропроветривание: НА НОЖНИЦАХ - это одно и тоже ? Точнее даже без микролифта нельзя сделать Микропроветривание НА НОЖНИЦАХ.
Если да, тогда получается не совсем верно. параметр Микролифт и Микропроветривание - доступны нам для выбора в поворотно-откидной створке, получается неопытный менеджер может выбрать Микролифт: Нет, а Микропроветривание: На ножницах; а это конфликт определений параметров.
Я права?
Может один из вариантов лишний (Микролифт или На ножницах)? Ведь одно без другого быть не может, а для варианта Микропроветривания: "ступенчатое" и "нет"- микролифт не нужен совсем. Может параметр Микролифт скрыть/удалить от пользователя, а сервису объяснить когда его надо применять его, а когда нет - если такое возможно. 
Что-то типа если Микропроветривание=на ножницах, тогда Микролифт=да; Иначе: Микролифт=нет.

**Comment by Oparin-Igor** [comment]
Микролифт- это опции фурнитуры МАСО.
Этот параметр нельзя использовать во всех вариантах фурнитуры.
Поэтому он вынесен отдельно.
