### ISSUE TITLE
Балконная дверь двупольная (штульп)

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#157]
Игорь, прикладываю рисунок балконной двупольной двери это гибрид штульпового окна и балконной двери.
Фурнитура может быть и как для окна и как основная у балконных дверей, основным способом запирания штульповой створки являются так же штульповые запоры, реже шпингалеты (как и у окон),  вместо ручек могут использоваться гарнитуры (простые и раздельные).
Так же как и обычные балконные двери створка может делиться горбыльком, снизу может быть филенка.
[Балконная дверь штульп.pdf](https://github.com/oknosoft/windowbuilder/files/564104/default.pdf)

**Comment by nmivan** [comment]
@aribaz , задача актуальна?

**Comment by aribaz** [comment]
@nmivan решила
