### ISSUE TITLE
Дверь н/о 113

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#158]
Профили для этой двери, которые я вам ранее не присылала
[Доп профиль (но 113).pdf](https://github.com/oknosoft/windowbuilder/files/564177/113.pdf)

сама дверь н/о двупольная (штульп) 113
[дверь наржнего открывания штульп.pdf](https://github.com/oknosoft/windowbuilder/files/564179/default.pdf)

Если из нее убрать средние вертикальные профили створок, то получится однопольная дверь наружнего открывания 113  #131 

Параметры к этой двери описаны в вопросе #127

**Comment by Oparin-Igor** [comment]
Закрыть

**Comment by aribaz** [comment]
Что закрыть? Задачу?

**Comment by Oparin-Igor** [comment]
да. сделано.

**Comment by aribaz** [comment]
спасибо
