### ISSUE TITLE
Сумма заказа (неправильное округление до копейки)

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#159]
Ошибка в сумме заказа при округлении

[Заказ](https://light.oknosoft.ru/#obj=doc.calc_order&ref=c198fd5f-e3ba-452b-f66d-f8fe90f6f745&frm=doc&view=orders)   3378,97000000000003руб

**Comment by aribaz** [comment]
В этом заказе работает.
Я пока не буду закрывать задачу, а в нее буду подобного рода заказы скидывать.
Хорошо?

**Comment by aribaz** [comment]
[Заказ 2](https://light.oknosoft.ru/#obj=doc.calc_order&ref=f56415b2-1693-4438-ad2a-2949d501ae30&frm=doc&view=orders)

**Comment by aribaz** [comment]
Заказ 3[https://light.oknosoft.ru/#obj=doc.calc_order&ref=e9e2218a-9a60-44c8-8ede-a907bd007bb5&frm=doc&view=orders](url)

**Comment by aribaz** [comment]
[Заказ 4](https://light.oknosoft.ru/#obj=doc.calc_order&ref=e9e2218a-9a60-44c8-8ede-a907bd007bb5&frm=doc&view=orders)

**Comment by aribaz** [comment]
[Заказ 5](https://light.oknosoft.ru/#obj=doc.calc_order&ref=f56415b2-1693-4438-ad2a-2949d501ae30&frm=doc&view=orders)

**Comment by aribaz** [comment]
[Заказ 6](https://light.oknosoft.ru/#obj=doc.calc_order&ref=19c05cfa-4d67-4e71-e864-b99969e879e2&frm=doc&view=orders)

**Comment by aribaz** [comment]
[Заказ 7](https://light.oknosoft.ru/#obj=doc.calc_order&ref=ebf0c292-b2d6-4dae-d3b7-bc14f25091f0&frm=doc&view=orders)

**Comment by aribaz** [comment]
[Заказ 8](https://light.oknosoft.ru/#obj=doc.calc_order&ref=45ca40c1-9fcf-4dc8-ed7e-e41477b4f07b&frm=doc&view=orders)

**Comment by aribaz** [comment]
[Заказ 9](https://light.oknosoft.ru/#obj=doc.calc_order&ref=d163c5bc-fe2d-4b01-a3c0-29fe1a0469bc&frm=doc&view=orders)

**Comment by aribaz** [comment]
Вроде все, просмотрела Черновики, Отправлено и Согласовано

**Comment by unpete** [comment]
Проблем не вижу. Старые заказы, естественно, не пересчитаны.
