### ISSUE TITLE
Копирование данных из табличных частей

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#161]
У меня назрело предложение по поводу инструмента выделения фрагмента копирования.
Если я хочу скопировать одну строчку или несколько, то у меня копируется вообще все 
[Пример копирования.docx](https://github.com/oknosoft/windowbuilder/files/580797/default.docx)
Можно ли сделать копирование выделенных фрагментов?
Выделить сегодня можно только одну строку. Но копируется все равно все .
Если мне надо скопировать несколько строк, было бы здорово сделать это  указав их мышью/стрелками на клавиатуре с зажатым ALT (например).
Но это пожелания сервису на будщее

**Comment by nmivan** [comment]
@aribaz , правильно понял, что хотите копировать для того, чтобы вставить в ворд или другое внешнее  приложение?

**Comment by aribaz** [comment]
@nmivan Надобность в этом с течением времени отпала. Но предполагалось  в ворд/эксель
