### ISSUE TITLE
Выделение на эскизе элементов изделия

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#162]
У меня вот какой вопрос созрел.
Сейчас при редактировании изделий заметила одно несоответствие.
Например, я редактирую дверь (но это применимо к любому изделию).
Хочу изменить верхний профиль створки. Курсором мыши нажимаю на эскизе на необходимый элемент, но выделенным становится не верхний элемент створки, а верхний элемент контура, хотя табчасть заказа указывает на то, что все же выделен элемент створки (исходя из названия элемента). Это вводит в заблуждение.

А если я хочу заменить верхний профиль коробки, то я  должна попасть мышкой в верхнюю линию габарита коробки (хотя профиль там виден хорошо и есть возможность попасть мышкой именно в профиль коробки), а визуально он у меня уже выделен на эскизе (хотя по факту это я створку выделяла). 
Можно ли сделать так, что если в табчасти отображен створочный профиль, то и на эскизе чтобы именно створочный профиль был выделен, о котором нам говорит табчасть, а не рамный.
А то путаюсь, приходится себя проверять и вспоминать "а что же я хотела менять раму или створку".

А вот с горбыльками и доборным профилем - все как надо, что мышкой показала, то выделилось и в табчасти отобразилось. Хотя размеры (отображение на эскизе) доборных профилей в створке простреливают до габаритов рамы почему-то.

**Comment by unpete** [comment]
> Хочу изменить верхний профиль створки

У элементов типа [Profile](https://github.com/oknosoft/windowbuilder/blob/master/src/geometry/profile.js) есть образующая (generatrix). Для вложенных контуров эта образующая совпадает с образующей внешнего элемента. Сейчас визуально выделяется именно образующая, т.к. двигать и гнуть можно только её, а не профиль, геометрия которого рассчитывается автоматически с учетом ширин и зазоров в соединениях.

> если я хочу заменить верхний профиль коробки

Можно погасить слой створки в дереве - тогда попадать будет проще

> сделать так, что если в табчасти отображен створочный профиль

Если кроме образующей (с которой всё правильно), выделять еще и тело профиля, проблем будет меньше

> с горбыльками и доборным профилем - все как надо

Все профили рисуются одинаково - и рамы, и створки, и сегменты раскладок. Трудность восприятия есть только для вложенных элементов
