### ISSUE TITLE
Обсада

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#163]
Она имеет место только для деревянных домов. Изготавливается из доски толщиной 50мм (в изделии), две стойки, на которых лежит поперечина, устанавливается буквой П, и защищает окно от нагрузок. Она обязательна. Но обсада может быть установлена заказчиком на этапе строительства силами подрядчика (черновая), а можем ее и мы и изготовить и поставить. Изготавливается всегда из доски, устанавливается по внешнему контуру окна, за исключением низа.

Хочу, чтобы при выборе параметра  Обсада "Да", программа сама посчитала ее стоимость, габариты и добавила ее в расчет-заказ отдельной строкой, но чтобы можно было понять какой комплект к какому окну относится.

Для расчета стоимости необходимы кв.м, для учета в заказе единица измерения - комплект (3 доски).

**Comment by unpete** [comment]
Это вставка в изделие. Задачи:

- [x] Добавить вставку
- [ ] Определиться с параметрами (ширина?)
- [ ] Алгоритм расчета габаритов
- [ ] Настроить спецификацию

**Comment by aribaz** [comment]
Посмотрите пожалуйста вопрос #168, там в целом вся информация по допам и параметрам (ширина), и некоторую информацию по расчету геометрии я ранее уже высылала Игорю.

**Comment by aribaz** [comment]
Сначала обсада прикручивается к блоку и только потом все это устанавливают в проем.
Есть два варианта установки обсады:

- Заподлицо с плоскостью стены
- с углублением в четверть 50мм (здесь появляется доп. брусок  35х50, устан-ся П-образно с внешней стороны блока и тоже он сначала прикручивается к обсаде).

Ширина обсады равна ширине проема.
Подоконник в этом случае делаем шире на толщину блока и заводим его под блок до паза под отлив, если он есть (а он как правило есть)- предварительно выбрав в нем четверть 10хtпрофиля рамы низ.
Стойки обсады длиньше чем высота блока на 24мм (толщина подоконника с учетом выбранной четверти)
Длина верхней палки равна=Вбл+50*2, где 50 - это толщина обсады.
Стойки обсады
Когда ставим обсаду, то как правило не ставим доборы, но если заказчику очень хочется то сделаем - но на моей памяти не было такого.
Обсада требует обналички (и внутренней, и внешней), размеры внешней зависят от способа установки обсады.

**Comment by aribaz** [comment]
[примыкание  в деревянном доме (обсада, обналичка).pdf](https://github.com/oknosoft/windowbuilder/files/610783/default.pdf)

**Comment by unpete** [comment]
Параметры:
- Ширина
- Вариант (перечисление №1, №2)

**Comment by Oparin-Igor** [comment]
Вставка 
Окосячка дер.
Обсада дер.

**Comment by unpete** [comment]
Если задать цены на наличники, плановая себестоимость и продажная цена - рассчитывается.
Похоже, ценообразование для доп. вставок работает

**Comment by aribaz** [comment]
Чем отличается Обсада от Обсада дер.?
У нас обсада только одна (в двух вариантах) и в сервисе она реализована как Обсада дер.
Прошу к обсаде добавить параметр: "Тип" (чистовая или черновая) - влиять будет на цену, чистовая с обработкой, черновая - без обработки.
Этого параметра не было раньше.

Обсада  - это наверное доборы?

**Comment by aribaz** [comment]
Прошу к обсаде добавить параметры:

 **"Тип"** - влиять будет на цену, чистовая с обработкой, черновая - без обработки. 
чистовая
черновая 

**Материал**
сосна
лиственница
дуб

**Comment by Oparin-Igor** [comment]
Есть параметр Материал дер.:
сосна
сосна сращенная
лиственница
лиственница сращенная
дуб
дуб сращенный
Он не подходит?
Или добавить новый параметр?
Материал
сосна
лиственница
дуб


"Тип" - название должно к чему-то относиться. Может "Вариант обработки"
чистовая
черновая

**Comment by aribaz** [comment]
Параметр Материал дер. я не вижу в параметрах обсады, поэтому и написала. 

Так как обсаду делают из доски, то она всегда цельноламельная, потому как она и есть цельная ламель, а из сращенных по длине (и уж тем более ширине) ламелей обсаду не делаем, поэтому три варианта древесины. 
Можно конечно в и оставить сращенные, как задел на будущее, просто я на простую и сращенную поставлю одну и ту же цену, но этот параметр я не вижу совсем.

Вариант обработки - меня вполне устраивает, давайте на нем и остановимся.

**Comment by Oparin-Igor** [comment]
https://light.oknosoft.ru/#obj=doc.calc_order&ref=fc92a273-728c-4eb6-fcf4-1e2bac95717f&frm=doc&view=orders

В изделии выбираю вставку в изделие "Монтаж дер." изделие не сохраняется.
Выбираю вставку  "Обсада дер.", при закрытии конструктора добавлена строка "Монтаж дер."
В изделии выбираю вставку в изделие "Обсада дер.", при закрытии конструктора добавлена строка "Монтаж дер."

**Comment by aribaz** [comment]
Варианты обработки:
черновая - без покраски; 
чистовая  - с покраской + дополнительные операции по обработке древесины

**Comment by Oparin-Igor** [comment]
Вставка 
"Обсада чистовая дер."
"Обсада черновая дер."

**Comment by aribaz** [comment]
@Oparin-Igor 
Нашла ошибку по количеству боковых наличников Окосячка снаружи.

У нас три варианта боковых наличников:
Стандарт
Тип2
Заказной

Если выбрать Стандарт или Тип 2, то в спецификацию попадает  или Наличник 110 - 1 шт или Наличник 100-1шт, соответственно (вместо двух палок того или иного типа) .

А вот если выбрать Заказной для боковых, то в спецификацию с ним попадет:
Наличник 100 -1шт
Наличник 110-1шт
Наличник заказной - 2шт.
Итого 4 боковых наличника, вместо 2

Окосячка изнутри правильно рассчитывает спецификацию.

**Comment by aribaz** [comment]
Вроде все работает, пока закрываю.
Спасибо.

**Comment by aribaz** [comment]
Нашла ошибку
При выборе варианта №2 (чистовая), в спецификации самой обсады отражается количество только полировки и грунтовки, а остальные материалы с 0 количеством.
![2017-01-11_09-59-01](https://cloud.githubusercontent.com/assets/22028048/21838712/a548773c-d7e4-11e6-94c8-8c3fac042879.png)
а при выборе варианта обсады №1 (черновая) все нормально.
![2017-01-11_10-01-03](https://cloud.githubusercontent.com/assets/22028048/21838777/1b2af858-d7e5-11e6-9acd-d7fd6c947155.png)

Но почему-то в списке изделий заказа к черновой не подцепляется толщина,
![2017-01-11_10-03-35](https://cloud.githubusercontent.com/assets/22028048/21838858/9077e936-d7e5-11e6-8c74-24d1b9db3486.png)
 хотя при открытии спецификации этих строк, толщина в названии присутствует.

И я вот еще что подумала, мы нигде не указываем ширину этой обсады, я ранее писала что она равна ширине проема, но от размеров проемов мы ушли, а про ширину обсады я что-то забыла.
Расчет обсады производится за кв.м. с учетом толщины (у нас стандартно 50мм).
Да и для производства как-то надо сказать какой ширины должна быть палка.

**Comment by nmivan** [comment]
@aribaz , задача актуальна?

**Comment by aribaz** [comment]
@nmivan уже все настроено
