### ISSUE TITLE
Доборы (внутренние и внешние)

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#164]
Это планки, которые закрывают откосы изнутри помещения. Имеют толщину в готовом изделии 18мм. Могут быть выполнены или из щита (покупной или самодельный, чаще покупной) или из МДФ16мм+шпон. Шпон сосна, лиственница и дуб. Устанавливаются буквой П. Для изделия измеряются в штуках, с длиной и шириной, хотя можно и комплектами считать, а для расчета цены нужны кв.м.

Хочу чтобы, программа смогла сама посчитать  габариты этих элементов и их стоимость, а затем внесла их в строку заказа.

**Comment by unpete** [comment]
Это вставка в изделие. Задачи:

- [ ] Добавить вставку
- [ ] Определиться с параметрами доборов
- [ ] Алгоритм расчета габаритов
- [ ] Настроить спецификацию

**Comment by aribaz** [comment]
Параметры доборов см. вопрос #168, таблица Параметры изделий.
МДФ и Щит, считаются в кв.м.
Спецификация за мной.

**Comment by aribaz** [comment]
Доборы могут быть снаружи и изнутри (на выбор).
Это три плашки, которые закрывают откосы они могут быть в доме любой конструкции (дерево, железобетон, кирпич). Это что-то типа обсады, только тоньше и не несут на себе нагрузку - используются только как элемент отделки.

Толщина всегда 17мм (это 2 слоя шпона и МДФ16мм между ними).

Выполняем из:
МДФ16мм+шпон/сосна
МДФ16мм+шпон/лиственница
МДФ16мм+шпон/дуб.

Так как длины/ширины вносим руками, то должны появиться параметры для каждой из сторон:
Длина добора верх
Длина добора бок
Ширина добора  - она для одной стороны (снаружи или изнутри) одинакова для всех трех палок.

Доборы красим с двух сторон так же как и сами изделия (количество сущностей такое же как для изделий), расход ЛКМ на 1кв.м.

**Comment by aribaz** [comment]
От полей Длина отказались, длину считаем равной габаритам блока.

**Comment by aribaz** [comment]
С доборами и наружними и внутренними в спецификацию попадают плашки, но без размеров и количества
![2017-01-11_09-29-49](https://cloud.githubusercontent.com/assets/22028048/21838001/9ab912bc-d7e0-11e6-929d-fa09cd791655.png)

К ним (к обоим) по идее еще надо подцепить тип материала (сосна, лиственница, дуб)

**Comment by nmivan** [comment]
@aribaz , здесь как дела?

**Comment by aribaz** [comment]
@nmivan Эту закрываю, перекочевала в #316
