### ISSUE TITLE
Внутренняя и внешняя обналичка (окосячка)

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#165]
Правильнее это называть обналичкой оконного проема (наличник  и карниз по периметру проема, устанавливаемые на плоскость стены), но на фабрике закрепилось название Окосячка.  

Окосячка может быть внутренняя и/или внешняя т.е устанавливается со стороны помещения и/или снаружи.

Сама по себе не присутствует в заказе.

Но если есть доборы, то может быть и окосячка изнутри помещения, а может и не быть (это желание клиента), но если доборов в заказе нет, то окосячки не будет. Тип конструкций дома (дерево, ж/б, кирпич) никак не влияет на наличие внутренней окосячки.

Это же касается и внешней стороны: если есть обсада чистовая, то может быть и окосячка снаружи, но не обязательно (желание клиента). Окосячка снаружи как правило ставится только на деревянных домах, хотя чисто теоретически ее можно и на железобетонные конструкции установить (но в моей практике такого не было).

Она выполняется из доски (сосна, лиственница или дуб), как и само окно. Затем красится по технологии окна, цвет соответствует цвету окна: для внутренней - цвет окна из помещения, для наружней (цвет окна с улицы)

**Comment by unpete** [comment]
Это вставка в изделие. Задачи:

- [ ] Добавить вставку
- [ ] Интерфейс редактирования вставок в изделие
- [ ] Определиться с параметрами окосячки - пока добавил два параметра (изнутри: булево, снаружи: булево). Возможно, потребуется добавить параметры ширина и глубина: число

**Comment by aribaz** [comment]
см. #168 там описаны параметры.

Обналичка в одной (любой) плоскости состоит из двух вертикальных палок и двух горизонтальных планок. Сейчас у нас как правило планки эти шириной 100мм, в целом набор этих планок образуют комплект.
Я предполагаю, что наши могут по желанию клиента сделать ширину обналички не 100мм, а к примеру 80 или 120 (или как угодно), при том, само сечение каждой планки не сильно изменится (калевки и пр. элементы украшения), кроме того что станет шире или уже. - можно ввести параметр ширина и толщина планок (что-то типа набор ширин/толщин) - об этом я не писала в таблице, так как этого сейчас нет.

**Comment by aribaz** [comment]
Позвонила менеджеру, на всякий случай, и начальнику производства.

Верх окосячки может отличаться от бока (карнизная планка) а также при одной ширине тип сечения профиля (любого) может отличаться, поэтому добавила некоторые параметры, с возможными значениями. По идее используется 1-2, но я на каждый вариант предположила 3 строки.
Может третью строку зарезервировать на вариант полного эксклюзива? По типу с заказным стеклопакетом? 
То есть ширина может устанавливаться руками (и участвовать в расчетах), название профиля Заказная  - на него цена за 1м.пог. планки (верх, бок, низ) должна устанавливаться руками. 

Еще как оказалось боковые планки могут иметь вылет (а могут и не иметь, тогда см. левую половину - без вылета) и по нижнему краю могут быть не только прямыми, но и фигурными.
Вылет влияет на цену, так как это сказывается на длине палки, а окончание на цену не сильно влияет (этим можно пренебречь при расчете, кроме пункта Заказное - тогда надо поставить цену, можно 0), но надо как-то сказать цеху о том, каким окончание должно быть (тут вплоть до эскиза от дизайнера - файлик может приложить или комментарий где искать данные о самой фигуре?). Про низ боковушек не знаю даже, вроде как нужен параметр - а иначе сделают не правильно, но на ценообразование не влияет, тогда как все остальные параметры- влияют на цену.
![default](https://cloud.githubusercontent.com/assets/22028048/20516972/f307a41e-b0a9-11e6-9357-45225a61c6a7.png)


![image](https://cloud.githubusercontent.com/assets/22028048/20516998/19ab3d2e-b0aa-11e6-83ea-b32e9b016d42.png)

**Comment by Oparin-Igor** [comment]
Чем отличается фигурное и заказное?
Когда есть параметры "Фигурное", то всегда остается проблема, какая фигура?.
Знает только заказчик и менеджер и листок.
Конечный производитель всегда либо уточняет либо звонит по каждой позиции.
Проще перечислить несколько известных значений (фигур не так уж и много) и этой проблемы никогда не будет.
Заказное предлагаю заменить (по шаблону) всегда понятно что должен прилагаться рисунок.

**Comment by aribaz** [comment]
Про "по шаблону" я не подумала - согласна.

По фигурам это как правило Прямое, Скос 45, Треугольник.
![default](https://cloud.githubusercontent.com/assets/22028048/20591353/2ee0e280-b239-11e6-90a6-7da15f263c13.png)

**Comment by unpete** [comment]
Зарегистрировать параметры в 1С, удалить `вылет` + дополнительно
- Длина верх
- Длина низ
- Длина бок

**Comment by unpete** [comment]
Если позиции Наличник 35-80-100-110 и т.д. продается в магазине, у меня нет претензий к спецификации.
Если наличник делают в цехе, правильнее было бы завести единственную номенклатуру и указывать (или вычислять) для неё два размера - как для стекла или сэндвичей

**Comment by aribaz** [comment]
Наличники делаем сами всегда

**Comment by aribaz** [comment]
Для внутренней окосячки не видны параметры совсем.
Для внешней доступны

Поля "Размер" - это длина палок как я поняла, они доступны.

У окосячки ведь есть еще и ширина, как ее задать?

К параметру Окончание прошу добавить вариант: По шаблону

Цвет окосячки пока пуст, я не знаю как проверить сам он подцеплется где-то и учитывается, или его руками надо указать обязательно. Поля с цветом пустые. 
Внутренняя окосячка должна наследовать цвет изделия изнутри, внешняя - цвет изделия снаружи.

**Нет параметров** 

1. материал изготовления окосячки 

- сосна;
- лиственница;
- дуб;
- МДФ/шпон (сосна/лиственница/дуб) - только для внутренней.

Расчет спецификации проверить не могу, так как она пока пуста, как собственно и цены.

В табчасти заказа было бы здорово видеть какая именно обналичка (внутренняя или внешняя), а то может я две одинаковых посчитала, а чтобы проверить надо внутрь залезть.

Появилось предложение по Номенклатуре самих изделий.
У нас в табчасти заказа обналичка называется обналичкой, а само изделие - типом сростки пиломатериала, может добавим в начале "Изделие: тип_сростки"?

**Comment by unpete** [comment]
> Расчет спецификации проверить не могу, так как она пока пуста

Неплохо бы ссылку на изделие, для которого спецификация "пуста"
Например, в [НЗАК1/03](https://light.oknosoft.ru/#obj=doc.calc_order&ref=cfa3c535-bd8c-4257-9c7f-18c3c5d65fec&frm=doc&view=orders) спецификация заполнена
И на проблемную вставку. Например, спецификация во вставке "Окосячка изнутри", код 000001376 - заполнена.

> как собственно и цены

Установка плановой себестоимости на используемые материалы - Ваша прерогатива

> предложение по Номенклатуре

В ближайшие дни сделаю для Арибаз отдельную базу Заказа дилера. Появится возможность как угодно изменять любые справочники без согласования со мной.

**Comment by aribaz** [comment]
И для внутренней и для внешней окосячки не хватает параметров:

**Материал:**
сосна;
лиственница;
дуб;
МДФ/Шпон Сосна (только для внутренней)
МДФ/Шпон Дуб (только для внутренней)
МДФ/Шпон Лиственница (только для внутренней)

**Ширина верх
Ширина бок
Ширина низ**

Ширины пользователь вводит сам.

Боковых палок должно быть две штуки в спецификации для каждого вида окосячки (внешняя и внутренняя).

**Comment by Oparin-Igor** [comment]
Материал:
здесь еще один параметр напрашивается.
 Тип материала:
- дерево
- шпон

Ширина верх
Ширина бок
Ширина низ
Все размеры были указаны в таблице, их не достаточно?

**Comment by aribaz** [comment]
По материалам у нас тогда получится две основные группы, одна из которых содержит три вида древесины, другая указывает на тип применяемого шпона к основе МДФ. Можно и так.

По ширине, я насколько помню, мы в конференции остановились на том, что ширину тоже надо добавить как параметр, так как по факту их могут сделать разными (и шире, и уже) и плюс к этому комплект может состоять из трех разных ширин относящихся к теоретически разным комплектам.

**Comment by aribaz** [comment]
Боковых палок должно быть 2 в спецификации (слева и справа).

**Comment by aribaz** [comment]
Плюс окосячку, мы красим в соответствии с цветом изделия со стороны установки окосячки.

В целом мы все деревяшки красим по аналогии с окнами.

**Comment by aribaz** [comment]
От полей Ширина мы отказались. 
В качестве нестандартных ширин используем тип Заказной, и при этом понимаем, что все размеры указаны в доп. чертежах, выполненных конструктором.

**Comment by aribaz** [comment]
@Oparin-Igor Боковых палок должно быть 2

**Comment by Oparin-Igor** [comment]
Во вставке указано 2.

**Comment by aribaz** [comment]
Странно, но в спецификации 1. Это справедливо как для внешней, так и для внутренней.
![2016-12-27_08-04-26](https://cloud.githubusercontent.com/assets/22028048/21491429/bea58c16-cc0d-11e6-9772-8f58d4d56094.png)

**Comment by aribaz** [comment]
@Oparin-Igor 
Нашла ошибку по количеству боковых наличников Окосячка снаружи.

У нас три варианта боковых наличников:
Стандарт
Тип2
Заказной

Если выбрать Стандарт или Тип 2, то в спецификацию попадает  или Наличник 110 - 1 шт или Наличник 100-1шт, соответственно (вместо двух палок того или иного типа) .

А вот если выбрать Заказной для боковых, то в спецификацию с ним попадет:
Наличник 100 -1шт
Наличник 110-1шт
Наличник заказной - 2шт.
Итого 4 боковых наличника, вместо 2

Окосячка изнутри правильно рассчитывает спецификацию.

**Comment by aribaz** [comment]
Теперь она не попадает в спецификацию совсем, и не дает сохранить изделие.
Хотя до исправлений все работала.
Получается как с отливом из полиэстера, я внесла изменения и тоже перестало работать.

**Comment by nmivan** [comment]
@aribaz , задача была решена?

**Comment by aribaz** [comment]
@nmivan в том виде, в котором ее создавали  - да.
