### ISSUE TITLE
Монтаж наш

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#166]
Монтируют наши монтажники (у нас с ними есть договор, но они не в штате), и в этом случае мы сами закупаем монтажные ленты, пену, анкерные пластины и болты), даем план помещений (если объект крупный), экспликацию дверных/оконных проемов (на плане обозначено месторасположение окон с указанием их маркировки). Наш монтаж как правило считается в процентах от суммы заказа. Процент может быть разный (2-3 варианта) для учета сложности выполнения монтажа (бывало так, что не было лестничных маршей, или приходилось поднимать на кабине лифта и пр. сложности)

**Comment by unpete** [comment]
Для расчета спецификации, в том числе, плановой зарплаты монтажников, логично задействовать вставку в изделие. Преимущества: единообразие + возможность использовать параметры

**Comment by aribaz** [comment]
Монтажники у нас работают по договору подряда, они не числятся в штате, а начальник снабжения на окладе. но в целом это нам никак не помешает, с учетом того, что можно будет редактировать вставку в групповом порядке, потому как касательно монтажа или весь заказ или ничего не монтируем. 
На монтаж скорее всего будет отдельный маржинальный коэффициент - но пока не уверенна.

**Comment by aribaz** [comment]
в мпецификацию с нашим монтажом должны попадать:
Монтажная лента ПСУЛ - м.пог., откосная, устанавливается П-образно
Монтажная лента МП 100х1,5 - м.пог., подоконная, устанавливается _ (по низу)
Монтажная лента СД 70 (100х70) - м.пог., отливная, устанавливается _ (по низу)
Монтажная лента СТ100 (100х1,5) - м.пог., откосная, устанавливается П-образно
Пена монтажная - баллон
Анкерная пластина (это надо уточнить, не помню параметры)
Дюбель (это надо уточнить, не помню параметры)

**Comment by unpete** [comment]
Это вставка в изделие. Без параметров.

**Comment by aribaz** [comment]
Добавить в спецификацию с этой вставкой:

**Монтажная лента ПСУЛ:**
м.пог, откосная, Устанавливается  П- образно Длина  (Нбл-17)* 2+ (Вбл - 17 * 2)

**Монтажная лента СТ100 (100х1,5)**
м.пог, откосная, Устанавливается П-образно L = (Нбл+50) * 2 + Впр

**Монтажная лента МП 100х1,5**
м.пог, подоконная, устанавливается (по низу)_  L = Вбл

**МОНТАЖНАЯ лента 70 СД (100х70)**
м.пог, отливная, устанавливается (по низу)_  L = Вбл+50

**Установка блока** - руб / кв.м блока, это уже сама работа

Где Н бл - высота блока; B бл - ширина блока

**Comment by nmivan** [comment]
@aribaz , задача актуальна?

**Comment by aribaz** [comment]
Уже все сделано.
