### ISSUE TITLE
Монтаж Дилера

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#167]
Вторая схема включает монтаж для клиента, но силами дилера. У них свои монтажники, и сам по себе монтаж - нас не касается, но было бы здорово, чтобы дилер мог вставить строчку со своим монтажом, который бы никак не отразился на нас. Это лишь для того, чтобы дилеру не пришлось мудрить с печатными формами и не считать монтаж где-то отдельно. Как он у них рассчитывается я пока не знаю.
Мне кажется вполне достаточно дать возможность устанавливать цену на него их руками по аналогии с составным стеклопакетом.

**Comment by unpete** [comment]
Решается организационно. Кодировать ничего не надо. На наши взаиморасчеты с дилером такие строки не влияют.
Пример в заказе [ТАР00000001](https://light.oknosoft.ru/#obj=doc.calc_order&ref=12ca1988-5fe1-4baa-c0e4-d2bebefd7baf&frm=doc&view=orders)

**Comment by aribaz** [comment]
Попробовала добавить монтаж.
Сделала это через добавить Материал, получилось.
Цену задала руками, цена доступна для изменения как Цена поставщика, так и Цена дилера. 
Если ставлю цену поставщика за этот монтаж, то Цена дилера считается автоматом с учетом Кмарж.
Строка с монтажом попадает в печатные формы счетов (те что есть сейчас), даже если цену ставлю только дилерскую., тогда по суммам 0, количество - 1.
Это нас обязывает юридически к монтажу фактическому за бесплатно, это не хорошо.

Не знаю как проверить попадет ли этот монтаж в 1С-ку (акты выполненных работ, заказ и пр.) в нашу, ведь мы не имеем отношения к этому монтажу, значит и в 1С его быть не должно, даже с нулевой ценой; он нужен только для удобства работы дилера с Сервисом.

**Comment by unpete** [comment]
> доступна для изменения

У Вас - полные права.
Дилеру поля `Цена поставщика` и `Скидка поставщика` недоступны для изменения в принципе.

> Строка с монтажом попадает в печатные формы счетов

Это вопрос к печатным формам, а не к механизму регистрации дилерских услуг в сервисе

> Не знаю как проверить

`Заказ`, `Оплата` и `Реализация` - самостоятельные события.
Чтобы строка с нулевой ценой в `Заказе` не оставляла следов в учете, просто не оформляйте по этой строке `Реализацию`.

**Comment by aribaz** [comment]
Монтаж дилера вносить как материал и просто указать цифру (цену) монтажа в колонке Цена дилера.

Работает, закрываю
