### ISSUE TITLE
Параметры изделий (таблица)

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#168]
Составила Таблицу [Параметры изделий.xlsx](https://github.com/oknosoft/windowbuilder/files/594968/default.xlsx)

В ней цветом выделила то что есть, то что надо удалить и то что добавить.
Добавила туда гиперссылки на задачи в Гитхабе.

Вот что еще думаю, если в заказе появляются допы (вставки: отлив, подоконники, доборы, окосячка, обсада) и не важно один или все вместе, то для расчета их размеров автоматом необходимо знать:

- ширину проема
- высоту проема
- глубину проема
- привязку изделия в толще стены

Что-то типа блока полей Проемы см. #171 .
Тогда в зависимости от этих размеров и размеров самого изделия можно будет посредством математических вычислений (при условии что мы знаем технологические минимумы и максимумы для вставок) определять размеры любой из вставок. Тогда наверное правильно вынести эти параметры в свойства изделия. 
Здесь еще момент,: мы предполагаем не только расчет автоматом размеров этих вставок (когда в полях с размерами будет написано Авто), но и возможность задать эти размеры вручную (например, готовых проемов еще нет - здание в процессе стройки, и как показывает практика факт от проекта могут очень отличаться).
Если допов нет или пользователь указывает размер этих вставок сам (значение полей не равно Авто и > 0, но не < размера окна) , то необходимость заполнения этих полей (проемов) отпадает, а если в полях вставок остается значение Авто, а поля блока Проемы - остались пусты, надо, чтобы сервис не дал возможность сохранить в таком виде изделие, а выдал сообщение об ошибке - "Заполните блок Проемы" или типа этого. 
Наличие блока проемы даст возможность менеджеру предупредить клиента о том, что зазор слишком узкий и окно таких размеров делать нельзя, их надо скорректировать (но дать возможность сохранить, даже если меньше ГОСТа, главное: размер окна должен быть хоть на 1см меньше размера проема).

Можно тогда и размеры окна привязать к проемам (но не обязательно). Только как тогда быть с балконным блоком (дверь и окно - проем не прямоугольный, а с уступом). а подоконника и отлива два и их общая длина будет больше, чем у одного блока, вписанного в такой-же проем.

![001](https://cloud.githubusercontent.com/assets/22028048/20349254/b5a7e5cc-ac1a-11e6-90c4-85b878adc701.jpg)

Сейчас у Игоря нет полной информации о том, что должно попадать в спецификацию совместно с некоторыми новыми параметрами. Я оформлю табличкой и тоже сюда прикреплю.

Все вставки из п/м должны краситься с двух плоскостей (лицевая/черновая).

Исходя из этих параметров начинает вырисовываться какая нужна проверка и что надо проверить, чтобы заказ запустить в работу автоматом.
Бывают такие случаи, когда заказ запускают в работу без оплаты.

**Comment by aribaz** [comment]
Добавила к параметрам Капельник.
Файл обновила 
[Параметры изделий.xlsx](https://github.com/oknosoft/windowbuilder/files/599251/default.xlsx)

**Comment by aribaz** [comment]
Я ранее писала о названиях продукции (системах профилей) см. #155.
Сейчас я сделал файлик [Системы профилей и их параметры.xlsx](https://github.com/oknosoft/windowbuilder/files/599368/default.xlsx) , в котором описала возможные сочетания профилей в зависимости от того в каком типе блока они применяются и у меня вырисовалось 4 системы профилей:

1. Оконный блок (обозначение в сервисе ОБ)
2. Балконная дверь (обозначение в сервисе ББ)
3. Дверь входная внутреннего открывания (обозначение в сервисе ДБ/В)
4. Дверь входная наружнего открывания (обозначение в сервисе ДБ/Н)

К этим системам я привязала возможные профили отдельно по типу элементов и внутри каждого элемента по положению (если есть разница) в изделии, а также к ним же привязала возможность применения конкретных параметров, которые были описаны в таблице Параметры изделий.
Не хватает в базе 4 профилей (всплыли), они выделены красным на листе Профили.

Прошу все же согласно табличке сделать нам 4 системы профилей, это позволит нам быть более свободными в проектировании и более гибко учитывать желания клиентов и наши возможности. Изменения в ней в основном коснулись дверей, о том что так можно соединять ранее просто не знала наверняка. А как выяснилось то что у нас есть сейчас дает мало возможностей для проектирования дверей (моя вина в написании ТЗ для дверей).
Так как принципиально новых профилей там нет, думаю Игорь сможет перераспределить профили по системам, возможно понадобится добавить новые соединения.

Еще пока разбирала чертежи и профили, выяснила, что у нас есть возможность сделать створку внутри створки (это делают крайне редко), в основном это просят сделать владельцы домашних питомцев, чтобы те могли выходить/заходить сами. 
Такую возможность нам дает один дополнительный профиль. Об этом профиле мы не говорили ранее, поэтому его в таблице нет. Я его добавлю, но позже (после старта), мне надо понять с чем его можно соединять, а с чем нет и чем это грозит - на это надо время.

Некоторые параметры должны повлиять на состав спецификации (их не много - в основном по дверям и доп. металлическим профилям - капельник, профиль покрытия оконных створок - хотя по ним есть информация в Гитхабе) - эта информация за мной, файл наполовину уже сделала.

Вот вспомогательная информация по этой же теме из гитхаба:

#143 Добавление параметров к изделию (цвет упл., проф.покр, цвет водоотвода)
#117 СтворкаНиз79 с водоотводом ( Профиль покрытия оконных створок)
#118 Водоотводный профиль характеристики
#129 Водоотвод закупка и учет в спецификации

#146 Параметры балконной двери
#110 профиль низа рамы дверей

Штульповые двери - по аналогии с окном, тоже со штульповым профилем в спец-ю попадает нащельник 52х8, как и в окнах.
#121 Как нарисовать штульповую дверь
#157 Штульповая дверь балконная

Остались нерешенными/не до конца решенными вопросы:
#134 по Сущностям ЛКМ
#122 по стеклопакетам с другими формулами (есть в ассортименте "Составной стп 40мм.")
#156 Блокада ручки (нужен или нет параметр)
#132 Цвет филенки
#130 Характеристики мебельного щита для филенки.

Это наверное все основные вопросы (включая эту задачу) до решения которых старт не может состояться, потому что затрагивает вопрос возможности рисовать основные виды конструкций и рассчитывать их стоимость - это необходимый минимум, который я должна предоставить мнеджерам и дилерам для тестирования - иначе для них сервис  - потеря времени (в том виде, в каком есть сейчас) - мне директор не даст запустить тестирование в таком случае.

**Comment by aribaz** [comment]
[Материалы в спецификацию с параметрами 2016-11-18.xlsx](https://github.com/oknosoft/windowbuilder/files/600352/2016-11-18.xlsx)

В файлике собрала данные по тем материалам, которые должны попадать в спецификацию при выборе каких-либо параметров из таблицы Системы профилей и их параметры.

Таблица не законченная, вторую часть на следующей неделе доделаю и выложу.

**Comment by aribaz** [comment]
[Материалы в спецификацию с параметрами 2016-11-21.xlsx](https://github.com/oknosoft/windowbuilder/files/602905/2016-11-21.xlsx)
Таблицу собрала, в ней содержатся только недостающие данные или те, которые надо было исправить. В этой версии появился Профиль покрытия оконных створок.
Еще раз прошу напоминаю, что Профиль покрытия оконных створок (сокращ. профиль покрытия) и Профиль водоотводный (сокращ. водоотвод)- это две разных самостоятельных единицы. Водоотвод ВСЕГДА должен быть в ОКНЕ, но не всегда в дверях. 
Физически он (водоотвод) устанавливается во внутрь рамы, но привязан сейчас он к профилю СтворкаНиз79 с водоотводом вместо СтворкаНиз79. Я предполагала, что профиль Створка низ79с водоотводом в спецификации учтет еще и  Профиль покрытия, помимо водоотвода.
Согласно таблице Системы профилей и их параметры водоотвод в дверях может быть только в том случае, если профиль низа рамы РамаНиз83 - и это справедливо для любого изделия (окно/дверь любая) только в этот профиль физически можно установить этот водоотвод и ни в какой другой его поставить не получится, какой бы створка по низу ни была. И правильнее наверное попадание Водоотводного профиля (и накладок к нему) привязать не к профилю створки, а к профилю РамаНиз83 - а то что в окне глухарь со створкой в глухой части не получится поставить водоотвод определяется наличием прилегающего профиля Рамная заклада.
Получается правило:
Если к РамаНиз83 НЕ примыкает Рамная_закладка, то водоотводный профиль ставим на весь профиль (и тогда расчет его длины для штульпа становится тоже правильным) и расчет длины осуществляется как Lводоотв = Габарит рамы - ширина профиля боковой рамы*2 +18*2 (так как профиль Рама низ устанваливается по всей ширине отдельно взятого блока, где 18мм - размер торцевого соединения водоттводного профиля и боковых профилей рам), 
иначе (если рамная закладка примыкает), то расчет длины профиля считаем так:
 Lводоотв= Lраманиз - Шр.левая+18-Шимп+18-(Lрам.зак - Разм(т-соед:рамзак/имп) - Разм(т-соед:рамзак/рамбок)-Шр.лев.
Именно ширина боковой рамы и импота, а не цифры, так как рама может иметь ширину и 63 и 83мм, равно как и импост может быть 79 и 89мм.

Единственное надо здесь учесть то, что все длины деревянных профилей больше на 20мм (припуск на концепт, а водоотводный профиль этого припуска не должен иметь.
Только я не знаю можно ли такую формулу создать 
![default](https://cloud.githubusercontent.com/assets/22028048/20475986/ba013fe2-afdf-11e6-9110-ef9e08bf3d24.jpg)

**Comment by aribaz** [comment]
Попробую подытожить то, что сегодня обговаривали.

У нас есть три вида вставки:
Вставка к Элементу
Вставка к Изделию
Вставка к Створке
Все наши допы (монтаж, отлив, подоконники, москитка, обсада, доборы, окосячка)- это вставки к изделию, за исключением Москитки - это вставка к Створке.
Из тех параметров, что я описала некоторые из них присутствуют обязательно, а некоторые  - исключительное желание заказчика.

Необходимо внести параметры, обязательные, к изделию:
- Цвет уплотнителя (хоть уплотнитель и присутствует уже в створке, его цвет - это желание заказчика), этот параметр применим к изделию в целом.

- Водоотводный профиль - это обязательный элемент и он у нас привязан сам по себе, необходимо вынести в параметр Цвет водоотводного профиля - он одинаков на все изделие, но для цвета Заказной должен появиться параметр: Цвет торцевых накладок. Для профиля цветом RAL 8017 - накладки коричневые, для RAL 9016 - белые.

Параметры исключительно желание заказчика (применяемые к элементу, т.е. вставка элемента):

- Профиль покрытия оконных створок (к элементу нижнего профиля створки, рамной закладке, профилям Глухарь (горизонтальным), горбылькам (горизонтальным), Импост Комби (горизонтальный). Цвет этого профиля надо указывать вручную, в не привязывать к цвету основного элемента. При выборе цвета Заказной - должен появиться параметр: Цвет торцевых накладок (для выбора вручную). Для профиля цветом RAL 8017 - накладки коричневые, для RAL 9016 - белые. 
- Капельник (к элементу нижнего профиля створки дверей). Цвет капельника должны указать руками, капельник не должен его наследовать от основного профиля.
- Защита порога (к элементу нижнего профиля рамы типа Порог для дверей)

Их надо добавить как Вставку элемента - это позволит не расширять состав номенклатуры комбинациями.

Все остальные параметры - содержатся в таблице и относятся в большей степени к фурнитуре, то есть их надо добавить к створке.

Профиль водоотводный 22/34 - привязан к СтворкаНиз79 с водоотводом, его надо перепривязать, а профиль СтворкаНиз79с водоотводом удалить.

**Comment by aribaz** [comment]
**ПРОЕМЫ**
у меня есть два типа узлов:

- для каменных (кирпич, бетон) домов 
- для деревянных домов.

Согласно эти узлам:

для **каменных домов** зазор между блоком и стеной по бокам и верху должен составлять 20мм, а зазор  между блоком и стеной по низу 30мм - это собственно минимальные размеры и они не зависят от габарита проема, но могут быть больше, а вот меньше не желательно (потому как окно может начать промерзать и пр. тонкости) и заказчика мы об этом предупреждаем обязательно, но на нашей практике зазоры бывали меньше необходимых и такие случаи чаще одного раза в год -заказчик кивает головой и говорит "Надо".

для **деревянных домов** верхний зазор между рамой и стеной должен составлять 4-5% от высоты проема (не блока), ориентируемся на максимум - это рекомендации изготовителей срубов, так как брус дает еще усадку.Остальные зазоры как для каменных домов, по бокам тоже по 20мм с каждой стороны и по низу зазор тоже 30мм. 

Зазоры для каменных домов.
Боковой
![-](https://cloud.githubusercontent.com/assets/22028048/20551965/eecfdd3c-b156-11e6-91ec-037e7ba8da4c.jpg)
Верхний
![-](https://cloud.githubusercontent.com/assets/22028048/20551963/eeca646a-b156-11e6-925d-9aed14e3af32.jpg)
Нижний
![-](https://cloud.githubusercontent.com/assets/22028048/20551964/eecdf29c-b156-11e6-8557-ad099991ce8b.jpg)

Зазоры для деревянных домов, но деревянные дома требуют обязательно обсады.
[примыкание  в деревянном доме-Model.pdf](https://github.com/oknosoft/windowbuilder/files/608145/-Model.pdf)

**Comment by aribaz** [comment]
Копия письма Игорю от 29-11-2016.

Игорь, я разбила файл Система профилей на два, в одном приведены только профили, в другом наличие/отсутствие параметров для этой системы.

У меня ранее дополнительный профиль числился в таблице с параметрами, но ввиду того, что теперь эти доп профили мы будем добавлять посредством вставки к элементу получается таких параметров изделий быть не должно.

Таких дополнительных алюминиевых профилей  (по желанию заказчика) у меня три:
Профиль покрытия оконных створок
Капельник
Защита порога
Капельник и Профиль покрытия оконных створок должны иметь параметр Цвет, Защита порога - это всегда только без покрытия.  
Все что должно попадать с этими профилями в спецификацию описано в файле Материалы, более поздняя версия (см. #168)

Капельник и Защита порога могут быть только на дверях. а профиль покрытия оконных створок еще и на окнах.

В таблице Системы профилей я опишу их как параметры - лишь для понимания где они могут быть, а где нет.



Еще вопрос к параметрам, почитала выдержки из наших с вами переписок, и нашла вот что (вы мне поясняли):
"Микропроветривание – щелевое, ступенчатое зависит от применения угловых переключателей и ответок."

Я скорее всего об этом забыла, потому что я считала что Ступенчатое - это Гребенка (ставится на профиль внутри помещения, что-то типа гребешка, для фиксации положения створки в открытом (поворотном и/или поворотно-откидном) состоянии). Если Ступенчатое - это не Гребенка, то вариант Гребенка надо добавить. Это не совсем конечно МИКРОпроветривание, потому что позволяет достаточно широко открыть створку, но Гребенки на балконных дверях мы ставим часто, да и на окнах тоже.
[Системы профилей (параметры)2016-11-29.xlsx](https://github.com/oknosoft/windowbuilder/files/619206/2016-11-29.xlsx)
[Системы профилей (профили) 2016-11-29.xlsx](https://github.com/oknosoft/windowbuilder/files/619207/2016-11-29.xlsx)

**Comment by aribaz** [comment]
Игорь  @Oparin-Igor , я  довнесла недостающие материалы из файла "Материалы в спецификацию с параметрами", можно их привязывать.

Вся фурнитура Roto Power Hinge в артикуле содержит префикс RPH (в таблице артикулы пусты были), по идее к петлям этим нужна колпачки разных цветов, но артикулов их у меня нет пока, поэтому я просто о них.
Внесла операцию "Обрезка нижнего профиля створки двери" для Алюминиевого порога, может в этой строке что-то не так внесла, операции ранее не вносила.

С меня еще характеристики материалов, которые должны попасть в спецификацию с допами (шпон  -характеристики, МДФ - характеристики)
У нас остались такие строки:

Колпачек декор
Колпачек декор 16мм коричневый

Это я так понимаю были колпачки Отлав, я не знаю привязаны они к чему-нибудь уже или нет (не знаю где можно это посмотреть), поэтому не стала их переименовывать, чтобы ничего не нарушить, а создала необходимые.

Ручка балконная металлическая
Ручка балконная пластикавая
Так как мы используем только пластиковую двух цветов, эти две позиции я не трогала, а создала две новые по той же причине.

**Comment by Oparin-Igor** [comment]
//Так как мы используем только пластиковую двух цветов, эти две позиции я не трогала, а создала две новые по той же причине

- Уточните какие артикулы создали

**Comment by aribaz** [comment]
Ручка балконная 040, белая  - переименовала название под артикул, строка была
Ручка балконная 040, коричневая - создала новую

**Comment by aribaz** [comment]
Колпачки для петель отлав в названии содержат диаметр и Otlav (их я тоже сама создала)

**Comment by Oparin-Igor** [comment]
На одну петлю идет 2 колпачка?

**Comment by Oparin-Igor** [comment]
Дв. петли дер.
- otl 495 160
- otl 495 160
+ колпачки

**Comment by aribaz** [comment]
У нас получается петля состоит и рамной части и створочной части, и колпачок (один для обеих частей одного диаметра) одевается и на рамную часть и на створочную часть

**Comment by nmivan** [comment]
@aribaz , задача актуальна?

**Comment by aribaz** [comment]
@nmivan уже нет, все настроено.
