### ISSUE TITLE
Разные вставки для одного материала

### ISSUE THREAD

**Issue by unpete** [oknosoft/windowbuilder#17]
Пример: AYPC.F50.0102 Стойка 62мм может работать и как рамный, и как импостный элемент.
Спецификация вставки, наверное, одинаковая, но точка привязки (размер B) - разные.
Замечание: _размер B_ переехал из номенклатуры во вставку. Теперь для одного материала можно задать разные точки привязки в зависимости от того, как этот материал используется

- Если сделать две вставки, станет проще и понятнее
- Чтобы не повторять общие части спецификации, можно задействовать вложенные вставки

**Comment by Oparin-Igor** [comment]
Что такое размер В

**Comment by unpete** [comment]
> Что такое размер В

Опорная линия. Для рамы чаще всего = 0, для импостов - половина ширины, но может быть смещено на любую величину, в том числе большую, чем ширина профиля. В извращенных случаях, створка может быть снаружи рамы, если этого захочет технолог.

**Comment by Oparin-Igor** [comment]
Тогда надо сделать обозначение В как, при использовании элемента в кач-ве импоста размер В.

**Comment by Oparin-Igor** [comment]
Т.к. один элемент может быть и рамой и импостом AYPC.F50.0102 Стойка 62мм.
Используя это во вставках можно ошибиться при выборе вставки.

**Comment by unpete** [comment]
> Используя это во вставках можно ошибиться при выборе вставки

Это как раз, не проблема. Доступность вставок можно ограничить в зависимости от положения и назначения элемента

**Comment by Oparin-Igor** [comment]
Но тогда не надо дублировать всавки, но если это реализовать сложнее тогда не спорю.
Что касается алюминия, то вставок будет в 2 раза больше.

**Comment by unpete** [comment]
> вставок будет в 2 раза больше

Вариантов не вижу. Номенклатура - это складская сущность и плодить её мы не можем.
Вставок, действительно, становится больше, но они простые - спецификация в отдельной общей вставке

**Comment by unpete** [comment]
> Цитата письма, чтобы не потерялось:

Коэффициент - вообще убрать
Расчет количества оставить только для (для элемента(используем количество), по шагам по формуле)
Угол(Основной, 90...) - перенести в формулы
Обозначения стандартные:
P-периметр (параметр по умолчанию, устанавливается только если надо вычислять, к примеру саморезы)
S-площадь (При установке в формулах считается по площади
B-ширина (При установка B считается по ширине 2 раза верх низ)
В1- ширина низ.
В2-ширина верх.
Н-высота
Н1 высота лево
Н2 высота право
L-Длинна (при установке параметра считаестся суммировано по периметру)
Расчет Угол (считается из построителя) вообще убрать - это опция как правило для станков, при формировании файла на станки  это можно учесть. Ставить только галочку если считать не надо)
Угол к горизонту тоже убрать в формулу, т.к используется в исключительных случаях
Пример: Параметр P(угол мин,угол мах.) P(0,89)
Длинна мин, мах определяется длинной профиля для оптимизации по умолчанию не заполняется, параметр устанавливается
редко.
Для саморезов P*4 -четыре самореза на 1м для шт с округлением
Для базового В1 считается только снизу.
По шагам В,250 по ширине через 250мм.

Створка с разным армированием, со стороны ручки используется другое армирование армирование.
Армирование 1 формула Н1
Армирование 2 формула P-H1
Длину мин, мах также можно убрать в формулу Р[0,200]

![inserts-sentence](https://cloud.githubusercontent.com/assets/12096477/13526539/4b2dbb28-e22a-11e5-85ed-7f3ae5148cf1.jpg)
