### ISSUE TITLE
Проемы

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#171]
**ПРОЕМЫ**
у меня есть два типа узлов:

- для каменных (кирпич, бетон) домов 
- для деревянных домов.

Согласно эти узлам:

для **каменных домов** зазор между блоком и стеной по бокам и верху должен составлять 20мм, а зазор  между блоком и стеной по низу 30мм - это собственно минимальные размеры и они не зависят от габарита проема, но могут быть больше, а вот меньше не желательно (потому как окно может начать промерзать и пр. тонкости) и заказчика мы об этом предупреждаем обязательно, но на нашей практике зазоры бывали меньше необходимых и такие случаи чаще одного раза в год -заказчик кивает головой и говорит "Надо".

для **деревянных домов** верхний зазор между рамой и стеной должен составлять 4-5% от высоты проема (не блока), ориентируемся на максимум - это рекомендации изготовителей срубов, так как брус дает еще усадку.Остальные зазоры как для каменных домов, по бокам тоже по 20мм с каждой стороны и по низу зазор тоже 30мм. 

Зазоры для каменных домов.
Боковой
![-](https://cloud.githubusercontent.com/assets/22028048/20551965/eecfdd3c-b156-11e6-91ec-037e7ba8da4c.jpg)
Верхний
![-](https://cloud.githubusercontent.com/assets/22028048/20551963/eeca646a-b156-11e6-925d-9aed14e3af32.jpg)
Нижний
![-](https://cloud.githubusercontent.com/assets/22028048/20551964/eecdf29c-b156-11e6-8557-ad099991ce8b.jpg)

Зазоры для деревянных домов, но деревянные дома требуют обязательно обсады.
[примыкание  в деревянном доме-Model.pdf](https://github.com/oknosoft/windowbuilder/files/608145/-Model.pdf)

**Comment by aribaz** [comment]
Тогда надо еще добавить два параметра: 

- параметр толщина проема - здесь пусть пользователь сам указывает толщину, потому как у стен отделка разная.
- параметр привязка оси блока к стене.

Здесь речь о том как поставят блок в толще стены от этого зависит ширина отлива и теоретически подоконника, но подоконник может понадобиться шире (решили его использовать как столешницу).
За ось блока предлагаю считать самую дальнюю плоскость рамы на улице.
[Привязка блока к толще стены.pdf](https://github.com/oknosoft/windowbuilder/files/608170/default.pdf)

**Comment by unpete** [comment]
Пометил задачу, как заготовку документации.
Закрываю, т.к. активных действий по ней не требуется
