### ISSUE TITLE
Расчет вставок

### ISSUE THREAD

**Issue by Oparin-Igor** [oknosoft/windowbuilder#173]
Изделие
https://light.oknosoft.ru/#obj=cat.characteristics&ref=3da166ec-02f1-46d5-df39-fe8bc0443ee2&frm=builder&view=orders
![image](https://cloud.githubusercontent.com/assets/17551128/20716424/00e918cc-b674-11e6-9a31-c22e8809b46c.png)
1. Спецификация, в колонке количество, материал "Грунт AQUA PRIMER 2900-02 COLOR" должно быть 1, кол-во++ не заполнено.
Вставка "дер.лак" входит во вставку "дер.Рама 83".
2. Параметр "Парам.белого" значение не заполнено.

**Comment by unpete** [comment]
Удалил из системы `Параметр "Парам.белого"` и связанные с ним `Связи параметров`
В фильтрах, вместо `Параметр "Парам.белого"` задействовал вычисляемый параметр `Цвет элемента`

**Comment by Oparin-Igor** [comment]
Поподробнее.

**Comment by aribaz** [comment]
Может окно для доп вставок в изделие не будет содержать в себе параметры, которые относятся ко всему изделию и доступны в табчасти изделия, ведь они обязательные, а не дополнительные?

**Comment by unpete** [comment]
> Может окно для доп вставок в изделие не будет содержать в себе параметры

Примерно так и сделано.
Пока не выделена ни одна строка допвставок - видим параметры изделия.
При фокусе на одной из допвставок - видим параметры допвставки.

**Comment by aribaz** [comment]
@unpete 
Я решила на одном окне проверить все вставки, все добавила, изделие не сохраняется, кнопка не приводит ни к каким действиям. Закрыла без сохранения изделия и из списка заказа исчезло само окно, остались только вставки в контур, а вставки в изделие тоже не появились. [Заказ 43](https://light.oknosoft.ru/#obj=doc.calc_order&ref=e8f39c6e-055e-4c21-c15a-e680175d152a&frm=doc&view=orders)

![2016-12-22_10-06-02](https://cloud.githubusercontent.com/assets/22028048/21417885/a46a1b60-c82e-11e6-9244-f76d5a7d6f3f.png)

**Comment by aribaz** [comment]
Не работает корректно вставка в изделие, а вставка в контур не приводит к ошибкам.
Если сразу в изделие добавлять и вставку к контуру и вставку к изделию, то в заказе остаются только строки со вставками в контур, а само изделие исчезает (см. рисунок выше).
Если сначала добавлять вставки в контур, сохранить, а потом добавить вставку в изделие, то изделие не пропадает, но вставки в изделие все равно не добавляются.

**Comment by unpete** [comment]
Не осилил текст предыдущего комментария.
Просьба привести сценарий воспроизведения проблемы или закрыть задачу с учетом #188

**Comment by aribaz** [comment]
Простите за мой русский )))
Закрываю, описала все в #188
