### ISSUE TITLE
Привязка бруса  к профилю

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#174]
У меня еще вот какой вопрос остался открытым.
Программа сейчас считает профиль, но ведь как такового профиля готового у нас нет. Весь этот профиль мы делаем из бруса, который в свою очередь может быть покупным или самодельным, тогда появляются доска, клей и работы.
И надо увязать между собой профиль и брус.

Брус всегда продается в кубических метрах.

Брус у нас есть двух размеров:
84х86
84х116 (импост)
Где 84 - это толщина, которая потом превращается в 78;
       86 (116) - это ширина бруса, из которой получаем 83/93/103/113/120

Каждый из этих размеров может быть одним из 6-ти наших типов древесины:
сосна сращеная
сосна цельноламельная
лиственница сращеная
лиственница цельноламельная
дуб сращеный
дуб цельноламельный.

Итого 12 номенклатур бруса.

Толщина пилы на фабрике 4мм (когда мы сами кроим брус).

Сращенный брус бывает 3000мм и 6000мм длиной, в основном покупаем 6м - это влияет на раскрой.

Цельноламельный брус у поставщиков имеет разные длины с шагом 100мм, начиная от 500мм.
На цене бруса это никак не сказывается (за куб м. любой длины) - а вот это нам мешает при производстве, прежде чем начать делать заказ производят сортировку (сначала раскладывают всю кубатуру (а это может быть и 20 кубов леса) по длинам, чтобы можно было понять какую палку для какого изделия использовать - это процесс не быстрый, и только потом когда всего хватает начинают делать окна).
Если мне к примеру надо 510, то купить придется 600, и 90 мм- в отход. Казалось бы, что можно произвести некоторую оптимизацию перед закупкой и купить длинные палки, а на производстве распилить как надо и сэкономить время, но НЕТ - так не продают - мы должны купить коротье (палки до 2м) тоже обязательно - так сложились традиции поставок у лесовиков - или так, или никак. Разрешено вместо двух коротких купить одну длинную (длиной как две короткие) если нет необходимых длин у поставщика в наличии (такое бывает). Они тоже не дураки и знают что и коротье нам тоже необходимо.

Брус в 90% мы покупаем готовый, но иногда бруса на рынке не бывает и делаем его сами из досок соответствующей породы, по деньгам примерно то же самое, а вот по срокам нет, так как впрок мы его не делаем, плюс это сказывается на том какой материал надо использовать для получения профиля - это спецификация полуфабриката Профиль, а так же материалы одни ли другие для списания бухгалтерией.

А вот брус дуба цельноламельный делаем сами часто, потому что его на рынке не много - а это сказывается на сроках.

Это я к тому, что для того чтобы выполнить заказ, сначала надо обзавестись брусом (чаще купить). Чтобы это сделать надо перевести профиль в брус.

Это в целом касается всего что мы делаем из пиломатериалов (подоконники, филенки, обсада, обналичка, доборы).

**Comment by aribaz** [comment]
Из разговора с Евгением поняла так, что будет сделана отдельная обработка, которая переводит профиль (полуфабрикат) в сырье

**Comment by unpete** [comment]
> будет сделана отдельная обработка

Скорее всего, не обработка, а документ `Корректировка потребностей`

**Comment by aribaz** [comment]
#179

**Comment by nmivan** [comment]
@aribaz , здесь что скажете? Есть изменения?

**Comment by aribaz** [comment]
@nmivan пока без изменений
Я для себя (для облегчения жизни в отсутствии инструментов) распределила брус по группам и в отчете по  спецификации использую группировку, складываю длины внутри каждой группы и перевожу в кубы - для понимания предстоящих материальных затрат на брус, а также для проверки наличия необходимого объема на складе.
