### ISSUE TITLE
Вычисляемый параметр Тип покрытия

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#175]
Я сделала в справочнике Цвето-ценовые группы 3 группы.
Тип покрытия Глухие цвета (кроме белого)
Тип покрытия Глухие цвета (только белый)
Тип покрытия Прозрачные цвета

Внутри каждой группы на закладке Соответствие цветов я добавила те цвета, которые относятся к этой группе,  а на закладке Ценовые группы, номенклатуры или папки номенклатур я добавила номенклатуры сущностей, которые возможны для этого типа покрытия. Возможных значений одной сущности - два или три, какое конкретно из них - определяется другими параметрами, которые указывает пользователь (Эффект покрытия - влияет на лак; Качество покрытия - влияет на грунт).

Качество покрытия = эконом, то применяется Грунт Aqua Primer 2900-02 Color (и для глухих, и для прозрачных)
Качество покрытия = стандарт, то применяется Грунт Aqua Primer 3130 white (для глухих) или Грунт Aqua Primer 2907-02 (для прозрачных)

Эффект покрытия = без эффекта, то применяется Лак AQUATOP 2600-83 CLEAN WHITE (только для белого) или Лак AQUATOP 2600-83 RAL 9010 Color (для глухих цветов кроме "белый); или Лак AQUATOP 2600-24 SG BASE T Color (для прозрачных цветов).
Эффект покрытия = матовый, то применяется Лак AQUATOP 2600-71 SM BASE T Color (и для глухих и для прозрачных)

**Comment by unpete** [comment]
Если параметр связан с группой цветов, тип его значения следует делать `Справочник.ЦветоценовыеГруппы`, а не `Справочник.ЗначенияСвойствОбъектов`.
Это значительно упрощает код. В условии указываем нужную цветоценовую группу и всё работает.
Если указаны значения свойств, нужно где-то хранить соответствие и писать код, который будет это соответствие отрабатывать.

- [ ] Изменить тип значения параметра `Покрытие`
- [ ] Включить параметр `Покрытие` в группу вычисляемых параметров - его нельзя будет указать в рисовалке, но можно использовать в соединениях и вставках
- [ ] Доработать соединения и вставки - указать в них цветоценовые группы вместо значений `глухое` или `прозрачное`
- [ ] Написать код, вычисляющий значение параметра для цветоценовой группы

**Comment by unpete** [comment]
- Параметр `Покрытие` теперь вычисляемый и возвращает массив цветоценовых групп, в которые входит цвет текущего элемента с учетом правил вычисления цвета для строки спецификации (как элемент, снаружи, изнутри, как изделие)
- Отредактированы вставки `дер. лак щит` (000001384) и `дер. лак` (000001296) - задействован вычисляемый параметр

**Comment by aribaz** [comment]
Евгений, у меня теперь из спецификации исчезли лакокрасочные материалы. Работа есть, а материалов нет.
[Заказ 40](https://light.oknosoft.ru/#obj=cat.characteristics&ref=0805649a-4ad3-4a2e-86b5-9b8ad7b62a81&frm=builder&view=orders)

**Comment by aribaz** [comment]
И выпадает еще Уплотнитель

**Comment by aribaz** [comment]
Параметр Тип покрытия исчез, но проверить то ли входит в спецификацию не могу, так как вместе с ним исчезли и сами ЛКМ из спецификации.
Этот вопрос закрываю, так как параметр исчез, чего и хотели добиться, а по исчезнувшим ЛКМ и уплотнителю создала отдельную задачу.
