### ISSUE TITLE
Вычисляемый параметр Поверхность

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#176]
Параметр Поверхность должен быть доступен только для материала бруса="дуб сращенный" или "дуб цельноламельный" . Вариант параметра Поверхность (гладкий или пористый) - выбирает пользователь.

**Comment by unpete** [comment]
Это частный случай связей параметров #177

**Comment by unpete** [comment]
В работе не проверял, но если связи параметров настроены, фильтр должен подключиться

**Comment by aribaz** [comment]
Для параметра Поверхность кроме ключа Система: дерево (так как этот параметр действителен только для нее), должен быть собственно еще ключ Материал бруса: дуб сращенный, дуб цельноламельный, что-то типа связки этих ключей; уже для комбинации которых и должен появляться параметр Поверхность.
Я правильно понимаю, что для того чтобы эта связь заработала надо добавить еще одну строку в справочник Ключ параметров, на закладке Параметры которой необходимо указать два параметра (Система и Материал бруса) и уже для этой строки в качестве ведомого параметра выбрать Поверхность, с вариантами этой поверхности?

**Comment by aribaz** [comment]
Закрываю, его настройка описана в задаче #177
