### ISSUE TITLE
Некорректное сохранение изделия

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#178]
Евгений, уже второй день сталкиваюсь с тем, что кнопка Рассчитать, записать и закрыть не совсем правильно работает.

Если я создаю изделие без вставок, и нажимаю Рассчитать, записать и закрыть, то все хорошо - изделие записывается и форма редактирования закрывается, а в заказе появляется строка с изделием.

Но если я открыла или создала изделие и добавила **вставки в изделие**, и нажимаю на кнопку Рассчитать, записать и закрыть изделие, значок синхронизации (вверху справа) при этом не крутится и ничего не происходит, когда нажимаю на кнопку Закрыть без сохранения, то соответственно всплывает сообщение об этом и: или я соглашаюсь и в изделии не появляются вставки (что логично, я же не сохранила их); или окно редактирования изделия остается открытым, но кнопка Рассчитать, записать и закрыть не срабатывает, как впрочем и кнопка Рассчитать и записать данные и кроме как закрыть изделие без сохранения мне ничего не остается, но само изделие при этом появляется в строке заказа.

Кнопка Записать (заказ) работает нормально при этом.
Вставки в контур работают нормально в этом же заказе и в том же изделии.
[НЗАР0000034](https://light.oknosoft.ru/#obj=doc.calc_order&ref=9fc91da5-b738-4d65-f0b3-a3720107cf23&frm=doc&view=orders)

**Comment by unpete** [comment]
Во вставках в изделие были странные строчки - не был указан способ расчета количества и отсутствовала формула. Поправил вставку `Обсада дер`.
Мне кажется, с сохранением изделия всё в порядке. Если написать нелепицу во вставке - спецификация не рассчитается. В консоль браузера сообщения об ошибках выводятся. Понять, что именно не так - не сложно.
Для целей отладки, просьба кроме ссылки на заказ, указывать номер изделия и проблемную вставку - так Игорю будет проще понять, где ошибка.

**Comment by aribaz** [comment]
Спасибо, работает.
Закрываю
