### ISSUE TITLE
Уплотнитель

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#180]
По умолчанию стоит в изделии уплотнитель цвета "Светлый дуб", но когда я его пытаюсь менять на другой вариант (белый, бежевый, коричневый), то динамический поиск не срабатывает. Я пишу название и ничего не происходит, поле потом остается пустым и из спецификации исчезает уплотнитель (хотя если поле Цвет уплотнителя <> Пусто, то он там есть), а если воспользоваться кнопкой "Показать все" и выбрать этот цвет, то название цвета не исчезает и цвет уплотнителя отображается и в спецификации.

Если менять цвет уплотнителя через "Показать все", то все работает хорошо.

Если менять цвет уплотнителя с помощью динамического поиска (ввожу руками нужный цвет в поле), то в табчасти  строки заказа исчезают размеры блока, его площадь, система и цвет изделия, и сохранить блок становится невозможным, так как система выдает ошибку.

![2016-12-15](https://cloud.githubusercontent.com/assets/22028048/21225166/b6fb0ae4-c2e0-11e6-8761-ccfdc2823fc5.PNG)

И если систему и цвет я могу указать снова, то поля с размерами недоступны для изменения. И при попытке опять сохранить изделие выдает такое же сообщение. Не удается так же закрыть изделие без сохранения, оно просто не сохраняется, при том, что до того, как изменять уплотнитель я сначала сохранила изделие и потом вновь открыла и только тогда меняла цвет уплотнителя. Приходится страничку перезагружать, потому что никак иначе из  этого окна не выйти, но тогда в заказе это изделие не сохраняется совсем, как будто его не было.
[Заказ](https://light.oknosoft.ru/#obj=doc.calc_order&ref=fbc78bc1-f713-474f-e1f6-b38d9d0e6315&frm=doc&view=orders)
Эта строчка, с которой я это делала отсутствует в этом заказе, потому как не сохранилась.

**Comment by Oparin-Igor** [comment]
https://light.oknosoft.ru/#obj=cat.characteristics&ref=6a384aba-9568-4103-a7eb-03592c320c7c&frm=builder&view=orders

**Comment by unpete** [comment]
Просьба более четко повторить шаги для воспроизведения проблемы:
1. открываем страницу в браузере
2. открываем заказ №...
3. делаем раз
4. делаем два
3. ...

**Comment by unpete** [comment]
Подключил связи параметров на стороне браузера #177

**Comment by aribaz** [comment]
Работает, спасибо.
Закрываю.
