### ISSUE TITLE
Профиль покрытия (вставка 1397)

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#181]
Игорь, а разве профиль покрытия было решено добавлять не путем вставки к элементу?

Ведь, как я писала ранее:

> Исходя из вновь выявленных обстоятельств (см. параметр Положение профиля покрытия) - этот профиль покрытия теперь стали ставить не только на низ створки (как изначально мной оговаривалось), но и на горизонтальные импосты (глухую часть), на низ глухих окон, на глухую часть окна (глухарь со створкой), а так же на горбыльки. Так как это сказывается на цене, то некоторые просят поставить только на низ створки, а кто-то еще и в глухие части, кто-то на все горизонтальные поверхности. То есть вопрос куда ставить, а куда нет - решает сам заказчик.

Сейчас в табчасти есть есть строка Профиль покрытия и возможность поставить в ней галочку, но наличие галочки на спецификации никак не сказывается.
И если все же добавляем профиль в строке, а не вставкой, тогда должны быть какие-то ведомые параметры, которые скажут куда его надо поставить, а куда нет (чтобы это правильно отразить в спецификации).

**Comment by Oparin-Igor** [comment]
Профиль покрытия створок описан в соединении с элементом Дер. СтворкаНиз 79

**Comment by aribaz** [comment]
Может я что-то не понимаю, может у меня что-то не отображается, может мы с вами недопонимаем друг друга, но я его не нашла.

С этим профилем в спецификацию попадает Профиль водоотводный 22/34, а 22/34 - это обязательный профиль, но это НЕ Профиль покрытия оконных створок (см. #117 от 19.09.16)

У нас ДВА РАЗНЫХ профиля, выполняющих функцию водоотвода:

- Профиль водоотводный 22/34 (обязательный, он есть в спецификации; отвод воды от низа рамы, чтобы не заливалась вода внутрь соединения рамы со створкой по низу)
- Профиль покрытия оконных створок (желание заказчика, его нет даже в справочнике Номенклатуры; отвод воды от профиля на который его поставили, защищает только снаружи).

Вот что у меня в спецификации при выборе СтворкаНиз79 с водоотводом:
![2016-12-20_07-57-22](https://cloud.githubusercontent.com/assets/22028048/21339802/fb2e8348-c692-11e6-996a-d876f44f063f.png)
![2016-12-20_07-58-51](https://cloud.githubusercontent.com/assets/22028048/21339805/05805682-c693-11e6-9596-e8b81b1cf81f.png)

Вот что у меня в спецификации при выборе СтворкаНиз79:
![2016-12-20_09-04-21](https://cloud.githubusercontent.com/assets/22028048/21339878/a5741e62-c693-11e6-8590-d53bcf7d4c8b.png)
![2016-12-20_09-04-57](https://cloud.githubusercontent.com/assets/22028048/21339882/ab58d48a-c693-11e6-9686-bf82e0caad02.png)
Если Профиль покрытия Створок=да, то спецификация такая:
![2016-12-20_09-08-10](https://cloud.githubusercontent.com/assets/22028048/21339930/fdf354e0-c693-11e6-8e60-d0c35dae8cd7.png)

То есть добавился Водоотводный профиль, а не Профиль покрытия оконных створок. Водоотводный 22/34 присутствовать должен всегда, а ПРОФИЛЬ ПОКРЫТИЯ так и не появился.

А должно было стать так :

1. Створканиз79
2. Дер. Профиль водоотводный 22/34 (это обязательно)
3. Дер. Торцевая накл. к проф. водоотв. прав.
4. Дер. Торцевая накл. к проф. водоотв. лев.
5. **Профиль покрытия оконных створок (арт. FP-18.01), м.пог. (это желание заказчика)
6. Накладка торц. на профиль FP-18, лев (коричневая или белая), шт
7. Накладка торц. на профиль FP-18, прав (коричневая или белая), шт
8. Держатель защелкивающийся 1шт на 150мм профиля (он нужен чтобы закрепить профиль покрытия оконных створок на Створке низ79)
9. Саморез 3х16 1шт на 150мм профиля (он нужен чтобы прикрутить держатель к профилю створка Низ79)**
10. Наполнитель швов
11. Отвердитель 303
12. Клейберит
13. Грунтовка и окраска
14. Уплотнитель 3053
15. Уплотнитель 3070

Позиции необходимые при профиле покрытия оконных створок (5-9) не попали в спецификацию.

Вылетает ЛКМ и уплотнитель при выборе Профиль покрытия створок=да, нет; я сказала Евгению об этом, он обещал поправить.

Ну и остается открытым вопрос о том, что профиль покрытия начали ставить не только на СтворкаНиз79 и СтворкаНиз79 с водоотводом, но и на:

- ДвНиз_в/о_113/109 ств
- ДвНиз_в/о_120/116 ств
- РамнаяЗакладка 79
- ИмпостКомби_83/79 
- ИмпостКомби_93/89
- Горбылек_83/76
- Горбылек_63/56
- Горбылек_113/105
- Глухарь_63/59
- Глухарь_83/79
- РамаГлух 83

Место установки - тоже желание заказчика, можно поставить только на один из них, можно на некоторые, можно на все. Главное чтобы профиль на который будут ставить Профиль покрытия был установлен не вертикально.

Еще должен быть цвет Заказной, с которым будет в спецификацию попадать Окраска профиля и Предварительная напиловка профиля (цвет: без покрытия)

[Заказ 40](https://light.oknosoft.ru/#obj=doc.calc_order&ref=7a1278f0-cf9e-497f-b3af-5e8475c2932d&frm=doc&view=orders)

**Comment by aribaz** [comment]
@Oparin-Igor 
Стало видно профиль покрытия оконных створок в спецификации при выборе  в качестве профиля створка низ СтворкаНиз79 и прамаетра Профиль покрытия =да
![2016-12-27_09-18-19](https://cloud.githubusercontent.com/assets/22028048/21492405/7ad3db02-cc15-11e6-807b-75d0724eeea1.png)

Только держатель с саморезом не попали в спецификацию.

А как быть с тем, что он может быть не только на створке низ?

**Comment by aribaz** [comment]
@Oparin-Igor 
Игорь, добрый день.
Была в конце прошлой неделе на фабрике. Общими усилиями пришли к тому, что профиль покрытия оконных створок устанавливается на все горизонтальные поверхности. Ушла возможность выбрать на какие именно, как я писала ранее.
Т.е. если выбираем параметр Профиля покрытия - Да, то в спецификацию он должен попасть со всеми горизонтальными профилями (горбыльки, импосты, закладки, створка низ).

**Comment by aribaz** [comment]
@unpete 
При добавлении к элементу профиля вставки, количество штук. добавляется не правильно. 
Метод расчета во вставке  профиль по периметру, заглушки для элемента. 
Добавлена к вставке профиль метод расчета по периметру.

При добавлении ном.Монтаж с. Единицей изм ед. Вид расчета к элементу В строку вставки контур.
При нажатии кнопки сохранить, не закрывается окно. Не сохраняется не добавляется в спецификацию  доп. Продукции.

**Comment by unpete** [comment]
> количество штук. добавляется не правильно

Какой именно вставки, в каком изделии, сколько ожидаете, сколько получаете, какая задействована формула?
Мы договаривались, что вопросы должны содержать внятные указания по воспроизведению проблемы.

**Comment by aribaz** [comment]
@unpete Евгений, извините, вопрос бегло создала, чтобы не забыть на основании замечаний Игоря.

Вставка в элемент Профиль покрытия оконных створок.
Сначала она была описана в соединениях и для этого профиля был создан параметр Профиль покрытия, при выборе варианта этого параметра Да, в спецификацию вместе с профилем Створка Низ попадал сам профиль и две торцевушки.
Ввиду вновь открывшихся обстоятельств, а именно, если и ставим профиль покрытия, то на всех горизонтальных (окологоризонтальных) профилях (створка низ, импост, закладки) он необходим. Другими словами он необходим будет в нижней части каждого стеклопакета. Сначала Игорь решил вопрос описанием соединений, но оказалось, что если в двери например закладок стоит несколько одна на другой - то и профилей считается на каждую, а надо одну палку.
Поэтому переделал его как вставку в элемент.
Теперь, чтобы добавить профиль открытия оконных створок в изделие, надо добавить вставку в элемент (где он необходим). По количеству я отклонений не увидела, ставлю одну вставку, считает профиль 1шт., но вот размер палки 0,0018/0,0013 неправильный, [(см. окно 2)](https://light.oknosoft.ru/#obj=cat.characteristics&ref=8889099b-23d3-4d32-ab10-16abfe11407f&frm=builder&view=orders)
Во вставке описано: 
Кол-во - 1
Размер - 0
Коэффициент - 0,001
Формула - пусто
Условие:
параметр "Профиль покрытия" Равно "Да"
По идее размер профиля должен считаться как размер самого профиля (куда делаем вставку) - 2*ширина профиля, с которым он соединяется (угловое)
Условно, например я ставлю его на профиль Створка низ 79, сама по себе створка низ 79 соединяется угловым соединением с профилем створка 79 (с обеих сторон), тогда размер профиля покрытия оконных створок будет равен= Длина ств.низ79 - 2*Ширина ств.79.

С другой стороны, если не использовать вставки в элемент, а просто воспользоваться параметром в табчасти Профиль покрытия, тогда ошибка по количеству этих палок идет. На одно окно с двумя стеклопакетами  - 4 профиля[ (см. изделие 3)](https://light.oknosoft.ru/#obj=cat.characteristics&ref=f5361f47-98cf-4863-d6a3-2064f342b405&frm=builder&view=orders), хотя в этом случае максимум два. Но мне кажется здесь просто сплелись обе вставки как-то и раз перешли на вставку к элементу, то использовать параметр в табчасти уже не правильно.
Вставка Профиль покрытия имеет параметр "Профиль покрытия": да, нет. Помимо этого такой же одноименный параметр есть и в табчасти. Может теперь этот параметр лишний и там и там? Ведь если я хочу добавить этот профиль, я просто добавляю вставку, если не хочу, то не добавляю.
Сейчас же профиль покрытия при уже добавленной вставке к элементу попадет только если в табчасти параметр Профиль покрытия установлю Да, несмотря на то, что я добавила вроде как самостоятельную вставку и внутри ее параметров этому же параметру присвоила Да.

По монтажу вынесу в отдельный вопрос.

**Comment by aribaz** [comment]
@Oparin-Igor 
Игорь, а если профиль покрытия привязать к соединению стеклопакета с нижним профилем (створки, импоста, горбылька, раскладки). Я разговаривала с Сергеем он сказал, что пусть лучше одной кнопкой (в параметрах) учитывется везде профиль даже пусть будет немного лишнего (на закладках), чем тыкать в каждый низ стеклопакета. По деньгам он понимает, что в таком случае будет чуть дороже, чем должно, но это только на дверях, а скорость обработки заказа увеличится и меньше шансов его где-то пропустить будет (для изделия с большим количеством створок и горбыльков.

**Comment by aribaz** [comment]
@unpete 
У меня вот какой вопрос возник.
Можно ли наличие этого способа учитывать двумя способами?
1. посредством вставки в элемент (тогда нужно в каждый профиль ткнуть в каждом заказе и вставить вставку) - тогда будет учтена возможность ставить этот профиль только на нужные деревянные профили
2.посредством параметра изделия (да/нет) - и привязать этот параметр к соединению стеклопакета с нижним деревянным профилем и параметром = да, тогда внутри одного изделия по низу каждого стеклопакета будет считаться этот профиль. (это удобно, когда в изделии >1стеклопакета и под каждый нужен профиль, по времени получится быстрее, чем первым способом).

Второй вариант ввобще имеет право на существование?
И в зависимости от желаний заказчика можно будет учесть одно или другое

**Comment by unpete** [comment]
> Можно ли наличие этого дополнения учитывать двумя способами программно

Конечно, можно. Обычные вставки должны учитывать параметр.
Если параметр=нет, можно добавить вставку в элемент.
Если параметр=да и указана вставка в элемент, в спецификации будут лишние строки.

**Comment by aribaz** [comment]
@unpete 
Евгений, посмотрите пожалуйста вставку  1397.
В спецификацию попадает странное количество.

По идее в спецификацию должен попадать сам профиль длиной равной длине створки и по одной накладке (что и описано во вставке), и тем не менее спецификация рассчитывается не верно.

![2017-02-27_09-23-08](https://cloud.githubusercontent.com/assets/22028048/23350838/6985ecde-fcce-11e6-8ba0-d84eafe62f15.png)

Это то что попало:
![2017-02-27_09-24-04](https://cloud.githubusercontent.com/assets/22028048/23350862/8d1c111e-fcce-11e6-8e3d-89bd2790f67b.png)

Игорь с этим вопросом адресовал к вам.

Вот это [окно](https://light.oknosoft.ru/?zone=2#obj=cat.characteristics&ref=c5927e4b-b7b6-4e22-b83d-b48a91f68deb&frm=builder&view=orders)

Более того, после того, как я при вас удалила параметр Профиль покрытия из табчасти, то при добавлении  этого профиля посредством вставки в элемент, профиль в спецификацию не попадает совсем почему-то, хотя во вставке нет привязки к параметру этого профиля.

**Comment by unpete** [comment]
Мне кажется, задача дублирует #264

**Comment by Oparin-Igor** [comment]
Вставка удалена.
Профиль покрытия считается в соединениях профиля и стеклопакета.
