### ISSUE TITLE
Наименования характеристик с дополнительными реквизитами

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#183]

**Comment by unpete** [comment]
Значения допреквизитов теперь подмешиваются в наименования характеристик

**Comment by aribaz** [comment]
В брусе все работает, а МДФ - нет. При сохранении в название ничего не подставляется, могу сама руками вписать что угодно, но после того как сохраню в строке с этой характеристикой  в названии "<>",  а при открытии пусто, будто я ничего и не писала.

Со шпоном тоже все заработало, только один нюанс:
у нас шпон может быть 0,5мм и 0,7 мм - стоит разных денег, а при записи характиристики с толщиной менее 1, округляет до 1, получается у меня две характеристики будут называться "1..." а как тогда понять какую из них надо использовать например при оприходовании материала.

**Comment by aribaz** [comment]
@unpete И еще вопрос, по характеристике Материал сырья. 
У нас есть сырье - оно всегда покупное (так как лес сами не заготавливаем, плиты МДФ не делаем, шпон с кругляка не снимаем), а есть полуфабрикаты их делают из сырья (можем сами делать, а можем купить готовые).

Доска, МДФ, Шпон - это сырье, а брус, щит - это полуфабрикат.

Сырье само по себе не имеет никакой сростки, склейки -то есть всегда имеет просто породу, из которой его получили; а чтобы получить полуфабрикаты - надо сырье напилить/нарезать, склеить (нашими силами или продавца- это не важно), и только полуфабрикаты  могут в характеристиках иметь тип сростки/склейки.

У нас сейчас есть 6 видов материала сырья с привязкой не только к породе но и сростке.
Доска и шпон - могут быть только породой без типа сростки, какой материал сырья им присваивать  в характеристиках, чтобы это потом правильно цеплялось.
Создать еще три материала: сосна, лиственница, дуб - дополнительно;
Или использовать вместо них Сосна цельно-ламельная, лиственница цельно-ламельная, дуб цельно-ламельный - что в целом верно.
Но у лесовиков сломается мировоззрение, когда они такое увидят в заявке, потому что доска не может быть сращенной - это уже брус/брусок или щит, а не доска (сырье); а доска априори цельная, сделанная из какой-то породы дерева. Равно как и Шпон не может быть сращенным или цельным, он просто шпон из какой-то породы.
Что посоветуете?

**Comment by unpete** [comment]
> В брусе все работает, а МДФ - нет

Была ошибка: толщина попадала в наименование только если указаны ширина и или высота - исправил

> шпон может быть 0,5мм и 0,7 мм

Для малых размеров добавлен разряд в дробной части

> Но у лесовиков сломается мировоззрение

Текст в печатной форме редко совпадает с наименованием в базе. Документы для поставщиков печатают в терминах номенклатуры поставщика

> Создать еще три материала

Это было бы ошибкой. Лучше использовать параметры для цельноламельных.
С позиций нормализации данных, правильнее было бы разбить параметры сырья на собственно материал и тип сростки, но это усложнило бы работу пользователя.

**Comment by aribaz** [comment]
Спасибо, работает.

Усложнять жизнь им не будем, а то дров наломают, я лучше сделаю привязку к цельно-ламельному.
Закрываю.
