### ISSUE TITLE
Вопросы по построителю (demo)

### ISSUE THREAD

**Issue by blackmixer** [oknosoft/windowbuilder#184]
1. как уравнять Раскладку в 2х створчатом окне с одной створкой в горизонтальной плоскости 
2. как вносятся изменения в технологически ограничения

**Comment by unpete** [comment]
> как уравнять Раскладку в 2х створчатом окне с одной створкой в горизонтальной плоскости

- Выделить область, чтобы в неё попали нужные элементы
- Выполнить команду `уравнять вверх` или `уравнять вниз`

Полезно почитать про [объектную модель рисовалки](https://github.com/oknosoft/windowbuilder/wiki/%D0%A1%D1%82%D1%80%D1%83%D0%BA%D1%82%D1%83%D1%80%D0%B0) и [подключаемые инструменты](https://github.com/oknosoft/windowbuilder/tree/master/src/tools)
Пользователи могут самостоятельно добавлять в графический редактор необходимые `инструменты` - например, для выравнивания раскладок.
Палитра типовых инструментов будет пополняться в ходе внедрений у новых клиентов.
Если есть предложения о критически важных инструментах - готов обсудить.
Для включения в типовую палитру, инструмент должен быть достаточно абстрактным и решать задачу в общем виде, а не единственную редкую операцию.

> как вносятся изменения в технологически ограничения

Если вопрос именно про **ограничения**, они настраиваются в спецификациях соединений, вставок и фурнитуры в общем списке материалов, но тип строки спецификации для них не `материал`, а `информация об ошибке`. Эти строки могут иметь визуализацию и подсвечиваться на эскизе, могут генерировать текстовые сообщения. Могут блокировать запись изделия или просто информировать менеджера о проблемах.
В настоящий момент, рабочее место технолога есть только в 1С.
Есть фоновая задача повторить формы редакторов технологических справочников на стороне браузера, но приоритет у этой задачи низкий

**Comment by blackmixer** [comment]
1. Есть ли Инструмент выравнивание Заполнений по геометрии или световому проёму (как в программе  Суперокна) ???
2. При построении арки как Указать нужный радиус или высоту дуги ???

**Comment by unpete** [comment]
> Инструмент выравнивание Заполнений по геометрии

Он тривиален, Код есть в рисовалке прошлого поколения для УПзП. В стандартные инструменты `Заказа дилера` такое выравнивание не включено. Есть идеи по более продвинутому инструменту.

> При построении арки как Указать нужный радиус или высоту дуги

Дуга с радиусом 1/2 размера строится автоматически (клик с пробелом или ctrl + пробел).
Еще, запланирован инструмент `таблица координат`, с помощью которого можно построить сегмент профиля по формуле или через N точек. Кривые по радиусу - частный случай использования этого инструмента.
