### ISSUE TITLE
Редактор составных пакетов

### ISSUE THREAD

**Issue by unpete** [oknosoft/windowbuilder#185]
- [x] Экранная форма редактора
- [x] Алгоритм формирования спецификации

**Comment by unpete** [comment]
Добавил редактор составных пакетов - вызывается той же кнопкой, что и допвставки в элемент:
![image](https://cloud.githubusercontent.com/assets/12096477/23330351/9a07d460-fb6d-11e6-836b-789ff332efd5.png)
- Ограничений на состав пакета нет - можно добавлять любые плёнки, рамки, стёкла и т.д. в любом порядке и количестве
- Текст формулы - это просто сумма имён вставок
- Кроме вставок с типом _Заполнение_, можно добавлять вставки в _Элемент_. Например, нанесение рисунка, обработку фацета, закаливание - любые материалы и работы, которые хотите учесть в спецификации нестандартного пакета

**Comment by aribaz** [comment]
Это здорово в целом, только я наверное какой-то пункт пропускаю.

У вас на рисунке изображены вставки, которые числятся в справочнике Вставки/Стеклопакет.
Но когда я выделяю стеклопакет на эскизе, нажимаю на кнопку Вставка (подчеркнутую у вас красным), то мне предлагается список из справочника Вставки/Заполнения. Пробовала предварительно изменить стеклопакет в табчасти на Составной заказной 40мм, но эффект тот же.
Может я какой-то важный шаг пропустила?

**Comment by unpete** [comment]
В прошлом месяце мы отказались от использования вставок с типами _Стеклопакет_ и _Типовой стеклопакет_. Про это была публичная информация, но где именно - не помню.Любые вставки в заполнение должны иметь тип _Заполнение_

**Comment by aribaz** [comment]
закрываю, я поправила тип вставок.
