### ISSUE TITLE
ЛКМ и Уплотнитель

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#186]
@unpete Евгений, у меня из спецификации исчезли ЛКМ и Уплотнитель, и соответсвенно они не учитываются в цене.

**Comment by unpete** [comment]
> из спецификации исчезли ЛКМ и Уплотнитель

Из спецификации какого изделия?

**Comment by aribaz** [comment]
Любого вновь создаваемого. 

Работы по окраске есть, а самих ЛКМ нет.

Раньше к каждому элементу (профилю) были строчки с ЛКМ, а теперь только работы во всех изделиях.

![2016-12-26_15-37-48](https://cloud.githubusercontent.com/assets/22028048/21482153/5917b7fc-cb81-11e6-9540-f42bede1bb20.png)

С уплотнителем я не понимаю как он попадает по факту, в теории должен с соединениями, но на практике в изделии [1](https://light.oknosoft.ru/#obj=doc.calc_order&ref=7feb6b74-dd9f-451a-ee3e-eb7355d1853d&frm=doc&view=orders) - есть, а в изделиях [2](https://light.oknosoft.ru/#obj=doc.calc_order&ref=7feb6b74-dd9f-451a-ee3e-eb7355d1853d&frm=doc&view=orders), [3](https://light.oknosoft.ru/#obj=doc.calc_order&ref=7feb6b74-dd9f-451a-ee3e-eb7355d1853d&frm=doc&view=orders), [4](https://light.oknosoft.ru/#obj=cat.characteristics&ref=330f45ae-52bc-440a-8da9-774acf34de91&frm=builder&view=orders) - почему-то нет.

 [Заказ 44](https://light.oknosoft.ru/#obj=doc.calc_order&ref=7feb6b74-dd9f-451a-ee3e-eb7355d1853d&frm=doc&view=orders)

Заказ 44 я создавала вчера с нуля.

**Comment by aribaz** [comment]
@unpete Евгений, а можно нам из списка всех вопросов с пометкой срочно этот вопрос считать приоритетным.

**Comment by unpete** [comment]
- Исправил алгоритм сравнения вычисляемых параметров
- Для вложенных вставок, теперь учитываются количества и коэффициенты родительских вставок
- Изменил формулу `totqty=1` - теперь она присваивает в `qty` и `totqty` не тупую единицу, а число, указанное в строке спецификации вставки с учетом родительских вставок

**Comment by unpete** [comment]
По уплотнителям, наверное, можно Игоря спросить.

**Comment by aribaz** [comment]
Евгений, спасибо ЛКМ появились.

**Comment by aribaz** [comment]
Я нашла способ при котором уплотнитель попадает в спецификацию. Надо в табчасти строки заказа перевыбрать Цвет уплотнения, тогда все хорошо.

Только я заметила ошибку, хотя раньше я ее не было.
Уплотнитель по идее должен был попасть с каждым профилем створки (точнее с соединением наложения профиля створки с профилем рамы/импоста)  - 4 отрезка, а по факту сейчас попадает 3. Попадает пара горизонтальных (верх/низ) и один из вертикальных, а раньше было и сейчас должно быть **два**.  
Даже для простого одностворчатого окна - где две боковушки рамы одинаковы и боковушки створки тоже одинаковы -с одним попадает, а с другим нет (хотя по идее соединение то для них одно).
@Oparin-Igor Игорь, подскажите как это исправить?

**Comment by aribaz** [comment]
![default](https://cloud.githubusercontent.com/assets/22028048/21922942/5e78531e-d982-11e6-8dd9-d67480757738.PNG)
Как-то так выглядит для одностворчатого окна. где бока  одинаковы.

**Comment by Oparin-Igor** [comment]
не работает выбор по диапазону угла, в соединениях.
если указать "угол мин"-"90", "угол мах"- "90". все работает.
если указать  "угол мин"-"46", "угол мах"- "134". не работает.

**Comment by unpete** [comment]
> выбор по диапазону угла, в соединениях

Есть гипотеза, что виновата цифра 326. Если указать вместо неё во всех строках 236, появляются все 4 уплотнителя
![image](https://cloud.githubusercontent.com/assets/12096477/21946398/1dec04b4-da02-11e6-8478-a560f1b70308.png)

Если вместо перечислимого типа в параметре `Цвет уплотнителя` использовать тип `Цвет`, спецификацию в примыкающем соединении можно сократить в 4 раза - сейчас там продублированы строки для `белого`, `коричневого`, `бежевого` и `светлого дуба` цветов.

**Comment by aribaz** [comment]
У меня все работает в целом.
А можно как-то сделать так, чтобы не пришлось перевыбирать цвет уплотнителя, чтобы он появлялся в спецификации всегда?
Если цвет нужен другой, то понятно, что выберут нужный и все будет хорошо;, а если нужен тот, который уже указан по умолчанию? Могут и забыть перевыбрать. ведь.

**Comment by unpete** [comment]
Параметр `Цвет уплотнителя` ничем не отличается от всех остальных параметров.
Если он задан в шаблоне, ничего _перевыбирать_ не  требуется.
Если я ошибаюсь - приведите сценарий воспроизведения проблемы.
Напомню, сценарии всегда начинаются с чистого листа - запуска браузера.

**Comment by aribaz** [comment]
Я нашла причину. 
Когда мы создаем изделие, то в списке параметров нет Цвета уплотнителя и если сразу в таком виде открыть спецификацию - то нет уплотнителя и в спецификации.
Если после создания изделия нажать на кнопку Обновить параметры, то параметр Цвет уплотнителя появляется в списке параметров и сам уплотнитель тоже появляется в спецификации, при том не обязательно что-то перевыбирать.
Спасибо, закрываю.
Обновить сначала это у меня уже автоматом, надо и не надо )
