### ISSUE TITLE
Количество изделий

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#187]
@unpete Евгений, На шаблоне Окно трехстворчатое не могу указать необходимое количество этих блоков, точнее могу, но Сумма поставщика остается как будто там одно изделие, а не больше.
[Заказ 44, изделие 2](https://light.oknosoft.ru/#obj=doc.calc_order&ref=7feb6b74-dd9f-451a-ee3e-eb7355d1853d&frm=doc&view=orders)

**Comment by unpete** [comment]
Проблема была в эскизе - присутствовала паразитная створка с нулевыми размерами.
Из-за этого, изделие не могло записаться и не происходил пересчет сумм.
Удалил паразитную створку - пересчет заработал.

**Comment by aribaz** [comment]
Работает, закрываю
