### ISSUE TITLE
Вставки в изделие

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#188]
Не могу проверить что попадает с ними в спецификацию, так как они не сохраняются в изделии.

**Comment by unpete** [comment]
> не сохраняются в изделии

Важно помнить, что изделие может не записываться по единственной причине: ошибки в табчасти спецификации технологического справочника - `фурнитура`, `соединение` или `вставка`.
Порядок решения проблемы:
- Выяснить, какая именно вставка вызывает ошибку при записи
- Исправить проблемные строки в табчасти спецификации вставки

Текущая задача зарегистрирована некорректно - отсутствует сценарий для воспроизведения проблемы

**Comment by aribaz** [comment]
Последовательное добавление вставок с промежуточным сохранением изделя.
Окосячка снаружи- сохранилась
Окосячка изнутри - сохранилась
Доборы внутренние - сохранились
Доборы наружние - сохранились

**Обсада чистовая дер - не сохранилась.**
У нее 2 параметра, их заполнила, но Кнопка сохранить и закрыть не срабатывает, могу только закрыть без сохранения и тогда закрывается, но обсада в списке не появляется,в отличие от предыдущих вставок.
**Обсада черновая дер - не сохранилась.**
У нее 2 параметра, их заполнила, но Кнопка сохранить и закрыть не срабатывает, могу только закрыть без сохранения и тогда закрывается, но обсада в списке не появляется.
**Монтаж дер. - не сохранился.**
У него нет параметров, но Кнопка сохранить и закрыть не срабатывает, могу только закрыть без сохранения и тогда закрывается, но монтаж в списке не появляется.

Если в изделие сразу (без предварительного сохранения изделия без вставок) добавляю одну из этих трех не сохраняющихся вставок, то само изделие тоже не сохраняется и не попадает в заказ; если только перед добавлением вставок не сохранить его.

Но если к новому изделию добавить сначала вставку в контур, а потом вставку к изделию и сохранить (именно в этой последовательности), то вставка в контур сохраняется сама по себе, а само изделие к которому вставка в контур предназначена и вставка в изделие  - нет. Но это справедливо только для подоконников и отливов, москитка не сохраняется.

Заказ [45](https://light.oknosoft.ru/#obj=doc.calc_order&ref=518b4d96-0a00-49f8-85b2-b3035413fedb&frm=doc&view=orders) - в нем Подоконник добавлен ко второму окну, которое не сохранилось; а отлив к третьему - оно тоже не сохранилось.

**Comment by aribaz** [comment]
Случайно закрыла

**Comment by unpete** [comment]
**Обсада чистовая дер** - были строки с пустым _методом расчета количества_
**Обсада черновая дер** - метод расчета _по периметру_ не реализован в объекте _Изделие_ - надо реализовать
**Монтаж дер.** - метод расчета _по периметру_ не реализован в объекте _Изделие_ - надо реализовать

**Comment by aribaz** [comment]
Чистовая теперь сохраняется.

Черновая и Монтаж не сохраняются, я так понимаю что пока не будет реализована формула, сохраняться она не будет.

**Comment by unpete** [comment]
Добавил поддержку метода расчета количества _по периметру_ для вставок в изделие и контур.
Важно: поле _метод расчета_ в строках спецификации оставлять пустым нельзя
Расчет сегментов периметра для изделий с несколькими контурами не закончен - это отдельная задача.

**Comment by aribaz** [comment]
Заработали, закрываю.
