### ISSUE TITLE
Материалы для цеха эксклюзива

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#189]
@unpete Евгений, подскажите, как лучше сделать.

У нас есть второй цех, и материалы. которые использует только и к окнам они не имеют совсем никакого отношения.
 Можно создать для них в справочнике Номенклатуры Группу Эксклюзив и все материалы, относящиеся к цеху эксклюзива и только к нему завести в нее?
Мне самой так проще будет.

**Comment by unpete** [comment]
> создать в справочнике _Номенклатуры_ группу _Эксклюзив_

Можно. Если эти материалы нужны в сервисе, создавать следует в _Заказе дилера_. Если эти позиции заказывают другим маршрутом, можно создать только в _1С КА_

**Comment by nmivan** [comment]
@aribaz , ответ на вопрос вроде получен? Закрываем?
