### ISSUE TITLE
Привязка оторванных профилей

### ISSUE THREAD

**Issue by unpete** [oknosoft/windowbuilder#19]
В некоторых случаях, узлы импостов и рам отказываются цепляться к другим сегментам после того, как были оторваны

**Comment by Oparin-Igor** [comment]
Очень сложно, изменить размеры потперемещать эдементыянув за элемент, узел, неоходимо рассмотреть механизм,
Который позволял бы перемещать либо по вертикали или по горизонтали, при необходимости его разблокировать.

**Comment by Oparin-Igor** [comment]
Пакеты (заполнения) не перемещать.

**Comment by unpete** [comment]
Горизонталь, вертикаль, наклон и т.д, давно реализованы. Запланирована куча
реально мощных инструментов. Подключать буду по мере готовности.
09.03.2016 19:01 пользователь "Igor" <notifications@github.com> написал:

**Comment by unpete** [comment]
- Реализовал дополнительные проверки, когда импост утыкается в угловое соединение
- Реализовал _elongate_ удлинение сегмента заполнения на очень тупых углах, для устранения ошибки _пересечение не найдено_
