### ISSUE TITLE
Размер створки

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#191]
@Oparin-Igor 
Я как-то давно пробовала  чертить окна разных конструкций, сейчас их хочу собрать в один заказ.
И случайно обнаружила вот что.

Окно делится вертикальным **симметричным импостом** на две равные части, следовательно створки должны быть тоже равны между собой, но получается разница в милиметр на чертеже, после выноски размерных линий по створкам, допускаю что не попала в точку, хотя они вроде магнитные.

Но в табчасти этого изделия размеры створок разные почему-то не только по ширине, но и по высоте и не совпадает одна из них с чертежом. И соответственно в спецификации тоже.
![2016-12-27_15-46-36](https://cloud.githubusercontent.com/assets/22028048/21500035/f42de5a2-cc4b-11e6-9ddb-63edea5f95bc.png)

Вот [окно](https://light.oknosoft.ru/#obj=cat.characteristics&ref=54b33141-bce0-4590-88bb-3aeac61784e8&frm=builder&view=orders) 
Заказ [47](https://light.oknosoft.ru/#obj=doc.calc_order&ref=d5a92110-48eb-4177-da5e-9b8968e76e62&frm=doc&view=orders)

**Comment by Oparin-Igor** [comment]
Типичное поведение построителя.

**Comment by aribaz** [comment]
А как-то это можно исправить? Ведь это не правильно, створки-то должны быть одинаковыми.

**Comment by Oparin-Igor** [comment]
- Нарисовать раму
- Выровнять размеры, углы
- Нарисовать импоста
- Проверить размеры.
- Нарисовать створки.
Если выравнивать размеры после установки створок, то ничего не получиться.

**Comment by aribaz** [comment]
Спасибо, все получилось. 
Закрываю.
