### ISSUE TITLE
Роли

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#192]
Вы обещали прислать письмо по Ролям. Это я на всякий случай, чтобы не забыли.

**Comment by unpete** [comment]
- Создать пользователя 1С Заказ дилера  (Администрирование – Настройки пользователей и прав – Пользователи)
- Доступ к 1С и пароль в карточке пользователя можно не задавать, т.к. пользователь будет авторизовываться в сервисе, а не 1С-кой
- Включить пользователя в нужные группы доступа (закладка Права доступа карточки пользователя)
- На закладке _Объекты доступа RLS_ карточки пользователя указать индивидуальный префикс докуменнтов и перечислить в табчасти контрагентов и организации, к которым у пользователя должен быть доступ.
Можно указывать папки – посмотрите настройки своего пользователя nata.aribaz – думаю, всё станет понятно
- Добавить пользователя в табчасть _Пользователи_ справочника _Абоненты_ (Интеграция – Абоненты – Арибаз)
- Указать для пользователя роли CouchDB – как у других пользователей – редактор открывается лупой в поле ввода
- Указать для пользователя пароль для авторизации в сервисе
- В обработке администрирования интеграции на закладке _Регистрация_ в правой табчасти выполнить команду _Заполнить по абоненту_, после чего, на той же закладке в левой табчасти выполнить команду _Настроить CouchDB_
На малых экранах, команды могут прятаться под кнопками _Ещё_. На больших экранах видны отдельные кнопки команд
- Если команда  _Настроить CouchDB_ отработала без ошибок, можно заходить в браузере под новым пользователем

**Comment by aribaz** [comment]
Получилось, спасибо!
Закрываю
