### ISSUE TITLE
Объявление

### ISSUE THREAD

**Issue by unpete** [oknosoft/windowbuilder#193]
С 12.01.2017 по 15.01.2017 запланированы работы по обновлению ядра _Заказ дилера_
- Обновление _CouchDB_ до v2.0.0
- Использование _ServiceWorkers_ для автономного режима
- Изменение алгоритма разделения доступа и репликации

Возможны перебои и ошибки в работе сервиса.
Просьба отнестись с пониманием и оперативно регистрировать в [issues](https://github.com/oknosoft/windowbuilder/issues/) выявленные проблемы

**Comment by aribaz** [comment]
Спасибо

**Comment by unpete** [comment]
Обновить ядро за выходные не успел - был занят другим проектом.
Работы по обновлению продолжатся до конца января.

**Comment by aribaz** [comment]
Поняла
