### ISSUE TITLE
Цвета

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#194]
@Oparin-Igor 
Игорь, подскажите.
Цвета RAL где создавать? В отдельной папке в справочнике Цвета или куда-то внутри уже существующих папок разместить (Дерево, Общие, например).
У нас всего 2 цвета по RAL - для алюминиевых профилей, которые мы можем купить в готовом виде, все остальные - это покраска поставщиком сырья, которая требует бОльшего времени и доп услуги (ее отражают в документах бухгалтерских).
А применительно к деревянным профилям - это готовая рецептура и на каждый индекс у поставщика она уже есть и ничего нам не добавляют (время, допуслуги), но для клиента вне зависимости от индекса RAL это какая-то одна установленная стоимость (по лаку).

И по цвету Заказной (применительно к алюминиевым профилям) надо ли вводить новый одноименный цвет или достаточно того, что в папке Дерево у меня есть "По образцу (глухой)"  и можно использовать его для обозначения какого-то специального цвета?

**Comment by Oparin-Igor** [comment]
Информацию по цвету RAL, для заказчика и подрядчика должна присутствовать в документах.
Поэтому весь ассортимент должен присутствовать в справочнике.
Лучше сделать отдельную папку.
В первом случае используете краску с цветом RAL....
Во втором покраска в цвет RAL....

**Comment by aribaz** [comment]
Спасибо.
Закрываю.

**Comment by aribaz** [comment]
На стороне браузера в справочнике Цвета я вижу папку Цвета по RAL но она пуста, а на стороне 1С ее не вижу, и я создала вчера папку RAL в справочнике Цвета до того как увидела в браузере папку Цвета по RAL.
Какую заполнять?

**Comment by Oparin-Igor** [comment]
А где создавали папку на стороне 1С или браузера?

**Comment by aribaz** [comment]
На стороне 1С, мною создана папка RAL

**Comment by aribaz** [comment]
На стороне 1С, я когда создавала не было папки Цвета по RAL,я поэтому и создала новую

**Comment by unpete** [comment]
Справочники следует редактировать в 1С. Тогда, изменения разбегаются по всем браузерам.
Пользователь с ролью `Технолог`, может редактировать справочники в браузере, но изменения останутся только на его компьютере и могут быть затёрты изменениям из 1С.

**Comment by aribaz** [comment]
Спасибо, тогда я продолжу заполнение на стороне 1С
