### ISSUE TITLE
ЛКМ в спецификации

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#195]
У меня неправильно ЛКМ некоторые попадают в спецификацию.

Изолянты и порозаполнитель правильно попадают, а вот основные (грунт и лак) нет.

Я даже не знаю как проверять.

С вновь занесенными цветами (RAL) в спецификацию никакие ЛКМ не попадают вне зависимости от типа материала древесины.

Цвет белый - он глухой и по идее с ним должны были попасть в спецификацию (без эффекта, сосна, стандарт):
Лак AQUATOP 2600-83 CLEAN WHITE (лак для белого без эффектов)
Грунт AQUA PRIMER 3130 WHITE (грунт стандарт для глухих)
А попали:
Лак AQUATOR 2600-24 SG BASE T Color (лак для прозрачных цветов без эффектов)
Грунт AQUA PRIMER 2900-02 COLOR (грунт эконом для прозрачных)

Для цветов: ясень, кедр, кемпас, венге,по образцу (прозрачные) (сосна, стандарт без эффектов) в спецификацию попал **только** грунт Грунт AQUA PRIMER 3130 WHITE (грунт стандарт для глухих), а должно было:
Грунт AQUA PRIMER 2907-02 BASE T ЦВЕТ (грунт стандарт для прозрачных) **и** 
AQUATOP 2600-24 SG BASE T ЦВЕТ (лак без эффектов для прозрачных).
Остальные прозрачные цвета не проверяла, но думаю что с ними так же.

А вот пропитка правильно прикрепляется (если поставить да) по типу покрытия.

Такое ощущение что просто перепутаны глухие и прозрачные цвета, и для прозрачных лак не подцеплен.

**Comment by Oparin-Igor** [comment]
Ранее была создана спецификация в экселе, затем говорилось что в ней была ошибка, я предложил её поправить и прислать.
Ждем...
В тексте я плохо ориентируюсь, в таблице картина яснее.

**Comment by aribaz** [comment]
Что-то с памятью моею стало )
[ЛКМ ТекносЦвета.xlsx](https://github.com/oknosoft/windowbuilder/files/708732/default.xlsx)
