### ISSUE TITLE
Цвет металлических элементов

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#196]
У меня такой вопрос назрел.
Я внесла все цвета RAL в справочник, теперь они доступны для выбора.

У нас есть металлические элементы и москитка, которые используют эти цвета. Но как я говорила ранее, из всего ассортимента цветов RAL купить мы можем готовое только:
RAL 8017 (Водоотводный профиль, профиль покрытия, капельник, МС)
RAL 9016 (Водоотводный профиль, профиль покрытия, капельник, МС и отлив)
RAL 8003 (отлив)
Все остальные цвета RAL - они Заказные, это значит что во-первых меняется цена,а во-вторых - сроки заказа становятся больше, потому как поставщик красит неокрашенные элементы в нужный нам цвет, а потом мы их забираем и в спецификации с ними должна появится строка Окраска элементов (условно)..
Хоть цвета RAL (кроме трех) никакого подбора рецептуры не требуют, но это все не готовая продукция, которую можно купить. С точки зрения цены не важно в какой конкретно цвет RAL красить, здесь важен сам факт необходимости покраски, а уж в какой цвет - это справочно.
Может для металлических элементов создать цвет Заказной? При выборе которого в спецификацию подтянется неокрашенный профиль и услуга по покраске.
Но тогда мне нужно поле, в котором надо указать в какой именно цвет красить - это для снабжения (зать сколько везти на покраску и сообщить поставщику необходимый цвет),, цеха (знать палку какого именно цвета поставить в изделие).
Или что вообще посоветуете?

**Comment by Oparin-Igor** [comment]
Профиль покрытия створок проверить расчет с разными цветами.
RAL 8017 
RAL 9016
Любой другой

**Comment by aribaz** [comment]
У меня список цветов для них ограничен и RAL-ов там нет сейчас совсем, я же могу изменить этот список в связях параметров?

Только у меня вопрос еще вот в чем, с цветами:
без характеристики
RAL 8017
RAL 9016 
не должна попадать окраска профиля. Так как это готовые цвета профилей, которые мы просто покупаем уже таких цветов.

А для всех остальных цветов RAL кроме (8017 и 9016) в спецификацию должен попасть профиль цвета Без характеристики и услуга Окраска профиля (м.пог,)

**Comment by Oparin-Igor** [comment]
Да.

**Comment by aribaz** [comment]
Для цветов RAL 8017, 9016 все правильно - за исключением цвета торцевых накладок.
Как я понимаю соответствие накладок тому или иному  цвету по RAL надо описать в Цвето-ценовых характеристиках?

Для цвета RAL 8003 - в спецификации появилась покраска профиля, только сам профиль в спецификацию попал белый, а должен был "Без характеристик" , т.е. неокрашенный или у нас он еще называется, как алюминиевый.

**Comment by aribaz** [comment]
А еще я должна указать где-то цвет водоотводного профиля
