### ISSUE TITLE
Типовые изделия

### ISSUE THREAD

**Issue by unpete** [oknosoft/windowbuilder#20]
- [x] Пересчитать в глобальной базе имеющиеся заказы, чтобы устранить ошибки порядка элементов в изделиях
- [x] Привязать к типовым блокам ссылки на продукции
- [x] Присвоить заказам-прототипам блокирующий статус, чтобы пользователи не могли испортить типовые блоки
- [x] Заменить статус заказа _шаблон_ ссылкой в справочнике предопределенных элементов
- [x] Реализовать форму выбора продукций с эскизами и отбором по заказу

**Comment by Oparin-Igor** [comment]
Заказы пересчитал, не создалась характеристика цветного штапика.

**Comment by unpete** [comment]
> Заказы пересчитал

Это я себе задачу поставил - есть скрытая от пользователя неоптимальность. Связана с внутренними номерами элементов. Хочется, чтобы в типовых блоках эти номера были хорошими - тогда при построении и редактировании изделий система будет делать меньше внутренних пересчетов
