### ISSUE TITLE
Приведенная площадь в стеклопакетах (не прямоугольных)

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#202]
Можно ли получить чертеж на сложных формах стеклопакетов?
Треугольники, трапеции, многоугольники, арки, криволинейные формы?
Ведь в случае с ними не достаточно только ширины и высоты стеклопакета, нужен еще чертеж, чтобы нам этот стеклопакет смогли изготовить.

Как программа считает в этом случае площадь таковых?
Нам поставщики выставляют ценник за максимальную площадь, а не фактическую, плюс на нее накидывают еще коэффициент за сложность.
![default](https://cloud.githubusercontent.com/assets/22028048/22193312/7e703274-e14b-11e6-98d8-d867f7af1be0.png)

**Comment by unpete** [comment]
У любого элемента рисовалки есть `bounds` - прямоугольная область.
Можно сделать, чтобы для заполнений в спецификацию по умолчанию подставлялась именно площадь `bounds`

Название задачи странное. Думал, что вопрос о формировании эскизов заполнений.

**Comment by aribaz** [comment]
И о них тоже.
Ведь эскиз нужен поставщику, чтобы сделать такой стеклопакет, какой надо

**Comment by unpete** [comment]
> И о них тоже

`Рисовалка`, `Спецификация`, `Безбумажка` и `Заказы поставщикам` - это четыре изолированные подсистемы. Они почти ничего друг про друга не знают, живут каждая своей жизнью, но используют общие данные. Хотелось бы задачи по разным подсистемам видеть в разных issues

**Comment by aribaz** [comment]
Стоимость  такого  стеклопакета также зависит от того, на какую площадь умножали ценник, нам поставщики считают по приведенной площади.
Здесь меня сначала интересует вопрос правильного ценообразования, а потом уже Заказ поставщику.

**Comment by aribaz** [comment]
Срочно к вопросу учета правильной (приведенной) площади фигуры в спецификации.

**Comment by unpete** [comment]
@aribaz Где ссылка на заказ с неправильной площадью и указанием правильной?
Если ставите `срочно`, почему не делаете ту подготовительную часть работы, которая в ваших силах?

**Comment by aribaz** [comment]
Евгений, извините.
Сейчас еще раз проверила, считает все-таки правильно по приведенной площади и для криволинейных и для многоугольников. Мне почему то в прошлый раз показалось что там фактическая площадь готового стеклопакета, не знаю почему.
Извините еще раз.
Остаются тогда эскизы для таких стеклопакетов поставщику.

**Comment by unpete** [comment]
> Остаются тогда эскизы для таких стеклопакетов поставщику

Не уверен, что получится поставить телегу впереди лошади.
Для заказа стеклопакетов нужна пачка заданий на производство.
Для пачки заданий нужны даты планирования - настроенная в полном объёме подсистема диспетчеризации.
Можно, конечно, сделать затычку - отчет, который сформирует список заполнений по списку заказов, плюс, выведет эскизы непрямоугольных заполнений.
Сценарий работы снабженца мы еще не обсуждали. Если есть идеи - накидайте примерную блок-схему, кто, в какое время и на на основании каких данных должен формировать заказы поставщикам. В любом случае, признак `срочно` у этой задачи придется снять.

**Comment by nmivan** [comment]
@aribaz , задача актуальна?

**Comment by aribaz** [comment]
@nmivan да актуальна.

**Comment by unpete** [comment]
Сейчас из коробки, заполнение знает как габаритную площадь, так и площадь с учетом произвольной кривой формы + есть рендер в растровые или векторные графические форматы + экспорт в dxf.
