### ISSUE TITLE
Криволинейные (радиусные) элементы профилей

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#207]
Можно ли программе как-то сказать, что если R (радиус) профиля не равен нулю, то его стоимость увеличивается к примеру в два раза?
Так как у нас дерево а не пластик, то материала на изготовление криволинейного профиля у нас уйдет больше чем на изготовление прямого, ведь мы не гнем его, а делаем из сегментов большего сечения и это увеличивает время трудоемкость изготовления такого профиля, появляются новые операции по обработке, которых нет на прямых элементах. 
Если есть дуга у профиля, то и штапик надо тоже сделать дугой.
И в целом как быть  в этой ситуации?

**Comment by Oparin-Igor** [comment]
Стандартно, для гнутых профилей во вставках, при условии что радиус не равен 0 добавляются услуги, типа изготовление арочной рамы, можно по градации от радиуса, за маленькую арку, добавляем услуги изготовление арки менее r500мм. с более высокими расценками.

**Comment by aribaz** [comment]
Возможно, но но у нас на арках не только доп работы появляются, которых нет на прямолинейных профилях, но и расход увеличивается материала, потому как чтобы сделать дугу, клеят сегменты, получается ломаная дуга (условно) шириной значительно больше исходного бруса в 2-3 раза, а потом ее профилируют и получают готовый радиусный профиль. Мы не гнем профили. как ПВХ-шники.

**Comment by Oparin-Igor** [comment]
как дуга влияет на расход и материалы, можете составить табличку.

**Comment by aribaz** [comment]
Вот тут я не могу точно сказать, каждый раз разный расход. Это зависит от длины сегмента, радиусов этой дуги, которые мы должны получить в итоге. Сегменты строят еще исходя из тех соображений, чтобы потом на станке можно было правильно обработать его, выстраивают определенные точки. Пока точнее сказать не могу, попросила конструктора прислать пример. Так же из сегментов делается и штапик для створки.
Ситуация с ломанными контурами почти такая же, там только расход не меняется,  а доп. операция появляется и тоже выстраивают точки определенные, потому что у профилей есть шипы и проушины и надо чтобы потом в сборе образовалась конструкция с необходимым углом.

**Comment by unpete** [comment]
Напомню о двух особенностях:
- Материал можно сделать вычисляемым, чтобы для криволинейных элементов требовались огромные брёвна вместо аккуратных брусьев
- В нашем графическом движке нет понятия `радиуса`. Есть `кривизна` - `curvature` и эта кривизна не в целом для элемента, а функция точки. В разных местах она может быть разной. Если элемент является правильной дугой, кривизна у него везде одинаковая, но правильные дуги - редкость. Чаще встречаются `овалы` и `безье`

**Comment by nmivan** [comment]
@aribaz , задача не решена?

**Comment by aribaz** [comment]
@nmivan изначально меня интересовал вопрос как учесть изменение цены, если профиль имеет кривизну, вопрос я решила приблизительно с точки зрения ценообразования.
Есть более детальный вопрос, так как у нас дерево, то для получения дуги, мы  не гнем прямой профиль, а клеим его из сегментов большего (значительно) сечения, чем готовый. количество сегметов и их сечение зависит от радиусов этой дуги. Плюс нам здесь нужны координаты определенных точек, чтобы завести эту клееную конструкцию на профилирование.
Но мы решили, что построение сегментов у нас будет делать конструктор. Будем считать задачу закрытой.
