### ISSUE TITLE
Ошибка в размерах створки

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#208]
Я тут нашала ошибку в размерах створки.
[Окно трехстворчатое](https://light.oknosoft.ru/#obj=doc.calc_order&ref=cdfdd76a-b4a9-4567-c430-c7d6c5659a2a&frm=doc&view=orders)

В правой части, ошибка связана с соединением профилей створки с Импост Гор ВП/Рама 90.

Во-первых, зрительно неправильно отображены прилегания створочного профиля к этому импосту.
Так как опорная линия этого импоста проходит на расстоянии 45мм - это середина этого профиля, а размер соединения профиля створка 79 и ИмпостГорВП/рама90 составляет 46мм, то линия верха створки должна наплывать на опорную линию импоста на 1мм, а на чертеже до нее даже не доходит.

Импост этот не симметричный, возможно я каких-то нюансов не понимаю/не знаю.
Но размеры этих створок не правильны по высоте, в частности у нижней она меньше чем надо на 17мм.
И я так думаю это обусловлено соединением наложения.

Профиль импоста может соединяться со створкой Низ 79 (верхняя створка) - размер соединения 29мм, и со створкой 79 (нижняя створка) - размер соединения 46мм.  Соединения я проверяла, описаны они верно, только у меня на одном из них 1мм убегает почему-то или 28 и 46, или 29 и 45. Но такое ощущение, что система как-то не правильно их применяет. Верхняя створка рассчитана правильно. А нижняя на 17мм меньше, такое ощущение, что используется не соединение Створка79-Импост (46мм), а соединение СтворкаНиз79-Импост (29мм), разница как раз совпадает (46-29 = 17мм).
![default](https://cloud.githubusercontent.com/assets/22028048/22279429/e2d66be8-e2db-11e6-839e-51d8f41ea1fd.jpg)

И такой вопрос. Можно ли для несимметричных импостов переместить опорную линию (зеленую) (указать размер В) согласно ее расположению на чертеже  - для нас это линия между двумя примыкающими створками (синяя), расположенная на равном расстоянии от границ створок прилегающих - это нам позволит более удобно и привычно редактировать размеры створок.

Подобного рода проблема есть и для импоста ИмпостГорВП/рама100

**Comment by unpete** [comment]
`Размер В` в программе нужно указывать `как в жизни`
Не забывайте, что в этом случае, имеет значение, как нарисовать импост _сверху вниз_ или _снизу вверх_ - размеры створок будут разными.

**Comment by aribaz** [comment]
@Oparin-Igor Игорь, посмотрите пожалуйста этот вопрос.

**Comment by Oparin-Igor** [comment]
Смогу. Вечером.
--
Отправлено из Mail.Ru для Android четверг, 26 января 2017г., 09:38 +03:00 от Звалинская Наталья  notifications@github.com :

**Comment by aribaz** [comment]
Евгений, помогите пожалуйста.

Для этого случая сделала два соединения, линию опорную оставила по центру импоста (ширина импоста 90, В=45). 
Пока руками меняю соединения, но не корректно считается размер обеих створок. 

Рисую раму, далее импост Дер. ИмпостГор ВП/Рама_90 (слева направо), вставляю створки сверху и снизу от импоста, далее меняю соединения примыкания этого профиля со створками:

**для верхней створки:**
импост Дер. ИмпостГор ВП/Рама_90 соединяется с профилем Дер. СтворкаНиз 79, соединение для этого случая автоматом ставится Дер. || рам ств низ 79 имп гор вп снар (размер соединения 29 - что правильно)

**для нижней створки**
импост Дер. ИмпостГор ВП/Рама_90 соединяется с профилем Дер. Створка 79, соединение для этого случая автоматом ставится Дер. || рам ств низ 79 имп гор вп снар (размер соединения 29 - что не правильно); меняю текущее соединение на Дер. || рам ств низ 79 имп гор вп изн (размер соединения 45, что правильно). 

И в целом все верно, только у меня верхняя створка получается на 3мм больше чем надо, а нижняя на 3мм меньше чем надо почему-то.

Никаких соединений на 3мм я не добавляла.
![2017-03-09_16-07-55](https://cloud.githubusercontent.com/assets/22028048/23752698/78e50464-04e7-11e7-844f-270a466b3702.png)

Как это исправить?

**Comment by unpete** [comment]
- Установил _Размер_B = 37_ - можно было сохранить 45, но лучше, когда координаты в системе равны тем, что в жизни
- Добавил фильтр по стороне соединения как при пересчете изделия, так и при выборе по строке или из формы выбора

Можно тестировать. Если размеры не понравятся, указывайте внятно: должно быть `X`, имеем `Y`
Про 3мм или, могу предположить, что дело было в кривых шаблонах. У вас базовые изделия были нарисованы дрожащей рукой - в них имелись разрывы профиля в узлах и непрямоугольность в несколько мм.

**Comment by aribaz** [comment]
Спасибо, работает.
