### ISSUE TITLE
Двери (балконные и входные)

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#209]
- [ ] Дополнить список профилей  и соединений
- [ ] Создать недостающие параметры и подцепить к ним номенклатуру
- [ ] Штульповое открывание предусмотреть

**Comment by aribaz** [comment]
Перечень содержится в файле с параметрами профилей, но дублирую.
Там же содержатся и параметры дверей.
Это списки профилей:
[Системы профилей (профили) 2016-12-07.xlsx](https://github.com/oknosoft/windowbuilder/files/728820/2016-12-07.xlsx)

Это списки параметров и для окон и для дверей.
[Системы профилей (параметры)2016-12-07.xlsx](https://github.com/oknosoft/windowbuilder/files/728829/2016-12-07.xlsx)

Что-то можно увидеть со стороны браузера по дверям, из того, то вы уже сделали (я про изменения)? Может я просто не знаю куда смотреть.

**Comment by aribaz** [comment]
См. Задачу 212

**Comment by Oparin-Igor** [comment]
Уточняю 
Сделать систему с профилями "все", "окно", "двери". Как назовете?

**Comment by Oparin-Igor** [comment]
Повторите чертеж Порог скос

**Comment by aribaz** [comment]
Пороги - образмереные, рядом с ними все, что может соединяться соединением наложения.
[ПорогСкос63.pdf](https://github.com/oknosoft/windowbuilder/files/729953/63.pdf)
[порогСкос83.pdf](https://github.com/oknosoft/windowbuilder/files/729954/83.pdf)

**Comment by aribaz** [comment]
Пусть система Все называется "Дерево IV", система Окно - "Оконный блок", система Двери - "Дверной блок".

Я правильно поняла, что будет три системы?

**Comment by Oparin-Igor** [comment]
Какие элементы в соединении?

**Comment by aribaz** [comment]
Дер. ДвНиз_в/о_113/109 ств
Дер. Дв_Н/о_120/116 ств
Дер. Дв_н/о_113/109
Дер. СтворкаНиз 79

**Comment by aribaz** [comment]
Угловые соединения такие же как для простых порогов

**Comment by Oparin-Igor** [comment]
Какие элементы (артикулы, уплотнение и т.д козырьки) в соединении?

**Comment by aribaz** [comment]
Для соединения наложения порогов (всех) со створками в спецификацию может попасть а может и нет  так называемая Защита порога в виде артикула Алюминиевая накладка (м.пог) и саморез для ее крепления - 3шт 

Эту накладку в целом можно ставить и как вставку к профилю, и как параметр. Физически она крепиться только к порогу.
Ее наличие - это желание заказчика. Бывает только алюминиевая, ее не красим, торцвушек не имеет.

Длина накладки рассчитывается как длина порога минус каждый размер профиля, с которым порог соединяется угловым соединением.

**Comment by aribaz** [comment]
С нижним профилем рамы Алюминиевый порог (арт. W86/32Ti) - хлыст 6м.пог., в спецификацию должны попасть:

1. Доборная планка (D8EV1) - м.пог.
2. Уплотнитель порога (TD 12/3) - м.пог.
3. Крепежная пластина - SH50 - 2шт
4. Шуруп - 3шт
5. Обрезка профиля низа створки по длине  (делаем наплав у профиля меньше, чтобы обеспечить зазор м/у створкой и полом) - м.пог (длина профиля створки по низу).

Длина элементов 1 и 2 - равна длине самого профиля Алюминиевый порог

**Comment by aribaz** [comment]
Мы используем **Регулируемые** петли. А сейчас попадают НЕ регулируемые (именно ни установлены в параметрах продукции по умолчанию, а со стороны пользователя нет возможности выбрать другие). Я могу их просто заменить на Регулируемые в параметрах продукции, без ущерба для системы?

**Comment by Oparin-Igor** [comment]
Мне нужны артикулы от названий толк мало
--
Отправлено из Mail.Ru для Android четверг, 26 января 2017г., 08:17 +03:00 от Звалинская Наталья  notifications@github.com :

**Comment by aribaz** [comment]
Если вы о петлях.
Конструктор наш создала окно с фурнитурой фрамуга и заметила, что в спецификации числятся не регулируемые петли, в частности "M_94030 Петля фрамужная **не рег**", а вместо не должна быть "М_52321 петля регулируемая".
Я открыла параметры продукции на стороне 1С, в них есть параметр "Тип петель", которому присвоено значение "НЕ регулируемые" и этот  парметр не доступен пользователю в построителе.
Затем я открыла набор для фурнитуры типа Фрамуга. В спецификации есть набор:
Масо петли фрам. дерево, в нем есть обе петли, но каждая из них привязана к параметру "Тип петель":
90340 - тип петель Не регулируемые
52321 - тип петель Регулируемые
Вот я и говорю, что если в параметрах продукции изменить значение параметра Тип петель с"Не регулируемые" (как сейчас)  на "Регулируемые", то я думаю, что в спецификации будет отображаться именно 52321.

Еще для фрамуги ножницы не те отображаются:
надо M 101548 Ножницы фрамужные
а есть M 209723 Ножницы фрамужные
Но ножницы не зависят от параметров.

**Comment by Oparin-Igor** [comment]
Ножницы зависят от параметра микролифт
--
Отправлено из Mail.Ru для Android четверг, 26 января 2017г., 08:44 +03:00 от Звалинская Наталья  notifications@github.com :

**Comment by aribaz** [comment]
Для фрамуги этот параметр скрыт на стороне браузера

**Comment by aribaz** [comment]
Теперь тип петель доступен, только выбрать ничего нельзя, кроме Не регулируемых.

**Comment by aribaz** [comment]
А по ножницам, в наборе для фрамуги есть две строки с ножницами 9 и 3, но в обеих числятся M 209723 Ножницы фрамужные и ни одна из них никак не зависит от параметров.

**Comment by aribaz** [comment]
На фрамуге петли убежали за раму слева
![image](https://cloud.githubusercontent.com/assets/22028048/22321825/c7df3bd0-e3a8-11e6-8d29-b86e2630cee1.png)

**Comment by Oparin-Igor** [comment]
Выкладывайте ссылку
--
Отправлено из Mail.Ru для Android четверг, 26 января 2017г., 09:21 +03:00 от Звалинская Наталья  notifications@github.com :

**Comment by aribaz** [comment]
https://light.oknosoft.ru/#obj=doc.calc_order&ref=5fe97bdc-13ee-461d-b458-91fee40a24de&frm=doc&view=orders

Делала на основании одностворчатого окна.

**Comment by Oparin-Igor** [comment]
Не понятно происхождение 2-х лишних эскизов петель( не нашел откуда берутся) кординаты у них не верные.
Кол-во стоит 0 а кол-во ++ почему-то 2. В настройках петель исправил кол-во, убрал петли ПВХ. и пока убрал(надо выяснить происхождение глюка) третью петлю для створок шире 900мм.
Артиулы сейчас выбираются правильно, в зависимости от параметра а спецификация по эскизам не 
изменилась. Петли рисуются со смещением. Причем нижняя справа, верхняя слева, левая снизу, хотя координаты верные..

**Comment by Oparin-Igor** [comment]
С нижним профилем рамы Алюминиевый порог (арт. W86/32Ti) - хлыст 6м.пог., в спецификацию должны попасть:

Доборная планка (D8EV1) - м.пог.
Уплотнитель порога (TD 12/3) - м.пог.
Крепежная пластина - SH50 - 2шт
Шуруп - 3шт
Обрезка профиля низа створки по длине (делаем наплав у профиля меньше, чтобы обеспечить зазор м/у створкой и полом) - м.пог (длина профиля створки по низу).
Длина элементов 1 и 2 - равна длине самого профиля Алюминиевый порог

Проверить

**Comment by aribaz** [comment]
В системе Дерево 78 такого профиля нет.
