### ISSUE TITLE
Отображение изменений в построителе

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#210]
Изменения, сделанные на эскизе в построителе не отображаются сразу, только после того, как сохранил-закрыл и вновь открыл изделие.

Это в целом не критично, система ведет себя так всегда, но было бы удобнее видеть сразу результат своей деятельности.
Это применительно к тем случаям, когда например меняешь сечение импоста, его положение в коробке. Размеры створок измененные появляются после сохранения и закрытия, кнопка Рассчитать не помогает. И в большей степени особенно заметна, если коробка имеет много импостов и створок.

**Comment by unpete** [comment]
> Изменения, сделанные на эскизе в построителе не отображаются сразу

Пример, пожалуйста, в студию. Скорее всего, у вас драматические ошибки в настройках систем, вставок или соединений

**Comment by aribaz** [comment]
Приз в студию )
Это шаблон - так было
![2017-01-26_14-03-56](https://cloud.githubusercontent.com/assets/22028048/22329183/24ecb44c-e3d1-11e6-83cb-4377d6b88743.png)
Это я изменила импост и нажала кнопку рассчитать
![2017-01-26_14-05-15](https://cloud.githubusercontent.com/assets/22028048/22329194/395acaea-e3d1-11e6-9172-22cb8edd0270.png)
А это после того как сохранила/закрыла и вновь открыла.

Единственное что меняется - так это цена, тут даже не надо рассчитывать.

**Comment by unpete** [comment]
Добавил пересчет лучей примыкающих элементов при смене вставки - раньше пересчитывались только лучи текущего элемента

**Comment by aribaz** [comment]
В целом работает.
А почему размеры створок на эскизе не меняются пока не сохраню и не открою снова, а в табчасти меняются сразу.

**Comment by aribaz** [comment]
Закрываю.
