### ISSUE TITLE
ЛКМ для допов

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#211]
Евгений, помогите пожалуйста.
У нас ЛКМ для допов не отображаются в спецификации и как следствие не принимают участия в ценообразовании, и параметры по покраске допов тоже.
Со стороны технологии Игорь их добавил.

**Comment by unpete** [comment]
Коды или хотя бы наименования вставок приведите. Куда смотреть?
С четверга по субботу буду недоступен. Если хотите срочно, почему нет полной информации о проблеме?

**Comment by Oparin-Igor** [comment]
Вставки
Вставка "Контур" Подоконник дер. содержит вставку "дер. лак щит"   и Монтаж.
Дер. Рама  83  Рама  Низ 83, содержит вставку "элемент" F-18профиль покрытия оконных створок.

**Comment by aribaz** [comment]
@unpete 
Игорь, у нас все вставки, которые из дерева/мдф должны краситься. 
Это и доборы, и наличники, и обсада.

**Comment by Oparin-Igor** [comment]
Нет не все, я еще не знаю как правильно добавить, пробовал по всякому пока не работает.

**Comment by unpete** [comment]
> пробовал по всякому

С высокой вероятностью, это **пробовал по всякому** - и есть причина всех проблем во вставках, Предлагаю прекратить **пробовать по всякому** и попытаться понять, как оно работает на самом деле.

**Comment by Oparin-Igor** [comment]
Если это решено, приведи пример, если нет, то не надо придираться к словам, просто напиши, что не решено.

**Comment by nmivan** [comment]
@aribaz , задача актуальна?

**Comment by aribaz** [comment]
@nmivan вопрос решили
