### ISSUE TITLE
Системы профилей

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#212]
Я в файлике делила системы по типам блоков на 4, но как оказалось если мне надо будет нарисовать составной блок из двери входной и окна, я должна буду использовать в качестве системы ИЛИ окно ИЛИ дверь, а в дверях профили створки не такие как в окнах.
Может все же об'единить все профили в одну систему? Ведь параметр фурнитура определяет состав самой фурнитуры.
Это я к вопросу о дверях.

**Comment by aribaz** [comment]
@Oparin-Igor 
Игорь, а можно еще подцепить в качестве заполнения к этим системам не только стеклопакеты, но и филенки. Иногда в составных блоках в оконных узких частях просят вместо стеклопакета поставить филенку.

**Comment by aribaz** [comment]
В качестве стеклопакета по умолчанию прошу использовать стеклопакет СПД 40мм 4-16-4-12-4i.

У меня еще вопрос по теме стеклопакетов.
В параметрах продукции на закладке Элементы числится наш обычный стеклопакет 4-16-4-12-4, а на закладке Соединения в соединениях наложения стеклопакета с чем-то в качестве стеклопакета указан 4х14х4х14х4 (40), толщина конечно у них одинаковая, а разве не имеет значения сама номенклатура (ее наименование)? Это мне для общего развития.

**Comment by Oparin-Igor** [comment]
Номенклатура значения не имеет . В форме ставится галочка арт1стеклопакет. Отбор идет по заданной толщине стп

**Comment by Oparin-Igor** [comment]
" снять приоритет 1"- приоритет трогать не надо.
Надо установить галочку для основного стеклопакета.
При добавлении в список стеклопакетов в параметрах продукции, добавляется в выпадающий список, при выборе пакета.
Работает только при смене системы, если не такой толщины в изменяемой конструкции.
Открываете документ "шаблон" открываете типовое изделие, меняете пакет, сохраняете.
