### ISSUE TITLE
Выделение элементов

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#213]
Ещё было пожелание от пользователей о выделении элементов. Сейчас чтобы выделить мышкой профиль рамы или импоста очень тяжело попадать в нужные точки, часто попадаю не в раму/импоста, а в створку, а если створки не погасить (отключить видимость), то выделить импост становится почти невозможно, особенно если он не широкий. При сегодняшнем выделении себя приходится контролировать в таблице части на предмет того а попала ли я мышкой туда, куда хотела.
Затруднение еще в том, что даже если попала в раму/импост на эскизе выделена графически рама /импост, это путает. Это можно отнести и к выставкам, там ведь тоже надо выделить раму/створку/элемент, чтобы вставить что надо и куда надо. Я так уже лепила МС к раме и долго не могла понять почему такой размер у москитки.
В целом конечно, знаю об этих особенностях, но если бы графика с табчастью совпадали, было бы удобнее намного.

**Comment by unpete** [comment]
- Добавил визуализацию выделения
- Запланировал новую горячую клавишу при выделении `Клик` при нажатом `Пробеле` будет выделять элементы только нижнего рамного слоя

**Comment by aribaz** [comment]
В целом работает и видно что выделено на всех окнах.
Только на окне Трехстворчатом (или там, где много створок внутри одной рамы, чтобы выделить импосты надо увеличить изображение, иначе в импост не попадаю, попадаю в створку, но во всяком случае я сразу вижу что именно выделила, и это уже хорошо, имею возможность вовремя среагировать.

**Comment by aribaz** [comment]
В балконной двери (система) при выделении створки выделяется штриховкой и закладка почему-то, а если выделить закладку, то штриховка выделяет только закладку.
![2017-01-26_13-52-23](https://cloud.githubusercontent.com/assets/22028048/22328781/0ebe1a1e-e3cf-11e6-835e-ccd1f767ecf9.png)
![2017-01-26_13-53-40](https://cloud.githubusercontent.com/assets/22028048/22328780/0eba7f08-e3cf-11e6-937e-da8590865db3.png)

**Comment by unpete** [comment]
В импост не надо попадать.
Нужно нажать пробел и затем, кликнуть по створке - будет выделен импост

26.01.2017 8:28 пользователь "Звалинская Наталья" <notifications@github.com>
написал:

**Comment by aribaz** [comment]
Работает. спасибо.
Закрываю.
