### ISSUE TITLE
Монтаж, как параметр вставок

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#214]
При добавлении ном.Монтаж с. Единицей изм ед. Вид расчета к элементу В строку вставки контур. 
При нажатии кнопки сохранить, не закрывается окно. Не сохраняется не добавляется в спецификацию доп. Продукции.

**Comment by unpete** [comment]
@aribaz зачем много раз писать про одно и то же.
Проблема очень простая: вы создаёте вставки, код которых не может быть исполнен в том контексте, где он выполняется. Например, контекст вставок в `контур` не содержит свойства `длина`. Понятно, что если вставка пытается рассчитать что-то, зависящее от `Длины` - возникнет ошибка времени исполнения.
`Длина` в данном случае приведена условно. Это может быть любое другое свойство, которое есть у `элемента`, но отсутствует у `контура` или `изделия`

Решить проблему будет проще, если вместо невнятного текста написать: _Ошибка во вставке с кодом XXXX_ - тогда я смогу открыть эту вставку в 1С и не заглядывая в рисовалку сказать, что именно в этой вставке мешает рассчитать спецификацию

**Comment by unpete** [comment]
Тестируйте - должно заработать. Проблема была связана с булевыми типами параметров.

**Comment by aribaz** [comment]
Вроде работает, но тестировала не все, а выборочно.
Закрываю, спасибо.
