### ISSUE TITLE
Разные Кмарж на продукцию из разного сырья

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#215]
Евгений, подскажите, можно ли использовать разные Кмарж для изделий из разных пиломатериалов?
Например изделия из дуба Кмарж=1,8, а на сосновые - 2,3. (условно)?

**Comment by unpete** [comment]
Строка `маржинальных коэффициентов` рассчитывается для каждой строки продукции.
Вопрос `можно ли` - не совсем корректен. В общем случае, `КМарж` на разную продукцию - разный.
В вашей базе есть пример с `КМарж` москитных сеток - для фильтрации там используются ценовые группы номенклатуры продукции.

**Comment by aribaz** [comment]
Спасибо, закрываю.
