### ISSUE TITLE
Инвертировать shift в типовых инструментах

### ISSUE THREAD

**Issue by unpete** [oknosoft/windowbuilder#216]
По умолчанию привязывать к 45 градусов

**Comment by unpete** [comment]
Внесены изменения в поведение инструментов _Выделение_ и _Рисование_

- При рисовании, по умолчанию линии тянутся с шагом 45°. Если нужна прямая с произвольным наклоном - удерживаем _shift_
- При сдвигах элементов мышью, по умолчанию сдвиг делается с шагом 90°. Если нужен сдвиг в произвольном направлении - удерживаем _shift_
- При _рисовании контура_, автоматически добавляется начало нового профиля в конечную точку нарисованного профиля (текучий интерфейс). Чтобы оборвать цепочку профилей, используйте клавишу _escape_ или правую кнопку мыши

**Comment by A-Shimko** [comment]
Рисую, все работает, мне очень нравится...
