### ISSUE TITLE
Не работает кнопка Добавить створку

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#217]
Не работает кнопка добавить створку в любых шаблонах.

**Comment by unpete** [comment]
В выходные рефакторил код класса [Contour](/oknosoft/windowbuilder/wiki/Контур-(Contour)-слой-изделия) - привнёс несколько ошибок.
Исправлено. Попутно выявил несколько не связанных с контуром ошибок и так же, исправил.

**Comment by aribaz** [comment]
Работает, закрываю.
Спасибо.
