### ISSUE TITLE
Параметр Цвет водоотводного профиля

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#219]
Мы еще оговаривали такой параметр, но его пока у нас нет.

Профиль стоит по-разному в зависимости от цвета, и его цвет выбирает заказчик не всегда ориентируясь на цвет изделия.

**Comment by nmivan** [comment]
@aribaz , с этой задачей как дела? Актуальна?

**Comment by aribaz** [comment]
@nmivan параметр, добавила. закрываю
