### ISSUE TITLE
Штульповая створка

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#220]
У меня с ней что-то случилось в одной половине нет стеклопакета и какая-то ошибка при выделении створки этой же (ответная), профили нижний и верхний у этой створки уплыли до самой рамы влево, сама створка целиком не выделяется, только отельными элементами.
Вставила ее из шаблона.
![2017-02-01_09-32-12](https://cloud.githubusercontent.com/assets/22028048/22497260/6c3bc5ba-e861-11e6-8b7e-a249981da703.png)

**Comment by Oparin-Igor** [comment]
https://light.oknosoft.ru/#obj=cat.characteristics&ref=1abb8a38-94b5-4862-87f1-a6a03fb3f30d&frm=builder&view=orders
При открытии изделия из шаблона, профили подставляются не из параметров продукции.
И не из шаблона.
Верх, низ встал профиль Ств. штульп 79, в параметрах продукции он стоит в списке профилей без галочки по умолчанию.

**Comment by Oparin-Igor** [comment]
Исправил эскиз, сохранил.
Открыл - все профили опять слетели.

**Comment by unpete** [comment]
Код поправил, просьба проверить все шаблоны - профили могли уплыть.
Корень проблемы в отсутствии автоматических регрессионных тестов.
Из-за этого, новая функциональность ломает старую.

**Comment by aribaz** [comment]
Вроде все нормально,  спасибо.
