### ISSUE TITLE
Другая продукция

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#221]
Евгений, а можно ли как-то добавить в изделие условную продукцию, у которой можно было бы указать например габариты ширина высота и цену указать руками без использования технологических справочников. Что-то типа материала, но выступает как продукция.
Например, ставни - их описывать пока не знаю как вообще, а хочется, чтобы весь перечень заказа был в одном месте на стороне браузера в рамном цехе.

**Comment by unpete** [comment]
Можно. Задача дублирует #67
Просьба привести примеры продукций, которые планируете добавлять таким способом.
