### ISSUE TITLE
Последние заказы за день не видны в списке

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#222]
Третий день наблюдаю такой эффект.

Я создаю заказ, сохраняю его, закрываю, в списке его нет.
Открываю/закрываю любой заказ и теперь вижу свой новый заказ в списке. На следующий день с этим заказом проблем не возникает, он виден.
Но теперь не видны вновь созданные сегодня заказы, их можно увидеть в списке тоже открыв-закрыв любой заказ, а на следующий день они уже видны.

И еще была 2 раза ситауция ( у Ефремовой и у меня):
создали последнее изделие, сохраняем и закрываем его, а в списке изделий только одна строка осталась пустая (без названия, без ничего), вместо цифр одни нули, а строчек было 4 и 7. Сохраняю заказ, перезагружаю браузер, открываю снова заказ и все изделия на месте.

Повторить такое у меня не получилось, я не поняла что произошло. Первый раз это было на прошлой неделе у Ефремовой,  при этом она свои изделия в заказе видела в виде одной пустой строки, а я когда смотрела под своей учеткой - у меня все было, я попросила ее перезагрузить свой браузер и все вернулось. А через несколько дней я сама все увидела на своем примере.
Больше плдобного не происходило, сохранялось все без проблем.

**Comment by unpete** [comment]
Не понял, чем именно могу помочь.
Есть задача отказа от пагинации в динсписках и более общая задача перехода на v2.
Есть задача вычисления страницы при пагинации #115 
Есть задача информирования пользователя об ошибках #218
Если вам есть что добавить к этим задачам по существу, почему бы не сделать это в уже открытых?
Зачем создавать новые?
