### ISSUE TITLE
Алгоритм связи створки с заполнением

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#225]
Когда хочу какую-то створку удалить из шаблона и немного его подредактировать, то вне зависимости от того какую створку я выделила удаляется нижняя створка в правом углу, а последующие створки удаляются правильно, что выделила, то и удалилось.

Раньше такое бывало иногда и не в каждом шаблоне, а сейчас всегда так. 

Створку конечно можно еще раз вставить, но наверное это не совсем правильно.

**Comment by unpete** [comment]
Вопрос касается не только удаления, но и любых других трансформаций внешнего контура или добавления-удаления слоёв

**Comment by nmivan** [comment]
@unpete , правильно понимаю, что это задача для разработки?

**Comment by unpete** [comment]
есть подозрение, что задача уже решена - надо бы протестировать

**Comment by aribaz** [comment]
@nmivan да, решена, закрываю
