### ISSUE TITLE
Ссылка на эскиз изделия

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#226]
Евгений, вы говорили, что поможете с вопросом обращения к эскизу изделия из Excel.

Я файлик в целом сделала, немного формат поправлю (шрифт, высота и пр.) и можно будет отдавать в использование.

**Comment by unpete** [comment]
Пример ссылки: https://light.oknosoft.ru/r/11/x/8f684a73-50bb-4f84-cb55-d5b1b10a5c31?att=svg
Но вряд ли вы сможете ей воспользоваться без программирования.
Скорее всего, я добавлю эскизы и шапки заказов в стандартную выгрузку по этому отчету.
Сейчас обдумываю постановку задачи.

**Comment by aribaz** [comment]
Ссылка в том виде, в котором она сейчас есть наверное не совсем правильно отображает эскиз.
Я вижу только низ блока, верх блока совсем не вижу.
Да, в таком виде она мне мало чем сможет помочь.
Пока я буду пользоваться печатным способом.

**Comment by unpete** [comment]
> Я вижу только низ блока, верх блока совсем не вижу.

Проблема не в низе и верхе. Там полный svg, у него есть viewport - эскиз можно сдвинуть и смасштабировать. Трудность в том, что это не делается без программирования. Вам пришлось бы разместить внутри xls некий код, который получал бы данные из веб, трансформировал и делал из них картинку.
Пока пользуйтесь тем, что есть. Универсальный отчет, совмещенный с печатной формой в планах стоит - рано или поздно войдёт в комплект поставки.
