### ISSUE TITLE
Цвет "Без цвета" во вставках  и соединениях

### ISSUE THREAD

**Issue by oplovpavel** [oknosoft/windowbuilder#227]
В построителе при создании белого контура окна номенклатура спецификации (Армировка саморезы) для которых указан цвет "Без цвета" имеют цвет белый (основной).
если в соединениях указать другой (отличный от "Без цвета ) то этот цвет сохраняется 
![screenshot_20170217_163039](https://cloud.githubusercontent.com/assets/24730013/23067058/9e486da4-f52e-11e6-962d-b74d80e3eba7.png)

**Comment by unpete** [comment]
Проблемы не вижу.
Цвет - это не характеристика материала, а просто реквизит спецификации. Смотрите на него, как на некие вспомогательные данные, которыми можно воспользоваться при расчетах, а можно проигнорировать.
Поведение системы в отношении цветов сейчас логичное и стабильное. У технолога есть возможность получить правильную спецификацию.
