### ISSUE TITLE
Вставка в элемент

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#228]
https://light.oknosoft.ru/#obj=cat.characteristics&ref=99bb7c33-dc47-4696-c3cb-c59d3dc412e3&frm=builder&view=orders

Это то, где сегодня была ошибка по вставке с профилем покрытия, строка при добавлении вставки не отображалась.

**Comment by unpete** [comment]
В системе нет ни одной вставки с типом `В элемент`. Вполне естественно, что поле выбора пустое.
