### ISSUE TITLE
К марж, ключ параметров дуб

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#229]
Попробовала, не сработало.

Все посчитало с Кмарж=2.
Попробовала на двух изделиях.

Заказ [НЗАР21](https://light.oknosoft.ru/#obj=doc.calc_order&ref=7700eca1-373e-4528-ae2a-812454360b96&frm=doc&view=orders), изделие 5 и 6.

![image](https://cloud.githubusercontent.com/assets/22028048/23154050/dcf471a6-f81c-11e6-93c1-79c103b834e3.png)

Новая строка с ключом по дубу не отображается на стороне браузера.

**Comment by unpete** [comment]
Во-первых, в ключе параметров были указаны невыполнимые условия.
Материал сырья не может быть одновременно _Дуб цельноламельный_ **И** _Дуб сращенный_
Правильно было бы указать: Материал сырья **в списке** _Дуб цельноламельный_, _Дуб сращенный_

Задачу взял в работу, с высокой вероятностью сегодня решу

**Comment by unpete** [comment]
Фильтрация по параметрам в маржинальных коэффициентах реализована не в полном объёме. Пока открыт вопрос с вычисляемыми параметрами, но ваша задача должна работать корректно.
Поддержаны виды сравнений _Равно_, _Не равно_, _В списке_, _Не в списке_.

По редактированию _списка опций_ на стороне 1С, см. #50

**Comment by aribaz** [comment]
Сработало, спасибо.

Закрываю.
