### ISSUE TITLE
Цвета и цветовые характеристики

### ISSUE THREAD

**Issue by unpete** [oknosoft/windowbuilder#23]
- [x] Выбор и сохранение цвета элементов в рисовалке
- [x] Для основного материала вставки приоритетным считать цвет соединения - это получается автоматически, т.к. строка основного материала служит только для вычисления номенклатуры, а цвет и геометрия рассчитываются по параметрам соединений с соседними профилями
- [x] Спрятать служебные цвета в полях и формах выбора
- [ ] Создание цветовых характеристик при расчете спецификации

**Comment by unpete** [comment]
- Ламинация и покраска рассчитываются одинаково:
    + Есть базовый материал, как правило - без характеристик
    + Есть площадь профиля изнутри и снаружи
    + В в спецификацию включаем
        + неокрашенный материал
        + краску или плёнку (если это наши материалы)
        + работы или услуги (зарплата наших сдельщиков или стоимость переработки)
- Для цветных материалов (тех, которые поступают на склад в определенном цвете)
    + Создаём цветовые характеристики
    + Устанавливаем плановую себестоимость и прайс с учетом цвета и справочника _Цвето-ценовые группы_
    + В спецификацию включаем материал с характеристикой, вычисляемой через цвет элемента с учетом справочника _Цвето-ценовые группы_
- Если ламинированный профиль или цветные стеклопакеты закупаются, а не изготавливаются по давальческой схеме, рассматриваем их как обычные цветные материалы - см. предыдущий пункт

**Comment by unpete** [comment]
Описать математику фильтрации цветов во вставках и системах

**Comment by unpete** [comment]
В форме выбора цветов реализована математика создания составного цвета.
- В панели формы есть поля для фильтрации цветов по цвету изнутри и цвету снаружи
- Если поля фильтра не заполнены, поведение формы не отличается от стандартного
- Если поля заполнены и существует подходящий цвет, поведение формы не отличается от стандартного
- Если подходящего цвета нет, при нажатии кнопки `Выбрать или создать`, создаётся новый элемент справочника и его полям `цвет изнутри` и `цвет снаружи` присваиваются значения фильтра
- Добавление цветов доступно только в online-режиме. При отсутствии доступа в интернет, создать составной цвет не получится

**Comment by aribaz** [comment]
Я правильно поняла, что для того, чтобы можно было выбрать разный цвет изнутри и снаружи для изделия, сначала надо создать сочетания цветов, в форме которых указать цвет изнутри и цвет снаружи?

**Comment by aribaz** [comment]
разобралась с составными, закрываю.
