### ISSUE TITLE
Доступность значений параметров на стороне браузера

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#230]
Параметр: Эффект покрытия - не видно значения "матовый".
Параметр: Дер.НизРама - не видно значения "Паз под подоконник с двух сторон"
#81 здесь некорректная работа
#234 цвет доп профиля тоже не правильно отображается

**Comment by aribaz** [comment]
Евгений, подскажите а можно как-то использовать оператор И/ИЛИ в поле Вид сравнения для описания правил применения номенклатур в спецификации.

Например: у нас есть порозаполнитель, он может применяться только в том случае, если параметр Поверхность=гладкая, который в свою очередь должен быть доступен только для дуба (и сращенного и цельноламельного). Но почему-то связь параметров не сработала (возможно я что-то не правильно настроила).

Так как параметр Поверхность доступен для любого материала, и пользователь сейчас имеет возможность его применить и к другим породам (не только к дубу), то чтобы в спецификацию попало все правильно, мне надо сделать две строки на порозаполнитель:
одну для дуба сращенного,
другую для дуба цельноламельного.

Можно ли записать правило одной строкой, в которой указать:
Параметр=материал сырья
Вид сравнения: ИЛИ
Значение: дуб цельноламельный, дуб сращенный.?

Если бы параметр этот был бы недоступен для остальных материалов (сосна и лиственница), то в правиле можно было бы указать вообще только параметр Поверхность со значением =гладкая, но та как он доступен, тогда мне надо привязывать еще и к материалу сырья (дубу в частности), чтобы спецификация правильно считала, даже если человек ошибется и случайно укажет поверхность гладкая для сосны или лиственницы.

**Comment by aribaz** [comment]
Сейчас по какой-то причине цвет водоотводного профиля наследуется от цвета изделия, хотя во вставке (1326) описано, что он должен зависеть от параметра Цвет доп. профиля (тип значения Цвет).

Как это исправить?

Еще одна странность: на стороне 1С я поправила список возможных цветов для параметра Цвет доп. профиля и ограничила его 2 цветами, вставку 1326 тоже поправила с учетом этих корректировок, но на стороне браузера я все равно вижу прежний список связи параметров Цвет доп. профиля (браузер я и обновляла, и историю очистила). 

Разве ограничение  по использованию цветов не в Цвето-ценовых группах мы должны назначать? Ведь это только наша база.

У меня часто встречается такая проблема со списками видимости параметров.

**Comment by unpete** [comment]
> использовать оператор И/ИЛИ

Элементы условий в ключах параметров складываются по **И**.
Из-за необходимости поддерживать совместимость с 1С, объединение по **Или** сделать проблематично. Вместо этого, рекомендуется использовать виды сравнений _В списке_ и _Не в списке_

@aribaz  Задачу надо адресовать технологу.
В такой постановке, как сейчас, я не знаю, чем могу быть полезен.
Вопрос про настройки ваших справочников, а не про работу движка.

**Comment by aribaz** [comment]
А по вопросу
Параметр: Эффект покрытия - не видно значения "матовый".
Параметр: Дер.НизРама - не видно значения "Паз под подоконник с двух сторон"

Это к технологу или к вам?

Эти ведь параметры в справочнике Параметры продукции есть, только значения этих параметров не все видны на стороне браузера.

**Comment by unpete** [comment]
> Это к технологу или к вам

Я люблю отвечать на вопросы "как это устроено изнутри". Если будете слушать - подробно расскажу про каждую строчку кода

> только значения этих параметров не все видны на стороне браузера

Вчера обнаружил снятую галку _Активность_ в настройках обмена с сайтом. Кто и когда её снял - загадка. Скорее всего, параметры, которых не видно просто не были отправлены в базу сервиса. Перезаписал _матовый_ и _Паз под подоконник с двух сторон_ - теперь они есть на стороне сервиса

**Comment by nmivan** [comment]
@aribaz , по этой задаче остались вопросы?

**Comment by aribaz** [comment]
@nmivan Закрываю, все вопросы закрыты уже
