### ISSUE TITLE
Трансляция свойства _цвет_ во вложенную вставку

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#232]
Евгений, посмотрите пожалуйста вставку 1296 (Дер. лак).

Не правильно применяются ЛКМ, в правилах описано одно, а в спецификацию попадает другое.

Правила я сама исправляла согласно фактической схеме применения, и в качестве параметров указывала только те, которые непосредственно влияют на применение конкретной номенклатуры.

**Comment by aribaz** [comment]
В большей степени это касается номенклатур ЛАК (их 4) и Грунт (их 3).
Изолянт и порозаполнитель применяются правильно.

Я вчера дополнила  списки цветов для групп Прозрачных (цвета Дуб 01... 20) и Глухих цветов (RAL все) недостающими цветами, но это никак не повлияло на спецификацию.
При выборе цветов RAL и Дуб - ЛКМ совсем никакие не попадают в спецификацию, как и до их внесения в группы.
При выборе прозрачного цвета (отличного от Дуб) в спецификацию не попадает только ЛАК, попадает грунт (правда не тот, что должен).
Грунт не учитывает выбранные пользователем параметр Качество покрытия и всегда ставит Грунт AQUA PRIMER 2900-02 COLOR, хотя по правилам он для качества покрытия=эконом.
Лак считается только для цвета Белый, но все равно не правильный.

Для составных цветов в спецификацию не попадают ЛКМ, только работа по окраске.

**Comment by unpete** [comment]
Реализовал [проброс цвета во вложенные вставки](/oknosoft/windowbuilder/commit/b2619dd4780173f5c1c436f9ae32e5e042a8cdfa) - тестируйте

**Comment by aribaz** [comment]
Для тех позиций, которые не привязаны к конкретному цвету или группе цветов при двухцветной окраске появляются 2 строчки с цветом: улицы и помещения.
А что делать с номенклатурами, которые зависят от непосредственно цвета? Эти позиции не появляются.

**Comment by aribaz** [comment]
Позиции привязанные к цвету не срабатывают при двухцветной окраске изделия:
Лак AQUATOR 2600-83 CLEAN WHITE - цвет элемента белый
Лак AQUATOR 2600-24 SG BASE T Color - цвет элемента в списке Прозрачные цвета
Лак AQUATOR 2600-83 RAL 9010 - цвет элемента <>белый и в списке глухие цвета
Изолянт Protec 370 - цвет элемента  в списке Глухие цвета
Изолянт Protec 330 - цвет элемента в списке Прозрачные цвета
Изолянт Protec330/1 - цвет элемента в списке Прозрачные цвета
Пропитка AQUAfiller 1100 VALKOINEN - цвет элемента в списке Прозрачные цвета
Пропитка AQUAfiller 6400-00 WHITE - цвет элемента Глухие цвета

А сегодня выдает сообщение 
![2017-05-05_10-30-20](https://cloud.githubusercontent.com/assets/22028048/25736973/e2e84d54-317d-11e7-971f-b8c357fd6989.png)
При попытке создать составной цвет
Если для изделия цвет один с двух сторон, то эти позиции работают нормально.

**Comment by unpete** [comment]
> А сегодня выдает сообщение [...]

Какое это имеет отношение к теме задачи (трансляции цвета во вложенную вставку)?

**Comment by unpete** [comment]
Ранее, трансляция цвета была добавлена в блок _расчета_ спецификации.
Реализовал аналогичную трансляцию в блок _фильтрации_ - можно тестировать после перезапуска браузера.

**Comment by aribaz** [comment]
Спасибо большое, все работает!!
