### ISSUE TITLE
Угол к горизонту

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#235]
@unpete 
  Евгений, помогите пожалуйста разобраться с углом наклона профилей к горизонту.

Предположим, я хочу нарисовать трапецивидное изделие.
У меня получается его нарисовать правильно только так:
![2017-02-22_16-20-46](https://cloud.githubusercontent.com/assets/22028048/23213397/cea1a60a-f91b-11e6-843c-0241f47ea2ae.png)
 
Если я угол делаю больше, то уже конструкция неправильная разрыв по наклонному профилю в угловых соединениях. Вот так
![2017-02-22_16-23-05](https://cloud.githubusercontent.com/assets/22028048/23213457/03f39c8c-f91c-11e6-9966-5af80f78e334.png)

Если я правильно поняла матчасть, то угол к горизонту этой вставки должен описываться во вставке этого профиля, в данном случае Рама83 (вставка 1285).

В ней в ограничениях ко всей вставке в целом написано min 0 max 360,
а непосредственно в строке с этим профилем (спецификация этой вставки) - min 0 max 0, то есть получается, что я бы даже не смогла его нарисовать в виде трапеции и при моих 19градусов   (первый рисунок). 

Угловое соединение этого профиля (Дер83 - 853)  по углу ограничений не имеет.

Где можно исправить это ограничние? Потому что по факту мы можем сделать на производстве и с углом больше 19 градусов, и по большому счету для рам у нас ограничений нет, максимум могут быть для створок с точки зрения фурнитуры.

**Comment by unpete** [comment]
Угловые диагональные и T соединения допускают любой угол между элементами.
В L-соединениях есть внутренние ограничения движка.
Если соединение называется _Угловое к горизонтальной_, примыкающий (вертикальный) элемент, можно наклонять как угодно, но тот, к которому он примыкает, должен быть горизонтальным в пределах некой дельты.
Если соединение _Угловое к вертикальной_, можно как угодно наклонять горизонтальную палку, но вертикальная должна быть примерно вертикальной.
Возможно, эти принципы нужно пересмотреть. Названия соединений унаследованы из суперокон. Они не точно отражают суть L-соединений.

**Comment by aribaz** [comment]
Получается для соединения Угловое к горизонтальной, коим является соединение описанное мной и изображенное на рисунке Дер.83 эта самая дельта и лежит в пределах 0-19градусов (вверх и/вниз от горизонтали).

А можно где-то эту величину изменить?

**Comment by unpete** [comment]
> А можно где-то эту величину изменить?

@aribaz  @Zmei99 Сейчас важнее не изменять величину, а объяснить мне, какой из элементов считать горизонтальным, а какой - вертикальным, если они оба наклонные.
Проблема не в расширении диапазона углов, а архитектурной ошибке L-соединений, унаследованных из суперокон.
Соединения _Угловое к горизонтальной_ и _Угловое к вертикальной_, надо выкидывать и разрешать вместо них T в углу - будет работать одинаково для рам и импостов и проблем с углом между элементами не будет.

Понятно, что выкидывать убогие соединения надо без революций - в рабочем порядке в течение года.

**Comment by unpete** [comment]
В разделе _Константы и списки_ есть раздел _Построитель_ и в нём параметр _orientation_delta_ - указал там 40 для вашей базы. Там есть еще интересные параметры - загляните.
![image](https://cloud.githubusercontent.com/assets/12096477/23496865/44087a50-ff42-11e6-9257-9d91ce12de07.png)

**Comment by Zmei99** [comment]
@unpete а есть уже где-то в вики описание этих параметров -что за что отвечает?

**Comment by aribaz** [comment]
@Zmei99 Спасибо
