### ISSUE TITLE
Формула стеклопакета на эскизе

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#237]
Добрый день, Евгений.

Вы реализовали подпись стеклопакетов на чертеже, это очень здорово, а можно еще в текст добавить номер элемента?
А то если их много в изделии и все примерно одинаковые - так будет производственникам проще понимать какой - куда нужно поставить.

**Comment by unpete** [comment]
Эскиз для производства может отличаться от эскиза внутри рисовалки.
У нас запланирован отдельный слой с номерами элементов - не только для заполнений.
Рано или поздно, этот слой будет содержать нужные данные.

**Comment by nmivan** [comment]
@aribaz , эта задача актуальна?

**Comment by aribaz** [comment]
@nmivan да. это было бы очень удобно, особенно когда в изделии куча схожих по размерам стеклопакетов (использование горбыльков).
Не могу сказать, что горит, но удобства добавит.
