### ISSUE TITLE
Список соединений || в браузере

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#238]
Евгений, добрый день.

А нельзя сделать так, чтобы на стороне браузера было видно список соединений примыканий и возможность выбрать необходимое из списка - если для этих профилей есть несколько вариантов соединения?

Сейчас если выделить два профиля, то видно только одно, самое первое созданное и применяется тоже оно.
Я мучаюсь с тем соединением, про которое я вам говорила - несимметричный горизонтальный импост и створки заходят в него на разную глубину снизу и сверху.

**Comment by unpete** [comment]
Скорее всего, вы выделяете элементы не в той последовательности. У II соединений есть элементы первый и второй.
Сейчас видны все соединения, но замечание принимается. Надо автоматически менять местами внешний и внутренний элементы при выделении.

**Comment by aribaz** [comment]
Спасибо. Помогло.
