### ISSUE TITLE
Непонятное поведение шаблонов

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#239]
Евгений, добрый день.

У меня шаблоны уже около часf ведут себя странно.
![image](https://cloud.githubusercontent.com/assets/22028048/23556475/d203a8d8-003d-11e7-9492-c2ef883acc6d.png)
Система Дер. трехстворчатое, Шаблон - 4-х створчатое.  Я час назад его использовала и все было хорошо, а это я его просто вставила и ничего не поменяла в нем даже.

До этого в Шаблон свободное проектирование вставила импост 115 вертикально и в просветы вставила створки, и вместо рассотяния 23 мм между створкам, как раньше было получилось 71мм. Соединение  Импост/Створка 79 (бок) никто не трогал, при этом пару часов назад такой ошибки не было.

Это чем можно объяснить? И как это исправить?
это выдало F12
![2017-03-03_18-26-35](https://cloud.githubusercontent.com/assets/22028048/23556930/463ce8e4-003f-11e7-9166-495df7bf465a.png)

**Comment by unpete** [comment]
Изменён алгоритм определения положения сегментов створок в изделиях с импостами.
Замечание учту.

**Comment by unpete** [comment]
Решено, можно тестировать.

@Zmei99 просьба обратить внимание:
В справочник систем добавлен реквизит _ПоложениеСтворокПоИмпостам_ - по умолчанию сброшен.
Соответственно, сегменты створок никогда не получают положения _Центр_, а бывают только верх, прав, лев, низ.
В балконной раздвижке параметр _ПоложениеСтворокПоИмпостам_ надо взводить. Это позволяет при определении вставки по умолчанию автоматически подставлять _створка центр_

**Comment by aribaz** [comment]
Спасибо, работает.

**Comment by Zmei99** [comment]
@unpete 
>В справочник систем добавлен реквизит ПоложениеСтворокПоИмпостам - по умолчанию сброшен.
Соответственно, сегменты створок никогда не получают положения Центр, а бывают только верх, прав, лев, низ.
В балконной раздвижке параметр ПоложениеСтворокПоИмпостам надо взводить. Это позволяет при определении вставки по умолчанию автоматически подставлять створка центр

Принято! просмотрел!!
