### ISSUE TITLE
Размер филенки (неправильный).

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#240]
@unpete Евгений, добрый день.

У нас в качестве заполнений может служить не только стеклопакет, но и филенка.
Я нарисовала дверь, и в нижней части надо было заменить стеклопакет на филенку, что я и сделала, только при этом размер филенки тоже изменился. Хотя кроме как наименования элемента я ничего не поменяла.

Надо 536х535 (как при стеклопакете), а стало 554х573 (при филенке).
Для филенки соединений отдельных не делали.
Вставка 1367.

Как это можно исправить?

**Comment by unpete** [comment]
> кроме как наименования элемента я ничего не поменяла

У элемента нет наименования.
У него есть **вставка** - это ссылочный тип
У вставки есть вычисляемое свойство - **номенклатура**
У **номенклатуры** есть **соединение** с соседним элементом, а у **соединения** есть **размер**, который влияет на размер нашего элемента
Для профилей, первичный фильтр делается по номенклатуре, для заполнений, учитывается только толщина вставки
Ранее описанные у вас заполнения, имели ведущую номенклатуру - алгоритм отрабатывал корректно.
Вставка _филёнка_ - пример составного заполнения, в котором нет в явном виде итоговой номенклатуры.
Доработал алгоритм - теперь фильтр по доступным толщинам и материалам выполняется более аккуратно

**Comment by aribaz** [comment]
Работает, спасибо.
