### ISSUE TITLE
Соединения || изнутри/снаружи применяются как изнутри/изнутри

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#241]
@unpete 
У нас есть импост Комби (2 типоразмера Дер. ИмпостКомби_93/89 и Дер. ИмпостКомби_83/79). Этот импост не допускает наличия створки с одной из сторон по отношению к импосту. К нему с одной стороны может прилегать только стеклопакет, а с другой стороны или только створка или только стеклпакет, но в купе с техвставкой. Нельзя по обе стороны от него поставить створки. В связи с этими ограничениями  были добавлены некоторые соединения
![2017-03-14_09-02-51](https://cloud.githubusercontent.com/assets/22028048/23887812/1820d584-0895-11e7-965c-8be81d2707fa.png)
![2017-03-14_09-03-07](https://cloud.githubusercontent.com/assets/22028048/23887813/182220ce-0895-11e7-9aa4-2b11f5ea279c.png)

Для этого профиля есть  4соединения типа ||:
Дер. || имп коиби верх ств низ (разрешает соединение со створкой изнутри + уплотн)
Дер. || имп комби низ ств верх(при соед.импоста со створкой снаружи - критич.ошибка, разм -10)
Дер \Ст 40 зап имп.комби тех вст (импост со стеклопакетом изнутри + техвставка)
Дер \Ст 40 зап имп.комби снар (импост со стеклопакетом снаружи без техвставки)

Но при рисовании этого импоста и просмотре соединений по обе стороны от него (без прилегающей створки) соединения одинаковы Дер \Ст 40 зап имп.комби тех вст и попытка заменить его с одной стороны на Дер \Ст 40 зап имп.комби снар - ни к чему не приводит, в списке видно это соединение, я его могу даже выбрать, но через мгновение там опять стоит Дер \Ст 40 зап имп.комби тех вст.

При делении рамы этим импостом по горизонтали сверху от него нельзя ставить створку за это отвечает соединение Дер. || имп комби низ ств верх и оно работает (там размер соединения -10 для наглядности, и в спецификации Критическая ошибка, которая на чертеже красные полосы выдает по створке если все-таки створку вставить).
Если раму этим импостом делить вертикально, то створка по отношению к импосту может быть или слева или справа - здесь важно как нарисовать импост сверху вниз или снизу вверх. Но в таком случае если я ставлю створку и по другую сторону, то размер соединения видно -10, а вот уже красных полос нет. Размер -10 конечно видно, что не так створка стоит, но красные полосы куда более информативны.

Причем получается, что по отношению к створке применяются примерно правильно соединения (за исключением красных полос, они куда-то пропадают) , а по отношению к стеклопакету одинаково по обе стороны  и всегда равно Дер \Ст 40 зап имп.комби тех вст, и не хочет меняться на второе доступное.

[Пример с комментариями на эскизе](https://light.oknosoft.ru/#obj=cat.characteristics&ref=e03716b4-c8db-4d87-cde0-f948031a8ef8&frm=builder&view=orders)

**Comment by aribaz** [comment]
@unpete Еще одна проблема с соединениями, но уже угловыми.
Рисую тоже штульповые створки., меняю на нужные профили и получаю вот что
![2017-03-15_23-59-22](https://cloud.githubusercontent.com/assets/22028048/23971230/2413a138-09de-11e7-9ee2-3a87139385d0.png)

Угловое соединение 1075 (Дер. L ств 79), а в нем нет сочетания Дер. Дв_в/о_120/116 ств с Дер. Дв_в/о_120/116 ств или с Дер. ДвШтульп_в/о_120/116. И из-за него длина профиля 10 735мм, вместо 772.
![2017-03-16_00-04-03](https://cloud.githubusercontent.com/assets/22028048/23970882/9d439132-09dc-11e7-8748-3af38c7c6f07.png)

Все остальные профили створок обеих показывали соединения 1061 - что соответствует действительности, что означает, что правая створка по ширине должна быть равна левой.

Затем в профиле 10 я  меняю соединение 1075 на 1061(Дер. L ств 120 в\о), рассчитываю створку, прохожу по всем профилям створок, у всех показывается 1061, проверяем спецификацию - там тоже все хорошо.

**Comment by aribaz** [comment]
Примерно такая же ситуация и с обычным одностворчатым окном.
Когда мы вставляем в пустую раму створку, то она вставляется с предопределенными профилями и набором фурнитуры. В качестве профилей по умолчанию ставятся Створка79 (буквой П) и по низу Створка низ 79.
Если я начинаю менять одну из стоек створки на другую ширину, то программа для измененного профиля оставляет соединение наложения то, которое было перед этим
![2017-03-16_08-55-14](https://cloud.githubusercontent.com/assets/22028048/23983893/943e37b8-0a27-11e7-8c76-13cc54a948ce.png)
меняю правую стойку на 113 и получаю
![2017-03-16_09-33-07](https://cloud.githubusercontent.com/assets/22028048/23984675/d986310a-0a2b-11e7-828d-90367b2e43e4.png)

после того, как выбираю Дер. L ств 113 в\о, второе становится больше недоступным.

Если то же самое проделать с левой стойкой (и вообще с любой), результат будет тот же.

теперь опять меняю правую стойку и вижу соединение из предыдущей
![2017-03-16_09-35-41](https://cloud.githubusercontent.com/assets/22028048/23984718/139ebd94-0a2c-11e7-87c1-5964e676294c.png)

но пока тестила заметила, что если пользоваться не кнопкой расчет, а просто встать указателем мыши на другой профиль и вернуться, или напрмер сменить окна туда/сюда, то все срабатывает. 
По кнопке расчет длина профиля меняется все же.

Только у меня беда еще вот в чем.
размер створки по ширине никак не должен меняться от того какие варианты профилей я выбираю  в качестве створочных, а он меняется. И на штульповой створке тоже меняется, а не должен.
Вот стеклопакет меняться должен, и он меняется, но габариты створок (как и длины самих створочных профилей нет). Причем размер стеклопакетов меняется всегда правильно, а габарит горизонтальных профилей створок - нет.
![2017-03-16_09-53-49](https://cloud.githubusercontent.com/assets/22028048/23985166/a0ddc4f0-0a2e-11e7-811f-d098c6965c9b.png)
![2017-03-16_10-03-23](https://cloud.githubusercontent.com/assets/22028048/23985405/f6c7b988-0a2f-11e7-9497-50bc9aaae2d2.png)
Вот что я заметила
![2017-03-16_10-16-52](https://cloud.githubusercontent.com/assets/22028048/23985744/c57229ac-0a31-11e7-9bb2-54cff4b40506.png)

Но подобного рода ошибки возникают в любой створке, где вертикали (стойки) створок не одинаковые по ширине.

**Comment by aribaz** [comment]
Если менять ширину поперечин створки и ставить их разными, то размер створки и ее стоек считается одинаково правильно что при одинаковых ширинах, что при разных.

**Comment by aribaz** [comment]
Еще я заметила, что в табчасти когда выделяешь профиль створок вертикальный, то он совпадает с размером створки.
![2017-03-16_12-56-45](https://cloud.githubusercontent.com/assets/22028048/23990762/1a7e0b4e-0a48-11e7-821a-6bf371f0731c.png)

А для горизонтальных профилей створок, не совпадает. И вообще не дает низ створки как надо, только между профилями и все.
![2017-03-16_12-59-07](https://cloud.githubusercontent.com/assets/22028048/23991081/32faac12-0a49-11e7-953d-0cd57badc3a8.png)
и Именно этот размер меняется при изменении боковых профилей. Как будто к этим цифрам он прибавляет ширину профилей и все, и поэтому и получаются разные размеры. Мне так кажется.
Может проблема здесь?
Хотя на закладке слои, ширину створки считает правильно 756 при любых ширинах боковушек.

**Comment by aribaz** [comment]
С размерами рамы такая же ситуация, только рамы в спецификации считаются правильно.
![2017-03-16_16-38-15](https://cloud.githubusercontent.com/assets/22028048/23999185/981be3a8-0a68-11e7-9741-49e83415050d.png)

**Comment by aribaz** [comment]
И для створки справедливо, что 598 - это не длина створочного профиля, а лишь внутреннее расстояние между стойками, только правильно оно считается при обеих боковушках равных 79 (для не штульповой створки) 598 +79+ 79=756, 756+20=776мм.


А если одну из боковушек поменять, то получается так
![2017-03-16_17-37-03](https://cloud.githubusercontent.com/assets/22028048/24002503/feef67a4-0a71-11e7-8e07-acd52122da60.png)

А для рамы так
![2017-03-16_17-47-32](https://cloud.githubusercontent.com/assets/22028048/24002250/4f1f648c-0a71-11e7-8eee-18b9793f5b93.png)

**Comment by aribaz** [comment]
Вот еще вариант ошибки с соединениями, но уже не у меня.
![default](https://cloud.githubusercontent.com/assets/22028048/24045560/9b707f78-0b30-11e7-86ee-fe6e5b0d5954.png)

А предыстория такова. Я подключилась к менеджеру совсем по другому вопросу, но случайно увидела ошибку в верхних горбыльках, решила исправить.
Во фрамуге в качестве горбыльков центральных установили Рама83, хотя конструктор уверяет что выбрала Горбылек 63.  В качестве импостов вертикальных стояли Импост 113, горизонтальный - Импост комби. И в нижней части было 3 створки. Но сейчас не суть, хотя чтобы выбрать раму надо сначала выбрать тип профиля рама.
Я стала исправлять и получилось так, правда там было 2 таких решетки (это я примерно воспроизвела, чтобы показать, то принт скрин не сделала)
![2017-03-17_16-45-38](https://cloud.githubusercontent.com/assets/22028048/24045771/44144e3e-0b31-11e7-83d6-be5f024990fd.png)
И эта веселая решетка числилась как створка, следовательно ее пришлось удалить, но как водится удаляется всегда первой не та, которую выделили, а правая нижняя, а так как таких решетки было две, то две нижние правые установленные правильные створки улетели наверх, и были заново установлены на свои места, в результате и получилась такая картина.

У меня складывается ощущение, что программа помнит что было сначала и игнорирует изменения, точнее сама себе на уме, потому как в некоторых местах все же предлагает правильные варианты, но не ставит их сама - как должна, в некоторых случаях предлагает, но не дает поставить; а в некоторых совсем не то предлагает.
И получается что для профилей имеющих разные соединения снаружи и изнутри ставит как-то их избирательно.

**Comment by unpete** [comment]
пересчет примыкающих соединений при добавлении створки

**Comment by aribaz** [comment]
если просто вставить створку в раму вместо стеклопакета, то срабатывает.

А если вставить сначала импост, то соединения прилегания импоста неправильно применяются.
![2017-03-28_15-50-21](https://cloud.githubusercontent.com/assets/22028048/24405896/1e96db8a-13cf-11e7-820a-66bd9c4277c8.png)
Помимо этого, если поставить створку в обе части (хотя именно с ним так нельзя)
Обе створки отображаются одинаково
![2017-03-28_15-59-12](https://cloud.githubusercontent.com/assets/22028048/24406034/90baf34a-13cf-11e7-849e-39d135f163d5.png)
При этом верхняя отображается правильно.

Увеличила высоту створки верхней  (точнее рамы, но посредством верхнего профиля)  и что-то пошло видно не так
![2017-03-28_16-02-41](https://cloud.githubusercontent.com/assets/22028048/24406137/048c1060-13d0-11e7-869a-fd2575e2c2e4.png)

Дал возможность сохранить в таком виде и вот [что](https://light.oknosoft.ru/?zone=2#obj=cat.characteristics&ref=6ba9090a-d08b-4cec-9a99-92384c0a3528&frm=builder&view=orders) в итоге.

**Comment by aribaz** [comment]
Неправильное отображение нижней створки проходит само, если закрыть/открыть чертеж.
Как только вставляю створку F12 выдает это
![2017-03-28_16-10-24](https://cloud.githubusercontent.com/assets/22028048/24406510/248bd282-13d1-11e7-8e4c-9213ce4bb6d4.png)

**Comment by aribaz** [comment]
@unpete 
  Евгений, у меня здесь осталась проблема с профилями (импост комби в частности), которые имеют два соединения с одним и тем же элементом, но снаружи и изнутри - они разные.
По обе стороны от импоста применяется автоматом соединение изнутри и не важно как рисовать слева направо или справа налево, сверху вниз или снизу вверх.

Так ведь быть не должно. Тут устанешь исправлять все соединения. В спецификацию ведь тоже попадает не то что надо и размеры стеклопакетов и створок из-за этого неправильные.

Можно как-то эту проблему решить? Это же основа изделия.
Этот импост часто используется.

**Comment by aribaz** [comment]
[Пример](https://light.oknosoft.ru/?zone=2#obj=cat.characteristics&ref=4e4e1173-2af8-444b-e899-60ecf7ad3022&frm=builder&view=orders)

**Comment by aribaz** [comment]
У нас 5 импостов, в которых соединения || импостов со створкой/стеклопакетом должны быть разные для сторон изнутри/снаружи (или по спецификации, или по размеру), а применяется не ясно как.

Ставлю импост комби, программа на чертеже по обе стороны показывает соединение снаружи (на эскизе, с размером -10), а в табчасти отображены названия соединения изнутри (по обе стороны),не дает возможности изменить ни с одной из сторон, зато если сохранить/закрыть изделие и снова открыть, то все нормально на эскизе. А вот в спецификации - нет, стойки створок как были меньше, чем надо, так и остались, хотя в табчасти габарит створки стал правильным после сохранить/открыть и уплотнитель тоже изменился. А цена не изменилась, хотя если изменился уплотнитель, цена хоть и немного,но должна была измениться.

![2017-03-29 17 42 11](https://cloud.githubusercontent.com/assets/22028048/24461442/c6058b20-14a9-11e7-810d-08155bd188c2.png)

Как-то это не правильно, мне кажется. У меня практически в каждом окне есть один из этих импостов.
Почините пожалуйста, а то толку нам от всего этого мало. Это же основа.

Я еще не настроила три импоста (снаружи/изнутри), а как их проверять - каждый раз сохранять открывать заново? И есть ли гарантия что в таком случае все верно всегда получается?

**Comment by unpete** [comment]
Могу ошибаться, но соединения снаружи/изнутри подставлялись и подставляются корректно.
Была проблема с паразитными лучами профилей створок: чтобы рассчитать угловые соединения створочных профилей, добавлялись лучи без учета примыканий. Это нормально и правильно, т.к. примыкающие соединения еще недоступны в тот момент, когда рассчитываются угловые соединения.
Удаление этих лучей и расчет геометрии сегментов створок в два прохода должны решить проблему.

**Comment by unpete** [comment]
Проверяйте - учтена сторона ii соединения заполнения с импостом, добавлен признак визуализации при формировании спецификаций соединений и вставок

**Comment by aribaz** [comment]
Спасибо большое, работает.
Соединения применяются правильно. Ошибку критическую показывает на эскизе.

А что означает признак визуализации при формировании соединений и вставок?

**Comment by unpete** [comment]
> что означает признак визуализации при формировании соединений и вставок

В строках спецификации есть поле `dop`
- 0 - строка добавлена технологическим справочником
- 1 - это строка аксессуара
- -1 - это строка визуализации

При добавлении визуализации справочником `фурнитура`, признак `dop=-1` устанавливался и линия ошибки показывалась на эскизе. При добавлении аналогичной номенклатуры справочниками `вставки` и `соединения` признак не устанавливался. Строка про ошибку была в спецификации, но её не было видно на эскизе

**Comment by aribaz** [comment]
По визуализации поняла.

Евгений, пока не закрываю нашла ошибку при замене импоста на другой. Сейчас ролик запишу покажу.

**Comment by aribaz** [comment]
Вот [что](https://youtu.be/1U1GfDs_dnw) обнаружила.

**Comment by aribaz** [comment]
Я закрою эту задачу, потому как соединения изнутри/снаружи применяются верно.
