### ISSUE TITLE
Размер стеклопакетов штульпых створок (дверных) по ширине

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#242]
Если применять в качестве створок профили для створок внутреннего открывания, то все правильно считается см. [пример](https://light.oknosoft.ru/#obj=cat.characteristics&ref=e44d9981-e398-4dd7-bdaa-5ff175af6e6d&frm=builder&view=orders)

Предполагала что для наружных профилей эта ошибка только.

Сейчас попробовала еще раз и не смогла повторить эксперимент.
Вот что у меня получилось если все с нуля отрисовать: 

[Пример без ошибок](https://light.oknosoft.ru/#obj=cat.characteristics&ref=c093d9c1-5a71-4ae9-c4b3-4f6f63b49bfa&frm=builder&view=orders)
[Пример с ошибкой](https://light.oknosoft.ru/#obj=cat.characteristics&ref=4c707bff-44e8-41dc-a64c-ee204bec29df&frm=builder&view=orders) 

Одно могу сказать, что в изделии с ошибкой я профили меняла туда/сюда много раз на разные комбинации, а в правильном варианте сначала отцентрировала положение импоста Би, а потом вставляла створки последовательно и меняла их состав. Единственное отличие - это штульповая створка (в одном месте она справа, в другом - слева), но эту версию проверила если рисовать с нуля правильно то все хорошо и так и так. Импост Би в обоих случаях рисовала сверху вниз.

Срочно не ставлю, но на всякий случай оставлю это здесь. 
Выход я нашла, но что это было и почему.

**Comment by unpete** [comment]
Вчера был изменён алгоритм привязки профилей створок к испоставм и штульпам. Поведение системы должно стать более адекватным.

**Comment by aribaz** [comment]
Дублирую сюда письмо

Я их проверила.
Правильно работает при комбинациях профилей по ширине (слева/справа):
79/79
79/120
120/120
120/79
Остальные варианты дают ошибку в 3 и 6 мм (меньше, чем надо).
113/113 - 6мм
79/113, 113/79, 113/120, 120/113 - 3мм.

**Comment by unpete** [comment]
Добавлен пересчет примыкающих соединений при добавлении створки

**Comment by aribaz** [comment]
113/113 -6мм
79/113 -3мм
113/79 - 3мм
113/120 -3мм
120/113- 3мм

**Comment by aribaz** [comment]
Евгений, спасибо большое!!!!
Все ошибки ушли.
