### ISSUE TITLE
Кнопка на смещение слоя целиком

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#243]
Я забыла после конференции добавить этот пункт.

Как вариант можно например сделать так, чтобы перед тем как добавить еще один контур в блоке на новом слое выделить сначала профиль, показывая тем самым куда ( к какому профилю, соединением наружу от него) должен прилепиться новый контур. 
Тогда не придется точки ловить, а если еще добавить поле для габаритов вставляемого контура будет совсем красота

**Comment by unpete** [comment]
Математику сделал. Двигать слой можно мышкой в инструменте _Панорама_ при зажатом {shift}, либо кнопками со стрелками в том же инструменте. При перемещении кнопками, shift можно не нажимать.
Прилипание к соединителю работает при перемещении кнопкой или мышкой одиночного элемента (рамы) инструментом _Элемент и узел_. При сдвиге слоя целиком, положение соединителей не анализируется.

На выходные запланировал видеоролик по новым механизмам:
- Размерные линии к произвольным точкам профиля
- Позиционирование и сдвиг относительно внешних и внутренних рёбер профиля
- Сдвиг слоя

**Comment by aribaz** [comment]
Перемещать получается, не получается прилепить к другой раме правильно, липнуть у меня получается к соединительному профилю, но чаще всего у той рамы которой липну плывут углы. Хотя, это поправимо. 
Мне осталось разобраться с соединительным профилем (вставка 1403). Где-то там ошибка с прилипанием этого профиля к раме. Или я чего-то не знаю?
![2017-03-17_17-39-36](https://cloud.githubusercontent.com/assets/22028048/24048112/f0f75a4a-0b38-11e7-910f-f61663120fa9.png)

**Comment by aribaz** [comment]
А как соединительный профиль вообще привязывается к раме?
![2017-03-17_17-51-51](https://cloud.githubusercontent.com/assets/22028048/24048715/c1cb9c66-0b3a-11e7-850e-866bbc9624ed.png)

Я предполагала, что к внешнему ребру рамы в стык, у рамы ведь опорная линия снаружи 0, а тут 55 откуда-то. В общем этот момент я не поняла совсем.

**Comment by nmivan** [comment]
@aribaz , задача актуальна?

**Comment by aribaz** [comment]
@nmivan здесь ода задача заплыла в другую.
Перемещать слой целиком просто получается хорошо, не получается подвинуть его к другой раме так, чтобы он прилип к узлу стоящей рамы и у двигаемой рамы не поплыли при этом размеры после передвижения.
В целом научилась это исправлять, но было бы удобнее без исправлений.

А по соединительному профилю, мы с Евгением проводили тест, он сказал надо вносить изменения и их не так уж и мало, я им пока совсем не пользуюсь, деньги это невеликие, а геометрия конструкции плывет. Из двух зол выбираю меньшее.
