### ISSUE TITLE
Групповая вставка импостов

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#244]
@unpete Евгений, добрый день.

Этот инструмент разворачивает свое окно на весь построитель и ужать его можно только по ширине,  Очистить кэш и аппаратная перезагрузка не помогли, он продолжает каждый раз разворачиваться на все окно. Ошибка есть на стороне завода у всех пользователей, у меня она не возникает. 

Я в целом сказала, что наверное к понедельнику ее устранят. И вам пишу, чтобы знали.

**Comment by unpete** [comment]
> Очистить кэш и аппаратная перезагрузка не помогли

Естественно. Размеры окна хранятся не в _кеше_, а в _localsrorage_

> к понедельнику ее устранят

Конечно. Исправить такую ошибку быстрее, чем писать про неё ответ.

**Comment by unpete** [comment]
![image](https://cloud.githubusercontent.com/assets/12096477/24076075/a034fe10-0c4a-11e7-82e9-95b1e8e7b841.png)
