### ISSUE TITLE
Привязка фурнитуры к весу створки

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#245]
Можно ли привязать как-то вес створки к фурнитуре?
 У нас для дверных петель (Отлав, Саймонсверк, Дорлайн) имеет наиболее важную роль не ширина/высота створки, а ее вес вместе со стеклопакетом, на разных петлях разная, но максимальный вес створки 130 кг.
Габаритами конечно можно ограничивать, но если например поставить макс 1100х2700 - створка - то это справделиво для простых стеклопакетов, если в такой створке сделают стеклопакет с триплексным стеклом хотя бы одним, то никакие петли такую створку не выдержат, ее и с меньшими габаритами сложно удержать будет.
Понятно, что и слишком высокие/широкие, но легкие створки тоже вывернет, но тут зрительно видно, а вес на глаз сложно определить - ведь это зависит и от ширины применяемых профилей и от древесины и от заполнения.

**Comment by aribaz** [comment]
Точнее так, я нашла в фурнитуре масса створки макс, а как программа поймет массу створки факт?
Надо в номенклатуре заполнять поля Плотность?
Если да, то что делать для профиля у нас там плотность разная.

**Comment by unpete** [comment]
> Надо в номенклатуре заполнять поля Плотность?

Да

> что делать для профиля у нас там плотность разная.

Значит, реквизит `Плотность` надо продублировать в регистре _Расширение номенклатуры с характеристикой_, что даст возможность указать плотность ключа {Номенклатура+Характеристика}.
Если этого будет недостаточно, есть _формулы_

**Comment by aribaz** [comment]
@unpete 
Что первично для программы?
Вес или габариты створки по ширине/высоте?
Сейчас, когда вес створки максимальный не установлен, то при рисовании створки с габаритами больше, чем разрешено набором фурнитуры, появляются красные полосы, которые нам говорят о том, что размер створки велик для этой фурнитуры.

Что будет если после описания веса комплектующих створки и установки максимального веса конкретного набора фурнитуры, я нарисую створку по габаритам не превышающую лимиты, но использую слишком тяжелый стеклопакет и превышу лимит створки по весу  - будет ли как-то это видно на чертеже (или как-то явно понятно) пользователю?
Чтобы была возможность исправить, а не запустить невозможное в цех.

**Comment by unpete** [comment]
> Что первично для программы

При включенных проверках, первичности нет.
Если по любому параметру случилось нарушение - должна возникать ошибка

**Comment by aribaz** [comment]
Евгений, подскажите.
Единица измерения всех профилей - м.пог.
В характеристиках (каждой) деревянных профилей есть поле Масса (кг) - здесь массу указать за какую длину профиля? 
За 1м.пог.?

И надо ли что-то писать в полях (длина, высота, толщина) - там сейчас везде 0.

![2017-03-30 17 58 36](https://cloud.githubusercontent.com/assets/22028048/24511069/a55623a6-1573-11e7-98d6-df84a0583e88.png)

**Comment by aribaz** [comment]
Или все-таки пользоваться полем Плотность на Главной?

**Comment by unpete** [comment]
Масса и прочите поля в характеристике имеют смысл **только** для продукции.
В материалах эти поля заполнять не надо.
Плотность измеряется в кг на единицу хранения. Для профиля - это масса погонного метра, для заполнений - масса квадратного метра.

**Comment by aribaz** [comment]
Поняла, спасибо

**Comment by aribaz** [comment]
Евгений, добрый.
Я привязала массу профилей и стеклопакетов, назначила ограничение по весу для одной фурнитуры, но не получила зрительную ошибку при превышении лимита.
Что я сделала не так?
Вот [пример](https://youtu.be/cAJ6Y2kOcpY)

**Comment by nmivan** [comment]
@aribaz , задача актуальна?

**Comment by aribaz** [comment]
@nmivan да, актуальна. Позволит менеджерам не ошибиться в фурнитуре на дверях или на больших окнах с двойным триплексом. Но горящей я бы ее не назвала.
