### ISSUE TITLE
Невозможно вставить створку в раму

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#246]
Евгений, добрый день.

У меня не вставляется створка в раму.
Вот что F12 выдает
![2017-03-23_09-31-05](https://cloud.githubusercontent.com/assets/22028048/24234918/d52ade6e-0fab-11e7-82a7-3c7a6c4711da.png)
и это
![2017-03-23_09-34-41](https://cloud.githubusercontent.com/assets/22028048/24234959/fd5c4aee-0fab-11e7-9b41-8a2ba8388697.png)

Аппаратная перезагрузка  убирает первую ошибку, вторая остается, но при попытке вставить створку еще раз, первая ошибка снова повторяется.

**Comment by unpete** [comment]
Сейчас починю. В последние недели я пошел на поводу у клиентов и вместо того, чтобы делать правильно, попытался делать быстро. Это сказалось на качестве.

**Comment by aribaz** [comment]
Работает, спасибо.
