### ISSUE TITLE
Значения В списке/ Не в списке

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#247]
[Пример](https://light.oknosoft.ru/?zone=2#obj=cat.characteristics&ref=50a92b5a-70b5-4736-a875-9eb000a30ee3&frm=builder&view=orders)

![2017-03-28_08-41-49](https://cloud.githubusercontent.com/assets/22028048/24391046/5627687e-1395-11e7-8db5-bca635540344.png)

По идее должен был появиться параметр Дв замок в табчасти, а его нет.
![2017-03-28_09-01-22](https://cloud.githubusercontent.com/assets/22028048/24391053/61ab7c9e-1395-11e7-9cea-5d7b386fce17.png)
Возможно из-за этого и нет позиции 55489

Тогда я перепривязала эту номенклатуру к списку из другого параметра (ручка). Но 55489 все равно не появилась в спецификации.
![2017-03-28_09-05-39](https://cloud.githubusercontent.com/assets/22028048/24391137/04c02100-1396-11e7-84c0-66c8df3d24ad.png)

**Comment by unpete** [comment]
Алгоритм на стороне браузера изменил - тестируйте

**Comment by aribaz** [comment]
Работает, спасибо.
