### ISSUE TITLE
Одновременная правка заказа

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#249]
Евгений, добрый день.

Вот еще с чем столкнулась.

Программа позволяет двум пользователям одновременно находиться в заказе и править его обоим пользователям.

А если делать в одном изделии противоречащие изменения из-под каждого пользователя? Что будет?

Может если я открыла уже открытый кем-то ранее заказ, то для меня только в режиме Чтения?
Мы так один заказ с менеджером одномоментно правили, а на следующий день мы видели его с нулями по цене, перезагрузки не помогли. Пришлось вручную ставить кол-во другое и потом снова необходимое, сохранить заказ и цены появились.

**Comment by unpete** [comment]
Вспомните штатный сценарий работы:
- Автор редактирует заказ в статусе _Черновик_ или _Отозван_
- После отправки документ становится _ro_ для автора
- Менеджер правит заказ _На согласовании_ - либо утверждает, либо отклоняет

_Гонок_ в такой схеме не возникает.

**Comment by unpete** [comment]
> Может если я открыла уже открытый кем-то ранее заказ, то для меня только в режиме Чтения?

Нет. С учетом offline, вы не знаете, сколько еще человек на своих offline устройствах просматривают или редактируют некие объекты
