### ISSUE TITLE
В створке не отображается набор фурнитуры

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#251]
Когда в раму вставляем створку, то в разделе Свойства створки в поле Фурнитура - пусто, но на эскизе отображена поворотно-откидная и в спецификации какой-то набор учтен уже, а вот какой именно?
![2017-03-29_08-18-45](https://cloud.githubusercontent.com/assets/22028048/24439716/9d548448-1458-11e7-9a59-20d957e41496.png)

**Comment by unpete** [comment]
> Когда в раму вставляем створку, то в разделе Свойства створки в поле Фурнитура - пусто

Не смог такое повторить на ваших данных

> какой-то набор учтен уже, а вот какой именно

Тот, который указал технолог в качестве значения по умолчанию для текущей системы. В вашей базе, для всех систем указана одинаковая `MACO поворотно-откидная`
![image](https://cloud.githubusercontent.com/assets/12096477/24440919/6b4ee714-1470-11e7-85a4-312b7340f6dc.png)

**Comment by aribaz** [comment]
Она получается так.
Вставляем створку и пока какой-то элемент не выделю, то название набора и его параметры не отображаются в табчасти, но при этом в спецификацию попадает набор по умолчанию.
Как только после вставки створки выделяю какой-то элемент, то через секунду все отображается.

**Comment by unpete** [comment]
> пока какой-то элемент не выделю, то название набора и его параметры не отображаются в табчасти

Это штатное поведение.
Табчасть с параметрами фурнитуры смотрит на текущий активный слой.
Наверное, будет интуитивно понятнее, если слой вставляемой створки автоматически делать активным - код добавлю.

**Comment by aribaz** [comment]
Поняла.
