### ISSUE TITLE
Отсутствуют варианты для вставки Заполнений

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#254]
Вставки со стеклопакетами не доступны в списке видимости, кроме филенки.

**Comment by aribaz** [comment]
Ошибка появилась 30.03 где-то в районе 19:00 +/- час по МСК.
Вы спрашивали когда появилось.

**Comment by aribaz** [comment]
[Видео](https://youtu.be/1U1GfDs_dnw) это о том, как это выглядит со стороны пользователя, смотреть с 7:13

**Comment by unpete** [comment]
> Вставки со стеклопакетами не доступны в списке видимости, кроме филенки

Список вставок в заполнения фильтруется по двум полям:
- тип вставки = _Заполнение_
- толщина вставки (вычисляется по вложенным номенклатурам) = _Диапазон, указанный в системе_

В вашей базе присутствует куча вставок с устаревшими типами _Стеклопакет_ и _Типовой стеклопакет_. Эти вставки по понятным причинам, не видны в списках выбора в браузере.
Если пометить лишние вставки на удаление, а в тех, что нужны, указать `тип вставки` = `Заполнение`, жить станет намного лучше и веселее.

**Comment by aribaz** [comment]
Здесь все правильно?
![2017-04-14_11-29-45](https://cloud.githubusercontent.com/assets/22028048/25038154/da7b2228-2105-11e7-9244-ba8e226bc86c.png)

**Comment by aribaz** [comment]
В интересующих меня стеклопакетах (СПД 40мм...) - которые не доступны я везде исправила тип вставки на **Заполнение** уже давно, толщина у номенклатур, которые сидят в ставках с подобным именем 40мм - это я сейчас проверила еще раз.
Но именно они мне нужны и именно они и не видны.

Вставки с типом Стеклопакет и типовой стеклопакет я пометила на удаление, сейчас.

**Comment by aribaz** [comment]
Теперь вот что видно

![2017-04-14 11 55 16](https://cloud.githubusercontent.com/assets/22028048/25038865/7de4658e-2109-11e7-85a3-af09afd8bf34.png)

А надо вот что:

![2017-04-14_11-58-31](https://cloud.githubusercontent.com/assets/22028048/25039008/37b2ffac-210a-11e7-927b-ee0e895dbded.png)
еще
![2017-04-14_11-59-07](https://cloud.githubusercontent.com/assets/22028048/25039017/40434032-210a-11e7-950b-4d4e34c8d68b.png)
и еще
![2017-04-14_11-59-28](https://cloud.githubusercontent.com/assets/22028048/25039027/50de69bc-210a-11e7-97aa-d6bdc08f062e.png)


Все остальные в общем-то не наши и остались от тех времен, когда база была одна на всех. Может их просто пометить на удаление и будет нам счастье?

**Comment by aribaz** [comment]
Работает, методом ввода от руки и последующим выбором.
Видно все что надо, кроме Стеклопакет заказной 40.

Все остальное правильно работает.

**Comment by unpete** [comment]
Кроме толщины и типа вставки, есть еще одно поле: _Тип вставки стеклопакета_.
Если оно пустое или = _Заполнение_, вставка доступна для выбора в качестве вставки заполнения.
Если в этом поле указан _газ_ или _рамка дистанционная_, такие вставки обрезаются.
В древние времена, в этом поле было написано _стекло_ и это значение оставалось в ваших вставках на стороне браузера. Перезаписал нужные вставки - стало хорошо

**Comment by aribaz** [comment]
СПАСИБИЩЕ!!!

Все работает.
