### ISSUE TITLE
Самопроизвольная замена профиля низа створки

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#256]
Дано: два контура рама с импостом/или без него и створка
При смещении профиля наружнего контура (рама, импост) горизонтального положения посредством размерных линий один из горизонтальных профилей створки превращается в профиль Импост комби сам по себе и соответственно угловые соединения со стойками створки у этого импоста показывают ошибку.

[Здесь ](https://youtu.be/1U1GfDs_dnw) есть пример с импостом, но если менять размер рамы по высоте с уже вставленной створкой, ошибка такая проскальзывает, но не могу понять как ее воспроизвести.

Это видео уже было. Смотреть  с 5:10

**Comment by unpete** [comment]
> Дано: два контура ...

Два контура не нужны. Одного вполне достаточно. Проблема возникала при вычислении свойства `pos`. Нижний профиль переставал быть нижним (или правый переставал быть правым) после изменения габаритов

**Comment by aribaz** [comment]
Работает, спасибо.
