### ISSUE TITLE
Смещение импоста

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#257]
Смещение импоста посредством размерных линий стало работать не так, как раньше.

[Пример](https://youtu.be/1U1GfDs_dnw) смотреть с 4:26

**Comment by unpete** [comment]
Происхождение проблемы понятно. Пару недель назад я разрешил Т соединения в
углах, но не успел доработать алгоритмы привязок. Сейчас, при смещении
элементов, система ведёт себя не очень адекватно.

**Comment by unpete** [comment]
Закрываю, т.к. дублирует #256
