### ISSUE TITLE
prev.generatrix.angle_to в классе Filling

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#259]

**Comment by unpete** [comment]
можно тестировать после перезапуска браузера

**Comment by aribaz** [comment]
Она есть в координатах, а в спецификации ее нет.
Но на чертеже  теперь смотрится нормально и в табчасти есть про нее данные.

**Comment by unpete** [comment]
> есть в координатах без нулей, а в спецификации ее нет

Какое изделие, какая вставка, какие соединения?

**Comment by aribaz** [comment]
Вот [пример](https://light.oknosoft.ru/?zone=2#obj=cat.characteristics&ref=9f44959b-93fb-4095-d0e4-8d4390d6c733&frm=builder&view=orders)

**Comment by aribaz** [comment]
не подставляется соединение T для раскладки с раскладкой (вставка 1404), 

![2017-04-13_16-13-25](https://cloud.githubusercontent.com/assets/22028048/25006318/27c92a80-2065-11e7-9e15-61f8c88759cd.png)

оно описано 1124
![2017-04-13_16-15-26](https://cloud.githubusercontent.com/assets/22028048/25006336/36237392-2065-11e7-9760-8558104fb69c.png)

есть еще соединение раскладки с пустотой 1127.
Хотя для вертикальной палки все соединения есть, но она тоже не попадает в спецификацию.
![2017-04-13_16-23-41](https://cloud.githubusercontent.com/assets/22028048/25006475/afacb976-2065-11e7-9282-cba1bf913150.png)

Вот это [окно](https://light.oknosoft.ru/?zone=2#obj=cat.characteristics&ref=d23037cd-6e5f-4aa0-82c2-0565987c95b1&frm=builder&view=orders)

**Comment by unpete** [comment]
Добавил `generatrix` в Filling, `nearest` в Onlay - можно тестировать

**Comment by unpete** [comment]
Инструмент групповой вставки раскладки работает не идеально. Раскладку пока лучше добавлять пером инструмента рисование - это отдельная не срочная задача.

**Comment by aribaz** [comment]
Раскладка появилась, только не в том количестве, как должно.
У мен должно было получиться по шт каждой длины
![2017-04-27_20-30-36](https://cloud.githubusercontent.com/assets/22028048/25496142/89a3e5fa-2b88-11e7-8739-005beec8bf36.png)
![2017-04-27_20-29-02](https://cloud.githubusercontent.com/assets/22028048/25496149/9047b2ec-2b88-11e7-80e3-0e363e35cc2e.png)
Рисовала с помощью пера.

**Comment by aribaz** [comment]
Все работает, спасибо.

**Comment by aribaz** [comment]
Евгений, добрый день, у меня перестала работать раскладка. 
Она прорисовывается, но в спецификацию не попадает.
После сохранения изделия и повторного открытия на эскизе ее нет совсем, а на вкладке Координаты строки есть, но координаты и количество 0
![2017-05-12_12-10-34](https://cloud.githubusercontent.com/assets/22028048/25991556/380e7220-370c-11e7-937e-b12cdbb628a4.png)
Вот [пример](https://light.oknosoft.ru/?zone=2#obj=cat.characteristics&ref=2e2db5e9-4c19-4a88-a0ab-a158a403bca4&frm=builder&view=orders) с ней

**Comment by unpete** [comment]
Проблему не понял. В примере по ссылке, у заполнения нет нижнего соединения - оно красное и подчеркнутое. То есть, система не может рассчитать размеры этого заполнения и раскладок, родителем которого является это заполнение.

**Comment by aribaz** [comment]
Евгений, извините. 
Все работает, спасибо.Это я ошиблась.
