### ISSUE TITLE
Пересчет изделия при изменении системы

### ISSUE THREAD

**Issue by unpete** [oknosoft/windowbuilder#26]
- [x] пересчет вставок в профили и соединений профилей при изменении системы
- [x] пересчет заполнений
- [x] пересчет доступных вставок в инструменте _рисование_

**Comment by Oparin-Igor** [comment]
https://light.oknosoft.ru/new/#obj=cat.characteristics
<https://light.oknosoft.ru/new/#obj=cat.characteristics&ref=d8a99214-765c-49
03-9eca-e96dbf839bc5&frm=builder&view=orders>
&ref=d8a99214-765c-4903-9eca-e96dbf839bc5&frm=builder&view=orders

не передаются <параметры изделия> из параметров продукции.

 

  _____

**Comment by unpete** [comment]
Исправлено
