### ISSUE TITLE
Формула в строке спецификации вставки

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#260]

**Comment by aribaz** [comment]
Не считается количество, но работает привязка к параметру материал сырья.

**Comment by unpete** [comment]
> Не считается количеств

В каком изделии, у какого элемента, вклад какой вставки, сколько ожидаете, сколько получаете?

**Comment by aribaz** [comment]
Вернее не так, количество (площадь) равно 1
Я насколько помню, вы временно ставили 1 в формуле
![2017-04-29_21-53-01](https://cloud.githubusercontent.com/assets/22028048/25558000/5b5f509a-2d26-11e7-91be-d9a01f7d8a14.png)
https://light.oknosoft.ru/?zone=2#obj=cat.characteristics&ref=8119167d-21f0-416f-9cb0-66c8fc3a5da6&frm=builder&view=orders

**Comment by unpete** [comment]
Задачу решил переименовать. Последствия у решения будут серьёзные.
Сейчас при расчете спецификации вставок, формула выполняется _только_ если `способ расчета количества` = `по формуле`. Это не правильно. Формула в общем случае, не обязана ничего знать про количество, а может, например, корректировать характеристику (ровно, как в задаче про филёнку)

Решено:
- Формула в строке вставки будет выполняться всегда, если заполнено поле `Формула`
- Количество рассчитывается по стандартным правилам (например, по площади)
- Если в поле `способ расчета количества` указано `по формуле`, количество автоматически не рассчитывается и автор формулы должен позаботиться о том, чтобы его формула заполнила поля `len`, `width`, `s` и `qty` в строке спецификации.

**Comment by unpete** [comment]
можно тестировать после перезапуска браузера

**Comment by aribaz** [comment]
Евгений, спасибо большое, работает.
