### ISSUE TITLE
Соединение 1134 (ошибка критическая плохо видна)

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#263]
Евгений, посмотрите пожалуйста это соединение.
В нем есть критическая ошибка, только она как будто прячется за этими импостами.

![2017-04-13_16-05-45](https://cloud.githubusercontent.com/assets/22028048/25005861/41ae92a2-2063-11e7-88d9-80db495777b1.png)

**Comment by unpete** [comment]
Создавать соединения, спецификация которых состоит из единственной строки с `критической ошибкой` - грубая ошибка (sic)
Правильнее, просто не создавать тех соединений, которые недопустимы в жизни. Система сама позаботится о визуализации таких проблем. По этому поводу не нужно загромождать спецификацию дополнительными строками.
Удалил лишнее, на мой взгляд соединение `1134` - эскизы стали выглядеть намного лучше.

**Comment by aribaz** [comment]
Нагляднее некуда. Спасибо, очень удобно. 

А давно стеклопакеты красным подсвечиваются? я собственно поэтому и сделала соединение это, чтобы увидели, что так нельзя
