### ISSUE TITLE
Визуализация ошибок в соединениях

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#265]
@unpete Евгений, у меня вот какой вопрос по использованию этой ошибки.

Я удалила все соединения, которые содержали подобную ошибку. Всего у меня таких соединений 7 было.
Как я поняла, сейчас если я попытаюсь в какой-то проофиль установить стеклопакет, а соединения такого нет, то заполнение становится розового цвета, и подчеркивается красным пунктиром тот профиль, который собственно и не допускает этого. К этой категории у меня относятся 5 соединений (1134, 1078, 1086, 1132, 1123). Их я все удалила и потом проверила такие комбинации, программа ведет себя более чем понятно. Это очень круто. Еще раз спасибо. Это соединения профиля и стеклопакета типа ||.

Но вот если не могут (не должны) соединяться между собой || профили, то без соединения с критической ошибкой в спецификации пользователь никак не поймет, что так нельзя. Я проверила, и в этом случае система никак не предупреждает о том что так нельзя, как при соединениях профиля с заполнением. К этой категории у меня относятся 2 соединения 1131 и 1123. Их я пометила на удаление, но программа мне ничего не подчеркнула сама и не выделила. 

Про соединения   "профиль || профиль" так и надо?
Мне снять пометку на удаление?

Я почему такую ошибку ввела, потому что менеджеры часто (очень) совершают подобные ошибки - а физически так делать нельзя - это не окно будет, а набор палок со стеклопакетами; чтобы они видели - что тут они что-то не доработали.

Пометку на удаление пока не снимаю. 
Как здесь правильно поступить?

Пример:
Соединение 1131, говорит о том, что так нельзя
![2017-04-14_16-16-26](https://cloud.githubusercontent.com/assets/22028048/25044184/dfc44052-212d-11e7-87a0-8b8809253b71.png)

После того, как это соединение удалила, программа ведет себя, как будто так можно, ничего не подчеркивает, не выделяет и пользователь ошибки не заметит.

**Comment by unpete** [comment]
Визуализацию ненайденых II соединений профилей добавлю в ближайшее время - задача про это есть, номер не помню.

**Comment by unpete** [comment]
Добавлена визуализация ненайденных примыкающих соединений https://github.com/oknosoft/windowbuilder/commit/84ae99dabf5eb3f109f89a25f18955983f94f444

**Comment by aribaz** [comment]
Спасибо!
