### ISSUE TITLE
Предопределенный параметр (цвет)

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#266]
Запишу сюда.

Мы как-то с вами разговаривали на тему предопределенного цвета для аллюминиевого профиля.

У меня идея такая. В таб части есть параметр изделия Цвет доп.профиля, значение которого выбирает пользователь.
Я бы хотела чтобы значение этого параметра перекочевало в спецификацию в частности к покраске профиля и к самому профилю (алюминиевому)

**Comment by unpete** [comment]
Вопрос не понял. Мне кажется, значение любого параметра можно использовать в формулах.
Какие конкретно изменения вы предлагаете внести в движок параметров?
Если вопрос "как написать формулу", то ответ: "поручить это человеку, знающему javascript"

**Comment by nmivan** [comment]
@aribaz , по этой задаче требуется что-то? Что решили?

**Comment by aribaz** [comment]
@nmivan не могу вспомнить что конкретно имела ввиду, закрываю. 
Если вдруг понадобится и вспомню, возобновлю задачу и напишу пояснения
