### ISSUE TITLE
Высота ручки на эскизе

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#273]
Евгений, сделайте пожалуйста размерную линию для высоты ручки на эскизе.

**Comment by unpete** [comment]
Предлагаю не создавать размерную линию высоты ручки на полном эскизе изделия, но формировать её на отдельном эскизе контура, который система генерирует для безбумажки.
Задачу можно объединить с #274

**Comment by aribaz** [comment]
Согласна, нас устроит.

**Comment by aribaz** [comment]
Решили, что ее мы ставим на ближайшем стеклопакете створки.

**Comment by unpete** [comment]
Автолинию решил не программировать.
Вместо этого, добавил возможность приклеивать пользовательские размерные линии к ручке.
Привязка работает как с внутренней, так и с наружной стороны профиля:
![image](https://cloud.githubusercontent.com/assets/12096477/26370075/24242d1a-4010-11e7-8b27-0b79d3a43849.png)

**Comment by aribaz** [comment]
Спасибо.
