### ISSUE TITLE
Размерные линии дополнительные

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#274]
Евгений. мы сегодня с вами разговаривали о размерах створок на чертежах, чтобы это можно было делать не вручную, а чтобы в печатные формы они попадали самостоятельно без участия пользователя.
Вы сказали, что так можно.
Сделайте пожалуйста.

**Comment by unpete** [comment]
Улучшил алгоритм в инструменте _Ruler_ привязка пользовательских линий должна стать адекватнее.

> чтобы в печатные формы они попадали без участия пользователя [...] сделайте пожалуйста

Это вопрос не к рисовалке, а к подсистеме подготовки производства.
Эскизы с размерами створок система умеет формировать уже сейчас - эта математика готова.
Другой вопрос: как приспособить эту математику к вашему сценарию работы. Предлагаю обсудить на конференции.

**Comment by aribaz** [comment]
Хорошо, давайте.
