### ISSUE TITLE
Параметры изделий/створок в печатных формах

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#275]
Мы сегодня обсуждали возможность вывода параметров изделия в печатную форму посредством проставления галочек напротив необходимых параметров из формы Отчеты по спецификации.

**Comment by unpete** [comment]
- В плате видов характеристик _Дополнительные реквизиты и сведения_ реализовано новое свойство _Включать в описание_
- Свойство учтено в типовом _Отчете по спецификации_ - информация о значениях параметров продукции подмешивается в блок описания строки заказа

**Comment by aribaz** [comment]
Спасибо, работает. Очень здорово.

А можно это свойство учесть в Счете с эскизами тоже?
