### ISSUE TITLE
Цены (новые) на материал не попадает в расчет

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#276]
Евгений, я сегодня создала документ УЦН на раскладку на стороне 1С, браузер перезапустила пару раз, создала новое изделие, нарисовала в нем раскладку, она считается физически, а экономически 0.
![2017-05-16_17-27-04](https://cloud.githubusercontent.com/assets/22028048/26111122/eb5b11d2-3a5c-11e7-8e11-68e77b253c1e.png)
![2017-05-16_17-27-48](https://cloud.githubusercontent.com/assets/22028048/26111164/0bd555c6-3a5d-11e7-852e-0b11aee21698.png)
Вот [пример](https://light.oknosoft.ru/?zone=2#obj=cat.characteristics&ref=7f59f1c2-7f90-4134-f89d-6f81500bffd0&frm=builder&view=orders).

**Comment by aribaz** [comment]
И еще я заметила, что цены, которые я вводила не в рублях на стороне браузера в марте-апреле, они срабатывали, а рублевые  - нет.

Поэтому я создала документы УЦН на стороне 1С только для рублевых материалов, которые не попадали в расчет. Но несмотря на это на все эти материалы (документы УЦН от 16.05.17)  цены не попадают в спецификацию.

**Comment by unpete** [comment]
- Изменён индекс couchdb (срез последних регистра _цены номенклатуры_)
- Добавлена подписка на событие для пересчета кеша цен в браузере при изменении документа установки цен

**Comment by aribaz** [comment]
Цены стали попадать, но некоторые цены в иностранной валюте не умножаются на курс валют.
![2017-05-22_07-49-58](https://cloud.githubusercontent.com/assets/22028048/26293515/fae827e4-3ec5-11e7-87d4-aceed731a409.png)
У нас все Лкм в евро - и для них только один документ УЦН, но почему-то лак умножился на курс, а грунт нет.

Это же касается Силикона, Отвердителя, Клейберита, Наполнителя швов, Уплотнителей (3070, 3053), Фурнитуры - эти цены устанавливались самые первые.

А вот например Клейкие ленты (1 и 2 мм) - умножаются на курс, их я добавляла недавно.

**Comment by unpete** [comment]
Изначально, реквизит `валюта цены` располагался в табчасти документа установки цен.
Это - правильное место, обеспечивающее максимальную гибкость этого документа, но в конце 2016 года для совместимости с КА 2.0, реквизит переместился в шапку документа, а для совместимости с запущенными экземплярами сервиса, был сохранён в табчасти.
Сейчас этот компромисс вышел боком - в регистр попала валюта цены из разных мест.
Убрал валюту из табчасти, обновил индекс - должно работать без сюрпризов - см.: https://github.com/oknosoft/windowbuilder/commit/bd1f0a5d98271a2970f11a072e077cbb8eae229f

**Comment by aribaz** [comment]
Работает, спасибо.
