### ISSUE TITLE
Округление

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#277]
Евгений, добрый день.
Если округлять в печатной форме, то тогда все материалы (строки спецификации) ведь округлятся, а не только профили, а мне нужны только профили.

Я пробовала в шаблоне на закладке Формула к строке
Размеры: row.sz
добавить .toFixed() - по аналогии со строкой Количество: qty.toFixed()
после этого делала перезагрузку и пыталась сделать отчет по спецификации - но программа на эту кнопку не реагировала совсем, а если возвращала в исходное состояние - то работало нормально.
в скобках писала 1,2 и "ничего" - результат одинаков был.

Пробовала row.Math.round(sz*1000/1000) - тоже нет реакции (документ спецификации не появился), хотя я не уверенна в правильности написания. Хотя наверное надо было 100, а не 1000, ведь хочу до 10-ков округлить.

Еще пробовала внутри номенклатуры Рама 83 поставить в поле Округление 1, но ничего не изменилось ни в спецификации ни в печатной форме.

Что я делаю не так?

**Comment by nmivan** [comment]
@aribaz , если задача актуальна, расскажете, где можно пример посмотреть?

**Comment by aribaz** [comment]
@nmivan Здесь речь идет об отчете по спецификации (печатная форма), но в целом я бы применила правила округления математики внутри спецификации.
Отчет по спецификации (столярка) у меня в новой версии не срабатывает, на нем показать не могу - но выше речь о нем.

Могу объяснить на примере спецификации.
![2017-09-14_09-07-44](https://user-images.githubusercontent.com/22028048/30414583-fab2e252-992c-11e7-925c-0ae45946a705.png)
Например Лак (или другие материалы, измеряющиеся в м.пог, кг, и др. не штучные) - его физически нельзя отмерить точнее, чем 1мл. Его единица измерения - л, следовательно в спецификации должно было стоять вместо 0,04488 - 0,045. Равно как и деньги за эту позицию поставщику мы не можем отдать меньше 1копейки, следовательно в деньгах должно быть округление по строкам согласно правилам математики до 1 копейки 27,849835 - нельзя столько отдать/взять можно только 27,85.
Но с учетом того, что я округлила кол-во лака 0,045 и его цены 620,54, получаем 0,045*620,54 =27,9243, округляем по математике до сотых и получаем 27,92, вместо 27,849835.

А в отчете по спецификации тоже такая же схема вычислений, но  мне кажется если округление сделать внутри спецификации изделия - так будет правильнее и с точки зрения определения цены и с точки зрения расхода материалов потом.

**Comment by unpete** [comment]
- внутри спецификации ничего округлять не надо, это служебная информация, на которую вы смотрите через отчеты
- отчет в новой версии сегодня заработает. я вчера починил, но не успел опубликовать обновление
- @aribaz @Felishia напомню, что в элементе справочника _Валюты_ есть поле _округлять до_. Значение этого поля используется в строках документа _Расчет_. Вы можете иметь цены и суммы в рублёвом документе без копеек (или даже с округлением до 100 руб), а в валютном документе округлять до центов.

**Comment by aribaz** [comment]
@unpete, спасибо.
