### ISSUE TITLE
Групповая вставка раскладок/импостов

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#278]
При использовании соединения крест в стык не попадают в спецификацию крестовины.
[Пример](https://light.oknosoft.ru/?zone=2#obj=cat.characteristics&ref=f748b779-9bd2-4a00-d0cc-3535462bb248&frm=builder&view=orders)
![2017-05-18_08-24-04](https://cloud.githubusercontent.com/assets/22028048/26187681/6995da0e-3ba3-11e7-951a-4c5a581c7487.png)
Другим способом не получается нарисовать шпрос, потому что профили липнут друг другу и не дают оставить в месте их пересечения зазор.

**Comment by unpete** [comment]
Добавил расчет спецификации соединений крест в стык

**Comment by aribaz** [comment]
Спасибо, работает
