### ISSUE TITLE
Группа цен контрагентов

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#279]
Евгений, я настроила 3 группы цен контрагентов.
0% (к марж =2) - Светлый дом
5% (Кмарж =2,05) Русокон
25% (к марж = 2,25) Розничный клиент
Но привязка по группам цен не срабатывает, умножается на 2 согласно Кмарж без группы цен.

Поправьте пожалуйста механизм расчета.

**Comment by unpete** [comment]
- В каком заказе смотреть?
- При работе от имени полноправного пользователя, контрагента нужно указывать до расчета изделий. Для пользователя с ограниченными правами контрагент подставляется по умолчанию

**Comment by aribaz** [comment]
[Пример](https://light.oknosoft.ru/?zone=2#obj=doc.calc_order&ref=ba303704-0f7c-4fab-ddaa-43488d47134c&frm=doc&view=orders)
Для этого контрагента установлен Кмарж 2,25, а получилась сумма с коэффициентом 2
Сначала выбираю клиента, а потом рисую изделия.

**Comment by unpete** [comment]
Код исправил - можно тестировать
