### ISSUE TITLE
Обработка для упрощенного заполнения заданий на пр-во

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#282]

**Comment by nmivan** [comment]
@aribaz , есть больше информации?

**Comment by aribaz** [comment]
@nmivan Мы ранее с Евгением обсуждали вопрос упрощенной схемы. У нас на заводе не запускают каждый день по 100шт и более изделий в производство.
И нам по большому счету для запуска достаточно видеть эскиз, список профилей, стеклопакетов и краткую информацию по заказу (тип фурнитуры( не список), цвет ручек, наличие/отстутсвие каких-либо дополнений к заказу, его цвет  - в основном это все, что касается параметров изделия).
Евгений предложил сделать для нас более краткую версию заполнения заданий.
Если кратко, то это все.

**Comment by unpete** [comment]
Сейчас на стороне 1С реализована неплохая математика планирования.
Можно сделать типовое заполнение заданий, а упрощенность учесть в настройках.

**Comment by nmivan** [comment]
Эту задачу закрою, т.к. она входит в более [крупную](https://github.com/oknosoft/windowbuilder/issues/224)
