### ISSUE TITLE
Вставки (в изделие, в контур, в элемент)

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#284]
Добрый день, Евгений.

Не правильно срабатывают вставки. Я записала [мини видео](https://youtu.be/KjWA56pJyds) о том, как это получается.
[Ссылка ](https://light.oknosoft.ru/?zone=2#obj=doc.calc_order&ref=bf13a9f4-4b02-4c9e-de13-aaee140b8c11&frm=doc&view=orders) на заказ, только когда изделие закрываю, оно его не дает сохранить, только закрыть без сохранения изменений.
У нас в каждом заказе есть подоконники, москитки и отливы, без них я не могу сделать полноценный заказ.
Почините пожалуйста.

**Comment by unpete** [comment]
Проблема была в неаккуратной установке _тихого_ режима при сохранении продукции, при котором, строки в табчасть добавлялись корректно, но интерфейс ничего про эти события не узнавал.
Исправлено: https://github.com/oknosoft/windowbuilder/commit/252a3fb5a884034ecd5761b37220c7e0b266797d

**Comment by aribaz** [comment]
Спасибо!!!
Все работает.
