### ISSUE TITLE
Эскиз оконных ручек

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#286]
Евгений, подскажите, как сделать так, чтобы эскиз ручки попал на чертеж?
Фурнитура Двери входные дерево.

**Comment by nmivan** [comment]
@aribaz , задача актуальна?

**Comment by aribaz** [comment]
@nmivan, да актуальна

**Comment by unpete** [comment]
может, @Sehktel или @A-Shimko смогут ответить.
Они большие мастера в визуализации петель, ручек и прочих элементов.

**Comment by A-Shimko** [comment]
Добрый день!
Опишу пример как это делаю я. На примере ручки
1. эскиз визуализации должен быть в формате *.svg
2. я сначала рисую эскиз в AutoCad (не обязательно, это мне так удобнее) и экспортирую в формат *.dxf
![image](https://user-images.githubusercontent.com/24698235/30417123-5040b33e-9937-11e7-83ea-feb170b57024.png)

3. в CorelDraw импортирую файл *.dxf и выставляю центр привязки эскиза на листе:
    - центр эскиза в данном случае штифт
    - а нулевая координата в CorelDraw - это верхний левый угол ЛИСТА
    - выставляю по перекрестию файла и потом это перекрестие удаляю
![image](https://user-images.githubusercontent.com/24698235/30417374-2657208e-9938-11e7-8f77-40a7f00491ca.png)
   Также в помощь выставление центра эскиза по координатам, но в данном случае здесь учитывается центр эскиза по осям, т.е. не "мой" центр, но его легко высчитать
![image](https://user-images.githubusercontent.com/24698235/30417534-c03bd0c8-9938-11e7-8440-e6ba39cda818.png)
 и экспортирую (сохраняю) в формате *.svg
![image](https://user-images.githubusercontent.com/24698235/30417591-f1f2dd1e-9938-11e7-8d17-921ca5018220.png)

4. открываю файл *.svg копирую в буфер нужный текст
![image](https://user-images.githubusercontent.com/24698235/30417629-23464928-9939-11e7-83df-d1ebad3a0c28.png)
в текстовом файле много лирики, нас интересуют символы и цифры заключенные между  d=" и z"/>
![image](https://user-images.githubusercontent.com/24698235/30417881-e19c88f6-9939-11e7-8612-f10a5f55d514.png)
![image](https://user-images.githubusercontent.com/24698235/30417939-071662a0-993a-11e7-9b9b-47234af90cbf.png)

5. в 1С вставляю текст и сразу вижу эскиз с мои центром
![image](https://user-images.githubusercontent.com/24698235/30418056-62808738-993a-11e7-8d4c-dd32029f8ee9.png)
6. назначаю где моя ручка должна появляться, в данном случае это фурнитура
![image](https://user-images.githubusercontent.com/24698235/30418170-c18213fa-993a-11e7-91a2-7c0a5c4baafa.png)

Более того я стараюсь в AutoCad не делать прямоугольников с 4-мя ровными углами, один угол стараюсь скруглить можно и более для симметри, тогда точно все данные при импорте в *.svg будут заключены в d=" и z"/>
Если сделать прямоугольник без скругления углов - то нужную строку в тексте надо еще поискать.
Я не парюсь, скругляю, нахожу, копирую, вставляю.
Можно поиграться еще в полях визуализации 1С "смещением", "сторонами элемента" и т.д.
![image](https://user-images.githubusercontent.com/24698235/30418565-197364c8-993c-11e7-8b31-2f1381f4c5ab.png)
Но, поскольку в большинстве случаев, необходимо поймать центр эскиза я все старюсь делать еще в CorelDraw.
Мой путь не обязателен, главное получить текст формата *.svg, много есть специальных приложений, мне удобнее так.

**Comment by unpete** [comment]
@A-Shimko спасибо за подробный ответ.

**Comment by aribaz** [comment]
@A-Shimko Спасибо, очень, подробно, попробую.

**Comment by blackmixer** [comment]
[ Inkscape](https://inkscape.org/ru/o-programye/) это высококачественный профессиональный инструмент для работы с векторной графикой для Windows, Mac OS X и Linux. Он широко используется любителями и профессионалами по всему миру для создания иллюстраций, иконок, логотипов, диаграмм, карт, а также веб-графики. Inkscape использует открытый стандарт SVG (Scalable Vector Graphics) от W3C в качестве формата по-умолчанию, а также сам является свободным и открытым программным обеспечением.

**Comment by unpete** [comment]
Реклама incscape, это хорошо, но создаваемый им svg содержит много мусора.
Если описывать путь ручками, строка svg будет заметно короче.

**Comment by aribaz** [comment]
@unpete Евгений, подскажите как можно эскиз относительно элемента подвинуть за чертеж?
![2017-11-17_16-00-11](https://user-images.githubusercontent.com/22028048/32948589-d0bbf8d8-cbb0-11e7-8b69-7c4bfd01402d.png)
Я этот эскиз привязала ко вставке профиля. Пробовала использовать смещение разное, и точку привязки и по Х и по Y, но вынести за чертеж вправо не смогла.

**Comment by unpete** [comment]
В каком изделии-вставке смотреть?

**Comment by unpete** [comment]
> https://github.com/oknosoft/windowbuilder/issues/286#issuecomment-345238947

Если смещение известно заранее (например, картинка всегда относится к нижнему элементу), смещение проще заложить в svg (`M 100 200` означает сдвинуть перо на 100 по x и на 200 по y)
Если смещение зависит от положения элемента, его надо рассчитать в соединении, вставке или фурнитуре

**Comment by aribaz** [comment]
Поняла, спасибо.
