### ISSUE TITLE
Арка из двух профилей

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#287]
Евгений, подскажите, что не правильно в моей арке?
Я нарисовала два профиля, потом один изогнула и перенесла его к прямому. 
Но стеклопакет не попал туда.
![2017-05-26_16-37-12](https://cloud.githubusercontent.com/assets/22028048/26496806/a4405e9c-4231-11e7-9c4d-7f4da24a315c.png)
[Пример](https://light.oknosoft.ru/?zone=2#obj=cat.characteristics&ref=115e5877-1263-43e1-e34a-05776df2f19b&frm=builder&view=orders)
Я хотела шаблон сделать.
У арочного профиля координаты по X начало и конец 0,3 (вместо 0) и 1200,9 (вместо 1200) и они вручную не меняются на вкладке Свойства элемента.
Точнее, если я меняю их, то плывут координаты у прямого профиля. И не получается поставить везде  1200 и 0.

**Comment by unpete** [comment]
Доработан алгоритм - см.: https://github.com/oknosoft/windowbuilder/commit/e694b5bb5eb7f5bef60c5d1fb4439bede7d005fa
