### ISSUE TITLE
Не могу удаляется створка на эскизе

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#288]
Евгений, если я удаляю створку, то в табчасти строки с этим слоем нет. а на эскизе она продолжает отображаться
![2017-05-30_16-12-39](https://cloud.githubusercontent.com/assets/22028048/26584818/d9136906-4552-11e7-8cd6-06e4155faffe.png)

**Comment by unpete** [comment]
Ссылка на проблемное изделие была бы полезнее красных меток

**Comment by aribaz** [comment]
Евгений, извините, я забыла про это, а сегодня не могу повторить эксперимент.
