### ISSUE TITLE
Изменение фурнитуры

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#289]
Перестал работать динамический поиск в поле Фурнитура, а так же оттуда исчез выпадающий список, можно изменить фурнитуру только сначала нажав на Показать все и выбрав необходимую.

Если начать писать название необходимой фурнитуры, то поиск не срабатывает и потом поле остается пустым и выбор через Показать все после этого не срабатывает тоже, в спецификации по фурнитуре пусто. Выглядит так.
![2017-05-30_17-08-16](https://cloud.githubusercontent.com/assets/22028048/26587425/0cdbfc46-455b-11e7-83af-8829eba7477d.png)
F12 вот что выдает
![2017-05-30_17-12-37](https://cloud.githubusercontent.com/assets/22028048/26587520/4690007c-455b-11e7-9334-0899ceedc2aa.png)

**Comment by unpete** [comment]
список фурнитуры в сценарии, когда не настроен фильтр доступных фурнитур https://github.com/oknosoft/windowbuilder/commit/0c1062959e6634e3f890e8ecbd150ad2e40a17f5

**Comment by aribaz** [comment]
Спасибо, работает
