### ISSUE TITLE
створки разные по высоте в штульповом окне

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#291]
Евгений, как такое может быть?
![2017-05-31 20 16 09](https://cloud.githubusercontent.com/assets/22028048/26644705/4d6078e4-463e-11e7-9eb9-a93b26863353.png)
![2017-05-31 20 17 10](https://cloud.githubusercontent.com/assets/22028048/26644717/58c7cdd6-463e-11e7-9dee-82d9b5e428e7.png)
Створка ведь никак не может входить в раму торцом, почему он обводит кругом?
и створки по высоте почему-то разные внизу, хотя профиль рамы один и тот же, как и сами профили створки по низу.
[Пример](https://light.oknosoft.ru/?zone=2#obj=cat.characteristics&ref=3c4a4406-0353-4bb5-dcbf-f96428d4b2ec&frm=builder&view=orders)

**Comment by aribaz** [comment]
Ошибок таких раньше не было, я их ранее тестировала.
Если можно, оставьте это до понедельника. У меня на завтра 01.06.2017  назначена  аттестация менеджеров, на предмет рисования свободного.

**Comment by aribaz** [comment]
Такой эффект появляется только если в качестве низа рамы используется Дер. Алюминиевый порог

**Comment by unpete** [comment]
Неадекватности в поведении системы не вижу.
В описанном примере, в левой створке был лишний элемент. Как он туда попал - не очень важно. Скорее всего, штульп удалялся и добавлялся или отрывался от рамы после добавления створки.
Створка по умолчанию не имеет соединения с _Дер. Алюминиевый порог_ - лечится заменой нижних створочных  элементов на _Дер. СтворкаНизУК 79_. При необходимости, можно добавить _Дер. СтворкаНиз 79_ в соединение _Дер. || ств ал порог_

**Comment by aribaz** [comment]
Спасибо, поняла
