### ISSUE TITLE
Некорректная работа спецификации вставок в контур и изделие

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#293]
Евгений, добрый день.

Стали активнее пользоваться вставками в контур и изделие, и вот что обнаружила.
Сама вставка попадает в заказ, а спецификация ее почти/совсем пуста, хотя ранее там было все нормально, спецификацию этих вставок я не меняла.
например:
Это спецификация отлива полиэстэр
![2017-06-07_09-13-15](https://user-images.githubusercontent.com/22028048/26864565-925f934e-4b61-11e7-824c-63c882cb6147.png)
а вот что там должно было быть
![2017-06-07_09-12-56](https://user-images.githubusercontent.com/22028048/26864587-a9e3e10a-4b61-11e7-918b-761f5076b0f2.png)
Ранее сам Отлив полиэстэр попадал в спецификацию вставки Отлив наружный.

Подобная ситуация со всеми вставками в контур и в изделие.
Вставки в элемент работают нормально.
Помогите пожалуйста.

**Comment by unpete** [comment]
> Подобная ситуация со всеми вставками в контур и в изделие

Скорее, не со вставками в контур и в изделие, а со строками спецификации вставок, где количество рассчитывается по формуле. В вашем случае, лечится одним из двух способов:
* для строки _отлив полиэстер_, можно указать способ расчета количества _для элемента_, вместо _по формуле_
* изменить формулу, чтобы она возвращала _1_ вместо _undefined_
