### ISSUE TITLE
Цены/суммы дилера равны нулю

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#294]
Евгений цены и суммы дилера равны нулю для всего кроме Москитки в любом заказе.
![2017-06-07_18-41-38](https://user-images.githubusercontent.com/22028048/26887580-06b9a226-4bb1-11e7-8ca2-f8fe35063023.png)

**Comment by unpete** [comment]
Дублирует #279 - закрываю.
Строки кмарж подбираются в полном соответствии с ключами параметров - тестируйте после перезапуска

**Comment by aribaz** [comment]
Сделала перезапуск Все равно нули в дилерских цифрах.
Сумма поставщика есть, нет суммы дилера.
![2017-06-07_19-26-54](https://user-images.githubusercontent.com/22028048/26889604-65af3858-4bb7-11e7-99ee-d8da6bd80aec.png)

**Comment by unpete** [comment]
Чудес не бывает - проанализируйте свойства контрагента "осень", ключи в маржинальных коэффициентах, наценку, заданную для текущего пользователя в браузере - больше, кажется, на дилерские цены ничего не влияет.
В заказе дилера есть куча неустойчивых алгоритмов, но ценообразование сделано очень надёжно - я не верю в странное поведение этой подсистемы.

**Comment by unpete** [comment]
К дилерским ценам не относится, но решил написать сюда: чтобы для москитки начала подтягиваться формула стоимости продажи, пришлось присвоить деревянным изделиям ценовую группу _Дерево_ и добавить уточнение в маржинальные коэффициенты.

**Comment by aribaz** [comment]
Получается, что если в форме контрагента наценка внешняя равна 0 и наценки/скидки для текущего пользователя тоже 0, то цена дилера и сумма дилера равна 0. Умножение на 0 дает ноль. 
А разве в этом случае сумма дилера не должна быть равна сумме поставщика? (Sдил = Цпост + Цпост*Нац. дил).

Но я обнаружила другую странность Посмотрите пожалуйста https://youtu.be/zUy3lExzNCQ

**Comment by unpete** [comment]
Дублирует #279
