### ISSUE TITLE
Кмарж неправильные цены при первом расчете изделия.

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#295]
[Пример](https://light.oknosoft.ru/?zone=2&couch_path=/couchdb/wb_&couch_suffix=#obj=doc.calc_order&ref=6cfee007-88ec-4cca-bfde-b0b00a4b2564&frm=doc&view=orders)

для Розничного клиента Кмарж =2,25, а срабатывает 2.
2,25 применяется только после пересчета

**Comment by unpete** [comment]
Дублирует #279 
Учтено в https://github.com/oknosoft/windowbuilder/commit/63513eb23f49ebf403c985cd5a29eb91e14f1fa0
