### ISSUE TITLE
Ошибка направляющей

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#296]
Добрый день, Евгений.

У меня вот какая проблема обнаружилась. Если окно арочное, и я пытаюсь нарисовать в нем раскладку, которая одним своим концом должна упираться в арку, то у меня ошибка вылетает как только я начинаю подводить второй конец раскладки к арочному элементу.
![2017-06-16 08 42 53](https://user-images.githubusercontent.com/22028048/27213532-23393d56-5270-11e7-9a15-e56b77509ed8.png)
Пользуюсь при этом инструментом перо.
![2017-06-16_08-49-14](https://user-images.githubusercontent.com/22028048/27213618-bdd5a4c6-5270-11e7-84a2-6bdd2be2e971.png)

**Comment by unpete** [comment]
Нужна ссылка на изделие - на типовом шаблоне ошибка не воспроизводится

**Comment by aribaz** [comment]
У меня теперь тоже это не воспроизводится, закрываю.
