### ISSUE TITLE
Двухцветная покраска

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#299]
Евгений, добрый день.

У меня перестала работать двухцветная покраска.
При выборе ее раньше попадали строки с самими ЛКМ, работами и Двухцветной покраской, а теперь только работы, перестали добавляться ЛКМ и двухцветная покраска.

Я ничего в справочниках не меняла.
[Пример](https://light.oknosoft.ru/?zone=2&couch_path=/couchdb/wb_&couch_suffix=#obj=cat.characteristics&ref=f4dd6d60-5d9f-4a0e-8552-75930e3c3fd0&frm=builder&view=orders)

**Comment by aribaz** [comment]
Перестала срабатывать формула "Это составной цвет"
И для любого цвета RAL перестали в спецификацию попадать ЛКМ, хотя раньше попадали.

**Comment by unpete** [comment]
Вопрос относится не только к покраске.
До мая 2017, формула во вставках выполнялась только для тех строк, в которых указан способ расчета _по формуле_. Формула должна была установить нужное значение в поле `qty` строки спецификации.
В мае 2017 были внесены изменения. Теперь формула выполняется всегда, вне зависимости от способа расчета количества. Это правильно, т.к. формула может быть вообще не про количество, а например, про подбор номенклатуры или характеристики.
Для бОльшей гибкости, формулы во вставках теперь должны возвращать значение числового типа. Это значение движок присваивает полю `qty` текущей строки спецификации.
Если формула написана в старом стиле и ничего не возвращает, в `qty` появляется 0 и такая строка удаляется из спецификации.

Технологам имеет смысл проверить все вставки, в которых используется способ расчета количества _по формуле_

**Comment by aribaz** [comment]
Теперь Если выбрать составной цвет, то строка по Двухцветной покраске попадает, а сами ЛКМ  - нет.

**Comment by unpete** [comment]
Исправил ошибку, из-за которой терялся контекст при вызове вложенных вставок.
Можно тестировать, естественно, в v2.
Сборка v0.12 заморожена - её держим на случай критических ошибок в v2.

**Comment by aribaz** [comment]
Спасибо, работает.
