### ISSUE TITLE
Формы финансов и технологии на стороне браузера

### ISSUE THREAD

**Issue by Oparin-Igor** [oknosoft/windowbuilder#30]
- [x] Пользователи, Физлица
- [x] Организации, Счета, Кассы
- [x] Контрагенты, Договоры
- [x] Просмотр цен из карточки номенклатуры

**Comment by Oparin-Igor** [comment]
Справочник связи параметров на стороне браузера.

**Comment by unpete** [comment]
> Справочник связи параметров

Почему такой почет именно этому справочнику?
Мне кажется, если мы заявляем полнофункциональное веб-приложение, у технолога должна быть возможность редактировать любые справочники.

**Comment by Oparin-Igor** [comment]
В параметрах могут быть много позиций, например в дверной фурнитуре, у
каждого заказчика свои предпочтения по замкам, петлям, ручкам.

Для того чтобы обрезать список, не удаляя из параметров, именно этот
справочник позволяет это сделать.

 

  _____

**Comment by nmivan** [comment]
Просмотр цен из карточки номенклатуры есть, в виде печатной формы.
