### ISSUE TITLE
НДС 

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#300]
Евгений, добрый день.

Подскажите размер НДС правильно считается?

Я пробовала в одном из договоров с контрагентом поставить галочку Учитывать НДС, и получилось на 15% больше, а не на 18%.

У нас же вроде НДС 18%.
Или я что-то не так понимаю?

**Comment by aribaz** [comment]
И второй вопрос по нему.

Если я для другого договора ставлю галочку Сумма включает НДС, то почему в печатной форме для этого заказа НДС равно 0?
НДС ведь в этом случае не равно 0.

**Comment by unpete** [comment]
В каком именно заказе, для какого контрагента, сколько ожидаете, сколько получаете.
Вопросы без инструкции по воспроизведению проблемы решить невозможно.

**Comment by nmivan** [comment]
@aribaz , есть пример для воспроизведения?

**Comment by aribaz** [comment]
@nmivan Пример прошлый не сохранила.
Контрагент Соловьев в договоре имеет галку Сумма включает НДС [Заказ](https://aribaz.oknosoft.ru/doc.calc_order/b8d93313-ce2c-4424-f7b2-ab75f1cfd768)
Контрагент СтройКант в договоре имеет галку Учитывать НДС (о чем писала выше) [Заказ](https://aribaz.oknosoft.ru/doc.calc_order/e348e000-5d42-4c0c-8282-15cfb2ee834d)
При попытке создать заказ для этих контрагентов цены в строках с изделиями 0 в обоих заказах.
Для проверки создала [заказа](https://aribaz.oknosoft.ru/doc.calc_order/8a1806f7-57f7-4722-ff10-4a90feebb8a2) для Розничного клиента цена рассчитана верно, у этого контрагента в договоре не стоит ни одна из галочек.
