### ISSUE TITLE
Учет размера соединений в обработках фурнитуры

### ISSUE THREAD

**Issue by blackmixer** [oknosoft/windowbuilder#303]
Учет размеров соеднений на внешнем элементе (рама или импост относительно створки )
т.к. соединения начала и конца элемента могуть быть разными.
Например
начало  - соединение Угловое к горизонтальной
конец - соединение Угловое диагональное

**Comment by unpete** [comment]
см: https://github.com/oknosoft/windowbuilder/commit/6e438f7540b7aa80ece512d6e1cd419bac7fa489#diff-6a1b0bd1cb73a897b9d3032c969731f1R197

**Comment by unpete** [comment]
Если я правильно понял проблему, то она сводится к тому, что в случае переноса операции на примыкающий, надо смотреть на его соединения, а не на соединения текущего элемента.
Для наглядности и устойчивости алгоритма, добавил классу _Profile_ свойство _dx0_, чтобы элемент мог сам отвечать на вопросы о своих припусках.
Код в фурнитуре стал чище - тестируйте.

см: https://github.com/oknosoft/windowbuilder/commit/98def57378034e6b88d2c75146bcdf623e84cf54

**Comment by blackmixer** [comment]
Проверено закрываю
