### ISSUE TITLE
Москитка покупная

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#304]
Евгений, у нас в москитке что-то не так.
Я заменила расчет кол-ва с По формуле, на Для элемента, но все равно выдает ошибку.
![2017-07-11 10 29 50](https://user-images.githubusercontent.com/22028048/28055980-f90a7866-6623-11e7-8fc0-b1501790d8d4.png)

**Comment by unpete** [comment]
В спецификации вставки _Москитка покупная_, есть единственная строка для вычисления номенклатуры виртуальной продукции. У таких строк, количество должно быть равно нулю.
Поставил 0 - ошибка исчезла.
Формула _Размеры фальц + 14x23_ не будет работать, если попытаться выполнить её в контексте обычной строки спецификации.

**Comment by aribaz** [comment]
Спасибо, работает.
