### ISSUE TITLE
формула Длина по парам. длина

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#305]
Евгений, подскажите что я делаю не так?

Мне нужно для вставки Отлив оцинкованный добавить позицию по окраске отлива.
Она у производителя в двух единицах измерения, кв.м. и м.пог. с разными ценами на них. 

В кв. м. я все правильно сделала, все считает как надо, а вот с м.пог. у меня не все хорошо.

Я внесла на эту позицию  (Покраска отлива полка <=250мм (м. пог.)) цену, и ед. измерения - м.пог. и предположила, что помножив длину отлива на 1шт и на цену, я получу в спецификации стоимость.
Я пробовала вообще без формул (кол-во 1, коэффициент - 0,001) расчет кол-ва:
 по периметру - тогда 4строки с покраской (2ширины и 2 длины) - не то;
для элемента - тогда  1шт без учета самой длины, а длина здесь нужна, тоже не то.

Попробовала использовать формулу Длина по парам. длина, тогда я получаю 
![2017-07-11_15-56-05](https://user-images.githubusercontent.com/22028048/28069273-865b2b48-6651-11e7-8660-99a61ffe0536.png)
Длину профиля считает правильно, а количество стает равным 0 и соответственно стоимость тоже равна нулю.
Вот что у меня описано:
![2017-07-11_15-57-55](https://user-images.githubusercontent.com/22028048/28069335-c9a931ba-6651-11e7-981a-50f50a6888e1.png)

Помогите пожалуйста, что у меня не правильно?

**Comment by unpete** [comment]
> предположила, что помножив длину отлива на 1шт и на цену, я получу в спецификации стоимость [...] тогда 1шт без учета самой длины, а длина здесь нужна

Ошибка в постановке задачи.
Если количество в штуках, то длина не нужна - тогда работает вариант без формулы.
Если длина всё-таки, нужна, то работает вариант с количеством _для элемента_ и указанной формулой, но итоговое количество получите в метрах

Важно для понимания:
- Формула может делать (и всегда делает) любую работу. Например, формула _Длина по парам длина_ - устанавливает длину в строке спецификации
- _Способ расчета количества_ - отвечает за расчет количества в строке спецификации. В данном случае, вы получаете 0 в количестве от того, что пытаетесь использовать для расчета количества формулу, которая для этого не приспособлена
- При необходимости, можно сделать формулу, которая положит длину в `len` и единицу в `totqty`, но такая строка будет выглядеть странно, т.к. арифметика этой строки будет отличаться от арифметики всех остальных строк в спецификациях

**Comment by unpete** [comment]
Ключевой вопрос: зачем вам длина для штучной номенклатуры?

**Comment by aribaz** [comment]
Конкретно для этой строки поставщик нам считает ее по цене за м.пог.

**Comment by aribaz** [comment]
Спасибо, работает.

**Comment by aribaz** [comment]
Работает спасибо.
