### ISSUE TITLE
Администрирование пользователей и репликаций CouchDB

### ISSUE THREAD

**Issue by unpete** [oknosoft/windowbuilder#307]
Расширен инструментарий подсистемы администрирования пользователей и репликаций CouchDB

- [x] Добавлен справочник _Серверы_ (основной сервер - это реквизит _Абонента_, кроме него, _Отделы абонентов_ могут иметь собственные серверы)
- [x] Реализован расчет и отображение состояния репликаций в форме _Абонента_
- [x] Справочник _Отделы абонентов_ дополнен командой, позволяющей создать базы CouchDB и пользователей только текущего отдела
- [x] При настройке иерархических репликаций, теперь поддержаны индивидуальные серверы отделов абонентов
- [x] В справочник _Отделы абонентов_ добавлен реквизит _Используется_. При создании баз и пользователей из справочника _Абоненты_ или _Панели администрирования_, базы и пользователи создаются только для активных отделов абонентов

### Задачи

- [ ] Визуализация статуса пользователя CouchDB (отсутствует, создан, заблокирован)
- [ ] Инструмент для блокировки и разблокировки пользователей
- [ ] Визуализация статуса баз CouchDB (отсутствует, работает, ошибка)

**Comment by blackmixer** [comment]
>  Справочник Отделы абонентов дополнен командой, позволяющей создать базы CouchDB и пользователей только текущего отдела

При создании базы одного пользователя в базе ram 
права доступа остаются у пользователя (пользователей) кто входит в этот отдел
Permissions -> Members

**Comment by blackmixer** [comment]
Суффикс отдела Абонента содержит 4 символа 
Если ранее суффикс было короче то при изменении дополниться ведущими нулями 
Ограничение на ввод данных Цифры и Буквы латинского  алфавита в нижнем регистре

**Comment by unpete** [comment]
> При создании базы текущего отдела в базе ram права доступа остаются у пользователя (пользователей) кто входит в этот отдел

Так и задумано. Базы `ram` не реплицируются - они общие для абонента

**Comment by unpete** [comment]
Перенёс задачи в https://github.com/oknosoft/metadata.js/issues/252, https://github.com/oknosoft/metadata.js/issues/253, https://github.com/oknosoft/metadata.js/issues/254
