### ISSUE TITLE
Учет углов кроме 0 при расчете кол-ва По периметру.

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#308]
[Пример](https://light.oknosoft.ru/?zone=2#obj=doc.calc_order&ref=204b3865-cc23-407b-ca79-26bd59ebdd02&frm=doc&view=orders)
Доборы наружные.

**Comment by unpete** [comment]
Код поправил - можно тестировать.
Проблема была в следующем:
- Для расчета спецификации, _Вставка_ ожидает получить в качестве параметра _Элемент_
- Чтобы рассчитать спецификации допвставок в изделие и контур (которые не являются элементами), я вставку _обманываю_ - подсовываю ей вместо _элемента_ некий _суррогат_, который она принимает за _элемент_
- Фильтр по свойствам _элемента_, ожидает поле _angle_hor_ (угол к горизонту), но в суррогатном элементе такого свойства не было - вместо него присутствовало свойство _angle_
- Добавил в суррогат _angle_hor_, как псевдоним к _angle_ - фильтры заработали в соответствии с ожиданиями

### Замечания
- Периметр изделия сейчас рассчитывается не честно и не полностью
  + Если изделие состоит из одного контура (окно), периметр изделия просто повторяет периметр контура
  + Для изделий из нескольких контуров, возвращается пустой массив - по хорошему, надо проанализировать примыкания контуров и вернуть внешний путь
- Вставки в контур работают строже. С расчетом их периметра и площади разночтений нет. Поведение вставок в контур будет более предсказуемо по сравнению со вставками в изделие

**Comment by aribaz** [comment]
Работает, спасибо.
