### ISSUE TITLE
Отчет по отклонениям спецификаций

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#310]
Евгений, добрый день.

У нас есть[ заказ](https://light.oknosoft.ru/?zone=2#obj=doc.calc_order&ref=29f86abe-13e5-49ad-acf7-b8fcabfcfaed&frm=doc&view=orders)
В нем первое изделие нарисовано с помощью шаблона, а второе изделие нарисовано с нуля. 

Шаблоны рисовала я, а строила второе изделие не я, а менеджер.
Параметры изделия, используемые профили, их положение идентичны, а цена отличается на 738 рублей. Чем это может быть обусловлено? 
Я посмотрела спецификацию там одни и те же позиции отличаются на сотые доли, но строк таких много, полагаю отсюда и расхождения, но ведь не должно же так быть?

**Comment by unpete** [comment]
Будет одинаково, разберёмся. Пока - в очередь.

**Comment by unpete** [comment]
Проблему подтвердить не могу.
Изделия в заказе БНАР0000068 от 25 июля 2017 отличаются довольно сильно.
Там разная фурнитура + разные размеры.
Перевыбрал фурнитуру, сделал уравнивание по заполнениям - суммы совпали до копейки.

Признаю, что нужен отчет по отклонениям спецификаций изделий и заказов - такие отчеты есть в плане.

**Comment by aribaz** [comment]
Я может чего-то недопонимаю?
![2017-08-14_15-04-38](https://user-images.githubusercontent.com/22028048/29271052-49625902-8102-11e7-8871-5fa3df98eb1e.png)
Но фактически там отличается только размер створок на 1мм по ширине. Во втором изделии 835мм, а в первом 834мм, при использовании шаблона я пользовалась инструментом выравнивания стеклопакетов. 
Менеджер утверждает, что при рисовании самостоятельном пользовался тем же, но получились разные размеры створок.
Фурнитура там одинаковая.
![2017-08-14_15-05-00](https://user-images.githubusercontent.com/22028048/29271320-77b6990c-8103-11e7-83c6-33180936f610.png)
![2017-08-14_15-06-08](https://user-images.githubusercontent.com/22028048/29271319-77b678dc-8103-11e7-970f-1f9e3adae204.png)
Если смотреть спецификацию, то как раз на этих позициях (нижний брусок и верхний брусок створок) и идут отличия в сумме, они очень малы, но таких позиций много, плюс еще Кмарж, вот наверное и набегает.
А инструмент выравнивая каждый раз будет одинаково (к одному и тому же) делить размеры стеклопакетов? если будет вопрос +/- 0,5мм его ведь можно к любому из всех прибавить или отнять.
Потому как сам расчет верный.

В обоих изделиях все стеклопакеты в глухих частях имеют ширину 734мм, а вот ширина створки в одном случае 704, а в другом 705мм, при том что ширина изделий одинакова  для двух изделий 2500. 
С менеджерами решим проблему пока тем, что одинаковые блоки должны быть нарисованы одинаковыми способами. Ведь зачем-то она сначала нарисовала блок с помощью шаблона, а потом решила порисовать руками.
Да, отчет в этом случае был бы не лишним.
Спасибо.
В целом можем закрыть вопрос.

**Comment by unpete** [comment]
Имеем два разных изделия с разными размерами, разным количеством элементов раскладки и разными параметрами фурнитуры.
Если сделать эти изделия одинаковыми - спецификация и стоимость так же, станут одинаковыми.
Способ, которым изделие родилось на свет значения не имеет.
Можно нарисовать от руки, можно по шаблону. Больше всего спецификации отличаются в части фурнитуры. Наверное от того, что после создания шаблона были добавлены новые параметры.

**Comment by nmivan** [comment]
По отчету есть отдельная задача, эту закрою.
