### ISSUE TITLE
Покраска в цвет RAL

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#313]
Евгений, у меня не учитываются ЛКМ, если использовать цвет RAL.
Вы как-то ранее смотрели, там у нас очень длинный список с цветами RAL, Вы сделали предположение, что возможно из-за этого.
Вот [пример](https://aribaz.oknosoft.ru/builder/3002f3d1-6c5e-437d-fd89-12bd75994405).

**Comment by unpete** [comment]
Проблема была в расхождении данных справочника _Цветоценовые группы_ в 1С и couchdb.
Вероятно, была отключена авторегистрация изменений или справочник редактировался со стороны браузера.
Сделал небольшую оптимизацию:
- Теперь в _Цветоценовых группах_ для группировки в параметрах можно указывать не только элементы, но и папки цветов. Весь ваш длинный RAL поместился в одну строчку
- Доработал формулу, чтобы учесть иерархию соответствия цветов

**Comment by aribaz** [comment]
Спасибо, работает
