### ISSUE TITLE
Вставка в контур и в изделие

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#314]
Евгений в новой версии при использовании вставок в контур  и в изделие я не вижу параметров этих вставок. Хотя я точно знаю, что они там есть и влияют на ценообразование этих вставок. Например, подоконник и отлив (полиэстер и оцинкованный), для них должна видеть и задать  ширину, как минимум.

**Comment by aribaz** [comment]
![2017-08-14_14-56-27](https://user-images.githubusercontent.com/22028048/29270750-da99955e-8100-11e7-9899-9571df1ceb90.png)

**Comment by unpete** [comment]
Исправил - проверяйте

**Comment by aribaz** [comment]
Работает, спасибо.
