### ISSUE TITLE
Формула Подоконник

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#315]
Евгений, помогите пожалуйста в формуле. 
Ценообразование/Подоконник МДФ.

Идея в том, что если параметр подоконника Материал=МДФ и Ширина >0 и <150мм, то цена должна удваиваться.

Формулу я начала делать, но не я не уверенна все ли так и не знаю, как сказать в ней про параметр Материал.

**Comment by nmivan** [comment]
@aribaz , проверьте, должно работать.

**Comment by aribaz** [comment]
@nmivan Работает, спасибо
