### ISSUE TITLE
Вставка доборы внутренние

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#316]
Евгений, помогите пожалуйста, я запуталась.

У нас есть вставка Доборы внутренние.
Для нее пользователь сам задает ширину этих доборов, длина же равна стороне изделия.
Доборы ставятся буквой П, то есть в спецификацию попадает 3 палки (2 - высота окна, 1 - ширина окна верхняя) - здесь все верно, ограничения по углам.
Стоимость этих доборов рассчитывается за кв.м.
Если я ставлю в поле Формула Размеры по парам (Расчет кол-ва  - по периметру), то у меня попадает только высота стороны окна, а параметр ширина в сторку не попадает.
 Сейчас так
![2017-08-15_08-51-45](https://user-images.githubusercontent.com/22028048/29303709-6b574b4a-8197-11e7-9da1-ebfb59c9028d.png)

А надо вот так
![2017-08-15_08-51-55](https://user-images.githubusercontent.com/22028048/29303715-7504e4fe-8197-11e7-826d-9efd1c0abdfd.png)

Что я не так сделала?

Если ставить расчет кол-ва Для элемента, то она игнорирует вообще его размеры, считает 1шт и умножает эту одну штуку на цену.
![2017-08-15_09-02-01](https://user-images.githubusercontent.com/22028048/29303860-74fe81da-8198-11e7-828d-c00a3c721d80.png)

У подоконника применяется формула Размеры по парам, расчет для элемента,  - там все правильно (только длину там тоже задает пользователь сам) и там получаем площадь подоконника умноженную на цену за квадратный метр.
Здесь мне в целом надо то же самое, только длину пользователь не сам задает, а берет у изделия.
Где-то я ошибаюсь, вот только не пойму где.
Помогите пожалуйста.
[Пример](https://aribaz.oknosoft.ru/builder/a71d0c45-247b-42ab-c7c3-bb70c66b9896)

**Comment by nmivan** [comment]
@aribaz , уточните, вопрос актуален?

**Comment by aribaz** [comment]
Да, актуальна
