### ISSUE TITLE
Локальная разработка v2

### ISSUE THREAD

**Issue by Sehktel** [oknosoft/windowbuilder#317]
Сделал согласно инструкции.

1. Не хватило компоненты DhtmlxCell - забрал с oknosoft.
2. поправил путь до couchdb в app.settings.js
3. Обновился. 
Говорит
```js 
TypeError: Class constructor CatObj cannot be invoked without 'new'
new CatUsers
src/metadata/init.js:8 ```

```js
   5 | 
   6 | $p.md.init({"enm":{"accumu     . . .  "}})
   7 | 
>  8 | (function(){
   9 |   const {EnumManager,CatManager,DocManager,DataProcessorsManager,ChartOfCharacteristicManager,ChartOfAccountManager,
  10 |     InfoRegManager,AccumRegManager,BusinessProcessManager,TaskManager,CatObj, DocObj, TabularSectionRow, DataProcessorObj,
  11 |     RegisterRow, BusinessProcessObj, TaskObj} = $p.constructor.classes;
```

```js
Object../src/index.js
src/index.js:33
  30 |   }
  31 | }
  32 | 
> 33 | render(
  34 |   <RootProvider />,
  35 |   document.getElementById('root'),
  36 | );
```

**Comment by Sehktel** [comment]
Ну или пока думаю. Как совсем упрусь - скажу

**Comment by unpete** [comment]
> поправил путь до couchdb в app.settings.js

Путь следует указывать в браузере.
В файле app.settings.js живёт не _путь к couchdb_, а значение по умолчанию

**Comment by Sehktel** [comment]
> Путь следует указывать в браузере.
Тогда скажу по другому.
Загрузка страницы не доходит до приветствия, логина и пароля, и соотв. не дает возможности указать путь к couchdb.
Т.е. я вперед получил ошибку, потом подумал что путь можно поправить значение по умолчанию и опять получил ошибку.

**Comment by unpete** [comment]
> Загрузка страницы не доходит до приветствия

1. А параметры url, в которых можно передать `couch_path`, `couch_url`, `zone` и `couch_suffix` кто-то запретил использовать?
2. Если загрузка куда-то не доходит, подключение или отсутствие подключения к couchdb никак не поможет решить эту проблему. Сервер и страница живут своей самостоятельной жизнью. Им друг на друга - наплевать.

**Comment by unpete** [comment]
@Sehktel, @blackmixer за информацию об ошибках - большое спасибо. Дистрибутив в ближайшее время поправлю.

**Comment by Sehktel** [comment]
Взял "чистый" исходник в zip, распаковал отдельно.
```js 
npm i
npm start 
```

**Failed to compile.**
```js
./src/components/App/RootView.js
Module not found: Can't resolve 'metadata-react/BrowserCompatibility' in '/home/sehktel/Work/Git/windowbuilder-master/src/components/App'
```

**Comment by unpete** [comment]
Это - ерунда, рабочий момент. Я веду разработку metadata и windowbuilder параллельно и не могу публиковать в npm каждый чих. 
Если хочешь работать с копией windowbuilder, такие вещи придется обходить постоянно. Учись ставить заглушки.

**Comment by blackmixer** [comment]
1 ./src/components/RepMaterialsDemand/RepParams.js
  Line 56:  'objs' is defined but never used  no-unused-vars

2 При открытии Расчет-заказа форма не занимает все свободное пространство 
![screenshot_20170913_153849](https://user-images.githubusercontent.com/24730013/30378050-97c6a512-989a-11e7-9dc6-09d2717cafa1.png)

Google Chrome
Версия 61.0.3163.79 (Официальная сборка), (64 бит)
node -v
v8.5.0
npm -v
5.4.1

**Comment by unpete** [comment]
В github живут рабочие файлы. Это не релиз. Если оно не компилируется или глючит - это нормально.
На сайт публикуются далеко не все изменения, как правило - после отладки.
Это общепринятая практика работы с git. В репозиториях многих проектов с миллионной посещаемостью есть кнопка-индикатор `build-passing` или `build-failed`, которая показывает консистентность сборки

**Comment by unpete** [comment]
Например, в https://github.com/pouchdb/pouchdb сейчас `build-error`.
Там 1000 форков, 200 контрибьюторов и все понимают, что компилировать текущий слепок репозитория и вставлять в production не нужно (стой, опасная зона, работа мозга)

**Comment by unpete** [comment]
https://github.com/oknosoft/windowbuilder/commit/cd2d05adb10e5272133da3958f65e7d84e3a1a35
