### ISSUE TITLE
Шаблоны документов в формате OpenDocument

### ISSUE THREAD

**Issue by blackmixer** [oknosoft/windowbuilder#318]
[node-odt](https://github.com/domachine/node-odt)
[file2html](https://github.com/file2html/file2html)

**Comment by Sehktel** [comment]
@blackmixer из интереса. Зачем потребовался odt? Чего не хватило в существующих шаблонах?

**Comment by blackmixer** [comment]
стили форматирования документов .docx могут изменяться при открытии в OpenOffice (LibreOffice)

**Comment by unpete** [comment]
При желании, решается в модификаторах. Тянуть все форматы в платформу - не обязательно.
