### ISSUE TITLE
Шаблоны, выделение строк заказа

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#319]
Евгений, добрый день.
Как-то странно выделяются строки.
![2017-08-18_12-23-00](https://user-images.githubusercontent.com/22028048/29452773-301495a8-8410-11e7-8a28-db810c4e9cd1.png)

**Comment by unpete** [comment]
Эта особенность мне известна - компонент миниэскизов будет доработан

**Comment by unpete** [comment]
В новых заказах должно работать адекватно
