### ISSUE TITLE
Ошибка при расчете цены

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#320]
Евгений, добрый день.
У нас есть заказы 124 и 125, они выполнены из разных материалов. Разница между ценой бруса практически 3 раза, но идентичные изделия отличаются по цене совсем незначительно.
[Лиственница изделие 1](https://aribaz.oknosoft.ru/builder/98b37b1f-8c5c-4c6f-8bd0-9717a20f35d8) 51008р
[Дуб изделие 1](https://aribaz.oknosoft.ru/builder/1b54585f-c8b7-45a5-9e28-4626343e5383) 55532р
Хотя основной профиль для одного первого изделия из лиственницы стоит примерно 5370, а для изделия из дуба 17011 - это еще до Кмарж (в спецификации).
Разница уже составляет 17011-5370 = **11641р** это только по профилю, без штапика, а ведь еще Кмарж.
А разница между готовыми изделиями составляет 55 532-51 008 = 4 524р. 
Сначала был создан заказ 124, потом на основе него сделали заказ 125, в котором заменили лиственницу на дуб.
Что делать?

**Comment by unpete** [comment]
> что делать

Составлять сценарий для воспроизведения проблемы.
Внятный и пошаговый.

**Comment by aribaz** [comment]
Евгений, я нашла корень проблемы.
У меня для контрагента Розничный клиент Кмарж 2,6, а для дуба 1,9.
Так вот получается, что когда я делаю дубовые изделия для розничного контрагента, то применяется коэффициент 1,9 к изделию в этом заказе, которые выполнено из дуба, а те что выполнены из других материалов к ним применяется Кмарж 2,6.
[Заказ 130](https://aribaz.oknosoft.ru/doc.calc_order/915e15b4-b1f2-4d96-c95b-6efa3bd5a940)
Изделия сделаны на основе шаблона.
лиственница без кмарж 5383,44;    5383,44*2,6=13971,59 - цена пост
дуб без к марж 7964,13;     7964,13*1,9=15134 - цена пост

Получается, если я хочу, чтобы для розничного клиента и изделий из дуба применялся коэффициент 2,6, то надо удалить строку с кмарж 1,9, а если нужен для этого сочетания какой-то свой коэффициент - то дополнить ключ.
Правильно?

**Comment by unpete** [comment]
Строка маржинальных коэффициентов ищется индивидуально для каждой строки
заказа. Учитывается приоритет, указанный в ключе. Если приоритеты
одинаковые, выигрывает ключ с большим числом параметров. Если длины ключей
одинаковы - первый подходящий.

**Comment by aribaz** [comment]
Спасибо.
