### ISSUE TITLE
список контрагентов

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#321]
Евгений, добрый день.

Я в новой версии вижу не весь список контрагентов, а только 3.

**Comment by aribaz** [comment]
![2017-08-22_11-46-34](https://user-images.githubusercontent.com/22028048/29556783-96ba04d8-872f-11e7-9a91-156bc3f6ae24.png)

**Comment by nmivan** [comment]
@aribaz , проблема еще актуальна? Если да, подключусь к вашей базе и посмотрю.

**Comment by aribaz** [comment]
@nmivan Да, актуальна.
Ситуация немного изменилась, но список тем не менее не весь.
Сейчас вот что есть:
![2017-09-13_09-10-45](https://user-images.githubusercontent.com/22028048/30362194-8e2f469e-9863-11e7-9a52-c097fffd87d1.png)
А должно быть:
![2017-09-13_09-11-07](https://user-images.githubusercontent.com/22028048/30362207-98b33044-9863-11e7-92b5-bfc380769069.png)

**Comment by nmivan** [comment]
@aribaz , а вы не меняли некоторое время назад настройку интеграции для справочника Контрагенты?

**Comment by nmivan** [comment]
@aribaz , проверьте теперь список контрагентов в сервисе.

**Comment by aribaz** [comment]
@nmivan Все работает, спасибо
