### ISSUE TITLE
К марж /Группа цен контрагента

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#323]
Евгений, помогите пожалуйста понять один момент.

У меня есть заказ [БНАР 97](https://aribaz.oknosoft.ru/doc.calc_order/cbce92ef-dd9b-43d7-db77-0729d1c058b7) у него контрагент Фабрика массив.

Я посчитала себестоимость одного [изделия ](https://aribaz.oknosoft.ru/builder/960dafeb-c706-48b7-de80-e6e062974f46) она получилась  примерно 24 828р, цена изделия в табчасти 55 303,8, это получается коэффициент 2,3, а среди моих маржинальных коэффициентов такого нет.

Почему так? Может я что-то пропускаю?

**Comment by aribaz** [comment]
Еще вот что нашла.
К марж для Подоконника я ставила ранее 2, но почему-то в 1С он числится, как 4, и еще на вкладке дилерские цены имеет 30% внешней наценки.
Хотя считает коэффициент 2:
![2017-09-07_14-30-03](https://user-images.githubusercontent.com/22028048/30161507-864c7b1a-93d9-11e7-80cd-3803ed0f5980.png)
![2017-09-07_14-33-47](https://user-images.githubusercontent.com/22028048/30161535-a5e2de4c-93d9-11e7-9682-82d56a5ba0e4.png)


Как понять что по факту считается?

**Comment by aribaz** [comment]
Складывать спецификацию на изделях руками очень долго, а CTRL+C, CTRL+V в Эксель результат интересный многие цены и суммы вставляются в странном формате:
![2017-09-07_14-38-45](https://user-images.githubusercontent.com/22028048/30161810-cb347830-93da-11e7-87d8-0df9a7a87bd9.png)
Если их преобразовать в число, то это не те числа, которые нужны, приходится все на калькуляторе считать или исправлять вручную месяц на цифру, а потом суммой.

**Comment by Sehktel** [comment]
Это связано с тем, что знак разделения разрядов является точкой.
В то время как в настройках Экселя знак разделения выбран как запятая.
Эксель, проявляя "заботу" пытается интерпретировать поле как дату.
Подсказать Экселю не делать этого в статье:  goo.gl/ndXzfL

**Comment by aribaz** [comment]
@Sehktel Спасибо.

**Comment by unpete** [comment]
> посчитала себестоимость одного изделия

Как именно считали? Вот два способа:
````javascript
paper.project.ox.calc_order_row.first_cost // 27651.9
paper.project.ox.specification.aggregate([], ['amount']) // 27651.89636984002
````
То есть, себестоимость изделия = 27652 руб.
Цена того же изделия = 55304
КМарж = 55304 / 27652  = 2, что подтверждается значением в строке заказа:
````javascript
paper.project.ox.calc_order_row.marginality // 2
````
Вынужден классифицировать задачу, как клевету.

**Comment by aribaz** [comment]
Евгений, я считала по спецификации:
[Проверка Кмарж.xlsx](https://github.com/oknosoft/windowbuilder/files/1286865/default.xlsx)

Вышеуказанными Вами способами не пользовалась, не умею. Если научите, будет здорово.

Но ведь сумма спецификации должна же по идее совпасть с вашими способами. Разве нет?

И в ней получается: 24 683,79, а не 27 652.

**Comment by unpete** [comment]
Уточните, что именно вы пытаетесь проверить?
Каким способом получен файл xls и на какой вопрос он призван отвечать?

**Comment by aribaz** [comment]
Файлик получен так:
Открыла спецификацию интересующего изделия,  далее в браузере со страничкой спецификации CTRL+A, CTRL+C - открыла пустой файл Эксель, CTRL+V.
Просуммировала значения колонки Сумма.
Ранее данный способ давал значение себестоимости изделия до применения Кмарж.
Хотела выяснить какой коэффициент Марж применился к данной строке.
Разделила стоимость изделия, показаную в табчасти на себестоимость из файлика и получила  2,24, вместо 2.

Вот поэтому и возник вопрос, откуда 2,24.

Или не все строки видны в спецификации? Я пробовала и вручную суммировать на калькуляторе двигаясь по строкам спецификации в браузере, сумма у меня тоже не получилась как у вас 27 652, а получилась меньше. Соответсвенно и Кмарж .получился не 2, а больше.
Разница между полученными мною способами и вами по себестоимости составляет 2 969, так ведь не должно.

Раньше такой мой метод проверки срабатывал правильно. К марж получался правильный.

**Comment by unpete** [comment]
Сегодня добавлю кнопку для экспорта табличной части в xlsx (сейчас, такая возможность есть для списка объектов, но это не ваш случай).
Проверять арифметику - занятие вполне бессмысленное. В программе _MS Excell_ вероятность внутренних ошибок выше, чем в _Chromium V8_
Есть смысл проверять состав строк, цены и количества, но _MS Excell_ в этом вряд ли поможет.
Вот файл с фактическим содержимым табчасти:
[default.xlsx](https://github.com/oknosoft/windowbuilder/files/1286927/default.xlsx)

**Comment by aribaz** [comment]
Спасибо, за кнопку. Поможет.

А как быть с Кмарж по подоконнику?
У меня в 1С стоит 4 почему-то, но считает правильно с коэффициентом 2. Я ставила 2.

**Comment by unpete** [comment]
Реализован экспорт произвольной табличной части в файл или буфер обмена.
Наравне с выгрузкой в xlsx, поддержано копирование в формате csv (текст с разделителями tab) и формате json.
Подменю экспорта расположено справа от поля поиска на панели инструментов табчасти

**Comment by aribaz** [comment]
Спасибо.
