### ISSUE TITLE
Построитель у Дилеров

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#325]
Не открывается построитель у всех менеджеров Фабрики Массив.
Появляются нулевые строки.
![2017-09-06_09-15-24](https://user-images.githubusercontent.com/22028048/30197660-c424307a-9471-11e7-87d9-fb451cb60f2a.png)

**Comment by unpete** [comment]
При создании пользователей, был указан неверный состав ролей.
Вместо `[ram_reader,doc_editor]`, у сотрудников фабрики массив стояло `[ram_reader,ram_editor]`.
Как следствие - они не могли ничего записать в базу `doc`.
Изделия и заказы создавались в памяти браузера, но не принимались сервером.

**Comment by aribaz** [comment]
Спасибо, все работает.
