### ISSUE TITLE
В спецификации цены 0

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#326]
Евгений, создаю заказ, рассчитываю, сохраняю - в спецификации все цены 0, и собственно цена изделия/заказа тоже. Список спецификации верный, но цены исчезли.
Вот [заказ](https://aribaz.oknosoft.ru/doc.calc_order/515409c8-99c2-4d43-d1a7-0b7bf2c3e54e/?ref=cb413c0c-3d91-4970-982f-bd20a3b16a9a)
Помогите пожалуйста

**Comment by unpete** [comment]
В записи маржинальных коэффициентов для _Дилер 0%_ вы указали пустой тип цен плановой себестоимости.
Фабрика массив входит в группу цен контрагента _Дилер 0%_. Система ищет цены номенклатуры, установленные по пустому типу цен. Т.к. таких цен в системе нет - получаете нулевую плановую себестоимость и цену продажи.

**Comment by aribaz** [comment]
Спасибо большое.
