### ISSUE TITLE
Настройки. Скидки и наценки дилера

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#327]
Евгений, добрый день.

В новой версии как добраться до странички с наценками и скидками каждого пользователя, которые раньше были в Настройках?

Сейчас при нажатии на этот раздел ошибка получается.

![2017-09-12_08-42-06](https://user-images.githubusercontent.com/22028048/30309882-4e3389c4-9796-11e7-9c91-e0cf21176c49.png)

**Comment by aribaz** [comment]
Прошу дать доступ к данной вкладке дилерам.

**Comment by unpete** [comment]
Страницу настроек подключил - проверяйте

**Comment by aribaz** [comment]
@unpete все работает, спасибо.
