### ISSUE TITLE
Работа в режиме Офлайн

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#328]
Евгений, подскажите пожалуйста.

В новой версии как работать в режиме офлайн?

**Comment by nmivan** [comment]
@aribaz , напомните, что решили вчера с Евгением про офлайн?

**Comment by aribaz** [comment]
@nmivan Решили, что эта опция нужна дилерам (такие у нас есть), но не нужна штатным менеджерам завода (такие тоже есть). Опция станет доступна, когда Евгений нам сделает доступной вкладку Настройки.

**Comment by unpete** [comment]
Галку в настройках добавил, но на этапе активной разработки, режим offline включать не буду.
При включенном offline, у меня нет возможности быстро подсунуть в браузер пользователя изменения кода. serviceworker обращается к серверу один раз в сутки.
Если я сделаю ошибку в коде, то исправления люди получат только на следующий день, а если ошибка критичная, это парализует работу без возможности исправить.
