### ISSUE TITLE
Внесение доп комплектующих и услуг

### ISSUE THREAD

**Issue by unpete** [oknosoft/windowbuilder#338]
> @Felishia пишет: нарисовали изделие, заходим на закладку свойства изделия, там делаем 2 кнопки - комплектация и услуги. При нажатии, выпадает таблица. По умолчанию, все поля пустые и неактивные, если установить галочку в нужное поле, например, отлив то, становятся активными параметры данного раздела. На картинке я показала свое видение. Я посчитала, что такой доп комплектации у нас может быть всего 5 видов: москитные сетки, подоконники, Водоотливы (кроме фигурных), Откосы, Доборные профили. Все активные поля - это параметры таких вставок. Цена рассчитывается из формулы вставки. Можно добавить несколько позиций к одной вставке и, в случае необходимости, удалить неправильно занесенную.

![image](https://user-images.githubusercontent.com/12096477/32741396-f0c0b6d2-c8c7-11e7-9dcb-0673894ae455.png)

**Comment by unpete** [comment]
* Запрашиваемая функциональность относится к документу _Расчет_, а не к изделию. Могут существовать заказы без окошек, только с подоконниками или материалами или услугами. Соответственно, кнопка редактора должна быть в форме заказа, а не в рисовалке
* Если будет сильное желание, компонент можно продублировать, как закладку рисовалки, но это сложно. контекст рисовалки привязан к строке заказа, а форма ввода допов и услуг изменяет весь заказ
* На текущем этапе, для скорости, оформим ввод допкомплектующих отдельным компонентом. Позже, я создам новый раздел в справочнике _Формулы_ - _Заполнение объекта_. Сейчас, в нашем распоряжении есть разделы _Печать_ и _Модификаторы_. Реализовать внешнюю форму можно в этих разделах, но в отдельной области _Заполнение объекта_ будет красивее

**Comment by unpete** [comment]
В документе _Расчет_ есть метод _process_add_product_list_, принимающий на вход объект обработки _dp.buyers_order_. По данным табчасти этой обработки, метод добавляет строки заказа, рассчитывает спецификации и цены. Задачу будем решать так:
* Создаём react-компонент формы допов и услуг
* Этот компонент получает на вход экземпляр текущего ДокуменОбъекта _Расчет_
* В теле конструктора, анализируем состав заказа заполняем табчасть обработки подходящими допами и услугами (это нужно при повторных открытиях формы)
* Сразу делаем снапшот табчасти, чтобы не пересоздавать те позиции, которые не меняли
* Действия пользователя в форме отражаем изменением табчастей _продукция_ и _параметры_ нашей обработки
* По кнопке _Ок_ или _Пересчитать_, вызываем метод _process_add_product_list_, в который передадим только изменённые строки и перезаполняем снапшот

**Comment by Felishia** [comment]
https://github.com/oknosoft/windowbuilder/tree/master/src/components/CalcOrderAdditions

**Comment by RapeFactory** [comment]
@unpete, Я готов взяться развивать этот модуль, но я слабо понимаю, как это всё работает. Сегодня нажимал в функционал, и с текущими вставками, у которых есть доп. параметры работает не ок. 
Перерабатывать ли вставки, унифицировать ли, я не пойму. Есть желание сделать логику простой и прозрачной, используя этот модуль. 
У меня есть всё, чтобы это понять.  С чего начать?

**Comment by unpete** [comment]
> С чего начать?

- Научиться думать на [Reactjs](https://reactjs.org/tutorial/tutorial.html)
- Разобраться с нашими [SchemeSettings](https://github.com/oknosoft/metadata.js/blob/develop/packages/metadata-abstract-ui/src/scheme_settings.js) и [SchemeSettings](https://github.com/oknosoft/metadata.js/tree/develop/packages/metadata-react/SchemeSettings) и [TabularSection](https://github.com/oknosoft/metadata.js/tree/develop/packages/metadata-react/TabularSection)

> доп. параметры работает не ок

Что конкретно не ок?
