### ISSUE TITLE
Прямоугольнное заполнение

### ISSUE THREAD

**Issue by Sehktel** [oknosoft/windowbuilder#339]
Мне кажется у нас неправильно определяется "прямоугольность" заполнения.
```js
  /**
   * Признак прямоугольности
   */
  get is_rectangular() {
    return this.profiles.length === 4 && !this._attr.path.hasHandles();
  }
```
Отсутствие ручек - это признак "линейности" `is_linear`. 
Сейчас я не могу использовать `is_rectangular` для трапециевидных стеклопакетов, т.к. он отдает true

Для определения прямоугольных стеклопакетов используется что-то вроде: 
```js
project.glasses.some((glass) => {
	let flag = true;
	glass.profiles.some((glass_profile) => {
		if (!(glass_profile.profile.is_linear() && Math.abs(glass_profile.profile.angle_hor % 90) < 1)){
			flag = flag && false;
		}
	})
})
```

**Comment by unpete** [comment]
Спасибо, учту

**Comment by unpete** [comment]
Проверяйте

**Comment by Sehktel** [comment]
Спасибо, работает.
