### ISSUE TITLE
Свойство "Система"

### ISSUE THREAD

**Issue by nmivan** [oknosoft/windowbuilder#342]
@unpete, не могу вспомнить, почему в ПВХ ПредопределенныеЭлементы нет свойства Система. В дополнительных реквизитах есть, а в предопределенных нет. Соответственно, у него нет синонима.
Я этот вопрос вроде задавал месяца 4 назад, но не помню, что ты ответил.

Контекст: в планировании используются свойства, которые есть в предопределенных элементах, в папке properties, и которые имеют синонимы. Там есть фурнитура и признак нестандарта, но нет системы.

**Comment by unpete** [comment]
Ответа не знаю.
Гипотеза: системы нет в обычных свойствах от того, что она перечислена в константе _Вычисляемые_, которое лежит в _ПредопределенныхЭлементах_ папка _Дополнительные реквизиты и сведения_

**Comment by nmivan** [comment]
А не знаешь, так и должно быть?

В той же константе _Вычисляемые_ есть _Фурнитура_, которая еще и лежит отдельно в папке _Дополнительные реквизиты_ и имеет синоним. А у системы синонима нет. И она не попадает в `job_prm`.

Правильно будет систему туда добавить?

**Comment by nmivan** [comment]
В локальную базу пока добавил, чтобы на месте не стоять. В `job_prm.properties` она появилась.

**Comment by unpete** [comment]
Если добавить, хуже не будет. Чтобы не возникало проблем при обмене формул, имеет смысл добавить во все базы с одинаковым guid

**Comment by unpete** [comment]
Закрываем?

**Comment by nmivan** [comment]
Да
