### ISSUE TITLE
Статусы репликации для поддержки 2.1.1

### ISSUE THREAD

**Issue by unpete** [oknosoft/windowbuilder#343]
- База _remote_ должна стать опциональной
- Статусы репликации надо получать специальным запросом, а не из _replicator/ddoc

**Comment by blackmixer** [comment]
На текущий момент базы remote не используются ???

**Comment by unpete** [comment]
Решил пока обойтись без _remote_.
Вроде, и планирование и склад и деньги получается аккуратно разместить в _doc_, не создавая лишнего трафика.
