### ISSUE TITLE
Предложение насчет отображения заполнений с размерами.

### ISSUE THREAD

**Issue by RapeFactory** [oknosoft/windowbuilder#344]
```
// Функция умеет работать с отображением элемента заполнения и возвращать в исходное

filling = function (n) {
    function showFilling(n) {
        if (paper.elm(n)._attr.hasOwnProperty('_dimlns')) {
            paper.elm(n)._attr._dimlns.visible = true;
        }
        paper.project.draw_fragment({
            elm: n
        });
        return true;
    }
    function showProduct() {
        paper.project.draw_fragment({
            elm: -1
        });
        if (paper.elm(n)._attr.hasOwnProperty('_dimlns')) {
            paper.elm(n)._attr._dimlns.visible = false;
        }
        return false;
    }

    if (!this.show) {
        this.show = showFilling(n);
    } else {
        this.show = showProduct();
    }
}
filling.show = false;

//И при вызове в консоли разработчика:
filling(n); //отобразит n-ный элемент с размерными линиями
//Еще раз:
filling(n); //скроет n-ный элемент и вернет эскиз всего изделия
```

**Comment by unpete** [comment]
Те, кто умеет пользоваться консолью, могут закинуть такую функцию в глобальный контекст самостоятельно. Imho, в стандартной поставке она не нужна.
Если хотите, чтобы она всегда присутствовала в Экооконном экземпляре Заказа дилера, можете создать элемент справочника _Формулы_ в папке _Модификаторы_ и поместить туда ваш текст.
В первой строке, вместо `filling = ...`, надо будет написать `window.filling = ...`

**Comment by RapeFactory** [comment]
Спасибо, @unpete , хорошее решение, чтобы не загромождать интерфейс. Если будет пользоваться спросом, то будем думать, как сделать функцию практичнее.

**Comment by unpete** [comment]
Просьба поаккуратнее с формулами...
В том числе с теми, текст которых предложил я.
Правило "70 раз отмерь, один отрежь" здесь очень уместно.
Формулы выполняются, в том числе в микросервисах, где нет объекта `window`.
Соответственно, формула из этой ветки вызывает ошибку времени исполнения и не даёт запуститься сервисам рендеринга эскизов и планирования.
Заплату сейчас поставлю, при этом, настоятельно рекомендую:
- завязывайте с отладкой формул на боевой базе
- перед публикацией формул, спрашивайте разрешение @BigShmax - он хоть не настоящий нормоконтролер, но откровенные ляпы не пропустит

**Comment by unpete** [comment]
Помните угловой штамп на гостовских чертежах?
Там есть подписи:
- Разработал
- Чертил
- Проверил
- Нормоконтролер
- Утвердил

Это на жалких бумажках про кирпичную стену или шестерёнку, а у нас, сложнейший программный код попадает в prod без согласования и проверки.
