### ISSUE TITLE
Фильтрация списка вставок в построителе (обсуждение)

### ISSUE THREAD

**Issue by blackmixer** [oknosoft/windowbuilder#346]
Есть небольшое предложение по фильтрации строк вставок в построителе при использовании доп вставок (в изделие и контур)
п1. на стороне  1с дать возможность технологу устанавливать возможность использование вставки в построителе (аналогично чек боксу доступно в интерфейсе ) 
Этим мы уберём технологические вставки типа контроля заполнений (список для выбора будет меньше, более лёгкая навигация в нем )
п2. более сложную фильтрацию система = > вставки, можно реализовать через связи параметров по ключу системы привязать в параметрах перечисление доступных вставок  если такой связи нет то покажем все вставки кроме обрезанных в п1

**Comment by unpete** [comment]
Сам я считаю такие задачи вредными, но клиенты настаивают и кое-что в этом направлении делается.
Добавлено новое назначение ключей параметров, в отделах абонентов можно будет указать ключи для ограничения списков систем и фурнитуры для разных отделов. Эта задача пока в работе.

Переопределить параметры выбора и связи параметров выбора вы можете и сейчас с помощью формул типа модификатор.

**Comment by blackmixer** [comment]
> Переопределить параметры выбора и связи параметров выбора вы можете и сейчас с помощью формул типа модификатор.
как я понимаю  для переопределения параметров выбора доступных вставок  мне нужно в модификаторе переопределить поведение  класса AdditionalInserts  
https://github.com/oknosoft/windowbuilder/blob/72f63c9a5207417599bcb9ac43337d70a67ce8fa/src/editor/additional_inserts.js#L2-L12
Вопрос как получить этот класс в модификаторе ???

**Comment by unpete** [comment]
Связи параметров к параметрическим вставкам будут добавлены.
На прошлом совещании ты меня убедил, что это не вредно.
