### ISSUE TITLE
svg-эскизы заполнений

### ISSUE THREAD

**Issue by RapeFactory** [oknosoft/windowbuilder#347]
Я занимаюсь печатной формой заполнений. И при признаке нестандартного стеклопакета хочу вытащить svg эскиз заполнения на форму.
Однако же я знаю только про `print_data.ПродукцияЭскизы`. И там только эскизы изделий.
Есть ли эскизы заполнений? Если есть, то где?

**Comment by unpete** [comment]
В `ПродукцияЭскизы` мы храним только основной эскиз.
Для безбумажки задуман [сервис отчетов и диспетчеризации](https://github.com/oknosoft/windowbuilder-reports)
Есть подозрение, что задачу вам поставили неточно.
Печатать фрагменты изделий из заказа - вредно. Это следует делать из `Задания на производство`.

Не стесняйтесь обсуждать постановку задачи, а не только реализацию - сэкономите кучу времени и денег учредителя.

**Comment by Felishia** [comment]
Данная печатная форма требуется сотрудникам ПТО для проверки заказов, а так же для пересылки поставщику с целью получения стоимости (нужно сделать предварительный расчет и выявить более выгодное предложение), перезаказа только стеклопакета из изделия

**Comment by unpete** [comment]
> требуется сотрудникам ПТО для проверки заказов

О чем я и говорю. Вы повторяете сложившийся бизнеспроцесс без учета новых возможностей.

Пример отчета по заказу с эскизами заполнений, конечно, сделаю, но правильнее imho, было бы пересмотреть порядок работы ПТО, снабжения и прочих подразделений.

**Comment by unpete** [comment]
Доработал сервис рендеринга эскизов, см.: https://github.com/oknosoft/windowbuilder-reports/commit/9e91dc38091938301dc3f94eb3edcd3d601bc208
Теперь он умеет отдельно формировать эскизы заполнений. Экономия трафика: 10 раз.
На тестовых изделиях, стандартный ответ сервиса ~ 200Kb, отдельно эскизы заполнений ~ 20Kb.

Следующим шагом будет пример печатной формы.

**Comment by unpete** [comment]
Можно тестировать после перезапуска браузера - печатная форма _3.9 Эскизы заполнений_
Сейчас используется старый endpoint (тот же, что для загрузки заказов в УПП) - на 90% лишний трафик и нет названия продукции (undefined) справа от стеклопакета.
Вечером перезапущу сервис - будет чуть красивее.

**Comment by Felishia** [comment]
Евгений - прям волшебство! Спасибо большое!!!

**Comment by unpete** [comment]
Правильное взаимодействие с производителями стеклопакетов со временем настроим через сервис [параметрических заказов](https://github.com/oknosoft/windowbuilder-parametric). Наверное, всем понятно, что СТИС в этом вопросе ничем не отличается от Кристаллита.
Сейчас, люди ориентированы на ручную обработку чертежей.
Всем кажется нормальным, когда сначала из цифры получается картинка, потом человек смотрит на эту картинку глазами и в другой программе опять превращает картинку в цифру.
Миссия окнософта - унифицировать этот процесс, выкинув лишние преобразования данных на помойку.
