### ISSUE TITLE
Инструмент "Рисование"

### ISSUE THREAD

**Issue by unpete** [oknosoft/windowbuilder#35]
- [x] Запоминать свойства в привязке к системе
- [x] Интеллектуальный алгоритм подстановки начальных значений
- [ ] Подписка на событие при изменении системы

**Comment by Oparin-Igor** [comment]
[]- при добавлении профиля задать длину и угол.

**Comment by unpete** [comment]
> задать длину и угол

Какой предполагается сценарий работы?
Что именно хочет сделать пользователь?
Возможно, для этой задачи нужен не инструмент _рисование_, а какой-то другой?

**Comment by Oparin-Igor** [comment]
Есть какая-то начальная точка, надо от этой точки нарисовать профиль
определенной длины и на определенный Угол (опция).

В том же окне с выбором профили и привязки. Добавить возможность установить
длину.

 

Не совсеми удобно сначало рисовать фигуру, а затем выверять размеры для
каждого элемента, надо много времени.

В суперОкнах сценарий такой. При создании нового изделия сначала задаем
размеры.

В Клаес. Сначала рисуем, затем задаем размеры контуров, для кривых и сложных
автоматичекски от вида линий задаются вспомогательные размеры.

 

Вопрос объемный, например как нарисовать треугольник, зная только размеры
сторон? Углы на замере точно не померить. Координаты неизвестных точек не
задать.

Если у тебя этот вопрос продуман, то хорошо. Если нет обсудим при встрече.

 

  _____
