### ISSUE TITLE
При изменении реквизита таб части продукции запускать пересчёт спецификации 

### ISSUE THREAD

**Issue by blackmixer** [oknosoft/windowbuilder#351]
https://github.com/oknosoft/windowbuilder/blob/ab15ba54587974af0914a8ea13e1cb00692cda22/src/modifiers/documents/doc_calc_order.js#L942

https://github.com/oknosoft/windowbuilder/blob/ab15ba54587974af0914a8ea13e1cb00692cda22/src/modifiers/common/glob_spec_building.js#L33

**Comment by unpete** [comment]
Со стороны движка, должно работать - проверяйте.
Примеры следящих вставок монтажа и доставки подготовить не успел - пробуйте самостоятельно.
Даю наводку: в коде формул этих вставок можно редактировать не только спецификацию текущей продукции, но и строку заказа, к которой эта продукция относится. Например, в этой строке можно рассчитать количество, как суммарную площадь изделий или массу или периметр или расстояние в километрах.

**Comment by unpete** [comment]
Было переполнение стека, см.:
https://github.com/oknosoft/windowbuilder/commit/fe5e0cbea84f20332abe3c48932b1cee549570b9#diff-e3fd6267ce00c54186d7dcd828b1f80cR999

**Comment by blackmixer** [comment]
Проверенно Закрываю
