### ISSUE TITLE
Кмарж в спецификации и стоимость продажи

### ISSUE THREAD

**Issue by blackmixer** [oknosoft/windowbuilder#352]
https://github.com/oknosoft/windowbuilder/blob/62a436f83e82666c5cf177db64188160b19ea1cd/src/modifiers/common/glob_pricing.js#L351-L354
Если в ценообразовании используется Кмарж в спецификации (галка в константах взведена)
то дополнительно нужно проверить есть ли спецификация иначе ссумировать будет нечего и на выходе получим 0

```
const price_cost = $p.job_prm.pricing.marginality_in_spec && prm.spec._obj.length  ?
      prm.spec.aggregate([], ["amount_marged"]) :
      this.nom_price(calc_order_row.nom, calc_order_row.characteristic, price_type.price_type_sale, prm, {});
```

**Comment by unpete** [comment]
Михаил, часто вижу в твоём коде обращения к _obj.
Этого следует, по возможности, избегать. _obj, _data, _attr - служебные реквизиты.

Замечание принять могу, но прозрачность системы от этого снижается.
Получиться, когда спецификация не пустая, цену берём из неё, а когда пустая - вычисляем по другим правилам.

Когда через год к вам обратится коммерческий директор с вопросом, почему в заказе №ххх такая цена, найти ответ будет не просто. Корректирующие формулы - из той же оперы.
