### ISSUE TITLE
Форма добавления услуг и комплектуюущих (CalcOrderAdditions)

### ISSUE THREAD

**Issue by blackmixer** [oknosoft/windowbuilder#353]
при использовании во вставках параметров разворачивать в строку добавления вставки

**Comment by unpete** [comment]
Реализована очень крутая и абстрактная функциональность - можно будет использовать не только в допвставках. Поле табчасти теперь умеет рисовать динамические колонки с правильной типизацией и связями параметров.
Применительно к нашей форме:
- Если для вставок определенного типа задействованы параметры, система на лету создаёт новые классы строк табчасти с дополнительными колонками
- Создаёт индивидуальные метаданные для экземпляра табчасти
- Дополняет элемент справочника scheme_settings новыми полями
- Если позволяют права текущего пользователя, записывает элемент scheme_settings

При необходимости погасить стандартные колонки или изменить заголовки, ширины и порядок колонок, элемент scheme_settings можно отредактировать руками в futon - настройки табчасти расползутся по всем пользователям.

**Comment by blackmixer** [comment]
При включении во вставке  дополнительных параметров (например вставка с типом подоконник
и Параметром Ширина шаг ) выдаётся сообщение об ошибке 
TypeError: Cannot set property 'row' of undefined
TabularSection.swap
node_modules/metadata-dhtmlx/index.js:324

**Comment by unpete** [comment]
> Cannot set property 'row' of undefined

А обновлять версии в npm кто за вас будет?
