### ISSUE TITLE
wnd_debug.js/ print_data.ВсегоИзделий&ВсегоПлощадьИзделий

### ISSUE THREAD

**Issue by RapeFactory** [oknosoft/windowbuilder#357]
Услуги и Аксессуары попадают в расчет полей `print_data.ВсегоИзделий` и `print_data.ВсегоПлощадьИзделий`, хотя не должны по условию. Что надо сделать, чтобы продукция корректно учитывалась? Только "Светопрозрачные конструкции".

Фрагмент кода:

     this.production.forEach((row) => {

      if(!row.characteristic.empty() && !row.nom.is_procedure && !row.nom.is_service && !row.nom.is_accessory) {

        res.Продукция.push(this.row_description(row));

        res.ВсегоИзделий += row.quantity;
        res.ВсегоПлощадьИзделий += row.quantity * row.s;

        get_imgs.push($p.cat.characteristics.get_attachment(row.characteristic.ref, 'svg')
          .then((blob) => $p.utils.blob_as_text(blob))
          .then((svg_text) => {
            res.ПродукцияЭскизы[row.characteristic.ref] = svg_text;
          })
          .catch((err) => err && err.status != 404 && $p.record_log(err))
        );
      }
    });
    res.ВсегоПлощадьИзделий = res.ВсегоПлощадьИзделий.round(3);

**Comment by unpete** [comment]
> хотя не должны по условию

Условия у разных пользователей сервиса - разные.
Типовая математика считает изделиями те строки, в которых непустая характеристика и при этом, номенклатура не помечена, как услуга, техоперация или аксессуар.

При необходимости, вы можете реализовать своё правило подсчета изделий и площади и разместить в коде печатной формы.
Если по эксклюзивням правилам должны рассчитываться итоги за месяц-год в разных разрезах, придётся написать свой дополнительный индекс couchdb

**Comment by RapeFactory** [comment]
@unpete Я могу сделать вывод, что неверно отметили номенклатуры. 
На примере подоконника: 
Вид номенклатуры - продукция. Но вида номенклатуры аксессуар нет. Поставить материал? Профиль? 
С точки зрения заказа подоконник это продукция, но не основная.

**Comment by RapeFactory** [comment]
Ответ есть. Нашли, где устанавливать эти свойства номенклатуры. Вопрос с площадью должен решиться.
