### ISSUE TITLE
wnd_debug.js / print_data.ПродукцияЭскизы

### ISSUE THREAD

**Issue by RapeFactory** [oknosoft/windowbuilder#358]
Есть ли возможность получать эскизы без размерных линий?

**Comment by unpete** [comment]
> возможность получать эскизы без размерных линий

Сохранённые эскизы формируются с размерными линиями.
Динамические - по гибким правилам, у нас предусмотрены параметры рендеринга.
Расскажите, в каком контексте планируете получать эскиз и под какую задачу?

**Comment by RapeFactory** [comment]
@unpete, чтобы из печатной формы Коммерческого предложения нельзя было взять размеры. Это следует из того, что замер бесплатный, и клиенты, взяв точные размеры, идут в другие компании.

**Comment by rnpoddor** [comment]
В одной из задач возникла острая необходимость в эскизе без размерных линий. В одной из печатных форм, нужно выводить эскиз без размерных линий. Было бы хорошо, если при вызове print_data, через параметр можно было задавать, с размерами эскиз нужен или нет!

**Comment by Sehktel** [comment]
@rnpoddor в случае офисного использования, эскиз без размерных линий следует получать с помощью сервиса рендера эскизов и отчетов - отдельная вещь, которая смотрит на те же данные, но выполняет вспомогательную функцию.
Есть вариант работы замерщиков, когда они находятся полностью офф-лайн. 
Если для решения вашей задачи можно использовать он-лайн режим, то спросите @RapeFactory, подобная задача ранее решалась.  За офф-лайн режим увы не скажу.

**Comment by unpete** [comment]
> возникла острая необходимость

Отчего же, тогда, эта задача не включена в веху? Нами, вроде, утверждён регламент: https://github.com/unpete/ecookna/blob/master/README.md

**Comment by unpete** [comment]
@RapeFactory, я тестировал на формуле `5.1 КП: Без логотипа`, изменил только вызов `print_data()`
````javascript
return obj.print_data({
	builder_props: {auto_lines: false, custom_lines: false}
}).then(async print_data => {...})
````
Получилось так:
![image](https://user-images.githubusercontent.com/12096477/44717491-8c65b880-aad6-11e8-9fb8-e4e567da6c1b.png)
dev обновил

**Comment by rnpoddor** [comment]
Безразмерные линии мы уже научились убирать. 2 месяца этот функционал у нас работает. Прошу прощения, за то что не оповестил. Там где нужно, мы перерисовываем характеристику продукции без размеров. Вот наш код:

```
$p.ecookna.get_sketch_no_dim_lines = ox => {
  const characteristic = $p.cat.characteristics.get(ox);
  // сохранение предыдущего состояния свойств построителя
  const propsPrev = characteristic.builder_props;
  // применение свойств построителя без размерных линий к характеристике
  characteristic.builder_props = {
    ...characteristic.builder_props,
    auto_lines: false,
    custom_lines: false
  };
  // генерация эскиза без размерных линий и подмена в print_data
  const attr = { res: {} };
  return characteristic.draw(attr)
    .then(res => {
      const rpl_ref = '_' + characteristic.ref.replace(/-/g, '_');
      let svg = '';
      if (res && res[rpl_ref]) {
        svg = res[rpl_ref].imgs.l0;
      }
      else if (attr.res[rpl_ref]) {
        svg = attr.res[rpl_ref].imgs.l0;
      }
      // возврат к предыдущим свойствам построителя
      characteristic.builder_props = propsPrev;

      return svg;
    });
};
```

**Comment by rnpoddor** [comment]
Например печатная форма `КП: Для клиента`.

**Comment by unpete** [comment]
Вместо изменения свойств характеристики, лучше передать builder_props в рисовалку.
По замыслу, в характеристике лежат умолчания экземпляра продукции, а для свойства конкретного эскиза задаём отдельно.

**Comment by rnpoddor** [comment]
Изменил печатную форму `КП: Для клиента`. Работает хорошо.
