### ISSUE TITLE
Площадь изделия. .s (балконные блоки)

### ISSUE THREAD

**Issue by RapeFactory** [oknosoft/windowbuilder#361]
![image](https://user-images.githubusercontent.com/33118494/34826031-0c330752-f6e6-11e7-875b-41e8fc8babf3.png)
Возьмем например балконный блок, который состоит из двух рам.
![image](https://user-images.githubusercontent.com/33118494/34826141-790db9b2-f6e6-11e7-9d57-8d94ef7c2d17.png)
Его площадь в программе 4, что неверно. Вычислено как 2м * 2м.
А реальная его площадь как сумма двух конструкций 1,82 + 1,4 = 3,22.
Где посмотреть код изначального вычисления площади?
Готов посодействовать, чтобы поправить этот момент.
Либо, в свою очередь, для нужд печатных форм могу сам уточнить вычисление площади в print_data().

**Comment by RapeFactory** [comment]
Продолжая тему, Нашли в scheme    
```
* ### Площадь изделия
* TODO: переделать с учетом пустот, наклонов и криволинейностей
```

**Comment by RapeFactory** [comment]
Если поправить геттер так?
```
get area() {
    let area = 0;
    this.contours.forEach( (row) => {
	area = area + row.path.area.round(0)/10e6;
    });
    return area;
}
```
Так он умеет считать конструкции составные. 
Будем дорабатывать с трапециями и арками.

**Comment by RapeFactory** [comment]
Этот вариант посчитает НЕпрямоугольные конструкции. Но без арок. (трапеции, например)
```
get area() {
    let area = 0;
    this.contours.forEach( (contour) => {
        let points = [];
        contour.nodes.forEach( (node) => {
            let point = [ node.x, node.y ];
            points.push( point );
        } );
        let path = new paper.Path( points );
	area = area + path.area.round(0)/10e6;
    });
    return area;
}
```

**Comment by Sehktel** [comment]
А еще мы добрались до кривых, в том плане, что кривая порождает точки 
и до образующей, на которой мы можем отступить точки с заданным шагом. 
Завтра дойдем до расчета площади криволинейных изделий. 
Разумеется с учетом наличия кривизны элемента как таковой,
т.е. если элемент прямой, то лишняя математика выполняться не будет.

**Comment by unpete** [comment]
Особо пристально посмотрите на [эти строки](https://github.com/oknosoft/windowbuilder/commit/0bc526222a25cff45586af0b7c5654df54e13257#diff-61c0c0a5ebe1e844e87031051a7f2624R294) и завязывайте с попытками считать площадь по точкам.
Авторы paperjs потратили несколько лет на булеву геометрию. Надо пользоваться результатами их труда, а не изобретать велосипеды.

- `area` теперь считается, как **габаритная** площадь всех контуров. для отчетов и ценообразования, лучше всего использовать именно эту площадь
- если нужны сохраненные значения `form_area` для отчетов или статистики в регистрах, имеет смысл добавить реквизит в характеристику

**Comment by unpete** [comment]
https://github.com/oknosoft/windowbuilder/commit/0bc526222a25cff45586af0b7c5654df54e13257
