### ISSUE TITLE
Форма добавления услуг и комплектуюущих TypeError: Cannot read property '_manager' of undefined

### ISSUE THREAD

**Issue by blackmixer** [oknosoft/windowbuilder#365]
Воспроизведение Ошибки по шагам 
1 ) Создаём докумет расчёт заказ 
2 ) Через форму "Аксессуары и услуги"  добавляем продукцию или услугу 
Важно во вставке генерирующей спецификацию присутствует дополнителный параметр Ширина Шаг
С типом Значения "Дополнительное значение"
3) Нажимаем Рассчитать и закрыть (Создаётся продукция  с Характеристикой в таб части продукции)
4) Повторно открываем форму   И про
и закрыть (Создаётся продукция  с Характеристикой в таб части продукции)
4) Повторно открываем форму   И пробуем изменить значение дополнительного параметра (Значение параметра не вернулось в форму) получаем Ошибку 
```
FieldInfinit.js:244 Uncaught TypeError: Cannot read property '_manager' of undefined
    at FieldInfinit.renderContainer (FieldInfinit.js:244)
    at FieldInfinit.render (FieldInfinit.js:329)
```

Дополнительно 
Если добавить еще одну строку продукции то Значение выбирается

**Comment by unpete** [comment]
Можно проверять

**Comment by blackmixer** [comment]
Проверено, работает. Закрываю.
