### ISSUE TITLE
Дополнительные возможности формы Аксессуары и услуги

### ISSUE THREAD

**Issue by blackmixer** [oknosoft/windowbuilder#366]
1 Ограничить доступность параметров для выбора путём применения связей параметров 
основной принцип связи (Вставка > параметр) Или (параметр > параметр )

**Comment by RapeFactory** [comment]
Поясните пожалуйста, как это работает. Как можно скрыть стандартный параметр?

**Comment by blackmixer** [comment]
> Поясните пожалуйста, как это работает. Как можно скрыть стандартный параметр?

Параметры (предопределённые такие как ширина и высота задаются в SchemeSettings)
https://github.com/oknosoft/windowbuilder/pull/375#issuecomment-362545787
https://github.com/oknosoft/windowbuilder/issues/353

дополнительно посмотри со стороны couchdb База doc на схемы 
![screenshot_20180208_174914](https://user-images.githubusercontent.com/24730013/35979257-eb54af30-0cf8-11e8-90b3-b76f07167367.png)

**Comment by RapeFactory** [comment]
Да, час назад нашёл, спасибо. Пробуем.
