### ISSUE TITLE
Управляемое прерывание расчета спецификации

### ISSUE THREAD

**Issue by Sehktel** [oknosoft/windowbuilder#368]
Иногда, возможно, по какой-либо причине потребуется прервать расчет спецификации.
К примеру мы получаем изделие, которое не сможем произвести (строго нет, даже "без гарантий"),
Мы положили в спецификацию строку с ошибкой и дальнейшие вычисления лишены смысла.
Вопрос - как это сделать наиболее корректно?

**Comment by blackmixer** [comment]
если не Хотите 
```
const {before_save} = $p.CatCharacteristics.prototype;
debugger;
$p.CatCharacteristics.prototype.__define('before_save', {
  value: function () {	  
	  if(before_save.call(this) === false) {
	  	return false;
	  };
	//Здесь код проверки на ошибки Возвращающий Ложь (return false;) 
	// если хотим запретить сохранение 

  }
});

```
