### ISSUE TITLE
Использование Ctrl+Scroll для приближения

### ISSUE THREAD

**Issue by Sehktel** [oknosoft/windowbuilder#369]
Вопрос больше "косметический" чем "технический" / обсуждение. 
Имеет ли смысл для унификации действий пользователя перенести приближение/удаление изделия с Alt + Scroll на Ctrl + Scroll?
Ctrl + Scroll ИМХО более предсказуемое поведение для приближения, т.к. эта комбинация используется и в браузерах и в Word.

**Comment by unpete** [comment]
Сейчас прокрутка делает три разные вещи при нажатых Alt, Shift и Ctrl - все эти комбинации нужны в работе.

**Comment by unpete** [comment]
Учтено в https://github.com/oknosoft/windowbuilder/commit/b5fdacd00c359151f7cdcb1a0f7f7855ac776011
