### ISSUE TITLE
Сравнение типа номенклатуры с перечисляемым значением

### ISSUE THREAD

**Issue by Sehktel** [oknosoft/windowbuilder#370]
Здравствуйте. 
Обратил внимание на то, что общая площадь в заказе, считается как простая сумма строк.
![image](https://user-images.githubusercontent.com/24711055/35510068-a072923c-0507-11e8-8abf-43e3174eb365.png)

```js 
          const footer = {
            columns: ",,,,#stat_total,,,#stat_s,#stat_total,,,,#stat_total,,,#stat_total",
            _in_header_stat_s: function(tag,index,data){
              const calck=function(){
                let sum=0;
                o.production.each((row) => {
                  sum += row.s * row.quantity;
                });
                return sum.toFixed(2);
              }
              this._stat_in_header(tag,calck,index,data);
            }
          }
```
Захотел добавить сравнение типа номенклатуры строки заказа с перечислением.
Для того, чтобы исключить из расчет Услуги.
```js
row.nom.nom_type
{name: "Товар", presentation: "Товар, материал", type: "enm.nom_types"}
row.nom.nom_type == $p.enm.nom_types.Товар
false
$p.enm.nom_types.Товар
EnumObj {_obj: {ref: "Товар", sequence: 0, synonym: "Товар, материал"}
```
Можно конечно сравнить со строкой.
```js
row.nom.nom_type.name == $p.enm.nom_types.Товар.ref
true
```
Но правильность этого действия вызывает сомнения.

Можно ли решить эту проблему по другому?

**Comment by unpete** [comment]
> Можно ли решить эту проблему по другому?

В типовом сценарии - нет.
Вы можете реализовать индивидуальный алгоритм в модификаторе прототипа документа _CalcOrder_

> Можно конечно сравнить со строкой

Можно, но это неграмотно. Ссылочные типы надо сравнивать без лишних разыменований.
