### ISSUE TITLE
Поиск заказа по номеру, без учета фильтра подразделения

### ISSUE THREAD

**Issue by unpete** [oknosoft/windowbuilder#372]
Рядом с полем поиска по строке добавлена кнопка с ключиком.
- Если она нажата **И** длина текста в поле фильтра больше 5 символов, поиск выполняется по всем, доступным пользователю заказам с учетом диапазона дат
- Если кнопка отжата или длина текста в поле фильтра меньше 6 символов, поиск выполняется для текущего подразделения и статуса
- Поиск выполняется не только по номеру, но так же по комментарию и названию контрагента. Это справедливо как для первого, так и второго режимов

**Comment by aribaz** [comment]
@unpete Евгений, подскажите, где искать эту кнопку?
![2018-02-01_10-54-33](https://user-images.githubusercontent.com/22028048/35667366-6fb74a64-073e-11e8-8dce-d4174dfb374a.png)

**Comment by blackmixer** [comment]
![screenshot_20180201_110019](https://user-images.githubusercontent.com/24730013/35667559-2c3b7b6a-073f-11e8-8533-d78766f825a6.png)

**Comment by unpete** [comment]
@blackmixer, у тебя старая (вчерашняя) версия
@aribaz в панели динсписка, в поле _фильтр_

**Comment by Sehktel** [comment]
![image](https://user-images.githubusercontent.com/24711055/35668058-fd816396-0740-11e8-8dd9-7f391054afd6.png)
После обновления выглядит так.
Работает.

**Comment by aribaz** [comment]
@nmivan Странно, а у меня не появилась.
Сделала сброс данных и снова вошла, сделала жесткую перезагрузку и все равно нет.
Историю почистить?
У других пользователей есть. За моим компом заходили под другой учеткой недавно, но я делала сборс данных.
