### ISSUE TITLE
Справочник номенклатуры Значение ЭтоУслуга 

### ISSUE THREAD

**Issue by blackmixer** [oknosoft/windowbuilder#377]
Обратил внимание что на стороне браузера фильтрация номенклатуры в расширении которой указано ЭтоУслуга перестало отрабатывать

для поиска номенклатуры использовал следующий код (консоль браузера)

```
let nomenklatura = [];//сюда сложем названия номенклатур
$p.cat.nom.forEach((row) => { //из справочника
  if (row.is_service == true) { //ЭтоУслуга
    nomenklatura.push(row.name); // кладём название
  }
});

nomenklatura; //выводим массив 
```
НА стороне couchdb в документах номенклатур нет записи is_service (true  или false)

Собственно вопрос планируется отказаться от Значения Это Услуга или это моя ошибка ???

**Comment by unpete** [comment]
В коде про is_service нашел ошибку.
Сегодня внесу исправления и верну признак на место - он используется в коде.

**Comment by blackmixer** [comment]
Проверенно закрываю
