### ISSUE TITLE
Справочник фурнитуры проверка ограничений строки фурнитуры 

### ISSUE THREAD

**Issue by blackmixer** [oknosoft/windowbuilder#382]
Проверяет ограничения строки фурнитуры

https://github.com/oknosoft/windowbuilder/blob/9b9eff1be0d85d8666973ed4b337fdd1876047f9/src/modifiers/catalogs/cat_furns.js#L364-L380

В строке 377 при сравнении длинны может сработать ограничение 
Например Входящие в набор 2 Элемента с ограничениями  
от 300  до 600 
от 601 до 1200
полученная длинна для сравнения  может быть не целым числом 

```
len
600.3000000000003
```

 Для округлени я предлагаю округлять значения математически 
![screenshot_20180208_103505](https://user-images.githubusercontent.com/24730013/35960728-e33b8edc-0cbb-11e8-81cb-70a1eddafff7.png)

 ```
 len = (row.side == 1 || row.side == 3) ? cache.w.round(0) : cache.h.round(0);
 ```

**Comment by unpete** [comment]
Округление w, h включу в сегодняшний commit

**Comment by blackmixer** [comment]
проверенно
