### ISSUE TITLE
Миниэскизы, как вложения

### ISSUE THREAD

**Issue by unpete** [oknosoft/windowbuilder#387]
Сейчас, svg-текст миниэскиза, хранится, как attachment к характеристике.
- Это значительно удлиняет репликацию (для вложений нет bulk-режима, их нельзя получить пачкой, только миллионом отдельных запросов)
- Нагружает браузер при отрисовке форм динсписка и документа - лаги + трафик
- Вынуждает иметь на сервере неоптимальный индекс
- Усложняет запись характеристик

Миниэскиз надо хранить обычным текстовым полем

**Comment by unpete** [comment]
### Подсказки администратору по обновлению данных

- останавливаем репликации (удаляем записи из базы `_replicator`)
- останавливаем регламентные задания на сервере 1С
- останавливаем nginx, чтобы пользователи из интернета не нагадили нам в базы во время реструктуризации
- удаляем дилерские базы
- устанавливаем для базы doc [_revs_limit=1](http://docs.couchdb.org/en/2.1.1/api/database/misc.html#db-revs-limit)
- с помощью [этого скрипта](https://github.com/oknosoft/windowbuilder/blob/master/scripts/move_svgs.js), переносим миниэскизы из вложений в реквизит характеристик (параметры авторизации задаются в переменных окружения, выполнять желательно в локальной сети сервера, чтобы не гонять через интернет лишние гигабайты)
- с помощью скрипта [backup.sh](https://github.com/oknosoft/windowbuilder/tree/master/scripts/couchdb-dump), архивируем базы `ram` и `doc`
- с помощью скрипта [restore.sh](https://github.com/oknosoft/windowbuilder/tree/master/scripts/couchdb-dump), восстанавливаем базы `ram` и `doc` из архива, при этом в новых базах не будет истории изменений документов и мусора от старых вложений
- удаляем из базы `doc` документ `_design/svgs`
- обновляем 1С (в drive.google.com опубликована свежая cf-ка)
- из интерфейса 1С, справочник `Абоненты`, выполняем команду `Создать базы и пользователей`
- запускаем репликации с перерывами в несколько минут, чтобы не слишком нагружать сервер
- по завершению начального такта репликаций, из интерфейса 1С библиотека интеграции → `Обслуживание`, выполняем пересчет индексов в базах `ram` и `doc` основного и дилерских отделов
- в базе `ram`, изменяем значение поля `version` документа `data_version`
- из интерфейса 1С библиотека интеграции, первая закладка `Адреса сервисов`, командой `Проверить подключение`, выясняем текущие `update_seq` баз `ram` и `doc` и копируем их на закладку `Загрузка` в колонку `Since`
- запускаем регламентные задания на сервере 1С
- включаем nginx

**Comment by unpete** [comment]
Параллельно с переносом миниэскизов, можно задействовать новый формат хранения среза цен номенклатуры: 
![image](https://user-images.githubusercontent.com/12096477/36605258-0ba3b0ac-18e2-11e8-99cb-f56c304647df.png)
Срез надо обновлять руками после редактирования документов установки цен

**Comment by Sehktel** [comment]
После обновления базы данных требует обновления кодовая база. 
Например сейчас при выборе изделия из типового блока формируется "нет эскиза".
За это отвечает файл widgets -> rsvg.js 
Откуда берется значение `val`  я пока не понимаю.
```js
function eXcell_rsvg(cell){ //the eXcell name is defined here
	if (cell){                // the default pattern, just copy it
		this.cell = cell;
		this.grid = this.cell.parentNode.grid;
	}
	this.edit = function(){};  //read-only cell doesn't have edit method
	this.isDisabled = function(){ return true; }; // the cell is read-only, so it's always in the disabled state
	this.setValue=function(val){
		this.cell.style.padding = "2px 4px";
		this.setCValue(val ? $p.iface.scale_svg(val, 120, 0) : "нет эскиза");
	}
}
```

**Comment by nmivan** [comment]
@unpete, поставь баллы.
