### ISSUE TITLE
Индикатор трапеции

### ISSUE THREAD

**Issue by unpete** [oknosoft/windowbuilder#388]
Добавить в правый верхний угол рисовалки индикатор, возникающий, если в изделии есть наклонные элементы

**Comment by Felishia** [comment]
@unpete , а по этому вопросу есть движения? Для нас сейчас очень актуально

**Comment by unpete** [comment]
Добавил индикатор в правый верхний угол рисовалки
- появляется, если есть наклонные элементы
- автоматически прячется, если изделие прямоугольное
- по индикатору можно кликнуть мышью - тогда на 1.5 секунды наклонные элементы подсветятся красным

Можно проверять в dev

**Comment by Felishia** [comment]
Отличный инструмент.
