### ISSUE TITLE
Документы установки цен

### ISSUE THREAD

**Issue by unpete** [oknosoft/windowbuilder#40]
Просьба внести в базу несколько документов установки цен номенклатуры.
Материалы разного типа и разных поставщиков разнести по разным документам.
Это позволит сделать выгрузку цен понятными кусочками.
Если положить алюминий и пвх в один документ установки цен, по ссылкам потянется лишняя номенклатура

**Comment by Oparin-Igor** [comment]
Смогу сделать, завтра с утра.

 

  _____

**Comment by Oparin-Igor** [comment]
В старой базе три прайслиста 
1. Фурнитура АХОР
2. Фурнитура РОТО
3 ПВХ  Експроф.
Другие цен нет надо разговаривать с поставщиками.
В новой технологической базе нет документа прайслист.
У меня есть механизм "загрузка из табличного документа" только в старую базу. 
Постепенно все цены загрузить можно.
для проверки цены Ехпроф, рото и ахор в принципе достаточно.

**Comment by unpete** [comment]
> В новой технологической базе нет документа прайслист

Есть. Даже название у него в точности совпадает с документом из УТ и КА: _Установка цен номенклатуры_

> Других цен нет надо разговаривать с поставщиками

За одно, предложить этим поставщикам сотрудничество. Они рекомендуют своим клиентам _Заказ дилера_, а _Заказ дилера_ делает для этого поставщика автоматические электронные заявки.
Без фанатизма, но цены на популярные профили и фурнитуры желательно иметь.

> У меня есть механизм "загрузка из табличного документа"

Загрузка табличного документа есть для любой базы - хоть в классическом, хоть в управляемом приложении. Наверное, физически это разные обработки, но обе есть на ИТС

> В старой базе три прайслиста

Ладно, перенесу прайсы самостоятельно. При переносе твоими руками можно было бы вычистить неиспользуемые позиции

**Comment by Oparin-Igor** [comment]
При общении задам вопрос по использованию обработок.
Не используемых позиций там нет, т.к. я цены сам добавлял.
