### ISSUE TITLE
Параметр "наименование изделия"

### ISSUE THREAD

**Issue by unpete** [oknosoft/windowbuilder#41]
> Используется для Балк.двери и окна, для автоматического установки параметра бал.ручка и защелка, в БД устанавливать в окне нет. А также при выборе замков в рото, используются замки с разной высотой ручки и соответственно меняется комплектация.

Ставлю фоновую задачу: либо избавиться от подобных параметров, либо убрать лишние системы профилей. Сейчас информация про одно и то же дублируется в двух местах.

**Comment by Oparin-Igor** [comment]
Не совсем так. В системах профилей другая информация.

Балконная ручка и защелка может устанавливаться отдельно, без обвязки.
Только петли, ручка и защелка.

Из параметров конечно наверное есть лишние, но не эти. Например в фурнитуре
Винкхаус несколько параметров созданные только для этой системы. 

В планах есть убрать лишние наборы фурнитуры. Дудлирующиеся наборы
-поворотная и штульп поворотная, пов-откидная и штульп пов-откидная.

 

  _____

**Comment by unpete** [comment]
> Не совсем так. В системах профилей другая информация

Как минимум, параметр нужно переименовать. Словосочетание "наименование изделия" неверно использовать в параметрах створки, т.к. в _изделии_ может быть много контуров, среди которых и балконные и оконные и пр. "тип блока" или "тип рамы" - более уместно

**Comment by Oparin-Igor** [comment]
переименован в "тип блока"
