### ISSUE TITLE
Ошибки в CF 2.3.7.241

### ISSUE THREAD

**Issue by blackmixer** [oknosoft/windowbuilder#410]
Интеграция Настройка Создать базы 

если у пользователя отсутствует отдел 
(возможно новое поведение системы)
> 
> {ОбщийМодуль.ИнтеграцияСериализацияСервер.Модуль(2214)}: Поле объекта не обнаружено (Отдел)
> 		Если Отделы[Стр.Отдел] = Неопределено Тогда

**Comment by blackmixer** [comment]
Массовый запуск репликаций 
для версии couchdb 2.1.1 необходимо сделать настройку 
[If user code reads or manipulates replicator document states, consider using the [replicator] update_docs = true compatibility parameter.](http://docs.couchdb.org/en/latest/whatsnew/2.1.html)

**Comment by unpete** [comment]
> для версии couchdb 2.1.1 необходимо сделать настройку

`update_docs = true` проще установить один раз в настройках couchdb - не вижу смысла указывать это для каждой репликации

**Comment by unpete** [comment]
Про пустой отдел, уточни, как в такую ситуацию попасть?
Если запускать пачку репликаций из списка в форме абонента, отдел всегда заполнен.
Или проблема не в запуске репликаций, а в какой-то другой операции?
