### ISSUE TITLE
Массовые ошибки в заказ дилере

### ISSUE THREAD

**Issue by rnpoddor** [oknosoft/windowbuilder#412]
**Ошибка №1:**

Проявляется в разных заказах, где много изделий, например здесь [ff1b599f-5d95-46e4-856e-9436af85776c](https://zakaz.ecookna.ru/doc.calc_order/ff1b599f-5d95-46e4-856e-9436af85776c). При переходе на редактирование изделий, выбрасывает ошибку. Проявляется при выборе последних изделий в списке.

![image](https://user-images.githubusercontent.com/33495931/42088195-6cd82750-7ba1-11e8-935a-2f71a3f1a3e1.png)

**Ошибка №2:**

Проявляется при создании нового изделия, при отображении выбора шаблонов. Например заказ [198fddbc-6ff0-4f9d-850f-61f70fe43e18](https://zakaz.ecookna.ru/doc.calc_order/198fddbc-6ff0-4f9d-850f-61f70fe43e18).

![image](https://user-images.githubusercontent.com/33495931/42090010-4edfbbbc-7ba8-11e8-8377-d1a7d9ebb112.png)

**Ошибка №3:**

Проявляется при выборе некоторых шаблонов. Например, добавляем шаблон

![image](https://user-images.githubusercontent.com/33495931/42090277-83d23af6-7ba9-11e8-8846-913ab1b99d22.png)

получаем следующую ошибку

![image](https://user-images.githubusercontent.com/33495931/42090312-a04384ba-7ba9-11e8-9078-5d0f8367bd3a.png)

**Comment by unpete** [comment]
Про шаблоны смотреть смысла нет. Вы, наверное, в курсе #503
По поводу пункту жду PR или более точную постановку задачи.

**Comment by rnpoddor** [comment]
Простите, обсуждение открыл не там где нужно.
