### ISSUE TITLE
ссылка на пустую характеристику при попытке обхода связей параметров

### ISSUE THREAD

**Issue by RapeFactory** [oknosoft/windowbuilder#424]
Хочу привлечь внимание к этому коду. 
https://github.com/oknosoft/windowbuilder/blob/12db818d1d56fe99d01759212e0f6bdbc2e3604b/src/metadata/chartscharacteristics/cch_properties.js#L225

Поле _ox_ получает в значение ссылку на объект с пустым _ref_, который не имеет ничего под капотом, что в дальнейшем разыменовании приводит к ошибке на строке
https://github.com/oknosoft/windowbuilder/blob/12db818d1d56fe99d01759212e0f6bdbc2e3604b/src/metadata/chartscharacteristics/cch_properties.js#L157
при обращении к _params_.

Но только в некоторых редких случаях вставок мы попадаем на условие в котором ошибка. Всё это в методе  https://github.com/oknosoft/windowbuilder/blob/12db818d1d56fe99d01759212e0f6bdbc2e3604b/src/metadata/chartscharacteristics/cch_properties.js#L117

@unpete или @nmivan, что вообще должно быть под _ox_?

**Comment by unpete** [comment]
Вы какую задачу на самом деле решить пытаетесь?

**Comment by RapeFactory** [comment]
Падение формы CalcOrderAdditions

**Comment by RapeFactory** [comment]
И причем на ходовом Подоконнике Российском, сейчас проверил.

**Comment by unpete** [comment]
Вероятно, связи параметров не получают от CalcOrderAdditions того контекста, на который рассчитаны.
Повторю вопрос(ы):
- что именно должны делать связи параметров в вашей задаче? они там точно нужны? не задействованы ли формулы, ожидающие контекст рисовалки?
- последовательность действий для воспроизведения

**Comment by Felishia** [comment]
Падение происходит только на одном виде - подоконник, на всех остальных работает.
Создаю счет, захожу на закладку продукция, нажимаю плюс - аксессуары и услуги. Появляется форма - в разделе подоконник нажимаю на плюс - выпадает подоконник российский пвх  - щелкаю в поле ширина подоконника и все падает

**Comment by RapeFactory** [comment]
develop

**Comment by RapeFactory** [comment]
Это относится к https://github.com/oknosoft/windowbuilder/pull/475# и к https://github.com/unpete/ecookna/issues/636
В подоконнике больше ошибок нет. 
Но есть как раз в группе вставок _Профиль_, и именно та же ошибка.

Я сразу закрою, так как есть более свежие разборы этой проблемы.
