### ISSUE TITLE
К обсуждению 12.04.2016

### ISSUE THREAD

**Issue by unpete** [oknosoft/windowbuilder#44]
- Похвастаться формулами
- Похвастаться параметрами
- Похвастаться визуализацией с акцентом на абстрактность
- Параметры про цвет, но вместо цвета используют значения свойств - **плохо**
- Цветовые характеристики для ламинированного профиля - **очень плохо**. Правильнее учитывать тот профиль, что покупаем + услугу ламинации или плёнку и собственные затраты на ламинацию
- Замечания про замечания, оформленные не по [Gherkin](http://wellbehaved.readthedocs.org/ru/latest/Gherkin.html). @Oparin-Igor Прочитать:
  - http://testvsio.com/index.php/a/18-android/android-basic/27-andr-b
  - https://www.ibm.com/developerworks/ru/library/a-devops5/
- Свойства _Ручка на стороне_ и _Ось поворота_ отличаются в разных фурнитурах. Предлагаю настроить единообразно, по умолчанию для левого открывания. Для правого - инвертировать сторону и координаты
- Рассказать про управление кнопками в диалоге размерных линий

**Comment by Oparin-Igor** [comment]
Намек не понял

 

  _____

**Comment by unpete** [comment]
> Намек не понял

Нет никакого намёка. Завершенные задачи принято закрывать, чтобы не болтались в списке.

Совещание 12.04 прошло. Соответственно, задача перенесена в закрытые.

 

 

С уважением, Маляров Евгений

1С:Франчайзи "Окнософт"

код партнера: 34991-75

тел: +73519093591

http://www.oknosoft.ru <http://www.oknosoft.ru/> 

 <mailto:info@oknosoft.ru> mailto:info@oknosoft.ru

Skype: unpete-m
