### ISSUE TITLE
Расчет ламинация

### ISSUE THREAD

**Issue by Oparin-Igor** [oknosoft/windowbuilder#46]
Добавить в расширение номенклатуры 2 поля. 
ширина пленки для ламинации наружной.
ширина пленки для ламинации внутренней

**Comment by unpete** [comment]
Делать будем в модном БСП-шном стиле - через допреквизиты, чтобы не менять структуру объекта номенклатуры.

Поля уже добавлены - видны на первой закладке карточки номенклатуры - можно заполнять.
Для единообразия с прежним реквизитом про окраску, нужно указывать площадь ламинации погонного метра профиля, а не ширину плёнки.

По замыслу, поля должны быть видны только у номенклатуры с видом номенклатуры _профиль_, но форма фильтр не отрабатывает, свойства видны у всех номенклатур. В рабочем порядке лишние поля спрячу. Это касается не только свойств окраски, а всех реквизитов. Например, масса или плотность в услугах и техоперациях.

**Comment by Oparin-Igor** [comment]
Для понимания 
Для рамы, створки Z 
цвет снаружи- широкая часть рамы, невидимая сторона рамы.
цвет изнутри - узкая часть рамы, видимая часть рамы, вид со стороны открывания.
Для створки Т
цвет снаружи -узкая часть створки, невидимая сторона створки.
цвет изнутри - широкая часть створки, видимая сторона, вид со стороны открывания.

**Comment by unpete** [comment]
Чтобы у меня и пользователей не возникло вопросов и разночтений,
предлагаю КАЖДЫЙ реквизит и параметр снабжать эскизами и пояснительным текстом.
Примеры я показывал вчера на конференции.

У нас есть возможность приклеить справку с эскизами не только к справочнику в целом,
но и к каждому элементу справочника в отдельности.

 

С уважением, Маляров Евгений

1С:Франчайзи "Окнософт"

код партнера: 34991-75

тел: +73519093591

http://www.oknosoft.ru <http://www.oknosoft.ru/> 

 <mailto:info@oknosoft.ru> mailto:info@oknosoft.ru

Skype: unpete-m

**Comment by unpete** [comment]
Закрыто, т.к. объединено с #23
