### ISSUE TITLE
Справочник Фурнитура

### ISSUE THREAD

**Issue by Oparin-Igor** [oknosoft/windowbuilder#47]
Рассмотреть целесообразность замены переноса привязки фурнитуры в системе профилей отдельным признаком "Активная" - по аналогии с самими системами

**Comment by unpete** [comment]
Проблема решена более радикально:

- Табличная часть _Фурнитура_ удалена из _Параметров продукции_, т.к. это создавало проблемы при нарезке баз новым клиентам с другими умолчаниями
- Реквизит _Активная_ удалён из _Параметров продукции_. В _Фурнитуру_ этот признак, так же, решено не добавлять

## Добавлена подсистема _Абоненты_
- Назначение подсистемы - управление подписчиками, хранение и управление списком пользователей и индивидуальными настройками абонентов
- В план видов характеристик _Предопределенные элементы_ и справочник _Формулы_ добавлен реквизит _Зона_, позволяющий создавать индивидуальные константы и формулы в привязке к абонентам
- Изменён алгоритм формирования начального образа. Теперь, он опирается на данные справочника _Абоненты_, а не на список заказов и галки _Активная_ в параметрах продукции
