### ISSUE TITLE
Печатные формы

### ISSUE THREAD

**Issue by unpete** [oknosoft/windowbuilder#48]
Для демоверсии достаточно четырёх форм:
- [x] Договор
- [x] Заказ с эскизами
- [ ] Спецификация с размерами и ценами для понимания, откуда что берётся
- [ ] фрагменты спецификации с эскизами для производства

**Comment by unpete** [comment]
Разработана и опробирована структура данных и API печатных форм:

- Шаблон и алгоритм печати живёт в элементе справочника _Формулы_. Отчет - это частный случай формулы
- Объект _SpreadsheetDocument_ реализует функциональность, аналогичную табличному документу 1С. Пока доступны лишь самые необходимые методы. Со временем, функциональность можно будет расширить
- Аналогом _Области ячеек табличного документа_ выбран стандартный _HTMLElement_ - у него из коробки больше возможностей чем у 1С-ного прототипа
- Для печати в PDF будем использовать [jsPDF](https://github.com/MrRio/jsPDF). Он, кажется, неплохо справляется с задачей HTML -> PDF

**Comment by nmivan** [comment]
@unpete , эти печатные формы еще нужны?

**Comment by unpete** [comment]
Это отчёт _анализ спецификации_

**Comment by nmivan** [comment]
Закрываем эту тогда?
