### ISSUE TITLE
Откат объектов без вложений в истории версий

### ISSUE THREAD

**Issue by nmivan** [oknosoft/windowbuilder#487]
+ исправление неточности в формировании timestamp

**Comment by nmivan** [comment]
Сейчас рано, там доделать нужно откат характеристик. Сейчас только "простые" объекты.

**Comment by unpete** [comment]
А можно узнать, чем характеристики не просты?

**Comment by nmivan** [comment]
Характеристики просты, а заказы - нет, т.к. содержат характеристики.
Ты ли это?
