### ISSUE TITLE
Список значений в дополнительных реквизитах (option list)

### ISSUE THREAD

**Issue by unpete** [oknosoft/windowbuilder#50]
Если бы не совместимость с 1С БСП, реализация не составила бы труда.
т.к. совместимость нужна, хранить будем JSON - строку с массивом guid-ов выбранных элементов
- [x] Признак _список_ в плане видов характеристик
- [x] Формы списка опций на стороне 1С и metadata.js
- [ ] Учесть списочные параметры в обработчиках

**Comment by unpete** [comment]
Форма _списка опций_ открывается вместо типовой формы выбора значения в двух случаях:
- В карточке _Параметра_ взведён бит _Список_
- В поле _Вид сравнения_ строки параметров выбран вид _В списке_ или _Не в списке_

![image](https://cloud.githubusercontent.com/assets/12096477/23342672/5e060068-fc80-11e6-9d6e-6c3640d2166f.png)

![image](https://cloud.githubusercontent.com/assets/12096477/23342678/7d6024c0-fc80-11e6-9949-4871095f7b8b.png)

Для открытия списка опций используйте команду _Показать все_
![image](https://cloud.githubusercontent.com/assets/12096477/23342689/aa9d87e8-fc80-11e6-9d20-1050c0f8e8ad.png)

![image](https://cloud.githubusercontent.com/assets/12096477/23342695/c02d6ab0-fc80-11e6-8b84-e0220950318e.png)

**Comment by nmivan** [comment]
Списочные параметры учтены в обработчиках на стороне сервиса, теперь и на стороне 1С, при подборе ключей параметров (модуль менеджера, функция ПоПараметрам()).
