### ISSUE TITLE
Настройка технолочических справочников

### ISSUE THREAD

**Issue by Oparin-Igor** [oknosoft/windowbuilder#51]
- [x] Корректировка наименований "номенклатура".
- [x] Корректировка наименований "спровочник вставки".
- [x] Размеры армировай "вставки"
- [x] Описание цвета элементов "вставки", "соединения"
- [x] Удаление дублирующих параметров фурнитура.
- [x] Заполнение параметров фурнитура в "Параметрах продукции"
- [x] Заполнение параметров профиль в "Параметрах продукции"
- [x] Удаление(оптимизация) неиспользуемых видов открывания, типа "штульп", "штульп с ручкой, без ручки"
- [x] Заполнение реквизита "площадь ламинации" системы КВЕ,
- [x] Заполнение реквизита "площадь ламинации" системы  Ехпроф
- [x] Добавление визуализация ручки в системе фурнитур maco, poto.
- [ ] Корректировка элементов визуализации (ответки, проветриватели, блокираторы и пр.)
- [x] Создание универсальной системы фурнитуры для дверей с визуализацией..
- [ ] Добавление формул дренажи в справочник "вставки"
- [ ] Добавить эскизы в справочнике "формулы" описание.
- [x] Корректировка вставок и соединений в системе витраж F50
- [x] Дополнить справочник глобал система профиль Дерево.
- [x] Заполнить справочник цвето-ценовые группы Дерево
- [x] Дополнить справочник глобал система фурнитура МАСО (Дерево+ПВХ)
- [ ] Дополнить фурнитуру МАСО, безопасность WK2, после реализации "списочные параметры"
- [x] Добавить документы для подключеных пользователей, установка цен номенклатуры с нулевыми ценами, для упрощения заполнения цен клиентами. 
  Фурнитура: AXOR, CTH, INTERNIKA, MACO, ROTO NT, Фурнитура общие элементы
  Профиль: AKFA, ALUPLAST, ALUTECH, ARTEC, BRUSBOX, EXPROF, PROPLEX, REHAU, VEKA,
  Армирование
- [ ] Добавить документы установка цен номенклатуры с нулевыми ценами
  Фурнитура:ELEMENTIS, ENDOW, FORNAX, FUHR, G-LOCK, GU, KALE, SCHURING, SIEGENIA-AUBI, VHS, VORNE, WINKHAUS.
- [ ] Добавить документы установка цен номенклатуры с нулевыми ценами
  Профиль: AVANGARD, BARS, BRUGMANN, CITYLUX, DIFENCE, FORWIN, FUNKE, GEALAN 8000, GOODWIN, GRAIN, GUTWERK, KBE, KRAUSS, LG, MONTBLANC, NOVOTEX, PLAFEN, SALAMANDER, SCHUCO, TECOLINE, Deceuninck, TROCAL, VITRAGE, WDS, WINTECH, СПК.

**Comment by Oparin-Igor** [comment]
Для удаления повторяющихся наборов фурнитур. Добавлен реквизит "Тип материала" , значения ПВХ, Алюминий, Дерево.

**Comment by unpete** [comment]
> Добавлен реквизит..

Короткий текст лучше гробового молчания, но  по возможности, просьба писать более развёрнуто. Из описания совсем не понятно, куда, что и зачем добавлено.
Пример _Было_ [`1`, `2`, `3`] _Стало_ [`2`, `7`] упростил бы понимание.
Существенные особенности настройки технологии можно сразу включать в wiki или помечать issue, как исходный материал для доработки и включения в wiki

**Comment by Oparin-Igor** [comment]
Вставка тип "Стеклопакет"   Мщ10 внутр и   Мщ10 нар
Не работает математика при выборе во вставке «расчет кол-ва» «по площади», не учитывается коэффициент.
