### ISSUE TITLE
После коммита c197798e 2019-07-24 | авторизация proxy [unpete] не компилится windowbuilder.

### ISSUE THREAD

**Issue by senitskiy** [oknosoft/windowbuilder#535]
c197798e 2019-07-24 | авторизация proxy [unpete]

Failed to compile.

./src/components/App/AppView.js
Module not found: Can't resolve 'metadata-react/FrmLogin/Proxy' in 'D:\Project\windowbuilder\src\components\App'

**Comment by unpete** [comment]
Это нормально. Вопрос ваши предшественники поднимали много раз.
Напомню ответ: Изменения в npm отстают от изменений в git. Я не могу публиковать в npm каждый чих без отладки.
Если работаете с локальным windowbuilder-ом, посмотрите скрипт 'meta:link' из wb или 'drawer:fetch' из wb-repotrs. Файлы внутри node_modules надо освежать из git.
Либо, тянуть к себе изменения только после выхода свежей версии metadata в npm.

**Comment by aks60** [comment]
В 'meta:link'  строка => 'const remoteNodeModules = 'D:\\WORK\\0KNOSOFT\\UniServer\\www\\builder2\\git-osde\\packages';'
Это откуда?

**Comment by unpete** [comment]
В вашем случае, путь будет другим. Можно напрямую из git, можно из локального каталога, если держите у себя копию метадаты.

**Comment by aks60** [comment]
Положил копию 'D:\\Data\\90\\metadata.js-develop\\packages';, запустил
скрипт meta.link.js. Получил отчёт.
from D:\Data\90\metadata.js-develop\packages\metadata-abstract-ui written 5
files
from D:\Data\90\metadata.js-develop\packages\metadata-core written 3 files
from D:\Data\90\metadata.js-develop\packages\metadata-dhtmlx written 1 files
from D:\Data\90\metadata.js-develop\packages\metadata-pouchdb written 2
files
from D:\Data\90\metadata.js-develop\packages\metadata-react written 4 files
from D:\Data\90\metadata.js-develop\packages\metadata-redux written 2 files
from D:\Data\90\metadata.js-develop\packages\metadata-superlogin written 4
files

Ошибка компиляции та же.
Failed to compile.
./src/components/App/AppView.js
Module not found: Can't resolve 'metadata-react/FrmLogin/Proxy' in
'C:\JScript\windowbuilder\src\components\App'

Почему вы внесли изменения metadata в ветку develop, а в windowbuilder в
master тем самым создали конфликт в opensours
проекте. Или я чего то не понимаю.

пн, 29 июл. 2019 г. в 19:11, Evgeniy Malyarov <notifications@github.com>:

**Comment by aks60** [comment]
На предыдущих версиях при запуске программы не проходит авторизация, на
последнем commit ошибка компиляции.

вт, 30 июл. 2019 г. в 12:13, Sergey Aksenov <gonved60@gmail.com>:

**Comment by unpete** [comment]
После https://github.com/oknosoft/windowbuilder/commit/0eae36259151cd7fc1fe4a2f9519df72ec00ab44 будет собираться, а на случай, когда не хватает файлов из метадаты, есть два решения: подтянуть их в свои папки скриптом или руками, либо дождаться релиза в npm.
