### ISSUE TITLE
Рабочие вопросы с клиентурой

### ISSUE THREAD

**Issue by Oparin-Igor** [oknosoft/windowbuilder#54]
- [ ] разработать основное положение для работы с клиентами ориентированных на продажу окон.
- [ ] разработать основной договор с клиентами
- [ ] определить методы и инструменты для работы с клиентами.

**Comment by unpete** [comment]
> основное положение для работы с клиентами

В качестве прототипа можно взять 1С:Fresh. Там сделано весьма разумно:

- Клиент может сам зарегистрироваться и начать работу - для запуска типовой базы с ограниченным функционалом не требуется участие нашего специалиста
- Есть тарифы и отчет для клиента по использованию сервиса
- Напоминания об оплате и счета формируются автоматически, факт оплаты и продление подписки заводятся руками оператора, который обрабатывает платежное поручение
- Если оплата не поступила - доступ к серверу блокируется - человек может продолжить работу в своей локальной копии

**Comment by Oparin-Igor** [comment]
*	Если оплата не поступила - доступ к серверу блокируется - человек
может продолжить работу в своей локальной копии 

А ограничить по времени можно? Или на данном этапе не будем ограничивать?

 

 

 

 

 

 

 

 

 

 

 

 

 

 

  _____

**Comment by unpete** [comment]
> А ограничить по времени можно

Локальная копия - вечная. Ограничить можно только доступ к синхронизации и обновлениям.
Наверное, можно настроить правило: убивать базу, если к ней никто не обращается ~ 90 дней.

**Comment by Oparin-Igor** [comment]
А 60 дней но с архивацией данных?

**Comment by Oparin-Igor** [comment]
Без договора плохо. Нодо, что бы была какая то ответственность пользователя.
