### ISSUE TITLE
Контроль активной репликации в форме отдела абонента

### ISSUE THREAD

**Issue by unpete** [oknosoft/windowbuilder#558]
Добавлена проверка и возможность оперативно перечитать статус репликации с сервера
![image](https://user-images.githubusercontent.com/12096477/72375335-b51f3a00-372d-11ea-9cd6-daac6bb366c0.png)

**Comment by unpete** [comment]
Пользователь с ролью `ПолныеПрава`, но без роли `АдминистрированиеИнтеграции` (который обычно редактирует пользователей и отделы абонентов), может останавливать репликацию, чтобы внести изменения, но не может запускать.

**Comment by rnpoddor** [comment]
Какие наши действия на случай работы репликации, мы её останавливаем, вносим изменения в отдел абонентов, направляем запрос Вам на запуск репликации? За период времени между остановкой репликации и вашим запуском даные реплицироваться не будут?

**Comment by unpete** [comment]
> За период времени между остановкой репликации и вашим запуском даные реплицироваться не будут?

Да, так безопаснее, чем сейчас.
Возможно, надо блокировать не всю форму, а только критические поля. Подумаю об этом.

**Comment by unpete** [comment]
- Блокироваться будут только опасные поля. Табчасти можно будет править без остановки репликации
- Доплнительно, в формы объекта и списка выведу индикатор, что репликация изменена и требуется перезапуск. Сейчас такой индикатор получаю отчетом - в формах будет удобнее

**Comment by rnpoddor** [comment]
> Да, так безопаснее, чем сейчас.

Тогда как то надо сокращать время между нашим запросом на запуск репликации и исполнением этого запроса. Если задержка будет 2-3 дня, для тех кто работает в этом отделе и подчинённых отделах работа парализуется.

**Comment by unpete** [comment]
Добавил реквизитов в формы объекта и списка отделов абонентов, изменил блокировку - теперь табчасти можно править и у реплицирующегося отдела.
Обновил cf в google drive.
