### ISSUE TITLE
Установка oknosoft

### ISSUE THREAD

**Issue by KILLLATIV** [oknosoft/windowbuilder#570]
Здравствуйте! Хотел бы узнать, есть ли у Вас инструкция по установке полной версии программы :)

С демо версией проекта ознакомился благодаря [статье](https://infostart.ru/public/540168/) на сайте. Заранее спасибо!

**Comment by unpete** [comment]
С наскока самостоятельно не запустите - там несколько частей и не все есть в github.
Решение, подходит ли оно в принципе под ваши задачи примем на скайп-конференции.
Детали обсудим в вашем приватном репозитории.
