### ISSUE TITLE
Ошибки построителя

### ISSUE THREAD

**Issue by Oparin-Igor** [oknosoft/windowbuilder#58]
- [x] при рисовании контура рисует линию.
- [x] при выборе артикула плодит окна выбора.
- [x] при установке импоста рисует линию.
- [x] при установке импоста створка примагничивается к импосту.
- [x] при выборе средней стойки пропадают пакеты.
- [x] вновь нарисованные изделия не сохраняются.
- [x] при выборе нового профиля левая панель сбоку становиться не доступной.
- [x] витраж соединение в 0 точке приводит к потере пакетов.
- [x] В спецификации размеры не соответствуют 3,4999 надо 3,5.
- [x] При увеличении размера рамы, используя сдвиг, пропадают пакеты и створок.
- [x] При выборе системы дерево в раму попадают импосты, должны профили из системы.
- [x] при изменении рамного профиля не меняются соединения.
- [ ] при установки створки профили не соответствуют настройки системы по умолчанию.
- [ ] на эскизе лишняя ручка внизу конструкции.
- [ ] в глухом контуре устанавливается фурнитура.
- [ ] размеры слоя створка не соответствует габаритам створки.
- [ ] высота ручки с открываниях лево- право разная.

**Comment by unpete** [comment]
> при установке створки профили не соответствуют настройкам системы по умолчанию

Просьба проверить - это сегодня было исправлено

> размеры слоя створка не соответствует габаритам створки

Просьба проверить - перенёс забытые ранее изменения

**Comment by unpete** [comment]
@Oparin-Igor Неужели, 60 часов, прошедших с момента предыдущего комментария недостаточно, чтобы проверить два пункта?

**Comment by unpete** [comment]
Закрываю, т.к. нет активности со стороны инициатора задачи

**Comment by Oparin-Igor** [comment]
по сделанным пунктам замечаний нет.
кроме округлений

**Comment by Oparin-Igor** [comment]
Высота ручки левая правая разная
https://light.oknosoft.ru/new/#obj=cat.characteristics&ref=d0513323-4baa-4fe4-e5bb-ba1db1e28d04&frm=builder&view=orders
