### ISSUE TITLE
Лишняя ручка

### ISSUE THREAD

**Issue by unpete** [oknosoft/windowbuilder#59]
Проявлялось на фурнитурах MACO. Возможно, и других фурнитурах.
Исправлено две ошибки:
- MCO-00036 (*Maco поворотно-откидная) - для поднабора VAR-00015 (Окно ручки) отсутствовал фильтр по типу механизма. Отсюда - вторая ручка
- MCO-00040 (Maco пов-отк механизм fix) - в строках, добавляющих визуализацию отсутствовал номер стороны, на которой рисовать ручку. Отсюда - ручка на нижнем элементе. Вероятно, сторона с номером 0 интерпретируется, как первая - нижняя

**Comment by Oparin-Igor** [comment]
ручка отображается как и задумано по указанному эскизу.
