### ISSUE TITLE
Регистрация и синхронизация на стороне 1С

### ISSUE THREAD

**Issue by unpete** [oknosoft/windowbuilder#60]
- [ ] Команда _Пересоздать зону_
- [ ] Команда _Заполнить_
- [ ] Команда _Дозаполнить_
- [ ] Команда _Зарегистрировать во всех зонах_
- [ ] Интеллектуальная регистрация для разделяемых справочников

**Comment by unpete** [comment]
Учесть при регистрации номенклатуру систем с иерархией и номенклатуру расчетов, включенных в зону

**Comment by nmivan** [comment]
@unpete , проверь пожалуйста актуальность списка в чекбоксе.

**Comment by unpete** [comment]
Закрываю
