### ISSUE TITLE
Регистр Корректировки спецификации

### ISSUE THREAD

**Issue by unpete** [oknosoft/windowbuilder#61]
Для повышения гибкости и единообразия, регистр `пзКорректировкаСпецификации` удалён из состава метаданных Заказа дилера.

Функциональность параметрических спецификаций предлагается реализовывать с помощью справочников `Вставки`, `Фурнитура` и `Формулы`. Перечисление `ТипыВставок` еще в 2014 году было дополнено значениями `Контур` и `Изделие`. Добавлен новый справочник `ПривязкиВставок`, связывающий номенклатуры продукций со вставками, фурнитурами или формулами, которые должны выполняться после расчета основной спецификации изделия

**Comment by Oparin-Igor** [comment]
расчет комплекта расширителя, соединителя в строке?
