### ISSUE TITLE
Связь характеристики материала вставки с параметрами продукции

### ISSUE THREAD

**Issue by Oparin-Igor** [oknosoft/windowbuilder#64]
- [x] Табчасть в системах профилей
- [x] Настроить для дерева
- [ ] Настроить для остальных материалов
- [x] Формула для вставок

**Comment by unpete** [comment]
- Добавлена формула _Характеристика по параметру_ (000001022)
- Пример использования формулы см. соединение _Дер. L рам гл 83_ (000001064)
- Пример спецификации с подстановкой характеристик см изделие [ТБ6/03/Дер. окно глухое](https://light.oknosoft.ru/#obj=cat.characteristics&ref=a0f1f99b-d504-486e-bdb0-d6c044bffda7&frm=builder&view=orders)

Перенос в браузер характеристик материалов пока не автоматизирован.
Характеристики остальных деревянных профилей нужно создать по аналогии с характеристиками  _Дер. Глухарь_83/79_ см. закладку _Параметры_
Наименование указывать не надо, оно формируется автоматически по табчасти параметров.
