### ISSUE TITLE
Параметры фурнитуры

### ISSUE THREAD

**Issue by Oparin-Igor** [oknosoft/windowbuilder#65]
Направление открывания не передается в параметры фурнитуры, не работает отбор по направлению открывания.

**Comment by unpete** [comment]
Отклонено, т.к. не указан порядок воспроизведения проблемы.
Проблема сформулирована небрежно.

**Comment by unpete** [comment]
> не работает отбор по направлению открывания

Теперь работает.
На текущий момент, в параметрическом движке доступны четыре вычисляемых параметра
- направление открывания
- цвет изделия
- цвет фурнитуры
- цвет элемента

Значения этих параметров не указываются явно в таблице параметров, а вычисляются динамически и могут использоваться для фильтрации.
При необходимости, можно реализовать другие вычисляемые параметры.

В настройках фурнитуры есть неоптимальные места: например, параметр _Цвет ручек (накладок)_ с перечислимым типом значения. Вместо него, логичнее было бы использовать параметр _Цвет фурнитуры_, с типом значения _Цвет_, а список доступных цветов ограничить, например, через _Связи параметров_

**Comment by unpete** [comment]
Еще, замечание по _Цвету ручек (накладок)_. Вместо десятка строк с отбором по этому параметру, правильнее сделать одну строку с вычисляемой по цвету _характеристикой_ или вычисляемой по цвету _номенклатурой_. Наличие справочника _Формулы_, делает такую задачу тривиальной

**Comment by Oparin-Igor** [comment]
в спецификацию попадают левые и правые части фурнитуры.https://light.oknosoft.ru/new/#obj=cat.characteristics&ref=6544be58-5bc5-4363-9fe1-9b54b85c2b4b&frm=builder&view=orders
M_52662 R ножницы 601-800
M_52663 L ножницы 601-800

**Comment by unpete** [comment]
Фильтр по направлению открывания исправил - просьба проверить (предварительно, перезапустить браузер)

**Comment by Oparin-Igor** [comment]
Все работает

 

  _____

**Comment by Oparin-Igor** [comment]
цвет изделия 
цвет фурнитуры
связи параметров
завтра на конференции

**Comment by Oparin-Igor** [comment]
фильтр "направление открывания " работает

**Comment by Oparin-Igor** [comment]
https://light.oknosoft.ru/new/#obj=cat.characteristics&ref=573f453a-0789-461d-e0b6-e453326ddabf&frm=builder&view=orders

Части фурнитуры считаются от ширины створки
Надо по ширине фальца створки
В спецификации
M_54674 средний запор 750-1050 
В настройках
ограничение ст 1 размер 751-1050
Должен дыть артикул
M_52453 средний МV300 600-750
В настройках
ограничение ст 1 размер 600-750

**Comment by Oparin-Igor** [comment]
https://light.oknosoft.ru/new/#obj=cat.characteristics&ref=7714719c-2418-43fa-946b-8681e8d6f4b1&frm=builder&view=orders
ссылка 0 зона

**Comment by unpete** [comment]
Алгоритм поправил частично: для прямоугольных конструкций теперь используются размеры контура по фальцу. Для косоугольных осталось по старому: для вычисления длины стороны из длины элемента вычитаются размеры фальца соседних профилей.

В изделии [Вика/03...](https://light.oknosoft.ru/new/#obj=cat.characteristics&ref=7714719c-2418-43fa-946b-8681e8d6f4b1&frm=builder&view=orders) подозреваю проблему с длиной элемента №10=796мм, вычисляется, как видимый размер 618+2*89 (из соединения Дер. L ств 83).
Получается, что элемент №10 длиннее на 20мм габарита створки = 776мм.

Собственно, из-за этих 20 мм и наблюдаем проблему со старым алгоритмом.
