### ISSUE TITLE
Вложенные вставки в спецификации соединений

### ISSUE THREAD

**Issue by unpete** [oknosoft/windowbuilder#66]
Перенесено из письма

> Изделие https://light.oknosoft.ru/new/#obj=cat.characteristics&ref=1e964d40-ce3c-4e23-f528-839919489019&frm=builder&view=orders
Соединение Дер \Ст 40 рама низ + рам зак элементы 9 и 3. В спецификацию не попадает  номенклатура Дер. РамнаяЗакладка 79 из вставки Дер. РамнаяЗакладка.

**Comment by unpete** [comment]
Движок честно отрабатывает то, что написано во вставке с кодом 000001289 (Дер. РамнаяЗакладка).

1. Признак _основной материал_ допустим и имеет смысл только для тех вставок, которые человек выбирает в построителе. Вложенная вставка - служебная и никакого основного материала у неё быть не должно
2. Для материала с кодом DRV00000026 (Дер. РамнаяЗакладка 79) было укзано количеество = 0, коэффициент = 0. В спецификацию попадает 0, строки с нулевым количеством и нулевой длиной  удаляются
3. Для материала с кодом DRV00000026 (Дер. РамнаяЗакладка 79) был установлен фильтр по углу к горизонту === 0
4. Не стоят коэффициенты для лака и грунта - получаем по этим позициям округление до штук. Так и задумано? Или это ошибка?
5. Для наполнителя швов коэффициент применяется дважды: сначала умножаем на 0.0001 в строке спецификации, затем, на 0.015 в строке вставки. Если хотелось 0.015 от размера вставки, надо написать 15. Поправки размеров вложенных вставок складываются, а коэффициенты - перемножаются.

В код расчета вложенных и обычных вставок внесены изменения. Браузер надо перезапустить

**Comment by Oparin-Igor** [comment]
1. планировалось что тех вставка и рамная закладка будет рисоваться на чертеже, поэтому и не менял, если для вложенных вставок и основных вставок шаблон разный. то я об этом должен знать. но мы этот вопрос еще не расматривали.
2.3. стоят коэффициенты для основного материала см.п1.
угол сначала поставил 180 затем экспериментировал поставил 0
4. по тех вставке понятно, но почему не считается наполнитель швов?
к расчету лака и грунта вопросов нет.
5. наполнитель швов это результаты эксперимента, т.к. вообще ничего не считалось.
6. Ни слова как надо, опять эксперементировать?

**Comment by Oparin-Igor** [comment]
коэффициент всегда был 0,001 откуда взялся =1.
тех вставка 0,0008 это что за количество?

**Comment by unpete** [comment]
Алгоритм поменял. В `aperture_len` теперь живёт длина проёма, а не длина ребра заполнения.
Это глобальное изменение. Надеюсь, в других местах не сломается.
Для изделия [ТБ000000006/18/](https://light.oknosoft.ru/new/#obj=cat.characteristics&ref=1e964d40-ce3c-4e23-f528-839919489019&frm=builder&view=orders), размеры штапик 705+8 закладка 705+18 получены - можно тестировать остальные места

**Comment by Oparin-Igor** [comment]
Проверено, замечаний нет.
