### ISSUE TITLE
Дверные петли визуализация

### ISSUE THREAD

**Issue by unpete** [oknosoft/windowbuilder#68]
@Oparin-Igor, Получилось эффектно, поздравляю

Сделал доработку:
- Объединил два прямоугольника в один svg путь
- Выкинул лишние строки из набора фурнитуры VAR-00009 (ДВ петли)

**Comment by Oparin-Igor** [comment]
эффект получился ожидаемый, левое открывание петли перевернутые.

**Comment by Oparin-Igor** [comment]
если добавить петли левые и петли правые, строчек будет ровно столько же, что и раньше.

**Comment by unpete** [comment]
Никого не интересует количество строк в настройках.
Экономить надо строки в **итоговой спецификации**

**Comment by Oparin-Igor** [comment]
может тогра служебный функционал не выводить в основную спецификацию.

**Comment by Oparin-Igor** [comment]
У нас визуализация была привязана к операциям обработок, операция обработки рамы и обработка створки разные, в принципе это и должно быть так, что бы потом не переделывать, а просто переименовать или прикрепить.

**Comment by Oparin-Igor** [comment]
визуализация и обработка это одного рода задача.
