### ISSUE TITLE
Протестировать формирование спецификации

### ISSUE THREAD

**Issue by unpete** [oknosoft/windowbuilder#7]
Спецификацию фурнитуры пока не анализируем - акцент на размерах профилей, заполнений и штапиков. При необходимости, внести изменения в технологические справочники

- [ ] Заказ Б0000000003 - проверить ПВХ
- [ ] Заказ Б0000000009 - AL балконы - есть ошибки в построении

**Comment by unpete** [comment]
> Заказы пересчитал, не создалась характеристика цветного штапика.

Перенесено из #20 
@Oparin-Igor просьба размещать комментарии в привязке к задачам верхнего уровня и снабжать ссылками для воспроизведения проблемы. Например, так: [Заказ Б0000003 изделие 03](https://light.oknosoft.ru/new/#obj=cat.characteristics&ref=db64b042-96fe-4dc3-842a-5dd6c83b76a2&frm=builder&view=orders)

По цветовым характеристикам, ошибку признаю. Создал задачу #23 с низким приоритетом

**Comment by unpete** [comment]
Перенесено из письма от Fri, 18 Mar 2016 03:46:55 -0700 (PDT)

> Импост в построителе ведет себя очень странно.
> Спецификация создает все по два, размеры длинные.
> Или мне пока не заглядывать в спецификацию?
> Выбор слоя то же ведет себя странно.

Обсудим на конференции.
Проблема _все по два раза_ была из-за того, что во вставках для основного материала поля `количество`, `размер` и `коэффициент` были ненулевыми. Для основных материалов, вычисляемых только по вставкам (например, заполнения или монтаж), это правильно, но для вставок в профиль, основной материал рассчитывается в соединении.
Понятно, что можно было сделать условие _если это вставка в профиль то..._, но сделано так.

**Comment by Oparin-Igor** [comment]
Армирование рассчитывается не верно.
Размер конструкции 1300, армирование должно быть 1205, сейчас 1211.
Рама с припуском на сварку 1306, армирование считается с припуском на сварку рамы.
B...03\02
