### ISSUE TITLE
Создание шаблонов

### ISSUE THREAD

**Issue by Oparin-Igor** [oknosoft/windowbuilder#70]
- [x] AKFA 6д
- [x] AKFA 6о
- [x] ALUPLAST 2дверн. сист.
- [x] ALUPLAST 2ок сист,
- [ ] ALUTECH витраж двери
- [x] ARTEC 4дверн. сист.
- [x] ARTEC 2ок сист,
- [x] AVANGARD 1дверн. сист.
- [x] AVANGARD 2ок сист,
- [x] BARS  1ок сист,
- [x] BRUGMANN 1дверн. сист.
- [x] BRUGMANN 2ок сист.
- [x] BRUSBOX 3ок сист, 
- [x] BRUSBOX 1дверн. сист.
- [x] CITYLUX 2дверн. сист.
- [x] CITYLUX 2ок сист,
- [x] DIFENCE 1дверн. сист.
- [x] DIFENCE 1ок сист
- [x] EXPROF 4ок сист, 
- [x] EXPROF 3дверн. сист.
- [x] FORWIN 1ок сист,
- [x] FUNKE 3дверн. сист.
- [x] FUNKE 2ок сист,
- [x] GEALAN 8000 1дверн. сист.
- [x] GEALAN 8000 1ок сист,
- [x] GOODWIN	 2дверн. сист.
- [x] GOODWIN 2ок сист,
- [x] GRAIN 1дверн. сист.
- [x] GRAIN 2ок сист,
- [x] GUTWERK 1ок сист,
- [x] KBE 6дверн. сист.
- [x] KBE 4ок сист, 
- [x] KRAUSS 5ок сист, 3дверн. сист.
- [x] LG 5ок сист, 2дверн. сист.
- [x] MONTBLANC 7ок сист, 7дверн. сист.
- [x] NOVOTEX 3ок сист, 
- [x] NOVOTEX 4дверн. сист.
- [x] PLAFEN 5ок сист, 2дверн. сист.
- [x] PROPLEX 5ок сист
- [x] PROPLEX 2дверн. сист.
- [x] REHAU 6ок сист,
- [x] REHAU 7дверн. сист.
- [x] SALAMANDER 5ок сист, 4дверн. сист.
- [x] SCHUCO 1ок сист, 2дверн. сист.
- [x] TECOLINE	 2ок сист,
- [x] Deceuninck 4ок сист, 2дверн. сист.
- [x] TROCAL 1ок сист,
- [x] VEKA 6ок сист, 
- [x] VEKA 10дверн. сист.
- [x] VITRAGE 3ок сист, 1дверн. сист.
- [x] WDS 3ок сист, 2дверн. сист.
- [x] WINTECH 3ок сист, 4дверн. сист.
- [x] Деревянный профиль 2док
- [x] СПК 2ок сист, 3дверн. сист.

Итого:189 документа

**Comment by torbeev** [comment]
Коллеги, по поводу шаблонов, почему нельзя сделать "абстрактные" шаблоны ? т.е. шаблоны без привязки к системе, не слишком ли затратно иметь матрицу шаблон/система ? прорисовать один раз возможные варианты.
