### ISSUE TITLE
Характеристики дублирование

### ISSUE THREAD

**Issue by Oparin-Igor** [oknosoft/windowbuilder#71]

**Comment by unpete** [comment]
Проблема, скорее всего была не в движке и не в клиентском коде и касается только нескольких шаблонов, которые мне пришлось в пятницу, 27.05 перезаполнить на стороне 1С, чтобы убрать из них ссылку на пользователя "Администратор".
Я написал специальную обработку и вероятно, эта обработка положила одинаковые характеристики в разные строки заказов.
Проверил несколько шаблонов, замеченные дубли удалил.
Предлагаю проверить созданные в конце прошлой недели шаблоны на предмет дублей характеристик, удалить лишнее и создать недостающее.

**Comment by Oparin-Igor** [comment]
>Предлагаю проверить созданные в конце прошлой недели шаблоны на предмет
дублей характеристик

Для информации шаблоны были созданы вчера вечером.

Просьба изделия не удалять из шаблонов, что бы не терять последовательность,
я их лучше переконструирую.

 

  _____

**Comment by unpete** [comment]
> Просьба изделия не удалять из шаблонов

Данные устроены несколько сложнее. "переконструировать" можно только уникальную ссылку.
Еще, поведение шаблонов на стороне браузера, отличается от обычных заказов.
Шаблоны сразу попадают в ОЗУ, а обычные заказы читаются из IndexedDB. При одновременном  изменении **шаблонов** на стороне 1С и в других браузерах, браузер лучше перезапустить - обычная синхронизация, скорее всего не отработает.

Еще, обнаружился надёжный способ создать себе трудности: нужно на одном компьютере открыть два экземпляра браузера или две закладки одного браузера с Заказом дилера.
Данные на сервере, естественно, не портятся, но в браузере получаем лажу.

> шаблоны были созданы вчера вечером

Я инженер. Мне не интересно, когда были созданы шаблоны. Есть факты:
1. В некоторых шаблонах есть дубли характеристик
2. **Штатными** средствами создать эти дубли **невозможно**
3. В пятницу,  27.05 я перезагружал табчасти нештатной обработкой

Наиболее вероятный вывод: данные испортила обработка.
Если у тебя есть другие гипотезы - приводи сценарий воспроизведения ошибки.
