### ISSUE TITLE
При изменении ссылок не меняется текст в табличных частях объектов

### ISSUE THREAD

**Issue by Oparin-Igor** [oknosoft/windowbuilder#72]
При изменении системы не меняется название номенклатуры продукции

**Comment by unpete** [comment]
Название номенклатуры продукции - это вычисляемое свойство. Оно обязательно меняется при любом изменении любого реквизита продукции, в том числе - при изменении системы.
Другое дело, что в каком-то окне или поле ввода не меняется текст.
Просьба указать, где именно текст не отслеживает изменение наименования.

**Comment by unpete** [comment]
Задачу надо переформулировать:
При изменении ссылок не меняется текст в табличных частях объектов.
Происхождение проблемы понятно. Табчасть перерисовывается, когда меняется любое значение в любой её строке.
Но! При изменении ссылки (номенклатура, характеристика, контрагент и т.д.), строка табчасти не менялась - изменилась ссылка.

Затычку сделать легко - можно подписаться на событие "при записи изделия построителя" и перерисовывать табчасть.

Более правильное решение - подписаться на событие при записи любого объекта, проверять, нет ли в нашей табчасти ссылок на изменённый объект и перерисовывать те ячейки, ссылки под которыми изменились.

**Comment by unpete** [comment]
Ограничился подпиской на событие "при записи изделия построителя".
Задачу на уровне ядра поставил в низкоприоритетные - на 2017-2018 год.

**Comment by Oparin-Igor** [comment]
Проверено.
