### ISSUE TITLE
Параметры фурнитуры по умолчанию

### ISSUE THREAD

**Issue by Oparin-Igor** [oknosoft/windowbuilder#73]
Параметры фурнитуры из системы по умолчанию не проставляются, при изменении системы

**Comment by unpete** [comment]
При изменении системы перезаполнялись только параметры изделия.
Добавил цикл по всем створкам с перезаполнением параметров фурнитуры.
Новые строки параметров не добавляю, т.к. они не нужны в фурнитуре - меняю признак _скрыть_ и меняю значение, если взведена галка _принудительно_

**Comment by Oparin-Igor** [comment]
Проверено. Пока нет замечаний.
