### ISSUE TITLE
Поле характеристика в браузере

### ISSUE THREAD

**Issue by Oparin-Igor** [oknosoft/windowbuilder#74]
~~Заблокировать поле выбора "характеристика" в строке заказа на стороне браузера на закладке продукция~~

@Oparin-Igor Обработчик формирования списка выбора, действительно, требует доработки, но _блокировать_ ничего не надо, как минимум потому, что характеристика бывает не только у изделий построителя. У этого поля такие же права, как у количества, номенклатуры или цены. Оператор должен иметь возможность его редактировать

**Comment by unpete** [comment]
Добавил свойство `_option_list_local` в метаданные поля

**Comment by Oparin-Igor** [comment]
Проверено. Полен при случайном нажатии не обнуляется, не перезаполняется
