### ISSUE TITLE
Инструмент Раскладки и импосты

### ISSUE THREAD

**Issue by unpete** [oknosoft/windowbuilder#81]
- [x] Метаданные в 1С
- [x] Форма инструмента
- [x] Визуализация деления при наведении мыши на заполнение
- [x] Создание элементов по щелчку мыши
- [x] Учесть наклонные и гнутые элементы
- [x] Видеоролик по вставке раскладок и импостов

**Comment by unpete** [comment]
Добавлено видео [импосты и раскладки](https://youtu.be/BDyB8eu_OLk?list=PLiVLBB_TTj5mQXHOzodkzP3duImksxVgB)

**Comment by unpete** [comment]
- [x] Реализовано добавление элементов в текущий слой, без привязки к заполнениям
- [x] Добавлена возможность указания разных вставок для горизонтальных и вертикальных элементов
- [x] Добавлено видео [Рисование витража](https://youtu.be/FjNBPtVZyBI?list=PLiVLBB_TTj5mQXHOzodkzP3duImksxVgB)

**Comment by aribaz** [comment]
Фильтр видимости для одного и того же типа профиля по осям X и Y не совсем правильно рабтает, в частности ось Х.

**Comment by unpete** [comment]
> Фильтр видимости для одного и того же типа профиля

Исправлено

**Comment by aribaz** [comment]
Спасибо, закрываю
