### ISSUE TITLE
Инструмент "Рисование"

### ISSUE THREAD

**Issue by unpete** [oknosoft/windowbuilder#83]
- [x] Вместо drag-and-drop задействовать щелчок мыши на первой и второй точках
- [x] Реализовать возможность указывать координаты точек в процессе рисования

Добавлен ролик [инструмент рисование новые возможности](https://youtu.be/7QT3-EgME-U?list=PLiVLBB_TTj5mQXHOzodkzP3duImksxVgB)

**Comment by unpete** [comment]
Из письма @Oparin-Igor 

> после установки размеров при выборе кнопки установить точку данные размеров сбрасываются

Набор слов, смысла не понял.
На кнопку можно нажать либо пробелом, либо {enter} - это стандарт в браузерных и настольных приложениях. Если мышь не двигать, ничего никуда не сбрасывается. Координаты, естественно, изменяются, т.к. точка в новом месте.
Еще, точку можно поставить щелчком мыши, но это дольше и опаснее - до мыши надо тянуться и если её сдвинуть перед или во время щелчка, координаты будут испорчены.

> что бы встать на поле выбора размеров, кнопку таб надо нажать более 6 раз

Есть 5 элементов (4 поля ввода и кнопка). В полноэкранном режиме 5 полей можно обойти за 5 переходов. Если браузер в обычном режиме и доступна строка адреса, обход в одном в одном направлении потребует 6 шагов.
Обычно, для перемещения по ячейкам таблиц или полям формы, используют направление. То есть, жмут {tab}, если надо идти вперёд или {shft+tab} для перехода к предыдущему полю. В этом случае, к любому полю можно перейти не более, чем за 3 таба.
Так же, не забываем про {escape}, который сбрасывает фокус.

> если рисовать изделие без использования нового механизма после отрисовки элемента, нет привязки начальной точки

Привязка начальной точки есть

> начальная точка привязывается к концу предыдущего элемента через раз

Куда и что будет привязываться, зависит от настроек инструмента (магнит к профилю и узлам), от наличия описанного углового или T-соединения текущих материалов и координаты, в окрестности которой ставится точка. Никакого randomize в коде нет.

> начальная точка устанавливается с задержкой. Нажал на мышку повел к конечной точке, точка появилась в промежутке

Никакой задержки там нет, путь формируется сразу, но пока у пути нулевая длина, точку, действительно не видно. Таково проектное решение на данном этапе. Со временем, визуализацию пути надо будет переделать

> если отключить мышку новый механизм ведет себя предсказуемей, но начальная точка не устанавливается. Но как работать без мышки

Точка устанавливается. Её просто не видно (см. предыдущий комментарий)

**Comment by Oparin-Igor** [comment]
Здравствуй, Евгений.

 

Тут совсем началось не продуктивное общение. 

Я такой сценарий предвидел, но не написать не мог.

Не надо из меня делать идиота, все что я написал правда.

Никто у меня во время установки размеров мыши не трогал.

Ну ты конечно говорил, что у меня дело все в компьютере он не такой.

 

 

> после установки размеров при выборе кнопки <установить точку> данные
размеров сбрасываются

после установки размеров в полях (размеры х,у,l, угол) при выборе(переходе
на) кнопки <установить точку> данные размеров в полях (размеры х,у,l, угол)
сбрасываются

> что бы встать на поле выбора размеров, кнопку таб надо нажать более 6 раз

если идти вперед при нажатии таб 6раз, идет через меню окон браузера, затем
возвращается к размерам.

 

>начальная точка привязывается к концу предыдущего элемента через раз

Не всегда попадает в конечную точку, рисуется просто линия без толщины.

Все привязки стоят.

 

  _____
