### ISSUE TITLE
Сумма заказа

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#88]
Исправить значение суммы в табчасти Заказы клиента (1С).
На стороне  1С в списке заказов не отображается сумма заказа.

**Comment by unpete** [comment]
Исправлено.

**Comment by aribaz** [comment]
Я вижу суммы только при пересчете заказа, а когда открыла список заказов клиента, то сумма была только у Соловьева и Русокон на 1803

**Comment by unpete** [comment]
Это нормально. Сумма учтена в коде импорта. Если нужно, чтобы цифры
появились в старых документах, их нужно пересчитать и перезаписать.

08.09.2016 0:55 пользователь "Звалинская Наталья" <notifications@github.com>
написал:
