### ISSUE TITLE
Дозаполнение реквизитов заказа при импорте в 1С

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#89]
Добавить реквизит Клиент (=поле Клиент в форма Заказа клиента в сервисе)  в форму Заказ клиента на вкладку Дополнительно.

**Comment by unpete** [comment]
- [ ] Клиент - тип: `Строка`, разместить в допреквизитах
- [ ] Склад - тип: `Справочник.Склады`, добавить реквизит в Заказ дилера, заполнять по умолчанию из свойств пользователя
- [ ] Дата отгрузки - тип: `Дата`, рассчитывать по табчасти планирование (сначала, реализовать автозаполнение и групповой редактор дат планирования)
