### ISSUE TITLE
Подтягивание Заказа при проведении платежки.

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#90]
При оформлении документа Поступление БДС  и/или Приходный кассовый ордер на вкладке Расшифровка платежа, поле Основание платежа - список выбора пуст.
Один кассовый ордер получилось выбрать основание платежа (ЦентрСтройСервис) после сохранения ордера, но в списке кассовых ордеров после проведения ордера основание для него не отображается . А для МаксГрупп основание платежа выбрать не удалось совсем.

**Comment by unpete** [comment]
Была проблема в справочнике `Договоры контрагентов`. Для оформления платежа, необходимо и достаточно:
- указать банковский счет - через него вычисляется организация
- указать плательщика - список доступных заказов и договоров будет обрезан по ключу `плательщик + организация`
- должен существовать _действующий_ договор с такими реквизитами:
  + Тип взаимоотношений: `С покупателем / заказчиком`
  + Статус: `Действует`
  + Детализация расчетов: `По заказам`
  + Оплата: `Расчеты в рублях, оплата в рублях`

**Comment by aribaz** [comment]
Проверила, все работает (и приходник, и безналичка).
Данные сразу видны в сервисе на вкладке Долги.

**Comment by unpete** [comment]
> Данные сразу видны в сервисе на вкладке Долги

Это приятная особенность. Механизм отражения оплат и отгрузок в сервисе я не тестировал. В будущем, должны всплыть ошибки и уточнения задачи.
