### ISSUE TITLE
Цвет "Составной"

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#91]
Не вижу цвет составной вообще, и следовательно не имею возможности его выбрать.
Меня больше интересует возможность указать, что изделие окрашивается в два цвета.
А вот по библиотеке цветов мы договорились о том, что пользователь сам создает необходимое ему сочетание из основной палитры цветов папки Дерево, чтобы не расширять справочник цветов.
Еще важно как-то определить как производственник поймет какой из двух цветов должен быть изнутри, а какой снаружи.
Не совсем пока представляю как это будет выглядеть. Но если цвета будут записаны через дробь, например, белый/каштан, то в для нас это с улицы - белый, из помещения - каштан. Это чтобы программа потом как-то это тоже учла при создании печатных форм для участка Малярка.

**Comment by unpete** [comment]
Редактор составных цветов см. #23

**Comment by unpete** [comment]
Добавил видео [Составные цвета](https://youtu.be/0rpEhdTASOo?list=PLiVLBB_TTj5mQXHOzodkzP3duImksxVgB)

> если цвета будут записаны через дробь

Кроме наименования, у нас есть ссылка с полями `цвет изнутри` и `цвет снаружи` - информацию в отчете можно вывернуть как угодно

**Comment by aribaz** [comment]
Спасибо, уже посмотрела, все поняла.

**Comment by aribaz** [comment]
Закрываю
