### ISSUE TITLE
Цвета RAL

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#92]
От меня поступало предложение чтобы папка с цветами RAL все же была в Цветах отдельной папкой. Цветами RAL пользуемся не только мы, но и ПВХ-шники тоже, думаю будет не лишним. Они есть у всех производителей ЛКМ вне зависимости от основы ЛКМ, хоть и не относятся к основной палитре производителя.

**Comment by unpete** [comment]
RAL - это просто еще один реквизит, в довесок к коду и наименованию.
Например, у человека есть имя, номер паспорта и ИНН. Группировать людей в папку по признаку, есть ли у них ИНН - не кажется правильным.

Проблема, как обычно, в плохой документации.
Цвета можно объединять в группы доступа, для поиска можно использовать одно из трёх полей: `код`, `наименование`, `ral`

Линейная иерархия не очень точно отражает реальность. Вместо папок для цветов было бы правильнее использовать категории, чтобы один цвет мог входить одновременно в разные группы.
1С в новых типовых конфигурациях проповедует похожие принципы: они убрали иерархию у контрагентов, прячут её у номенклатуры и других справочников. Письма в почтовых клиентах группируются в основном, по категориям (возможность группировать по папкам сохранена)

Резюме: Иерархию цветов настроите самостоятельно после отключения базы Арибаз от глобальной базы Заказа дилера. Тогда же, можно будет удалить в вашем экземпляре лишние элементы других справочников
