### ISSUE TITLE
CTRL+C, CTRL+V (буфер обмена) для установки цен

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#93]
Создание инструмента копирования и последующей вставки символов (текст, цифры) таблицы на стороне сервиса для использования в создании Документа Установка Цен Номенклатуры, и не только для этого.

На стороне 1С в Закупки/Цены поставщиков(прайс-листы) есть кнопка Загрузить из внешнего файла, если на нее нажать, то появляется форма "Загрузка цен поставщика из файла", которая содержит графы Артикул и Номенклатура поставщика, здесь справочно написано, что "необходимо скопировать колонки в таблицу из внешнего файла (Excel, Word и пр.) через буфер обмена" - это не то, что вы предложили сделать для сервиса? Только это на стороне 1С.
Единственное здесь необходимо выбрать вид цен, а список Видов цен в этой форме пуст. Хотя если заходить в Цены через СРМ, то там есть возможность выбрать вид цен.
Можно ли пользоваться этим инструментом для установки цен номенклатуры? 
Я пробовала из справочника скопировать одно название номенклатуры и вписала от руки артикул для проверки, указала поставщика "База комплектующих". Я вот только не поняла как он поймет какую цену надо поставить, ведь колонки Цена (новая) нет ну и соответственно она ругается "Не удалось создать документ регистрации цен поставщика" и справка внизу гласит "Отсутствуют измененные цены", что в общем-то логично новые цены я нигде не указала, а где их можно указать не ясно, во всяком случае мне.

**Comment by unpete** [comment]
В документ установки цен добавлена поддержка буфера обмена
см: https://youtu.be/olXYQwuGCJY?list=PLiVLBB_TTj5mQXHOzodkzP3duImksxVgB

**Comment by aribaz** [comment]
У меня в документе валюта отображается в строчках документа, а не вкладке Реквизиты.
И все что я скопировала из таблички (4 строки для пробы) оно все вставилось в первую строку с названием вместе с ценой.

**Comment by aribaz** [comment]
Перезагрузила страничку, попробовала снова и все получилось.
Табчасть документа выглядит теперь так же как и в вашем примере.
Спасибо.

**Comment by aribaz** [comment]
У меня небольшой вопрос. Я сделала таким способом документ установки Цен для профилей, для того, чтобы вручную не писать названия в файле, я их скопировала из папки Профили /Дерево, добавила каждому профилю шесть вариантов древесины, и когда копировала данные из файла, то он вставил 114 строк, а в файле их 120, он упустил один вид профиля (название), эти 6 строк (разная сростка) я добавила вручную и все в целом получилось, это здорово, но сервис меня не оповестил о том, что не все строки вставлены. И если бы я не сравнила количество строк, я бы и не узнала, что я не все цены установила. Хотя названия скопированы из базы все разом и в них ошибки быть не может по идее, ведь все остальные правильные.
Теперь я вставила цены на фурнитуру, но использовала вместо названия артикул, и опять у меня в файле 171 строка, а в документе 158, не вставилось 13 строк, сервис тоже мне ничего не сказал. Как же мне понять какие конкретно не вставились? Есть какой-то способ, или просто сравнивать глазами списки? Было бы здорово, если бы он говорил, что такие-то строки не вставились, или что хотя бы не все вставилось.

**Comment by aribaz** [comment]
Способ как найти то, что не вошло, я нашла в документе установки цен CTRL+A, CTRL+C и в табличный файл  CTRL+V (удаляем лишние строки, копируется ведь вообще все, а выделить необходимый фрагмент не получается)- и сравниваем или названия или артикулы, в принципе времени на поиск 13 позиций ушло максимум минут 7. Но было бы здорово вообще видеть что что-то не вошло. Сообщение какое-нибудь или что-то еще, если можно.

**Comment by unpete** [comment]
Следует перезапустить браузер

09.09.2016 17:55 пользователь "Звалинская Наталья" <notifications@github.com>
написал:

**Comment by unpete** [comment]
Создал задачу [Абстрактная работа с буфером обмена в динсписках и табличных частях](https://github.com/oknosoft/metadata.js/issues/160).
В заказе дилера пока останется обрезанный вариант.
Внутри установки цен нужно доработать алгоритм вставки:
- [ ] Контролировать ошибочные строки и формировать информативное сообщение

**Comment by aribaz** [comment]
Закрываю
