### ISSUE TITLE
Москитные сетки

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#94]
Игорь написал по допам:
"Пока механизм по допам. не реализован на стороне браузера."

Евгений, прошу подключиться.

**Comment by unpete** [comment]
Внесены изменения в структуру метаданных характеристики продукции.
- Добавлена табличная часть _Вставки_ - теперь в контур или изделие можно добавить произвольное количество дополнительных вставок
- Удалена табличная часть _Москитки_ и реквизиты москитки в строках конструкций, т.к. москитка - это частный случай вставки в рамный или створочный контур

Задачи:

- [ ] Поддержка редактирования табчасти вставок со стороны интерфейса
- [ ] Расчет спецификаций допвставок
- [ ] Математика для вытягивания фрагментов спецификаций в отдельные изделия заказа

**Comment by aribaz** [comment]
Как установить цену если единица измерения - шт, а покупаем мы ее исходя из площади этой сетки?

Производитель этих сеток считает нам их стоимость за кв.м., примерно как у стеклопакетов.

При габаритах створки, например 1209х726, размер москитной сетки должен быть 1192х700мм. И хотелось бы понимать какая москитка относится к какому окну.

Если площадь москитной сетки менее 1кв.м., то в ценник попадает стоимость 1кв.м.; если более 1кв.м. - тогда считают площадь

Еще москитки могут иметь, как и створка, не прямоугольную форму, а криволинейную, например, арочную - тогда к цене применяется коэффициент, но расчет производится все равно по площади описанного вокруг фигуры прямоугольника..

**Comment by aribaz** [comment]
При добавлении вставки в контур новая строка не видна в табчасти сразу, хотя если зайти в спецификацию и там открыть вкладку вставка, то вижу все добавленные строки (их много, потому как подумала, что не нажала на кнопку, а оказалось что нажималась кнопка), правда они пустые.
Даже если сохраняю изделие, то новую строчку в табчасти заказа на вкладке Вставки не вижу, только в спецификации.
[Пример](https://light.oknosoft.ru/#obj=cat.characteristics&ref=3fdff73c-8abb-49b6-8d2d-2e08af21e72b&frm=builder&view=orders)

**Comment by aribaz** [comment]
Что может выступать в качестве Вставки (по замыслу) в контур или изделие кроме МС?
Пока есть только МС в качестве вставки.

**Comment by aribaz** [comment]
По размерам Москитки.
размер разный, так как у нас низ рамы профиля отличается от боков и верха.
Разговаривала с конструктором, она сказала, что москитку мы ставим на раму (за уличной плоскостью рамы), заглубляется она на ширину профиля москитной сетки, у нас это 25мм.

Я попробовала перерисовать то что мне объяснили, вот что получилось.
![default](https://cloud.githubusercontent.com/assets/22028048/20336893/a47bac34-abde-11e6-8812-ceb527f54468.jpg)
![default](https://cloud.githubusercontent.com/assets/22028048/20337158/5346908e-abe0-11e6-916b-975579a6acdb.jpg)


При створке 291х408, размер москитки должен составить 274х366, что собственно я и сделала. С небольшими поправками.
Если соблюдать 25мм заглубления и итоговый размер сетки, полуачется сетка по низу не прилегает к профилю (не хватает 2мм), я ее опустила на 2мм так как там у нас по низу всегда стоит водоотвод и он имеет свою толщину.
Но по низу москитка у меня зашла не на 25мм, а на 35, но мне кажется это вопрос от чего считать 25мм (их я тоже обозначила) - конструктор наших (в сервисе) тонкостей расчета размеров не знает.

**Comment by Oparin-Igor** [comment]
Должен быть размер 37 (от внутреннего габарита рамы) ?

**Comment by aribaz** [comment]
Чисто технически по чертежу да, но там по низу стоит водоотвод и он выходит за плоскость профиля на ~2мм дальше на улицу, если москитки считать с размером 37, то она отклонится от вертикали нижним краем (должна по идее), так как водоотвод не даст ей примкнуть к низу профиля рамы, а упрется в водоотвод и поэтому получается  у меня 35. Или если крепления сетки позволяют, то слегка на 2мм будет болтаться по верхнему профилю - хотя может это и не критично.
Здесь математика с практикой не совсем почему-то сходятся, знаю что именно таких размеров сетку мы и заказали бы.

**Comment by unpete** [comment]
Добавил формулу, позволяющую указать разные отступы по вертикали и горизонтали.
Решение не идеальное, но результат даёт. См. [Заказ НЗАР0000012](https://light.oknosoft.ru/#obj=doc.calc_order&ref=1db79430-26cd-48b2-a3fd-75c69d76f9e1&frm=doc&view=orders)
Предлагаю оставить в таком виде до лучших времён.

**Comment by aribaz** [comment]
Договорились, главное работает.
Проверила , работает.
