### ISSUE TITLE
Подоконники

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#96]
Подоконники

 

Подоконники могут быть, а могут и не быть в заказе - это желание заказчика.

Подоконники считаем в штуках на производстве, но для расчета цены определяющим является площадь подоконника.

Подоконники делаем сами. Выполняем их или в дереве или из МДФ со шпоном.

И у тех и у тех может быть 5 видов калевки внешнего края. Калевка влияет только на профиль подоконника, но не на цену.

Толщиной 35мм.

Если выполняем их из дерева, то используем или щит (покупной или сами изготавливаем из доски), или брус (актуально для лиственницы, так как качество досок и щита часто оставляет желать лучшего).

Если выполняем из МДФ, то берем две детали МДФ толщиной 16мм каждая, и размерами будущего подокнника, склеиваем между собой с помощью Смолы КФЖ (0,3кг/кв.м ), далее с лицевой стороны клеим шпон (сосна, лиственница или дуб) 0,5-0,6мм толщиной с помощью той же смолы КФЖ (0.3 кг/кв.м), а с изнаночной стороны клеим или бумагу специальную, или черновой шпон, чтобы подоконник не повело.

Затем подоконник красим. С лицевой стороны - технология аналогична оконной, а с изнанки как правило только грунтуем.

Если подоконник из МДФ, то склейку листов МДФ и наклейку шпона производит другой цех - цех эксклюзива, а на покраску привозят в оконных цех, так как эксклюзивный и рамный цех используют покрытия на разных основах.

Теоретически вычислить размер подоконника можно. Надо знать толщину стены, привязку окна к стене, и по хорошему ширину проема (или как вариант величину зазора между окном и стеной с каждой стороны. Можно конечно и вручную указать необходимый размер, но хочется автоматом, чтобы получалось.

Единственное уточнение, для балконных блоков может быть с обоих сторон (улица/помещение) подоконник, а не отлив/подоконник.

Это я писала ранее Игорю

**Comment by unpete** [comment]
Для гибкости-надёжности, длину и ширину предлагаю указывать руками.
Со стороны интерфейса, оформляем, как вставку в рамный контур. Можно было бы, как вставку в изделие, но в контур - правильнее. Могут быть изделия, в разных контурах которого разные подоконники.
Параметры:
- Длина подок. (число)
- Ширина подок. (число)
- Толщина подок. (число)
- Материал (перечисление или номенклатура ??)
- Цвет (цвета, по умолчанию - как изделие)
- Калевка (перечисление)

**Comment by aribaz** [comment]
Цвет как изделие со стороны установки подоконника для цвета Составной.

По материалу не знаю как правильнее. Если делаем из Щита покупного - то это номенклатура, если из своего щита, который делаем сами - то можем сделать из бруса или доски щит, и использовать его  в качестве основы для подоконника, а если МДФ - то вырезаем из большого листа толщ. 16мм 2 детали необходимого размера и склеиваем их в прессе в одну деталь, а потом еще обклеиваем шпоном с одной стороны и черновым материалов (шпон или технич. бумага) с другой стороны. В зависимости от необходимой толщины подоконника могут использоваться исходные материалы разных толщин.

**Comment by unpete** [comment]
> И у тех и у тех может быть 5 видов калевки внешнего края

Просьба перечислить виды калевки

**Comment by unpete** [comment]
- [ ] Добавить параметры подоконников
- [ ] Фильтр - разделитель `Вставка` в табчасти параметров
- [ ] Формулы для трансляции значений параметров в размеры доп. аксессуара
- [ ] Вызов стандартного алгоритма расчета спецификации в контексте дополнительных вставок
- [ ] Настроить и отладить спецификацию (Опарин)
- [ ] Настроить и отладить ценообразование допов
- [ ] Визуализация на основном эскизе + эскиз доп. аксессуара

В заказе [НЗАК1](https://light.oknosoft.ru/#obj=doc.calc_order&ref=cfa3c535-bd8c-4257-9c7f-18c3c5d65fec&frm=doc&view=orders) добавлен подоконник, как допвставка в рамный контур

**Comment by aribaz** [comment]
Параметр Материал подоконника.
Подоконник мы можем изготовить из дерева (сосна, лиственница, дуб) или МДФ/шпон (сосна/лиственница/дуб).
Если заказчик выбирает деревянный подоконник, а не МДФ - то ему без разницы из чего конкретно мы его делаем из покупного щита или из доски склеенной в щит на своем производстве, а мы используем тот или иной метод в зависимости от того, каким сырьем обладаем. Щит на рынке всегда есть сосновый; лиственница встречается, но часто плохая в готовом щите; а дуб в основном делаем сами из доски. Для заказчика способ изготовления деревянного подоконника никак не влияет на цену. Для нас это конечно здорово иметь возможность сразу определить способ изготовления и соответственно иметь возможность отразить это в цене и сроках (потому что щит надо набрать, склеить, подождать когда просохнет), но менеджер на момент оформления заказа не знает наверняка как будут делать подоконник, поэтому отталкиваемся от самого трудоемкого процесса и самого дорогого (для одного типа древесины).

Я прошу в качестве параметров материала для подоконника учесть вот какие:
сосна
лиственница
дуб
МДФ/шпон(сосна)
МДФ/шпон(листв.)
МДФ/шпон(дуб)

**Comment by aribaz** [comment]
@Oparin-Igor  во вставке Подоконник параметр Материал разделился на две строки: Материал основ. (тип материала)  и Материал допов. (вид древесины) их теперь два надо использовать?

Вариант доска или щит - на момент регистрации заказа не известен, здесь важно принципиально из пиломатериала (сосна, дуб, лиственница) или МДФ (на выбор: со шпоном трех пород дерева или без шпона вообще под глухую покраску), и если из пиломатериала как такового, то из чего конкретно будут делать (щит или доска) решает производство с учетом наличия сырья на складе когда доход дело до изготовления.

**Comment by aribaz** [comment]
@Oparin-Igor 
Еще лирическое отступление. На тему пород.
С Евгением разговаривала про то, как заводить номенклатуру сырья. Решили, что на каждый тип материала будет заведена одна строка номенклатуры, а вот порода, толщины этих материалов будут описаны в характеристиках этой номенклатуры; а не отдельные строки на каждую комбинацию.

Итого, у меня будут такие номенклатуры по пиломатериалам:

1. Брус (здесь речь о склейке из досок; может быть как покупной, так и самодельный)
2. Доска (делается  из кругляка, т.е без клея; нам поступает как готовая, самого кругляка у нас нет)
3. Шпон (покупаем готовый разных толщин и пород)
4. МДФ (покупаем разных толщин; шпоном можем обклеивать, а можем и нет, но тогда покраска только глухая)

А возможные их породы, толщины, ширины и их комбинации описываю в характеристиках.

**Comment by Oparin-Igor** [comment]
Правильнее было бы переименовать
"Материал основ." - "Основа"
"Материал допов. " - "вид древесины"
Вариант, где решение выбора материала решает производство я не знаю.

**Comment by aribaz** [comment]
Мы по этому поводу разговаривали с Евгением. Ведь наш профиль - это мы тоже нигде не закупаем готовый, а делаем из бруса и брус в свою очередь можно купить готовый, а можно сделать самим; и у нас используются оба способа, хотя в 90% покупаем. То есть весь наш профиль - это что-то типа виртуального полуфабриката, который можно сделать двумя разными способами и с использованием разных материалов.
Евгений сказал, что этот вопрос закроем некой обработкой, которая позволит перевести профиль или в готовый брус или в доски - в зависимости от наличия сырья, уже после регистрации заказа.
Думаю то же самое будет и здесь.

Еще обнаружила, что если я пишу толщину подоконника <>35 или 50мм, то в спецификации не отображается доска подоконная никакая; если 35, то Доска подоконная 35, если 50мм - Доска подоконная 50.
Если я вместо доски использую МДФ, то в спецификацию все равно попадает Доска подоконная.
А по идее должен попадать сэндвич из МДФ и шпона + Смола.
Если выбираю Щит, то в спецификацию попадает опять Доска подоконная.
Еще не смотря на то что я выбрала сосну, попал Изолянт, а с ним для подоконников так же как и с профилем.

Предлагаю вот что:
Подоконник - это готовая продукция, в качестве **Основы (параметр)** для нее можем использовать **значения параметра**: вместо Доска и Щит одну позицию - пусть будет **Древесина**; и второй вариант так и остается **МДФ**.
Цена для клиента на подоконник из древесины не зависит от того, из чего конкретно мы сделали его: из щита или из доски, а может из бруса. Разница в цене лишь для клиента зависит Древесина или МДФ.

При выборе значения параметра Основа - Древесина,
в спецификацию будет попадать условно виртуальная номенклатура "Доска подоконная нужной толщины", которая в свою очередь может изготавливаться из доски или щита - это решается посредством обработки и требуется уже на стадии производства. Для определения цены заказа будет установлена цена на Подоконную доску (по аналогии с профилем).

При выборе значения параметра Основа - МДФ,
в спецификацию с которым будет попадать условно виртуальная номенклатура Доска Подоконная сэндвич нужной толщины.

Параметр Материал допов. переименовать в "Порода" (это технически правильно) и тут наши три варианта: Сосна, Лиственница, Дуб.
И может добавить "без шпона"? Эта позиция только для МДФ, в этом случае шпон совсем не используется никакой, плиту МДФ красят как она есть.

Еще меня смущает толщина подоконников, как сделать так, чтобы правильную толщину материалов использовала программа. Евгений говорит. что раз мы материалы вводим одной строкой, а толщины описываем в характеристиках, то эти характеристики можно использовать.
Прошу, прочтите пожалуйста еще вопрос #179 он как раз эту тему затрагивает.

**Comment by Oparin-Igor** [comment]
"Доска Подоконная сэндвич нужной толщины."
Подоконная МДФ (по тексту) имеет толщину 35мм. или есть варианты?

**Comment by aribaz** [comment]
8, 10, 12, 16,19, 22, 25, 30, 32, но самые распространенные в продаже это 10, 16, 22

Из них набираем нужную толщину-3мм, склеивая между собой смолой КФЖ, а потом на этот сэндвич клеим шпон с двух сторон все на ту же смолу

**Comment by Oparin-Igor** [comment]
"набираем нужную толщину-3мм,"
- 35мм.?

**Comment by aribaz** [comment]
Если готовый окрашенный подоконник нам нужен толщиной 35мм, то для этого нам надо:

- Шпон 0,5мм
-  смола
- МДФ16мм
-  смола
- МДФ 16мм
-  смола
- Шпон 0,5мм

МДФ: 16*2 = 32мм
Шпон: 0,5*2=1мм 
итого: 33мм, остается 2мм на 3 слоя смолы.

 +/- 1 мм большой роли не сыграет
 -3мм - это примерно.

Для подоконников 35мм - используем всегда МДФ16мм, а для других толщин принятых стандартов нет.

**Comment by Oparin-Igor** [comment]
Параметр "Материал основы"-щит.
Какую номенклатуру использовать?

**Comment by aribaz** [comment]
Вместо материала Основы Щит или Доска, используем Древесину, с ней в спецификацию попадает Доска подоконная нужной толщины и всё, то из чего она делатся будет (доска или щит (покупной или готовой)) - это обработкой.

**Comment by aribaz** [comment]
Для сосны Изолянт не нужен. Здесь по аналогии с профилем.

У меня еще вот какой вопрос. У нас толщины мдф и породы досок описаны в характеристиках.
При выборе материала допов (для доски и шпона) на спецификации они никак не сказываются, появляется конечно доска или шпон, но в характеристиках этих строк в спецификации пусто, а по идее должно быть написано то, что выбрали в качестве материала допов. ведь стоят эти материалы совсем разных денег.
То же самое и с МДФ , от толщины мдф зависит стоимость квадратного метра (чем толще лист, тем он дороже)

**Comment by aribaz** [comment]
А в остальном все работает.

**Comment by aribaz** [comment]
@Oparin-Igor 
Игорь, добрый день, сегодня разговаривала с Евгением на тему подоконников.
Так как по факту мы делаем подоконники 2-х толщин (35 и 40мм), то мы решили вместо параметра тощина, вводимого руками пользователя предоставить им право выбора из 2-х толщин, на каждый из которых будет своя четкая спецификация, которая будет использовать характеристику (толщину) самого подоконника.
Евгений сказал, что добавит возможность в спецификации учитывать характеристику номенклатуры (см. #199).
Почему именно так. Мы пиломатериалы покупаем в куб. метрах и платим тоже за кубы. При сегодняшнем раскладе мне не понятно как назначать цену за дерево, выраженное в кв.м., когда меня интересуют кубы;  к тому же по факту мы не развлекаемся каждый раз с толщинами подоконниками, а все же используем в 95% 2 толщины, которые изготавливаем как правило всегда по одним и тем же технологиям, и материал необходимый на изготовление из раза в раз одинаков..

**Comment by aribaz** [comment]
@Oparin-Igor 
Игорь, а как можно выбрать для РамаНиз 83 изготовление паза под подоконник с двух сторон?
на стороне 1С зачение такое у параметра есть и во вставке оно описано, а в браузере я его не вижу

**Comment by Oparin-Igor** [comment]
Я не ограничивал эти параметры, попробуйте перезагрузить базы. Или спросите у Евгения.
--
Отправлено из Mail.Ru для Android четверг, 26 января 2017г., 14:00 +03:00 от Звалинская Наталья  notifications@github.com :

**Comment by aribaz** [comment]
@unpete 
Евгений, помогите пожалуйста.
Кнопка Стереть справочники и перезаполнить данными сервера не помогла.

**Comment by Oparin-Igor** [comment]
Попробуйте нарисовать новое окно, а не выбирать из типовых
--
Отправлено из Mail.Ru для Android четверг, 26 января 2017г., 14:26 +03:00 от Звалинская Наталья  notifications@github.com :

**Comment by aribaz** [comment]
Не помогло, дин.поиск в браузере тоже не дал результатов, список дополнительных значений для этого параметра не содержит тот паз в браузере, хотя на 1С он есть.

**Comment by Oparin-Igor** [comment]
Попробуйте на стороне 1с зайти во вставке зайти в параметр сохранить параметр сохранить вставку, я смогу только через часа 2
--
Отправлено из Mail.Ru для Android четверг, 26 января 2017г., 14:39 +03:00 от Звалинская Наталья  notifications@github.com :

**Comment by aribaz** [comment]
Тоже не помогло. И даже очистка истории не сработала.

Я на стороне 1С меняла название импоста 115-го. Было Импост 115, стало Импост 113. и поменяла размер его.
По идее надо изменить размер В для него во вставке, но при попытке это сделать, 1С говорит что не заполнена графа Расчет угла, а она и не была заполнена. И размер В по этой причине изменить не могу, как и переименовать саму вставку, выдает то же самое при попытке перезаписи. Может надо что-то туда поставить? В Расчет угла я имею ввиду. У меня вопрос в том что именно.
Но в браузере у меня он до сих пор называется Импост 115, почему-то - наверное из-за того что вставка для него не переименована.

**Comment by unpete** [comment]
Закрываем?
