### ISSUE TITLE
Ошибка при пересчете цен в рубли 

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#97]
У меня был ранее создан документ УЦН Общие материалы, он состоял как из рублевых так и евровых позиций. В связи с необходимостью разделения цен,я этот документ изменила, оставив в нем только рублевые позиции и создала еще новый для евровых. Оба документа провела, выгрузила изменения справочников на сервер, создала новый заказ. Цена меня смутила, я стала проверять.
Цены для этих позиций (которые я сегодня меняла, в частности наполнитель швов) он не персчитывает в рубли, а евровую цену умножает на количество и получает сумму и ее суммирует с остальными суммами, тогда как для фурнитуры (ее я забивала вчера и она тоже евровая) цена указана уже с учетом перевода из евро в рубли, то есть верная. получается она складывает евро и рубли и получается стоимость изделия в рублях.
У меня такое ощущение, что она считает по старому варианту, до разделения этого документа на два. Ведь после того как валюту вынесли в реквизиты этот документ стал рублевым значиться, хотя там были позиции в разной валюте.
Еще я до создания внесла цены на лак, стеклопакеты (сегодня до создания заказа), штапик и техвставку (вчера), но все эти позиции стоят с нулевыми ценами.
Документы провела и выгрузила все на сервер и только после этого создала заказ
Каждую строчку спецификации не смотрела отдельно, пролистала в общем.
Проблему решила перезагрузкой приложения.

**Comment by unpete** [comment]
Важно: Цены в браузере пересчитываются при загрузке страницы, а не при записи документа ценообразования.
