### ISSUE TITLE
Не работает таблица соответствия цветов

### ISSUE THREAD

**Issue by aribaz** [oknosoft/windowbuilder#99]
Попробовала проверить как изменится цвет водоотводного 22/34 профиля в зависимости от того каким будет изделие.
Для начала посмотрела таблицу соответствия цветов для профиля и уплотнителя, и для цвета J100 цвет профиля водоотводного и уплотнителя должен быть белый.
Я залезла в заказ выбрала цвет изделия J100, рассчитала спецификацию итого - хракатеристика водоотводного профиля пуста, а в графе цвет для всех вообще комплектующих числится J100. Мне казалось, что должен быть цвет белый для водоотводного профиля и уплотнителя. Может я что-то не так понимаю? 

Еще мне казалось, что если мы в справочнике соединений описываем состав спецификации и цвет номенклатуры, то это и должно отображаться. Например, для номенклатуры Пластина рихтовочная в графе Цвет написано: Без характеристики, а для профиля написано Как Элемент (справочник Соединения).
В спецификации изделия  Пластина рихтовочная в графе характеристика имеет пусто, а в графе Цвет J100 хотя по факту они не такого цвета, и он в принципе не важен для этой позиции ( у них есть 4 цвета, но они для зрительного определения толщины пластины, например красные толщиной 3мм, желтые 2мм), а для профиля в графе характеристика числится тип древесины (что и должно), а в графе цвет J100, что и должно. Если эти цвета из графы Цвет никак не влияют на печатные формы для цеха и задания на производство и заказы поставщикам, и в них будут значится те данные, которые должны, то ничего страшного, иначе это не хорошо, надо исправить.

**Comment by nmivan** [comment]
@aribaz , проблема еще актуальна?
